### ISSUE TITLE
PHP 8.1 Return Type Inheritance Warnings

### ISSUE THREAD

**Issue by rhift** [webonyx/graphql-php#1001]
Hey there, please add the `mixed` return type hint to the following so as to not generate a warning in PHP 8.1 (either that or the `#[\ReturnTypeWillChange]` attribute should be used to temporarily suppress the notice).

* `\GraphQL\Error\Error::jsonSerialize`
* `\GraphQL\Executor\ExecutionResult::jsonSerialize`
* `\GraphQL\Language\SourceLocation::jsonSerialize`
* `\GraphQL\Type\Definition\Type::jsonSerialize`
* `\GraphQL\Language\AST\NodeList::offsetGet`
* `\GraphQL\Utils\MixedStore::offsetGet`

I used `mixed` since that seemed to be the most backwards compatible.

Thank you!!

**Comment by spawnia** [comment]
We are targeting PHP 8.0 for the next release. Can you add a PR to fix this?

**Comment by rhift** [comment]
Looks like `dev-master` is using more specific return type declarations and generates no 8.1 warnings. Feel free to close this!

**Comment by vhenzl** [comment]
> We are targeting PHP 8.0 for the next release. 

Is that so? In that case, it would be good to drop PHP 7.4 on master and start benefiting from PHP 8 features like native unions immediately.

**Comment by spawnia** [comment]
That came out wrong. We are actually targeting 7.4, perhaps we can go for 8.0 in the next major version.
