### ISSUE TITLE
Switch to php-cs-fixer

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#1020]
We currently use https://github.com/squizlabs/PHP_CodeSniffer for formatting. I have been annoyed with it because:
1. it keeps messing up complex types in PHPDocs (e.g. https://github.com/webonyx/graphql-php/pull/1016#discussion_r756812057)
2. the way it aligns some code is nearly impossible to do right manually
3. alignment leads to ugly diffs
4. configuration options are very hard to discover
5. XML-based configuration is clunky

I propose we switch to https://github.com/FriendsOfPHP/PHP-CS-Fixer instead. I am using it in a lot of projects and have not had much issues with it at all. It addresses the above mentioned pain points:
1. it deals fine with complex types (e.g. https://github.com/nuwave/lighthouse/blob/04a74cc6bbc6e592de988096a890958ebe112a4e/src/Schema/AST/DocumentAST.php#L40)
2. my code is mostly fine the way i type it
3. it is easily configured to left-align everything
4. https://mlocati.github.io/php-cs-fixer-configurator
5. PHP-based configuration is nice and composable

**Comment by mfn** [comment]
# 👍🏼 

from my side.

Whilst I'm happy both projects are maintained, my impression is that with PHP adaptions, adjustments, release cadence and whatnot makes a healthy project, next to the technical things pointed out, php-cs-fixer is in a better state.

My experience is similar and I propose it also in many projects working on.

This combined with a CI webhook to auto-add a commit reduces developer friction a lot.

**Comment by ruudk** [comment]
FWIW: It would be great to move forward with this, as currently phpcs/phpcbf don't work at all:
```
vendor/bin/phpcbf
ERROR: Referenced sniff "Doctrine" does not exist

Run "phpcbf --help" for usage information
```
