### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ruudk** [webonyx/graphql-php#1037]
I see lots of activity in the [`master` branch](https://github.com/webonyx/graphql-php/compare/v14.11.3...master) lately which is amazing 👏 

No pressure, but I was wondering if there is already an ETA for the new (prob major) version?

The reason why I'm asking is that for [OverblogGraphQLBundle](https://github.com/overblog/GraphQLBundle) we currently use `dev-master` on our `master` branch and like to release it at some point.

**Comment by spawnia** [comment]
I am planning to get to PHPStan `level: max` before.

**Comment by enumag** [comment]
Can you please make a bugfix release with PHP 8.1 compatibility? https://github.com/webonyx/graphql-php/commit/51ad17c3af192e34bc2e368a3c645a5a668f3e15

**Comment by spawnia** [comment]
> Can you please make a bugfix release with PHP 8.1 compatibility? [51ad17c](https://github.com/webonyx/graphql-php/commit/51ad17c3af192e34bc2e368a3c645a5a668f3e15) + #924

Those changes should be present in the latest `14.x` release. If something is missing, please add a pull request that targets the `14.x` branch.

**Comment by mfn** [comment]
Indeed, they are in the 14.x branch / release; they were cherry-picked, that's why the original commit hash has no association with the branch https://github.com/webonyx/graphql-php/commit/527bdee2747dca166db9a51a952eba450bbd0d96

**Comment by abdullahseba** [comment]
I'm looking forward to the new release and I was running on the master branch in dev as it addressed https://github.com/webonyx/graphql-php/pull/934.  Is a reason why this fix cannot be released in v14.x?

**Comment by spawnia** [comment]
> I'm looking forward to the new release and I was running on the master branch in dev as it addressed #934. Is a reason why this fix cannot be released in v14.x?

It is a behavioural change with potential for breakage.

**Comment by vladdnepr** [comment]
Hello. When will v15 be released?

**Comment by spawnia** [comment]
I just released v15.0.0-alpha.1 - please try it and leave feedback in https://github.com/webonyx/graphql-php/discussions/1231 or open issues.
