### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function object()

### ISSUE THREAD

**Issue by oojacoboo** [webonyx/graphql-php#1048]
This is one of the strangest stack-traces I've seen in quite a while.  I was able to finally track down the issue and resolve it, but it took way too long and I'm pretty frustrated with that.  Please see below:

```
[07-Jan-2022 02:22:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function object() in /srv/www/vendor/webonyx/graphql-php/src/Type/Schema.php:417
Stack trace:
#0 /srv/www/vendor/webonyx/graphql-php/src/Type/Definition/ListOfType.php(30): GraphQL\Type\Schema::resolveType('object')
#1 /srv/www/vendor/webonyx/graphql-php/src/Type/Definition/ListOfType.php(25): GraphQL\Type\Definition\ListOfType->getOfType()
#2 /srv/www/vendor/webonyx/graphql-php/src/Type/Definition/NonNull.php(26): GraphQL\Type\Definition\ListOfType->toString()
#3 /srv/www/vendor/webonyx/graphql-php/src/Type/Definition/Type.php(315): GraphQL\Type\Definition\NonNull->toString()
#4 [internal function]: GraphQL\Type\Definition\Type->jsonSerialize()
#5 /srv/www/vendor/acme/sprockets/src/Json/Encoder.php(141): json_encode(Array, 0, 256)
#6 /srv/www/vendor/acme/sprockets/src/File/Logger.php(131): Acme\Sprocket\Json\Encoder::encode(Array)
#7 /srv/www/vendor/acme/sprockets/src/File/Logger.php(97): Acme\Sprocket\File\Logger->log('critical', 'An exception oc...', Array)
#8 /srv/www/vendor/acme/sprockets/src/Log/Dispatcher.php(78): Acme\Sprocket\File\Logger->logException(Object(Doctrine\DBAL\Exception\InvalidFieldNameException))
#9 /srv/www/vendor/acme/sprockets/src/Exception/Handler.php(43): Acme\Sprocket\Log\Dispatcher->logException(Object(Doctrine\DBAL\Exception\InvalidFieldNameException))
#10 /srv/www/vendor/acme/sprockets/src/Exception/Handler.php(77): Acme\Sprocket\Exception\Handler::handleLog(Object(Doctrine\DBAL\Exception\InvalidFieldNameException))
#11 [internal function]: Acme\Sprocket\Exception\Handler::handle(Object(Doctrine\DBAL\Exception\InvalidFieldNameException))
```

So, the issue here is that Doctrine had a column that was defined in an entity that wasn't in the database.  Luckily the stack-trace includes the Doctrine exception being thrown, `InvalidFieldNameException`.  However, there isn't much else to go off of here.

Honestly, the stack-trace doesn't even make much sense.  I can't even tell the direction of the call stack.  It's like call #4 somehow reverses the order of the call-stack.

I guess my question here is... does this lib try to catch all Throwables inside the resolver logic?  And if so, it isn't properly re-throwing these.  I don't see how it's getting to a fatal error when an Exception has been thrown.

**Comment by spawnia** [comment]
Looks like you are trying to `json_encode()` arbitrary data as part of your error logging (which is risky). That surfaced an error in your schema definition, apparently you defined the type of a field as a `NonNull(ListOfType('object'))` (which is wrong).
