### ISSUE TITLE
Query batching support?

### ISSUE THREAD

**Issue by piscis** [webonyx/graphql-php#105]
We're currently implementing several React Components that talk to a PHP GraphQL backend. 

Looking at:
http://dev.apollodata.com/core/network.html#BatchingExample
And:
https://github.com/nodkz/react-relay-network-layer#batching-several-requests-into-one

I was wondering if graphql-php supports query batching or if there are any plans to support it?

Thanks,

Alex

**Comment by vladar** [comment]
It should be easy to implement in user-land code. Just call `GraphQL::execute()` (or `GraphQL::executeAndGetResult`) in a loop and then combine results (unless I am missing something about this feature).

We will likely add some helper tools in future to enable this out of the box, but this should be easy to do even now.

**Comment by mcg-web** [comment]
That exactly what we doing in the bundle. A next solution is to implement a guzzle http batching system sending request to your main endpoint separately. Last solution is the best because you can async batching so doing win runtime...

**Comment by vladar** [comment]
Next version (v0.10.0) will contain Standard Server implementation with batching support. One of the major benefits over sequence of `GraphQL::execute()` calls is that Deferred resolvers won't be isolated in queries.

So for example following batch will require single DB request (if `user` field is deferred):

```json
[
  {
    "query": "{user(id: 1)} { id }"
  },
  {
    "query": "{user(id: 1)} { id }"
  },
  {
    "query": "{user(id: 1)} { id }"
  }
]
```

**Comment by vladar** [comment]
Released in v0.10.0. See [documentation](http://webonyx.github.io/graphql-php/executing-queries/#query-batching). 

It is not battle-tested yet, so please report in new issues if you encounter any problems.

**Comment by sebastienbarre** [comment]
Very interested in query batching, but cannot run the Standard Server. Does anybody have some user land code they could share? @mcg-web? Thx.

**Comment by MasonD** [comment]
If anyone still needs an answer to @sebastienbarre's question, the relevant code can be found in the Standard Server's Helper::executeBatch() at https://github.com/webonyx/graphql-php/blob/master/src/Server/Helper.php#L217
