### ISSUE TITLE
Repeatable directives

### ISSUE THREAD

**Issue by sb-onoffice-de** [webonyx/graphql-php#1053]
Hello!

We're using version 14.11.3.

Assuming this piece of code:

```php
<?php

namespace onOffice\GraphQL;

use PHPUnit\Framework\TestCase;
use GraphQL\GraphQL;
use GraphQL\Utils\BuildSchema;

class RepeatableDirectivesTest extends TestCase
{
	public function testRepeatableDirectives()
	{
		$schema =  /* @lang GraphQL */ <<< GRAPHQL
directive @foo(bar: Int) repeatable on OBJECT

type Baz @foo(bar: 1) @foo(bar: 2) {
	id: ID!
}

type Query {
	baz: Baz
}
GRAPHQL;

		$result = GraphQL::executeQuery(BuildSchema::build($schema), 'query { baz { id }');

		$this->assertNull($result->data);
	}
}
```

It says:

```
GraphQL\Error\Error: The directive "foo" can only be used once at this location.
```

I believe it's a problem in Validator/Rules/UniqueDirectivesPerLocation.php. If I change that 

```php
if (! isset($uniqueDirectiveMap[$directiveName]))
```

to

```php
if (! isset($uniqueDirectiveMap[$directiveName]) ||
	$uniqueDirectiveMap[$directiveName])
```

it seems to be working, but I don't know whether this is the right fix.

Stefan

**Comment by spawnia** [comment]
This should be fixed as of 14.6.2, see https://github.com/webonyx/graphql-php/commit/bcbb6926bbf2d0cf466c63d0b9edc90e44d5dd3f

**Comment by sb-onoffice-de** [comment]
Yes, the schema validates, but the object type defintion does not, we're using 14.11.3

**Comment by sb-onoffice-de** [comment]
Is 14.6.2 newer than 14.11.3 that we're using? Or could you give me a hint where to look at?

**Comment by spawnia** [comment]
Fixed with https://github.com/webonyx/graphql-php/releases/tag/v14.11.4
