### ISSUE TITLE
Allow Resolve of Invokable Classes

### ISSUE THREAD

**Issue by NikolaiEngel** [webonyx/graphql-php#1088]
Thanks for this awesome library
I have a feature request which i want to propose. I would like to be able to specify an invokable class when resolving fields. This gives me the advantage that class dependencies are only resolved when the resolve is needed and it can be better separated from configuration and business logic. 

See example:
```
Endpoint configuration
$fields[self::FIELD_TEST] = [
    'description' => 'My Test Field',
    'type' => self::string(),
    'resolve' => TestInvokable::class
];
```
```
Buisness Logic
class TestInvokable
{

    private FooBar $fooBar;

    public function __construct(FooBar $fooBar)
    {
        $this->fooBar= $fooBar;
    }

    public function __invoke($source, array $args): string
    {
        return 'FooBar';
    }
}
```

For implementation we need a place where the PSR container is optionally passed and use the container for resolving. Because an invokable class behaves the same way as a callable type, there are no differences after resolving it.

What is your opinion on this?

**Comment by CptKirk** [comment]
Awesome proposal, we hope it gets implemented!

**Comment by PatUlm** [comment]
Sounds like an interesting approach to keeping the code clean and adds even more lazy loading capabilities.

**Comment by spawnia** [comment]
Given you can lazily define fields, I don't feel this is necessary.

```php
$fields[self::FIELD_TEST] = function (): array {
      return [
        'description' => 'My Test Field',
        'type' => self::string(),
        'resolve' => Container::make(TestInvokable::class),
    ];
}
```

**Comment by NikolaiEngel** [comment]
Hey @spawnia, thanks for your feedback. In your example, if I use a different endpoint, the TestInvokable class is still instantiated. I would like to avoid this behavior with a container support. Especially for large interfaces with many dependencies this can give a lot of performance bonus.

**Comment by spawnia** [comment]
> if I use a different endpoint

What do you mean by endpoint?

> large interfaces with many dependencies

What do you mean by large interfaces?

Anyways, lazy field definitions are only resolved when the field is actually used in a query. For example, if you define the fields of your root `type Query` lazily, only the ones that are actually part of the client's query are instantiated.

**Comment by NikolaiEngel** [comment]
I have summarized my setup for a better understanding:
```
// index.php
$rawInput = file_get_contents('php://input');
$input = json_decode($rawInput, true);
$query = $input['query'] ?? '';
$variableValues = $input['variables'] ?? null;
$operationName = $input['operationName'] ?? null;

$queryType = $container->get(QueryType::class);

$schema = new Schema(['query' => $queryType]);

// execute query
$result = GraphQL::executeQuery(
    $schema,
    $query,
    null,
    null,
    $variableValues,
    $operationName
)->toArray();

echo json_encode($result);
```

```
// QueryType.php
class QueryType extends ObjectType
{

    private const TEST1_FIELD = 'Test1';
    private const TEST2_FIELD = 'Test2';

    private ContainerInterface $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
        parent::__construct($this->getConfig());
    }

    public function getConfig(): array
    {
        return [
            'fields' => fn() => [
                self::TEST1_FIELD => [
                    'description' => 'My Test Field 1',
                    'type' => self::string(),
                    'resolve' => $this->container->get(TestInvokable::class),
                ],
                self::TEST2_FIELD => [
                    'description' => 'My Test Field 2',
                    'type' => self::string(),
                    'resolve' => fn() => 'Hello World',
                ]
            ],
        ];
    }
}
```

```
// Test Invokable
class TestInvokable
{

    public function __construct()
    {
        // Heavy dependencies
        sleep(3);
    }

    public function __invoke($source, array $args): string
    {
        return 'FooBar';
    }
}
```

If I now call the endpoint "Test2", the heavy dependency InvokableClass is still resolved. Therefore my call now takes +3 seconds although I don't need the class at all. Can you follow me better now, or do you have a good suggestion how I can get a better handle on this behavior?

**Comment by spawnia** [comment]
You are wrapping all of your fields within a single callable. What you need to do instead is wrap each individual field in a callable.

```diff
    public function getConfig(): array
    {
        return [
-            'fields' => fn() => [
+            'fields' => [
-               self::TEST1_FIELD => [
+               self::TEST1_FIELD => fn () => [
                    'description' => 'My Test Field 1',
                    'type' => self::string(),
                    'resolve' => $this->container->get(TestInvokable::class),
                ],
-               self::TEST2_FIELD => [
+               self::TEST2_FIELD => fn() => [
                    'description' => 'My Test Field 2',
                    'type' => self::string(),
                    'resolve' => fn() => 'Hello World',
                ]
            ],
        ];
    }
```

**Comment by spawnia** [comment]
About terminology: there is no such thing as an endpoint in GraphQL. You probably mean fields.

**Comment by NikolaiEngel** [comment]
Thanks for pointing out the terminology. Unfortunately, your suggestion only leads to this error.

`Return value of GraphQL\\Type\\Schema::resolveType() must be an instance of GraphQL\\Type\\Definition\\Type, array returned'`

**Comment by spawnia** [comment]
Make sure you are using the latest version and consider https://github.com/webonyx/graphql-php/pull/861/files#diff-7bbb5376d72f8561023190dadb349c5acf905edf96ef2763b7164887f44fe7a6

**Comment by NikolaiEngel** [comment]
After an update it works again - my bad.

I have found the point where we are talking at cross purposes. If I run the GraphQL via the `SchemaBuilder` with a ready `schema.graphql` and `fieldResolver`, then I get my desired result. The `InvokableClass` was not created if i query the field `test2.`

In my project currently I don't work with this construct and let the schema parse on every call. 
`$schema = new Schema(['query' => $queryType]);`
Thus I have the problem that for each queried field the class `InvokableClass` is created.
