### ISSUE TITLE
Best Way to Resolve Fields

### ISSUE THREAD

**Issue by Purus** [webonyx/graphql-php#109]
I have developed a working example of GraphQL for one of open-source application. Although it works I am not confident that I did it correct. Why i think so?

The only reason i think so is that main benefit of GraphQL is you fetch only what you need.  For example for an user query, if I need only name and city I fetch only those 2 columns from the back-end database. 

But what I do is I fetch all data of an user every time. I don't think I am doing it the correct way.

How can I change my code to fetch database for only the data I need? Currently I resolve all fields in a single place.

Example query of my code are provided below for your reference and guidance.

```php
 'photo' => [
                   'type' => Types::listOf(Types::photo()),
                    'description' => 'Returns all photos uploaded',
                    'args' => [
                        'id' => [
                            'type' => Types::id(),
                            'description' => 'Id for which the photos are requested. Other arguments will be ignored',
                            'defaultValue' => 0
                        ],
                        'userId' => [
                            'type' => Types::id(),
                            'description' => 'User id for which the photos are requested. Other arguments will be ignored',
                            'defaultValue' => 0
                        ],
                        'key' => [
                            'type' => Types::photoListEnum(),
                            'description' => 'Type of photo list to get',
                            'defaultValue' => 'latest'
                        ],
                        'offset' => [
                            'type' => Types::int(),
                            'description' => 'Offset to fetch data from',
                            'defaultValue' => 1
                        ],
                        'limit' => [
                            'type' => Types::int(),
                            'description' => 'Data limit to fetch',
                            'defaultValue' => 50
                        ],
                    ],
                    'resolve' => function($value, $args, $context, ResolveInfo $info) {
                        $context->profileService->getProfileById(1);
                        if ($args['id'] > 0) {
                            return $context->photoService->getPhotoById($args['id']);
                        } else if ($args['userId'] > 0) {
                            return $context->photoService->getPhotoByUserId($args['userId'], $args['offset'], $args['limit']);
                        } else {
                            return $context->photoService->getPhotoList($args['key'], $args['offset'], $args['limit']);
                        }
                    }
                ]
```

**Comment by VaclavSir** [comment]
I think this benefit is more important for the network performance - your app does less requests and transfers less amount of data. On the server-sice, there is usually no significant difference between `SELECT u FROM User u` and `SELECT PARTIAL u.{id,name,city} FROM User u`.

But when you measure that some data are expensive to fetch and your clients don't always need them, you can get the list of fields from the `ResolveInfo` object:

```php
$fields = $info->getFieldSelection();
if (isset($fields['someExpensiveField'])) {
    return $this->resolver->fetchWithTheExpensiveField();
} else {
    return $this->resolver->fetchWithoutTheExpensiveField();
}
```

**Comment by vladar** [comment]
As of my experience you want two things for DB-layer performance (assuming you use relational database):

1. Do not re-fetch **rows** which you have already fetched during this query execution. It is actually up to you how to do it. If you use Doctrine - it will handle it for you via IdentityMap. Facebook's dataloder and [it's PHP version](https://github.com/overblog/dataloader-php#using-with-webonyxgraphql) also does that out of the box. But if you use your own custom data access layer - it is your responsibility to choose and implement runtime caching strategies.

2. Batch multiple requested rows into single query to avoid N+1 problem. [Read this entry in docs](http://webonyx.github.io/graphql-php/data-fetching/#solving-n1-problem) for details. You have two options here - implement your own buffers or use [DataLoader implementation](https://github.com/overblog/dataloader-php#using-with-webonyxgraphql).

As for fine-grained list of **columns** in your SQL query... If you use per-row caching - it makes little sense (you don't want to cache partial data for the row). 

But if you don't use per-row cache and your app is relatively simple - then you can use the method which @VaclavSir mentioned - by using `$info->getFieldSelection()` in your resolver to figure out which sub-fields were requested and query the database for those fields/columns only.

Also a separate note about "query only what you need": keep in mind that this principle is applied to client-sever communication, not to internal data access layer. 

It is very important for slow mobile connections to receive only what was requested, but that doesn't mean that your internal data-access layer (which is very fast comparing to client-server communication) has to implement the same granularity level.

**Comment by Purus** [comment]
Thanks for your thoughts.

My CMS does not contain information in a single table. Even for a single entity, multiple tables are involved in some cases. So ideally I have to fetch all columns irrespective of requested columns.
