### ISSUE TITLE
Support: render custom  directive SDL into introspection query 

### ISSUE THREAD

**Issue by Sundayfree** [webonyx/graphql-php#1091]
For example
 ```
directive @documentation(
  example: String!
) on FIELD_DEFINITION | ENUM_VALUE

type user {
  id: id!
  username: String @documentation(example: "hi username")
  firstname: String @deprecated(reason: "Not supported yet")
}
```

Introspection query can not render documentation as one of a field argument(username), is there a way that does not change core code to implement this?  Thx in advance

**Comment by spawnia** [comment]
No, this is not supported by the GraphQL specification - see https://github.com/graphql/graphql-spec/issues/300
