### ISSUE TITLE
Lazy field definitions are eager loaded when schema has no type loader

### ISSUE THREAD

**Issue by NikolaiEngel** [webonyx/graphql-php#1093]
Hey, 

i have created the following sample code to prove that the lazy loading feature does not work as desired.

If I query the field `Test2`, the class `TestInvokable` is created despite lazy loading. This has the consequence that a lot of dependencies have to be resolved, which are not necessary for the query. In this example this is illustrated by a sleep of 3 seconds. 

I have also created an alternative TestCase in which it works. When I set up the `Schema` as in the linked page: https://webonyx.github.io/graphql-php/schema-definition-language/, the `TestInvokable` class is not created. Since there are two ways to use the GraphQL, I would like to have this feature also for the scenario described below.

```
// index.php
$rawInput = file_get_contents('php://input');
$input = json_decode($rawInput, true);
$query = $input['query'] ?? '';
$variableValues = $input['variables'] ?? null;
$operationName = $input['operationName'] ?? null;

$queryType = $container->get(QueryType::class);

$schema = new Schema(['query' => $queryType]);

// execute query
$result = GraphQL::executeQuery(
    $schema,
    $query,
    null,
    null,
    $variableValues,
    $operationName
)->toArray();

echo json_encode($result);
```
```
// QueryType.php
class QueryType extends ObjectType
{

    private const TEST1_FIELD = 'Test1';
    private const TEST2_FIELD = 'Test2';

    private ContainerInterface $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
        parent::__construct($this->getConfig());
    }

    public function getConfig(): array
    {
        return [
            'fields' => [
                self::TEST1_FIELD => fn() => [
                    'description' => 'My Test Field 1',
                    'type' => self::string(),
                    'resolve' => $this->container->get(TestInvokable::class),
                ],
                self::TEST2_FIELD => fn() => [
                    'description' => 'My Test Field 2',
                    'type' => self::string(),
                    'resolve' => fn() => 'Hello World',
                ]
            ],
        ];
    }
}
```
```
// Test Invokable
class TestInvokable
{

    public function __construct()
    {
        // Heavy dependencies
        sleep(3);
    }

    public function __invoke($source, array $args): string
    {
        return 'FooBar';
    }
}
```

Linked issue is a feature request to create a DI container known to GraphQL to use invokable classes for resolution. https://github.com/webonyx/graphql-php/issues/1088

**Comment by spawnia** [comment]
Got it, I can reproduce the issue in a test case. The problem is that the schema is always loader eagerly when no type loader is present. I am trying to fix this in https://github.com/webonyx/graphql-php/pull/1104
