### ISSUE TITLE
Feature Request: Allow Resolve of Invokable Classes

### ISSUE THREAD

**Issue by NikolaiEngel** [webonyx/graphql-php#1094]
I created a new issue, because the old one was closed without the community feedback result. https://github.com/webonyx/graphql-php/issues/1088

I have a feature request which i want to propose. I would like to be able to specify an invokable class when resolving fields. 
this brings the following advantages:
- class dependencies are only resolved when the resolve is needed
- configuration of the interface and resolving of business logic is separated
- easier to create UnitTests for the resolvers

See example:

```
// Field configuration
$fields['test_field'] = [
    'description' => 'My Test Field',
    'type' => self::string(),
    'resolve' => TestInvokable::class
];
```
```
// Buisness Logic
class TestInvokable
{

    private FooBar $fooBar;

    public function __construct(FooBar $fooBar)
    {
        $this->fooBar= $fooBar;
    }

    public function __invoke($source, array $args): string
    {
        return 'FooBar';
    }
}
```
For implementation we need a place where the PSR container is optionally passed and use the container for resolving. Because an invokable class behaves the same way as a callable type, there are no differences after resolving it.

What is your opinion on this?

**Comment by spawnia** [comment]
My point in https://github.com/webonyx/graphql-php/issues/1088#issuecomment-1073339288 stands, allowing fields to be defined as a callable and thus lazy loading their resolve function is a clean and sufficient abstraction. We have tests that ensure this definition style indeed works as intended - see https://github.com/webonyx/graphql-php/blob/master/tests/Type/DefinitionTest.php#L1886-L1984
