### ISSUE TITLE
Impossible to enable Access-Control-Allow-Origin with parameter (or other response header params) 

### ISSUE THREAD

**Issue by silviomarini** [webonyx/graphql-php#1096]
header parameters set in emitResponse function (src\Server\Helper.php) are hardcoded and is not possible to add some new params.  In order to enable Access-Control-Allow-Origin, I've added a new row in the function but could be very helpful if they can be passed as parameters to the method.

**Comment by spawnia** [comment]
It is quite easy to compose the methods in `StandardServer` and `Helper` for more advanced use cases. Enhancing `emitResponse` in that way would complicate the simple methods in there unnecessarily.
