### ISSUE TITLE
Mutations with Relay (React)

### ISSUE THREAD

**Issue by chrissm79** [webonyx/graphql-php#11]
I'm using the [laravel-graphql] (https://github.com/Folkloreatelier/laravel-graphql#eager-loading-relationships), and created an [issue] (https://github.com/Folkloreatelier/laravel-graphql/issues/17#issuecomment-155924524) but I'm not sure if it's something that should actually be created here (still trying to wrap my head around GraphQL).

When working with Relay, it expects that mutations have only one argument called input. Looking at the todo example, in the [schema.json] (https://github.com/facebook/relay/blob/master/examples/todo/data/schema.json#L498-L523) file it has that field listed as an INPUT_OBJECT type. I created the following (again, using laravel-graphql), but I'm unable to get the fields from the InputObjectType. Am I doing something wrong?

```php
namespace App\GraphQL\Mutations;

use GraphQL;
use App\Models\Customer;
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\InputObjectType;
use Folklore\GraphQL\Support\Mutation;

class UpdateCustomerEmail extends Mutation
{
    /**
     * Associated GraphQL Type.
     *
     * @return mixed
     */
    public function type()
    {
        return GraphQL::type('customerPayload');
    }

    /**
     * Available arguments for mutation.
     *
     * @return array
     */
    public function args()
    {
        return [
            'input' => [
                'name' => 'input',
                'type' => new InputObjectType([
                    'name' => 'updateCustomerEmailInput',
                    'fields' => [
                        'entity_id' => [
                            'name' => 'entity_id',
                            'type' => Type::nonNull(Type::string())
                        ],
                        'email' => [
                            'name' => 'email',
                            'type' => Type::nonNull(Type::string())
                        ]
                    ]
                ])
            ]
        ];
    }

    /**
     * Resolve mutation.
     *
     * @param  string $root
     * @param  array $args
     * @return Customer
     */
    public function resolve($root, $args, $info)
    {
        // $root is null, $args is an empty array and nothing in $info gives me the 
        // variables passed in the request
        $customer = Customer::find($args['input']['entity_id']); // $args['input'] is not set
        $customer->email = $args['input']['email'];
        return $customer;
    }
}
```

**Comment by smolinari** [comment]
Did you also add the mutation to the configuration file, as explained [here](https://github.com/Folkloreatelier/laravel-graphql#creating-a-mutation)? (which seems to me to be a bit strange thing to have to do)

Scott

**Comment by chrissm79** [comment]
I did add it to the config file (this is a fairly [common setup] (http://laravel.com/docs/5.1/events#registering-events-and-listeners) in Laravel). Overall everything has been really easy to work with except for mutations. Just trying to determine if this is an issue with the laravel package or if I'm not setting up my mutation properly. 

I did see that the [controller] (https://github.com/Folkloreatelier/laravel-graphql/blob/master/src/Folklore/GraphQL/GraphQLController.php#L11) is passing through 'params' from the request instead of 'variables'. After switching that out, I'm hitting a different error message which leads me to believe that I need to make a change in my mutation, just not sure what:

```"Variable $input_0 expected value of type updateCustomerEmailInput but got: {"entity_id":"2","email":"john.doe@example.com","clientMutationId":"4"}."```

**Comment by smolinari** [comment]
Sorry, I missed the "Or" just below the config note saying can use the config OR use the facade. 

I am also not deep enough into graphql-php code to help further. Hopefully Vladamir (@vladar) can help.

Scott

**Comment by vladar** [comment]
Hey, I am not familiar with `laravel-graphql`, but in pure `graphql-php`, mutations do work with Relay for me with following helper (basically ported from https://github.com/graphql/graphql-relay-js):

```php
<?php
namespace MyGraphQL;

// See https://github.com/graphql/graphql-relay-js/blob/master/src/mutation/mutation.js
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;
use GraphQL\Utils;

class Mutation
{
    public static function mutationWithClientMutationId(array $config)
    {
        Utils::invariant(
            isset($config['inputFields'], $config['outputFields'], $config['mutateAndGetPayload']),
            "Invalid mutation config: make sure that options 'inputFields', 'outputFields' and 'mutateAndGetPayload' are set"
        );

        $outputType = new ObjectType([
            'name' => $config['name'] . 'Payload',
            'fields' => $config['outputFields'] + [
                'clientMutationId' => [
                    'type' => Type::nonNull(Type::string())
                ]
            ]
        ]);

        $inputType = new InputObjectType([
            'name' => $config['name'] . 'Input',
            'fields' => $config['inputFields'] + [
                'clientMutationId' => [
                    'type' => Type::nonNull(Type::string())
                ]
            ]
        ]);

        return [
            'type' => $outputType,
            'args' => [
                'input' => ['type' => Type::nonNull($inputType)]
            ],
            'resolve' => function($_, $args, ResolveInfo $info) use ($config) {
                DataLoader::cacheResults(false);
                $payload = call_user_func($config['mutateAndGetPayload'], $args['input'], $info);
                Utils::invariant(is_array($payload), 'Function "mutateAndGetPayload" is expected to return array');

                return $payload + [
                    'clientMutationId' => $args['input']['clientMutationId']
                ];
            }
        ];
    }
} 
```

Then your mutation type can be defined as:
```php
namespace MyGraphQL;

use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Utils;

$toggleLikeMutation = Mutation::mutationWithClientMutationId([
    'name' => 'ToggleLike',
    'description' => 'Toggle like',
    'inputFields' => [
        'id' => [
            'type' => Type::id()
        ]
    ],
    'outputFields' => [
        'story' => [
            'type' => $myTypes->get('Story'),
            'resolve' => function($payload) {
                // fetch and return liked story by id
            }
        ]
    ],
    'mutateAndGetPayload' => function(array $input, ResolveInfo $info) {
        // ... perform mutation ...
        return [
            'id' => $input['id']
        ];
    }
]);

```

And then don't forget to add it to your Schema:

```php
$schema = new Schema($queryType, new ObjectType([
    'name' => 'Mutation',
    'fields' => [
        'toggleLike' => $toggleLikeMutation
    ]
]))
```

Then check your `schema.js` for Relay. It should have types `ToggleLikeInput` and `ToggleLikePayload`. Relay expects them to exist to perform mutation correctly.

**Comment by chrissm79** [comment]
@vladar Thank you!! I'll give this a try, but thank you for providing this, it ought to be a big help for anyone trying to leverage GraphQL/PHP and Relay. There are a few other helpers I found in the graphql-relay-js package that I'll try to migrate over, but this is a great start.

**Comment by smolinari** [comment]
Yes, thanks for the great response @vladar. :+1: It actually helps me too, with another concern I have.

Scott

**Comment by vladar** [comment]
Glad to hear! Feel free to reopen this if you have other problems with mutations.

**Comment by chrissm79** [comment]
@vladar Did you have to create some sort of interface for your types? I'm having an issue when attempting to run an [update mutation] (https://gist.github.com/chrissm79/d7142f52480ff8fd3c46). It successfully sends the request to the server and gets a successful response with the updated data, but the component never reflects any of the changes. Asking around, someone mentioned that it may be an issue with [Object Identification] (https://facebook.github.io/relay/docs/graphql-object-identification.html). Just curious if you've found a solution for this as well. Thanks again @vladar !

**Comment by vladar** [comment]
@chrissm79 Yeah, you need `Node` interface and each of your entity types must implement this interface.

Basically this interface only has one field `id` of type `ID` (`Type::id()`). Then when you map response in Mutation.getConfigs(), Relay expects you to use `id` field (not `entity_id` as you do now).

So your `getConfigs()` would look like:
```js
{
  type: 'FIELDS_CHANGE',
  fieldIDs: {
    customer: this.props.customer.id, // <-- note, this must be field `id` of type `ID`, not `String`
  }
}
```

Also note, that Relay requires your `Query` type to contain top-level field `node` of type `Node` with `id` argument.

Another requirement is that you must be able to fetch your entity using this `id`. For example in my case `id` is composed of `entity_id` and `entity_type`, so that it globally identifies your `entities`.

Make sure to check docs on https://facebook.github.io/relay/docs/graphql-object-identification.html

Also, this JS helper has some hints on how to define these types: https://github.com/graphql/graphql-relay-js/blob/master/src/node/node.js

**Comment by smolinari** [comment]
A bit of an off-topic question, and because I am too lazy to go looking for the code, but does graphq-php make up the opaque IDs automatically or does that need to be covered by the underlying model to offer such IDs to graphql-php?

Scott

**Comment by vladar** [comment]
No, graphql doesn't provide any opaque ids automatically. Your data is your data. Maybe `laravel-graphql` does something here, but I am not aware of that.

**Comment by smolinari** [comment]
Cool. That is actually good and the answer I was hoping for, because I have [a different method to create opaque (hashed) ids](http://hashids.org/), than base64 encoding, like the Facebook docs suggest.

Scott

**Comment by vladar** [comment]
Yes, you can use such tools. base64 is just one of the options. Relay doesn't care much on how you encode your ids.

But note, that you should be able to fetch any node given the `id` only.

So, in RDBMS terms, if you have 10 tables for entities with autoincrement ids, Relay `id` must somehow encode both - table + row id, otherwise you won't be able to determine which table to query against.

**Comment by smolinari** [comment]
Yes, yes. Of course. :smile: 

Or, you actually [have a database](http://orientdb.com/), which has defined, system wide unique ids for all records and can query on the ids to find the records directly and anywhere in the (distributed) system. :wink:

SELECT * FROM someId 

That is cool stuff, isn't it? Oh, and actually, all graph databases can do that, but with differing commands for their supported query languages. :smile: 

Scott

**Comment by chrissm79** [comment]
@smolinari That's pretty slick that OrientDB can do that! I'll have to check that out. 

Unfortunately, I am indeed working with data that is in a MySQL DB and auto-increments all of it's IDs (it's a [Magento] (http://magento.com/) store). So, since that's the case what I need to do is create a resolve function on my Type's id field that encodes the ID plus some sort of identifier (to tell me which GraphQL Type it is), correct? Just want to clarify for anybody who may be following along. 

The only piece I'm confused on now is what gets called on the ObjectType that is returned from the Interface? The README states that ```Interface types do not participate in data fetching. They just resolve actual object type which will be asked for data when GraphQL query is executed.``` So I'm returning the ObjectType based on the decrypted id argument and I get:

```json
"errors": [
    {
      "message": "Trying to get property of non-object",
      "locations": [
        {
          "line": 17,
          "column": 7
        }
      ]
    }
  ]
```

So it appears to be calling something on the ObjectType that is returned, but I don't know what it is.

**Comment by timbofield** [comment]
@vladar If you get a moment would you also be able to show what the corresponding Relay query would look like in [the above comment](https://github.com/webonyx/graphql-php/issues/11#issuecomment-156105837) ?

I'm trying something like this currently:

```json
{"query": "mutation M { updatePost(input: {id: 10 title: \"New title\"}) { title }} "}
```

Basically I'm not sure how to pass the input argument correctly. The above complains with 

`Argument "input\ expected type UpdatePostInput! but got: {id: 10, title: "New Title"}.`

I've got the the following mutation defined in schema so far *( sorry too much code )* 

```PHP
    function updatePostMutation() {
        return Mutation::mutationWithClientMutationId([
            'name' => 'UpdatePost',
            'inputFields' => [
                'id' => [
                    'type' => Type::id(),
                ],
                'title' => [
                    'type' => Type::string(),
                ],
            ],
            'outputFields' => [
                'post' => [
                    'type' => $this->getPostInterface(),
                    'resolve' => function($payload) {
                        return get_post($payload['id']);
                    }
                ]
            ],
            'mutateAndGetPayload' => function(array $input, ResolveInfo $info) {
                // ... perform mutation ...
                wp_update_post([
                        'ID' => $input['id'],
                        'post_title' => $input['title']
                    ], false);

                return [
                    'id' => $input['id']
                ];
            }
        ]);
    }
```

**Comment by vladar** [comment]
@timbofield Try passing InputObject as query variable vs inlining it? Don't remember if I had time to migrate a part of parser that accepts inlined object values.

Will make sure it works in next major release.

**Comment by vladar** [comment]
Actually, looks like you have to pass input objects as variables in JS version as well. You may check out [GraphiQL chrome extension](https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij) and try to build query there to make sure

**Comment by vladar** [comment]
Summary:
1. Input objects should be passed in as variables, not inlined
2. Field `clientMutationId` is required for your `UpdatePostInput` type, so valid value for your input type is: `{id: 10, title: "New title", clientMutationId: 1}`

**Comment by crirus** [comment]
Hello

I am just starting up with graphql-php. Is there complete example on writing mutation?

Thank you.

**Comment by vladar** [comment]
[This project](https://github.com/ivome/graphql-relay-php) contains helper methods and documentation on how to use this library with Relay

**Comment by crirus** [comment]
Thank you for your reply.
I understand this example. Is there any way to reuse the type definitions from query side?
I managed to make that work pretty well with one of my database entity and now I am facing a redo for all the fields defined there?
I read somewhere that the Input and Output are separate, but still... can't we just use one type?

**Comment by vladar** [comment]
If some of your mutations return the same result then, of course, you can re-use this type for all mutations.

The other option you have is to use interfaces. For example, if you have some CRUD operations and each of your entity implements Node interface, then you can introduce single type for all create/update mutations:

```
type NodeCreateResult {
  ok: Boolean!
  created: Node!
}

type NodeUpdateResult {
  ok: Boolean!
  created: Node!
}


interface Node {
  id
}

type MyEntityType implements Node {
  id
  someField
  someOtherField
}
```
But that's all project-specific. 

As for `InputObjectType` - you use it when your mutation needs complex arguments. For example when you create some deeply-nested structure.

It is also useful in the context of `query` when your fields have complex filters (e.g. `DateRangeInput` as typical example).
