### ISSUE TITLE
PHP 8.1 Deprecated error - Optional parameter $formatter declared before required parameter $debug

### ISSUE THREAD

**Issue by victormacko** [webonyx/graphql-php#1112]
Just upgraded to PHP 8.1 and got this deprecation warning:

Deprecated: Optional parameter $formatter declared before required parameter $debug is implicitly treated as a required parameter in vendor/webonyx/graphql-php/src/Error/FormattedError.php

Hope it helps - let me know if you need any more info or anything to help on my end.

**Comment by spawnia** [comment]
This is fixed in the most recent release.

**Comment by victormacko** [comment]
Oh, nice -- my bad, did a quick scan of the commits but couldn't see it, sorry about that!
Was that already tagged & sent out the door, or still pending release?
