### ISSUE TITLE
01-blog example: id field is resolved incorrectly

### ISSUE THREAD

**Issue by apapacy** [webonyx/graphql-php#114]
01-blog example [Type.name] in response - {"user": {"id": "ID" ...  
php5.6, php7.0

![image](https://cloud.githubusercontent.com/assets/4279840/25583946/9ed4ec1e-2e9c-11e7-880f-da512bee7cb5.png)

**Comment by TerraSkye** [comment]
you mean the "likes" is null?

can u please clarify what your trying to express

**Comment by apapacy** [comment]
I want to see in the in the response
`{
  "data": {
     "user": {
         "id": "1"
`
but get twise
`{
  "data": {
     "user": {
         "id": "ID"
`
**ID** is Type.name. No user identifier.
**"1"** is user idetifyer.
But it not present in the response/

**Comment by TerraSkye** [comment]
found the issue.

UserType extends ObjectType 
ObjectType extends Type
Type contains the static method "id"

Usertype resolves 
```
        if (method_exists($this, $info->fieldName)) {
                    return $this->{$info->fieldName}($value, $args, $context, $info);
                } else {
                    return $value->{$info->fieldName};
                }
```

therefore u get a return "ID" wich is a bug.


repreducable with the folowing query 
```
{
  user(id:1){
    id
  }
}
```

**Comment by TerraSkye** [comment]
#115 https://github.com/webonyx/graphql-php/pull/115 a fix for your usecase

**Comment by vladar** [comment]
Fixed via https://github.com/webonyx/graphql-php/commit/f668300cd87c471a026fd0026c9b9e65e7765554
