### ISSUE TITLE
Lexer wrong location when multiline comments

### ISSUE THREAD

**Issue by olivernybroe** [webonyx/graphql-php#1177]
When using the lexer with a schema that has a multiline comments the location is wrong.

Taken the following schema
```
"""
testing
"""
scalar something
```
It ends up saying that the name token `scalar` is on line 2.

**Comment by spawnia** [comment]
Can you provide a pull request with a failing test case? The issue might be with the lexer, but I think a test for this would fit better with https://github.com/webonyx/graphql-php/blob/e8098fae49e2a007f389aa838796c6c154138744/tests/Language/SchemaParserTest.php#L166.

**Comment by spawnia** [comment]
Fixed with https://github.com/webonyx/graphql-php/releases/tag/v15.11.1
