### ISSUE TITLE
InputObjectType parse value not working

### ISSUE THREAD

**Issue by Warxcell** [webonyx/graphql-php#1178]
Its documented under: https://webonyx.github.io/graphql-php/type-definitions/inputs/#converting-input-object-array-to-value-object

But it simply arrives as array.

I was able to follow it down to https://github.com/webonyx/graphql-php/blob/master/src/Utils/AST.php#L392-L435

its simply not called at all.

**Comment by spawnia** [comment]
The docs reflect the latest changes in `master` which are not yet released. I recognize this is a problem so I created https://github.com/webonyx/graphql-php/issues/1179

**Comment by Warxcell** [comment]
> The docs reflect the latest changes in `master` which are not yet released. I recognize this is a problem so I created #1179. For now you can either use `master` or look at https://github.com/webonyx/graphql-php/tree/14.x/docs.

I saw that it exists only in master - I upgraded and still not working.

**Comment by Warxcell** [comment]
This is the entrypoint:

https://github.com/webonyx/graphql-php/blob/master/src/Executor/ReferenceExecutor.php#L690
it calls this
https://github.com/webonyx/graphql-php/blob/master/src/Executor/Values.php#L180
then it calls this
https://github.com/webonyx/graphql-php/blob/master/src/Executor/Values.php#L205
which calls this
https://github.com/webonyx/graphql-php/blob/master/src/Executor/Values.php#L269

which returns array, not the result of parseValue fn.

**Comment by Warxcell** [comment]
was able to reproduce it when used with SchemaExtender. See https://github.com/webonyx/graphql-php/pull/1180
