### ISSUE TITLE
Out of memory on error

### ISSUE THREAD

**Issue by pascaldevink** [webonyx/graphql-php#119]
I've noticed that there is an error that, once throw, results in an out of memory exception. This is particularly annoying, as it hides the actual error.

It seems to happen when there is a type mismatch, and an object type was expected and an interface or union type was returned. I've traced it down to here: https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L986
I'm pretty sure the `print_r` call is the culprit (educated guess though), but I'm not sure how to replace it, while still providing the same valuable information.

**Comment by vladar** [comment]
Oh, you are right. This is a bug.

**Comment by vladar** [comment]
Fixed in https://github.com/webonyx/graphql-php/commit/6fb62b25b35f7252e8b2c3baad7540cfa73ec8a5

Will be included in next 0.9.10 release.
