### ISSUE TITLE
When will PHP enums be released

### ISSUE THREAD

**Issue by CalvinMcGee** [webonyx/graphql-php#1192]
The support for [PHP Enums](https://webonyx.github.io/graphql-php/type-definitions/enums/#construction-from-php-enum) have been merged into master some time ago. But a release has yet not been done containing this functionality.

I see nothing mentioning this functionality among the [milestones](https://github.com/webonyx/graphql-php/milestones).

So my simple question is, when will this functionality be released?

**Comment by spawnia** [comment]
See https://github.com/webonyx/graphql-php/issues/1037
