### ISSUE TITLE
Naming a Type like a callable function in scope calls the existing function even if its unintended

### ISSUE THREAD

**Issue by oneserv-heuser** [webonyx/graphql-php#1193]
I have a Type called 'Link'. When resolving the schema with webonyx/graphql-php since 14.0.0 I get the following error:
```
.ERROR: link() expects exactly 2 parameters, 0 given
```
This happens because of the following lines, especially line 1028:

https://github.com/webonyx/graphql-php/blob/d0b7c5270e155c9d7369c5d35dd4731d98e8ba52/src/Executor/ReferenceExecutor.php#L1026-L1032

The [is_callable doc](https://www.php.net/manual/en/function.is-callable.php) says that it returns whether a value can be called as a function from the current scope. As the function is used in line 1028 any Type with a name same as any function callable from the ReferenceExecutor class scope will be handled as callable instead of a Type.

That leads to the execution of Schema::resolveType() and the passed argument is now "Link". Now the php "link" function is called and leads to the error as no parameters are given.
https://github.com/webonyx/graphql-php/blob/d0b7c5270e155c9d7369c5d35dd4731d98e8ba52/src/Type/Schema.php#L318-L325

This works with any function callable from the ReferenceExecutor class scope.
An easy fix I tested for my use case would be to add a !is_string check to [line 1028 from the ReferenceExecutor.](https://github.com/webonyx/graphql-php/blob/d0b7c5270e155c9d7369c5d35dd4731d98e8ba52/src/Executor/ReferenceExecutor.php#L1028)
```PHP
if ($typeCandidate === null) {
    $runtimeType = static::defaultTypeResolver($result, $exeContext->contextValue, $info, $returnType);
/** added !is_string check**/
} elseif (is_callable($typeCandidate) && !is_string($typeCandidate)) {
    $runtimeType = $typeCandidate();
} else {
    $runtimeType = $typeCandidate;
}
```

**Comment by spawnia** [comment]
Thanks for the report. Please try and add a pull request with a failing test, probably in https://github.com/webonyx/graphql-php/blob/master/tests/Type/LazyTypeLoaderTest.php or https://github.com/webonyx/graphql-php/blob/master/tests/Executor/ExecutorLazySchemaTest.php.

**Comment by oneserv-heuser** [comment]
@spawnia Added a test, as requested in #1194
