### ISSUE TITLE
conflict because they return conflicting types

### ISSUE THREAD

**Issue by videni** [webonyx/graphql-php#1198]
```
interface A {
    label: String!
}

type B implements A {
  label: String!
 default: Float! 
}

type C implements A {
  label: String!
  default: Boolean!
}

Query {
    all: [A]
}

query something {
   all {
        label
        ... on B {
            default
        }
        ... C {
            default
        }
    }
}
```
Will get error 
```
Fields \"default\" conflict because they return conflicting types Float! and Boolean!. Use different aliases on the fields to fetch both if this was intentional.
```

I know we can add alias to the default field, but this is quite verbose,  since the `default` field is not in the interface A,  it is valid that each type  has  a same field with different type. I am wondering why we enforce  the  rule above, is it safe to remove this fule?  any bad sife effects if I remove it for this case?  as I know ,  Shopify GraphQL API doesn't has this rule.

**Comment by spawnia** [comment]
This rule follows from the specification, see https://spec.graphql.org/draft/#sec-Field-Selection-Merging.Explanatory-Text.
