### ISSUE TITLE
StandardServer response dont support UTF-8

### ISSUE THREAD

**Issue by Kagayakashi** [webonyx/graphql-php#1199]
StandardServer response dont support UTF-8.
Where json_encode function calls, need to add UTF8 support.

**Comment by spawnia** [comment]
How is the current behaviour problematic?

**Comment by Kagayakashi** [comment]
> How is the current behaviour problematic?

At this moment we are working on Graphql API and using StandardServer.
We have multilanguage response and cyrillic is not supported.

We can make a temporary solution if graphql-php release is delayed, but preferable avoid temporary solutions.
