### ISSUE TITLE
IDType validated incorrectly

### ISSUE THREAD

**Issue by akomm** [webonyx/graphql-php#121]
For IDType, resolving types which can not be casted to string raises a `Notice: X to string conversion`.
Happens in any case, when `GraphQL\Executor\Values::isValidPHPValue` is executed.

For example this results in 500 internal errors in [overblog/GraphQLBundle](https://github.com/overblog/GraphQLBundle), in mutations, when an invalid ID is set as input, instead of proper graphql validation error response.

**Comment by vladar** [comment]
Can you provide a reproducible example for this error?

**Comment by akomm** [comment]
Added a test for the mutation argument test:

https://github.com/akomm/graphql-php/tree/test-case-issue-121

`$ bin/phpunit --filter ArgumentsOfCorrectType`

Same happens, when you resolve object for string type.

**Comment by vladar** [comment]
Sorry for long delay on this. 

This test doesn't seem right. Validator works against AST values which are always strings (provided by parser). So if you want to test that object value fails on argument of string type it must be written differently. Like this:

```php
    /**
     * @it Object into String
     */
    public function testObjectIntoString()
    {
        $this->expectFailsRule(new ArgumentsOfCorrectType(), '
        {
          complicatedArgs {
            stringArgField(stringArg: {prop: "val"})
          }
        }
        ', [
            $this->badValue('stringArg', 'String', '{prop: "val"}', 4, 39)
        ]);
    }
```

vs:

```php
   /**
     * @it Object into String
     */
    public function testObjectIntoString()
    {
        $this->expectFailsRule(new ArgumentsOfCorrectType(), '
        {
          complicatedArgs {
            stringArgField(stringArg: 1)
          }
        }
        ', [
            $this->badValue('stringArg', 'Object', ['prop' => 'val'], 4, 39)
        ]);
    }
```

But then the test passes. So it is still not clear what your actual problem is.

**Comment by vladar** [comment]
Actually I realized what you mean (but unfortunately test case didn't help much). Fixed in https://github.com/webonyx/graphql-php/commit/8fe26a1a21e3a96e470b5712bc9d392239e8308f
