### ISSUE TITLE
Confusing usage of InvariantViolation error

### ISSUE THREAD

**Issue by mcg-web** [webonyx/graphql-php#123]
There some confusing usage of `GraphQL\Error\InvariantViolation` error in the lib, sometime this error is use to send some useful information to graphQL clients (wrong types value parsing [like here](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/IntType.php#L60)) and sometime we use it to send system error (sensitive information) that should not be display to client ([here an example](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/ResolveInfo.php#L155)). Can we separate both information throw two distinct exception? This we help to create a more safe prod environment without hiding useful errors to client...

**Comment by vladar** [comment]
Agree. In general invariant violation should be used for system errors only. This exception should not be used for errors exposed to clients. 

Can you prepare PR for suggested changes? Let me know if you need anything from me to make it happen.

**Comment by mcg-web** [comment]
Ok i'll PR this. Thank you for quick answer ;).
