### ISSUE TITLE
Deprecated: Using ${var} in strings is deprecated in php 8.2.1

### ISSUE THREAD

**Issue by Kagayakashi** [webonyx/graphql-php#1273]
PHP version is 8.2.1
Deprecated:
Using ${var} in strings is deprecated, use {$var} instead in /vendor/webonyx/graphql-php/src/Validator/Rules/ValuesOfCorrectType.php on line 182

**Comment by spawnia** [comment]
This will be fixed in v15, see https://github.com/webonyx/graphql-php/pull/1260#issuecomment-1357373079
