### ISSUE TITLE
Describing Error for InvariantViolation

### ISSUE THREAD

**Issue by tim-hanssen** [webonyx/graphql-php#1306]
Hi!

I was looking for a way to generate a more describing error instead of the "Internal server error" after a InvariantViolation exception.

`throw new InvariantViolation("Runtime Object type \"{$runtimeType}\" is not a possible type for \"{$returnType}\".");`

It would be nice to show the user what is going wrong.

Any suggestions?

**Comment by spawnia** [comment]
https://webonyx.github.io/graphql-php/error-handling

**Comment by tim-hanssen** [comment]
Hey @spawnia I founded that one indeed reference -> https://webonyx.github.io/graphql-php/error-handling/#schema-errors

But if I just create a simple test exactly what is in that example, the InvariantViolation exception is not caught by the try/catch. It will just give a normal response with the Internal server error from the Executor.

**Comment by spawnia** [comment]
https://webonyx.github.io/graphql-php/error-handling/#debugging-tools

**Comment by tim-hanssen** [comment]
That was it!

But the docs contain a bug

`If you only want to re-throw Exceptions that are not marked as safe through the ClientAware interface, use the flag Debug::RETHROW_UNSAFE_EXCEPTIONS.`

`Debug::RETHROW_UNSAFE_EXCEPTIONS` should be `DebugFlag::RETHROW_UNSAFE_EXCEPTIONS`

**Comment by tim-hanssen** [comment]
https://github.com/webonyx/graphql-php/pull/1307

**Comment by tim-hanssen** [comment]
Looks great!
