### ISSUE TITLE
Multiple custom errors from a single resolve function

### ISSUE THREAD

**Issue by clintburgos** [webonyx/graphql-php#133]
Hello,

I'm aware that custom errors are possible by throwing an exception in a resolve function, but I have a case where I need to add multiple errors from a single resolve. I'm currently switching from the Youshido implementation of GraphQL to this one, and in that implementation the execution context is passed as part of the ResolveInfo and so errors could be added to it directly.

Is there a way to add multiple custom errors from a single resolve? If not, I'd love something similar to what I mentioned above in this implementation.

Thanks,
Clint

**Comment by vladar** [comment]
Every resolver has following signature: `($value, $arguments, $contextValue, ResolveInfo $info)`

Note that `$context` is your own value which is passed in 4th argument of GraphQL::execute() call:

```php
GraphQL::execute($schema, $query, $rootValue, $contextValue, $variableValues);
```

So you can easily pass your own context object with any error collecting logic. Also `ResolveInfo` has all the information you may need to enhance error reporting (e.g. `$info->path` property).

**Comment by clintburgos** [comment]
Wow, thanks for the quick reply. This is exactly what I was looking for and it works well. Thanks!
