### ISSUE TITLE
Typed property App\\Domain\\GraphQL\\Data\\Customers::$addressLine2 must be string, null used

### ISSUE THREAD

**Issue by dovanmanh080485** [webonyx/graphql-php#1334]
`{
  "errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ],
      "path": [
        "customers"
      ],
      "extensions": {
        "debugMessage": "Typed property App\\Domain\\GraphQL\\Data\\Customers::$addressLine2 must be string, null used"
      }
    }
  ],
  "data": {
    "customers": null
  }
}`
Class Customers:

`declare(strict_types=1);

namespace App\Domain\GraphQL\Data;

use GraphQL\Utils\Utils;

class Customers
{
    public  string $customerNumber;
    public  string $customerName;
    public  string $contactLastName;
    public  string $contactFirstName;
    public  string $phone;
    public  string $addressLine1;
    public  string $addressLine2;
    public  string $city;
    public  string $state;
    public  string $postalCode;
    public  string $country;
    public  string $salesRepEmployeeNumber;
    public  string $creditLimit;

    /**
     * @param array<string, mixed> $data
     */
    public function __construct(array $data)
    {

        Utils::assign($this, $data);

    }
}`

Hello everyone!
I'm trying to create a GraphQL example, but I keep getting the error message mentioned above. Can you please let me know what's causing this?
Thank you!

**Comment by spawnia** [comment]
This is really just a problem in your code. The issue tracker is not a general support forum.
