### ISSUE TITLE
0.9.11 not support dynamic build schema

### ISSUE THREAD

**Issue by tsingsun** [webonyx/graphql-php#135]
my app build schema when client request ,it will according client query.client query may be only mutation,like "mutation login .....",the backend build the schema bellow
```php
$schema = new Schema([
  'query'=>null,//because the query is mutation ,so it is null
  'mutation'=>$mutation,//var $mutaion is mutation login,
 'types'=>$types
])
```
before 0.9.11 the code work fine,but 0.9.11,it will throw exception:
Schema query must be Object Type but got: NULL..

so i change the code 
```php
//config is null or [] or query config
$query = new ObjectType($config);
$schema = new Schema([
  'query'=> $query,
  'mutation'=>$mutation,//var $mutaion is mutation login,
 'types'=>$types
])
```
it works ,but extend other problem when the  api backend only have mutation,the schema  introspection query in chrome GraphiQL throw exception
Error: Query fields must be an object with field names as keys or a function which returns such an object.

i don't think the validator is a good idea,it is not support dynamic build schema.

**Comment by TerraSkye** [comment]
i solved it with returning an empty array.

**Comment by tsingsun** [comment]
i update the issue..more description

**Comment by TerraSkye** [comment]
To solve that u gotta leave query out of the array send too schema

**Comment by tsingsun** [comment]
$result = new Schema([
            'mutation' => $mutation,
            'types' => $types
        ]);
it does not work

**Comment by TerraSkye** [comment]
i fixed it this way (https://github.com/TerraSkye/yii1-graphql/blob/master/components/GraphQL.php#L111) 
i made a port for yii1 of your implementation. and had the same issue.

**Comment by vladar** [comment]
@tsingsun The query is required part. I am curious which version you were using before (which allowed query to be null)? That previous behavor was actually buggish, not the current one.

Quote from [GraphQL spec](http://facebook.github.io/graphql/#sec-Initial-types): 
```
The query type must always be provided, and is an Object base type.
```

If you really want to have empty query, just pass an empty object type:

```php
$result = new Schema([
  'query' => new ObjectType(['name' => 'Query', 'fields' => []])
  'mutation' => $mutation,
  'types' => $types
]);
```

**Comment by tsingsun** [comment]
ths,its usefull..sorry,I made a mistake,the graphql version is correct.
