### ISSUE TITLE
PHP 8.2 compatibility issue: Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by kirkmadera** [webonyx/graphql-php#1376]
This seems like a quick fix, so I am making an issue. This happens when making any call to the GraphQL endpoint before opcache has stored it.

> Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in vendor/webonyx/graphql-php/src/Validator/Rules/ValuesOfCorrectType.php on line 183

**Comment by kirkmadera** [comment]
Confirmed that my PR fixes the issue I am running into

**Comment by spawnia** [comment]
See https://github.com/webonyx/graphql-php#versioning:

> Older versions are no longer supported.
