### ISSUE TITLE
Schema must contain unique named types but contains multiple types named "%s" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).

### ISSUE THREAD

**Issue by jeroendesloovere** [webonyx/graphql-php#1396]
Hi there,

**Context**
When upgrading from pimcore 10.1 tot 10.5, webonyx/graphql-php also upgraded from v14.9.0 to v14.11.9.
Suddenly we are getting the following error:
```
Schema must contain unique named types but contains multiple types named "%s" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).
```
and %s = "dimensions" in our case.
![graphql-error](https://github.com/webonyx/graphql-php/assets/588616/b1cbbb85-1cbe-48fa-ba19-db9ca77798f2)

We are not even executing a query, just opening the graphql explorer.

**Questions**
Can somebody explain to us what that error actually means. Perhapse by using an example, so that is clear to us?

**Comment by spawnia** [comment]
This validation triggers when multiple instances of a type with a given name are present in the schema, you must only ever have one. See https://webonyx.github.io/graphql-php/schema-definition/#lazy-loading-of-types.

Also, I recommend v15, it fixes a lot of issues.
