### ISSUE TITLE
how ObjectType reuse in graphql argument

### ISSUE THREAD

**Issue by tsingsun** [webonyx/graphql-php#140]
graphql argument use InputObjectType,and i defined biz types use ObjectType.usually,model reuse in the DTO, client get a model , commit the model when assigned values.  so i use a objectType in mutation look like 
```php
//the userType is instance of ObjectType
'updateUser' => [
                        'type' => Type::boolean(),
                        'args' => ['user' => ['type' => Types::UserType()]],
                    ],
```
but it doesn't work,how can i reuse the ObjectType when commit data thought mutation args

**Comment by vladar** [comment]
Short answer is: you can't. You must create separate UserInputType with some fields from UserType which make sense in write context. 

But you can re-use scalar and enum fields from UserType, for example:

```php
$userType = Types::UserType();

$inputUserType = new InputObjectType([
  'name' => 'InputUserType',
  'fields' => [
    $userType->getField('id'),
    $userType->getField('email'),
    // etc...
  ]
]);
```

**Comment by tsingsun** [comment]
thx,is there a plan to support that?

**Comment by vladar** [comment]
No. Input and output types are separate by GraphQL design and spec. 

And in practice, write and read models are often different. You may have lots of fields in your UserType which shouldn't be allowed in write context (say list of user friends which may be nested indefinitely).
