### ISSUE TITLE
EnumType with boolean values won't work

### ISSUE THREAD

**Issue by janaleible** [webonyx/graphql-php#141]
I have an EnumType with values mapping to true and false. Trying to query a field of this type results in the error "array_key_exists(): The first argument should be either a string or an integer".
However, according to the [documentation](http://webonyx.github.io/graphql-php/type-system/enum-types/), this should work: 

> value, type mixed, Internal representation of enum item in your application (could be any value, including complex objects or callbacks)

This seems to be the result of how enumValues are handled internally: they are represented as an array where the value is the key to an object holding information such as the enum value's name. True/false are converted to 1/0, however, when checking whether the given value is valid, array_key_exists () is called with the boolean value rather than an integer, which results in above exception (in `MixedStore.php`, line 72).

I'm using version 0.9.2 with PHP 7.1

**Comment by vladar** [comment]
You are right, this is a bug. In the meantime you can use 0 and 1 for values instead.

**Comment by vladar** [comment]
Closed via https://github.com/webonyx/graphql-php/commit/bc6a7a3d1dd7b3d3f6b242fd94fc628c28c9c1cb (will publish in v0.9.12 soon)
