### ISSUE TITLE
Potential unaddressed DDOS vector - how can I privately report this?

### ISSUE THREAD

**Issue by GuySartorelli** [webonyx/graphql-php#1430]
Hi there,

I've found what might be a DDOS vector in this library that is currently not addressed by any mitigations I was able to find. I would like to report this privately to maintainers so that you can work on a fix without risking bad actors becoming aware of it prematurely.

Is there an email address or something I can use to get in contact with maintainers about this? The GitHub link for your security policy just shows me the docs about your existing mitigations rather than an actual policy for reporting security vulnerabilities 😅

Cheers.

**Comment by shmax** [comment]
Surely, a crafty security researcher can sniff out the email of one of the maintainers (hint: look at github profile pages, or clone repo and inspect commit metadata using `git log`)...

**Comment by GuySartorelli** [comment]
I'm not a security researcher, and I'd rather not send emails to people at random if there's a preferred way the maintainers would like me to use to get in contact with them.

**Comment by shmax** [comment]
Yes, and the maitainer's email is listed right on his profile page.

**Comment by spawnia** [comment]
See https://github.com/webonyx/graphql-php/commit/928f27ccba5635957a0e31d4c1b1787de3a9dd58.
