### ISSUE TITLE
Fatal error: Class 'GraphQL\Blog\Data\DataSource' not found 

### ISSUE THREAD

**Issue by nbulusanjr** [webonyx/graphql-php#144]
Am I missing something?

**Comment by vladar** [comment]
You are missing at least some more details to reproduce this %)

At least:
1. What example you were using?
2. What was the GraphQL query you were trying to run

**Comment by vladar** [comment]
Quick search over source files doesn't find any `GraphQL\Blog\Data` namespace.  Only `GraphQL\Examples\Blog\Data`. 

So I am curious which code is producing this error. Is it your custom code or code of one of the examples?

**Comment by nbulusanjr** [comment]
Hi vladar. I think i figured it out already. I forgot to do a composer install on the root directory. Thank you.
