### ISSUE TITLE
PHP attribute field definition for not null?

### ISSUE THREAD

**Issue by jsakars** [webonyx/graphql-php#1462]
Hi!

`#[GQL\Field(type: Type::STRING)]` can be used to specify that given input field is a string - nullable

In order to define not null string the only option is: `#[GQL\Field(type: 'String!')]`

Is there a smoother option rather then using string `'String!`? Something like `#[GQL\Field(type: Type::STRING!)]` maybe?

**Comment by spawnia** [comment]
This library does not implement any PHP attributes, your issue belongs elsewhere.

**Comment by jsakars** [comment]
@spawnia what about these [ones](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/Type.php#L14-L18) then? Those are used in `overblog/GraphQLBundle` => see [here](https://github.com/overblog/GraphQLBundle/blob/e2a114ba14022799604681ce20bc23cf68cfb038/src/Generator/TypeBuilder.php#L13) and [here](https://github.com/search?q=repo%3Aoverblog%2FGraphQLBundle%20Type%3A%3ASTRING&type=code)

**Comment by spawnia** [comment]
Those are constants which hold a string. Looks like your issue belongs into `overblog/GraphQLBundle`.
