### ISSUE TITLE
Defining a fragment before the query results in an error

### ISSUE THREAD

**Issue by TheGlenn88** [webonyx/graphql-php#1478]
Hi,

I've been implementing the Type Registry, following the docs:
https://webonyx.github.io/graphql-php/schema-definition/#lazy-loading-of-types

and using the example
https://github.com/webonyx/graphql-php/tree/master/examples/01-blog

What i've found is that if you define a fragment before the query like this:
```
fragment Name on User {
  firstName
}

{
  user(id: 1) {
    ...Name
  }
}
```

it throws an exception: `Exception: Unknown graphql type: User`

if you write the query the other way around

```
{
  user(id: 1) {
    ...Name
  }
}

fragment Name on User {
  firstName
}
```

It returns the user record correctly.

I've been having this problem in my own implementation and spent a long time trying to fix my code and accidentally found that removing the fragment removed the error, so I realised it was some sort of issue with the fragment.

Is this a bug of graphql-php or is this a problem with the Type Registry implementation?

For reference, I ran the same query against an express-graphql implementation and it doesn't matter which way around the fragment is defined.

Thanks
Mike

**Comment by spawnia** [comment]
@shmax I believe the issue here is that the implementation of `Types::byTypeName()` introduced in https://github.com/webonyx/graphql-php/pull/1363 is insufficient. That function is used as `Schema.typeLoader`, it needs to be able to locate and instantiate types that were not yet loaded.
