### ISSUE TITLE
Recursive definitions won't seem to work

### ISSUE THREAD

**Issue by rkrx** [webonyx/graphql-php#149]
I've tried to define a schema with a recursive definition. In theory, I have a user that belongs to _n_ groups and each group has _n_ users. So my [definition of a _User_](https://gist.github.com/anonymous/6fc7c63870f9078a94ee01b940490c08#file-index-php-L14-L36) would look like this:

```php
$config = [
	'name' => 'User',
	'fields' => function () {
		return [
			'id' => Type::id(),
			...
			'groups' => new ListOfType(new GroupType()),
		];
	},
	...
];
```

And the [definition of a _Group_](https://gist.github.com/anonymous/6fc7c63870f9078a94ee01b940490c08#file-index-php-L42-L67) should look like this:

```php
$config = [
	'name' => 'Group',
	'fields' => function () {
		return [
			'id' => Type::id(),
			'users' => new ListOfType(new UserType()),
		];
	},
	...
];
```

[Here](https://gist.github.com/anonymous/6fc7c63870f9078a94ee01b940490c08) is a full, (non-)working example. When I run this query...

```graphql
query {
  user (id: 123) {
    id
    active
    name
    groups {
      id
      users
    }
  }
}
```

I get this error:

```
GraphQL\Error\InvariantViolation: Schema must contain unique named types but contains multiple types named "User". in vendor\webonyx\graphql-php\src\Utils.php on line 221
```

I'm using v0.9.13 right now.

**Comment by vladar** [comment]
This error is not related to recursive definitions. You are creating a new instance of a type in every definition and most likely you have multiple instances of `GroupType` or `UserType` in your schema.

Each type must be represented by single instance within one schema. So you need some sort of registry for your types. Make sure to read the section of docs [about type registry](http://webonyx.github.io/graphql-php/type-system/#type-registry)

**Comment by rkrx** [comment]
Thank you! I've fixed the issue by ensuring, that only one instance of each definition is used per Schema. May be you should include a link to the registry-doc in that error message since the error-message is somewhat ambiguous.

**Comment by vladar** [comment]
Makes sense, thanks for your advice.

**Comment by vladar** [comment]
Done in v0.10.0
