### ISSUE TITLE
Question about Interfaces 

### ISSUE THREAD

**Issue by timbofield** [webonyx/graphql-php#15]
Thank you very much for this great library. 

I've got a question about Interfaces and validation

To [play nice with relay](https://github.com/facebook/relay/issues/112) it seems easier to follow the "node / viewer" pattern. 

So for example a single entry point for all characters ( the node query ) could be implemented like this 

```
return [
            'name' => 'Query',
            'fields' => [
                'character' => [
                    'type' => $characterInterface,
                    'args' => [
                        'id' => [
                            'name' => 'id',
                            'description' => 'global id of the character',
                            'type' => Type::nonNull(Type::string())
                        ]
                    ],
                    'resolve' => function ($root, $args) {
                        return //.. get character by global id
                    }
                ]
                //...
            ]
        ];

```

Then we rely on the resolveType function of our character interface to return a droid or a human type. 

So far so good!

But if I want to add a field that only exists for droids let say "modelNumber" I run into a validation problem, **DocumentValidator fails as it only checks the fields of the interface**, and not the fields of my resolved type.  **Is this a bug ?**

**Comment by vladar** [comment]
Given your description, it sounds like you do not use type-casting in GraphQL query. So for example you have `CharacterInterface` and specific `Droid` and `Human` types. 

Then your query should look this way:

```
{
  character {
    name
    someOtherInterfaceField

    ... on Droid {
      modelNumber
    }

    ... on Human {
      dateOfBirth
    }
  }
}
```

But to say for sure I need to see your query, because DocumentValidator runs against GraphQL query document, so query is important here to debug.

Also I do use this library with Relay and haven't seen such issues, so it shouldn't be a bug.

**Comment by timbofield** [comment]
Thanks you are quite right, I needed to read [this](https://github.com/facebook/graphql) some more. 

Thanks again for a great library.
