### ISSUE TITLE
Is there a way to convert AST back to query string?

### ISSUE THREAD

**Issue by moon0326** [webonyx/graphql-php#151]
Hi,

I'm trying to come up with a way to split graphql servers into multiple servers.

Let's say I have three objects in my schema,

object1: should be queried against server 1
object2: should be queried against server 2
object3: should be queried against server 3

Then I will have an API Gateway that is aware of where those objects are.

My first step is to see if there is a way to get a portion of query. 

Let's say I have the following query

```json
{
  test: Creative{
    id
    products {
      name
    }
  },
  hello: HelloWorld
}
```

I would like to get the following string from "Creative" resolver. It looks like I can get AST from **OperationDefinitionNode** object, but I don't think there is a function that converts AST back to string.

```json
{
  test: Creative{
    id
    products {
      name
    }
  }
}
```

Is there a way to do that already or should I implement it myself?

**Comment by vladar** [comment]
Use printer:
```php
GraphQL\Language\Printer::doPrint($myAst);
```

**Comment by moon0326** [comment]
@vladar Thank you!

Is there a way to access AST in a resolver?

**Comment by vladar** [comment]
Which part of AST?

Resolver signature is `function ($value, $args, $context, ResolveInfo $info)`.

`ResolveInfo` has `$info->fieldNodes` (AST of the resolved field), `$info->operation` (AST of the operation definition) and `$info->fragments` (list of operation fragment ASTs)

**Comment by moon0326** [comment]
@vladar That's all I needed. Thank you so much for taking for to reply!
