### ISSUE TITLE
Order of input object values

### ISSUE THREAD

**Issue by kinglozzer** [webonyx/graphql-php#1524]
When `InputObjectType` values are parsed, they’re re-ordered to match the order they are set in the schema definition:

https://github.com/webonyx/graphql-php/blob/d6c965ecbd78cd5260ebc083978562f8c9409d63/src/Utils/Value.php#L124-L126

We (Silverstripe framework) pass sort order args as input objects, e.g:

Query:
```graphql
query ($sort: SortFields) {
  readObjects(sort: $sort) {
    created,
    name
  }
}
```

Variables:
```json
{
  "sort": {
    "created": "ASC",
    "name": "ASC"
  }
}
```

If `name` was defined first in the schema for `SortFields`, the objects returned will come back in the wrong order as that is what comes through “first” in the resulting query.

Is this something that could be changed in this library? Are we misunderstanding how this ordering works/should we be using a different approach to ensure the order of these sort fields is preserved?

Thanks!

**Comment by LastDragon-ru** [comment]
> Is this something that could be changed in this library?

[According to the spec](https://spec.graphql.org/October2021/#sec-Input-Object-Values.Input-object-fields-are-unordered)

> > Input object fields may be provided in any syntactic order and maintain identical semantic mean
> >
> > These two operations are semantically identical:
> > 
> > ```graphql
> > {
> >   nearestThing(location: { lon: 12.43, lat: -53.211 })
> > }
> > ```
> > ```graphql
> > {
> >   nearestThing(location: { lat: -53.211, lon: 12.43 })
> > }
> > ```


> should we be using a different approach to ensure the order of these sort fields is preserved?

You can use array, but you probably will need to add some check to make sure that only one field passed (until `@oneOf`, #619). You can also check [my package](https://github.com/LastDragon-ru/lara-asp/blob/main/packages/graphql/docs/Directives/@sortBy.md) to see how we a doing it.

```graphql
{
  "sort": [
    {"created": "ASC"},
    {"name": "ASC"}
  ]
}
```
