### ISSUE TITLE
Infinite loop when instantiating StandardServer

### ISSUE THREAD

**Issue by justmoon** [webonyx/graphql-php#153]
The constructor for `StandardServer` calls itself, creating an infinite loop:

https://github.com/webonyx/graphql-php/blob/v0.10/src/Server/StandardServer.php#L82

<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Maximum function nesting level of '256' reached, aborting! in /var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php on line <i>76</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>363000</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/graphql/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0764</td><td bgcolor='#eeeeec' align='right'>9490880</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/graphql/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>17</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>9511952</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php' bgcolor='#eeeeec'>.../StandardServer.php<b>:</b>82</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>9512032</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php' bgcolor='#eeeeec'>.../StandardServer.php<b>:</b>82</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>9512112</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php' bgcolor='#eeeeec'>.../StandardServer.php<b>:</b>82</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>9512192</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php' bgcolor='#eeeeec'>.../StandardServer.php<b>:</b>82</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>9512272</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php' bgcolor='#eeeeec'>.../StandardServer.php<b>:</b>82</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>9512352</td><td bgcolor='#eeeeec'>GraphQL\Server\StandardServer->__construct(  )</td><td title='/var/www/html/vendor/webonyx/graphql-php/src/Server/StandardServer.php' bgcolor='#eeeeec'>.../StandardServer.php<b>:</b>82</td></tr>

Affected versions: 0.10

**Comment by vladar** [comment]
Thanks for reporting! Somehow screwed it up during rebasing. Fixed in https://github.com/webonyx/graphql-php/commit/d95fb461eefe23f357fa6471f5b30e00a04ac974 (will publish v0.10.1 as soon as travis build completes)

**Comment by justmoon** [comment]
@vladar Awesome, thanks for the super-quick reply!

Fantastic library btw! :+1:

**Comment by vladar** [comment]
The server is a new component, not battle-tested yet (although it's main logic is covered by tests), so please report any errors encountered :) 

I will integrate it to an existing project rather soon, so hopefully, it will evolve fast.

**Comment by chrisharrison** [comment]
> will publish v0.10.1 as soon as travis build completes

Does this mean you expect it should be fixed in `0.10.1`? Because I'm on that version according to composer and the constructor is still returning a `new static`.

**Comment by vladar** [comment]
It's easy to check by github tag: https://github.com/webonyx/graphql-php/blob/v0.10.1/src/Server/StandardServer.php#L76

Also, I updated to 0.10.1 myself and it worked fine. I suspect something is wrong with your composer setup. Maybe try a fresh install?

**Comment by chrisharrison** [comment]
Composer was resolving to 0.10.x-dev and it is not fixed on that branch:
https://github.com/webonyx/graphql-php/tree/v0.10

**Comment by vladar** [comment]
Oh, sorry. Forgot to delete this dev branch. Deleted now.

**Comment by chrisharrison** [comment]
👍 Thanks! All working now.
