### ISSUE TITLE
Async example

### ISSUE THREAD

**Issue by adri** [webonyx/graphql-php#154]
First of all, thank you very much for this library. Especially for the great recent release of 0.10 🎉 

I was wondering if there is an example how to setup async processing of resolvers (or their returned promises)? E.g. with something like react/event-loop.

**Comment by vladar** [comment]
@lordthorzonus as far as I remember you were experimenting with ReactPHP version. Any hints how to use it?

**Comment by lordthorzonus** [comment]
@vladar Yup! Currently running a small api gateway in prod and it works like a charm, thanks for the awesome package :). 

@adri We are using https://github.com/lordthorzonus/php-dataloader as the dataloader/batch-loader as it's integrated with React's event-loop. And then returning it's promises from resolvers. In our codebase it looks something like this: 

```php
<?php

class EventType extends AbstractObjectType
{
    protected $name = 'Event';
    
    /**
     * @var TypeRepository
     */
    private $types;

    /**
     * @var CountryByIdLoader
     */
    private $countryLoader;

    public function __construct(TypeRepository $types, CountryByIdLoader $countryLoader)
    {
        $this->types = $types;
        $this->countryLoader = $countryLoader;
    }

    public function fields()
    {
        return [
            'id' => [
                'type' => Type::int(),
            ],
            'country' => [
                'type' => $this->types->getType(CountryType::class),
                'resolve' => function (Event $event) {
                    return $this->countryLoader->load($event->countryId);
                },
            ],
        ];
    }
}
```

Then in our controller endpoint we are just executing the query, telling the event-loop to run and returning the resolved response. **Note that we are using still older version of this package where the results could be either promises or ExecutionResults. (should update soon..)**  This is not the case anymore if I have been following the package's development correctly. Now you should probably just call `GraphQl::promiseToExecute()` and be happy.  Pseudo code example from our codebase:

```php
<?php

class GraphqlController extends Controller
{
    /**
     * @var GraphQl
     */
    private $graphQl;

    /**
     * @var LoopInterface
     */
    private $loop;

    public function __construct(GraphQl $graphQl, LoopInterface $loop)
    {
        $this->graphQl = $graphQl;
        $this->loop = $loop;
    }

    public function queryAction(Request $request)
    {
        $query = $request->getBodyParam('query');
        $variables = $request->getBodyParam('variables');

        $result = $this->graphQl->execute($query, null, null, $variables);

        // There is a possibility in our API gateway that the query isn't using promises at all
        // In that case a normal result is returned. Otherwise we'll handle the promise.
        if (!is_array($result)) {
            return $this->handlePromiseResult($result);
        }

        return $result;
    }
    
    private function handlePromiseResult(Promise $result)
    {
        $response = null;
        
        // Let the EventLoop run to resolve the promises.
        $this->loop->run();
        
        $result->then(
            function ($promiseResult) use (&$response) {
                $response = $promiseResult;
            }
        );
        
        return $response;
    }
}
```

The graphql class that we use is just a small wrapper around `https://github.com/webonyx/graphql-php/blob/master/src/GraphQL.php` which just builds our schema and sets the correct PromiseAdapter in our DI container when it's constructed. 

The same singleton EventLoop is injected from DI container to all our data loaders and to the controller.

Hope this helps! Ping me if there's something you would like to discuss, happy to help :).

**Comment by adri** [comment]
Awesome thanks for the detailed example. This should be enough to get me started.

I was wondering; how are your experiences using async libraries in PHP? I’m thinking about e.g.  MySQL, Memcached and Redis. Any tips, also in regards to using react-php?
