### ISSUE TITLE
Usage of JsonSerializable

### ISSUE THREAD

**Issue by Ngob** [webonyx/graphql-php#158]
Hello,

I am new to graphql and to your lib, so maybe I missunderstood something.
I am using a query with a field  defined as following:
```php
$that = $this;
\GraphQL\Type\Definition\FieldDefinition::create([
            "name" => "FooQuery",
            "type" => $typeRegistry->get((Foo::class)),
            'args'    => [
                'id' => Type::nonNull(Type::id())
            ],
            "resolve" => function($rootValue, $args) use ($that) { // Todo use callable
                return $that->findOneById($args["id"]);
            }
        ]);
```

The function `$that->findOneById($args["id"]);` return a `JsonSerializable` object but it seems as your lib does not support `JsonSerializable` object but only array. Is there any way to make your lib accept a `JsonSerializable` ?
If it is not possible, I wonder why? Is this something wrong to do?
By the way, I can add this feature it if needed.

Thanks,

**Comment by vladar** [comment]
Can you shed some lights on how do you expect it to work? Say your object (returned by `findOneById`) has 10 fields, but a user only requested two fields in his query (not even saying about deeper nesting).

How do you expect `JsonSerializable` to help in this situation?

Also, make sure you understand how resolving works and what a [default resolver](http://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver) is (Note: it supports array, simple objects with public props and `ArrayAccess` interface). 

If default resolver doesn't work for you, you can override it via `fieldResolver` argument of [executeQuery](http://webonyx.github.io/graphql-php/executing-queries/).

**Comment by Ngob** [comment]
At  the begininng I wanted to use the json's representation of my object to be used as the response (this way I just had to maintain jsonSerialize which is farily used in my application). If I understood right, the right way is using default resolver as you said, this way I can manage nesting 👍 
Thanks a lot for your help.

**Comment by vladar** [comment]
I am not sure that we are on the same page, so feel free to ask more question when you get them %)

**Comment by Ngob** [comment]
Thanks you!
