### ISSUE TITLE
Looking for Library to work with AWS AppSync (non amplify)

### ISSUE THREAD

**Issue by slikk66** [webonyx/graphql-php#1584]
Hi - we're running php 8.2 on Debian/bookwork inside of ECS containers.  I would like to do the following inside our PHP app.

- connect to existing to AppSync API @ AWS (in another account)
- sign the request using IAM credentials, but not from the server's IAM role, manually supplied

I don't see any examples/info that seem to suggest this is possible with this library... but this does seem to be the best graphQL library for PHP.

Does anyone know if this is possible?

Some more info:
- PHP will check local vpc memcache for credentials to use on the server side
- If credentials don't exist in memcache, the server will run an "assume role" on a scope-limited role in another account to get short lived credentials, and store them in memcache
- This is needed because AWS AppSync currently doesn't support cross-account resource policies (sure wish it did!)
- PHP will then load the GraphQL client, presumably load some type of transfomer that will sign the request, and then make the call to the GraphQL API @ AppSync

**Comment by slikk66** [comment]
closing issue.. reading more this seems to be server side.. I need a client, my mistake!

**Comment by spawnia** [comment]
I recommend https://github.com/spawnia/sailor as a client.

**Comment by slikk66** [comment]
I'll check out Sailor.  I did get it working with just Guzzle and AWS SDK, but I'm sure I could use some nice touches provided by a nice client.

Here's my solution in case others are curious:

````
    protected function sign(
        RequestInterface $request,
        string $accessKeyId,
        string $secretAccessKey,
        string $sessionToken
    ): RequestInterface {
        $signature = new SignatureV4('appsync', 'us-west-2');
        $credentials = new Credentials($accessKeyId, $secretAccessKey, $sessionToken);

        return $signature->signRequest($request, $credentials);
    }

    public function graphql() {

        $stsClient = new Aws\Sts\StsClient([
            'region' => 'us-west-2',
            'version' => '2011-06-15'
        ]);

        $ARN = "arn:aws:iam::123456:role/iam-crossaccount";
        $sessionName = "grahql-example";

        $result = $stsClient->AssumeRole([
              'RoleArn' => $ARN,
              'RoleSessionName' => $sessionName,
        ]);

        $headers = [
            'content-type' => 'application/json'
        ];

        $body='{"query":"query GetMyItem {\n  getMyItem {\n    id    __typename\n  }\n}\n","variables":{}}';

        $request = new GuzzleHttp\Psr7\Request('POST','https://myappsync.appsync-api.us-west-2.amazonaws.com/graphql',$headers,$body);

        $signed_request = self::sign($request, $result['Credentials']['AccessKeyId'], $result['Credentials']['SecretAccessKey'], $result['Credentials']['SessionToken']);

        $client = new \GuzzleHttp\Client();

        $promise = $client->sendAsync($signed_request)->then(function ($response) {
            echo 'I completed! ' . $response->getBody();
        });
        $promise->wait();

    }
````
