### ISSUE TITLE
How to use it without Composer?

### ISSUE THREAD

**Issue by cinder92** [webonyx/graphql-php#159]
i can't install composer in my server because its shared :/

**Comment by vladar** [comment]
1. Download [source files](https://github.com/webonyx/graphql-php/releases)
2. Set up PSR4-compatible autoloader ([example](http://www.php-fig.org/psr/psr-4/examples/)) 
3. Set "GraphQL\\" namespace to point to "src/" folder of library source files
4. Profit!

In general, it's a standard PHP library, so nothing special.

**Comment by cinder92** [comment]
thanks, after all i need to install composer, but now i'm having another issue, its the first on the list. can you please help me?

**Comment by AmtechInnovarch** [comment]
Is this still the obfuscated process required to use this as a regular library?

Shouldn't the auto-loader be part of the library?

Last time I checked libraries are supposed to set the namespace...

It would be nice if step 2 and 3 were included in the library.

How I want to implement GraphQL-PHP:
```
include_once 'path/to/library/grqphql.php';

$graphql = new GraphQL;

// literally no other lines of code required
```
^^^See how simple that is? That's how PHP is supposed to be.

It's not server-side JavaScript after all. It should not be obfuscated like server-side JavaScript.

**Comment by simPod** [comment]
No
