### ISSUE TITLE
Infinite loop when using recursive types and interfaces

### ISSUE THREAD

**Issue by ooflorent** [webonyx/graphql-php#16]
#### tl;dr

 Splitting `ObjectType#initialize` in two methods would solve the issue.

#### Details

When using recursive types with interfaces `InterfaceType::addImplementationToInterfaces`, `ObjectType#initialize` and `ObjectType#getInterfaces` result in an infinite loop. Using the same implementation as the JS version would solve the issue since `getInterfaces` would not trigger `getFields`.

**Comment by vladar** [comment]
Thanks for submitting! 

Can you provide an example schema to reproduce this? GraphQL shorthand notation will work (like `interface Character {name: String}`, `type Human : Character {name: String}`, etc)

**Comment by ooflorent** [comment]
Sure. 

```js
interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  blogs: [Blog!]!
}

type Blog implements Node {
  id: ID!
  owner: User!
}
```

Note that the structure is similar to Relay but is not. Our schema is so big that our types must not be defined in specific order. We use closures to define fields. e.g.

```php
abstract class ObjectDefinition {
  abstract protected function name() {}
  
  protected function fields() { return []; }
  protected function interfaces() { return []; }
    
  public function toType(TypeResolver $resolver) {
    $resolveFields = function () use ($resolver) {
      $fields = $this->fields();

      foreach ($fields as $name => &$def) {
        $def['type'] = $resolver->resolveType($def['type']);
      }

      return $fields;
    };

    $resolveInterfaces = function () use ($resolver) {
      $interfaces = $this->interfaces();

      foreach ($interfaces as $name => &$def) {
        $def = $resolver->resolveType($def);
      }

      return $interfaces;
    };

    return new ObjectType([
      'name' => $this->name(),
      'fields' => $fields,
      'interfaces' => $interfaces,
    ]);
  }
}

class Blog extends ObjectDefinition {
  protected function name() {
    return 'Blog'; 
  }

  protected function interfaces() {
    return ['Node'];
  }

  protected function fields() {
    return [
      'id' => ['type' => 'ID!'],
      'owner' => ['type' => 'User!'],
    ];
  }
}
```

**Comment by vladar** [comment]
Hey, maybe I am missing something, but `graphql-php` supports closures for field types for recursive cases like this. Have you tried it?

Something like this:
```php
$blog = new ObjectType([
  'name' => 'Blog',
  'fields' => [
    'owner' => function() use ($typeFactory) {
      return $typeFactory->user();
    }
  ],
  'interfaces' => [],
]);

$user = new ObjectType([
  'name' => 'User',
  'fields' => [
    'blogs' => Type::listOf(function() use ($typeFactory) {
      return $typeFactory->blog();
    })
  ]
]);

// Same should work for interface fields as well
```

But I guess I understand what you mean - having whole fields / interfaces array as closure is a better way to do this than defining closures per-field.

**Comment by ooflorent** [comment]
Your snippet would work but is not a viable solution. The bug is introduce by `ObjectType::initialize`. Removing the validation logic and moving field-related checks to `getFields` and interface-related fields to `getInterfaces` would solve the issue (just like the JS implementation). Such modification would reduce the configuration complexity of object types.

**Comment by vladar** [comment]
Fixed in https://github.com/webonyx/graphql-php/commit/98e5835620ec14c8b24fb178dfabd2d8abdf03c2
