### ISSUE TITLE
Unexpected EOF (End of file) after install it with composer

### ISSUE THREAD

**Issue by cinder92** [webonyx/graphql-php#160]
im receiving this error after install in real server

```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL (1:1) Unexpected <EOF>\n\n1: \n   ^\n",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
```

Code

```
<?php
require __DIR__."/vendor/autoload.php";

use GraphQL\GraphQL;
use GraphQL\Type\Schema;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;

$queryType = new ObjectType([
    'name' => 'Query',
    'fields' => [
        'echo' => [
            'type' => Type::string(),
            'args' => [
                'message' => Type::nonNull(Type::string()),
            ],
            'resolve' => function ($root, $args) {
                return $args['message'];
            }
        ]
    ]
]);

$schema = new Schema([
    'query' => $queryType
]);

$rawInput = file_get_contents('php://input');
$input = json_decode($rawInput, true);
$query = $input['query'];
$variableValues = isset($input['variables']) ? $input['variables'] : null;

// var_dump([
//     "request" => $_REQUEST,
//     "raw_input" => $rawInput,
//     "query" => $query,
//     "variables" => $variableValues
// ]);

try {
    $rootValue = ['prefix' => 'You said: '];
    $result = GraphQL::executeQuery($schema, $query, $rootValue, null, $variableValues);
    $output = $result->toArray();
} catch (Exception $e) {
    $output = [
        'errors' => [
            [
                'message' => $e->getMessage(),
                'input' => $input,
                'query' => $query
            ]
        ]
    ];
}
header('Content-Type: application/json');
echo json_encode($output);
```

NOTE : Is NOT the `catch` from example

any ideas?

**Comment by vladar** [comment]
This error means that you pass empty query to execution. So what does `var_dump` shows for the `$query` variable before execution?

I suspect that you have invalid request (either GET vs POST or unexpected request body structure). You may try [StandardServer](http://webonyx.github.io/graphql-php/executing-queries/#using-server) instead, which will parse the request for you and report request-related errors.

**Comment by cinder92** [comment]
var dump

```
array(4) { ["request"]=> array(6) { ["cartstack_com-cartid"]=> string(0) "" ["__utma"]=> string(54) "111872281.82465390.1480367970.1496335355.1496339142.13" ["__utmz"]=> string(70) "111872281.1480367970.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)" ["__atuvc"]=> string(25) "0|28,0|29,0|30,14|31,2|32" ["_ga"]=> string(25) "GA1.1.82465390.1480367970" ["SQLiteManager_currentLangue"]=> string(2) "10" } ["raw_input"]=> string(0) "" ["query"]=> NULL ["variables"]=> NULL } {"errors":[{"message":"Syntax Error GraphQL (1:1) Unexpected \n\n1: \n ^\n","category":"graphql","locations":[{"line":1,"column":1}]}]}
```
and using `GraphiQL` returns this with POST

SyntaxError: Unexpected token a in JSON at position 0

**Comment by vladar** [comment]
As you can see, there is nothing in $raw_input. You simply don't pass a query in your request body. Debug it starting from the browser and make sure that:

1. Network request is a POST request
2. POST body contains valid JSON object with `query` and `variables` keys

But this is a basics of PHP debugging, so please respect my time as well %) I'll gladly help if you have issues with the library itself.

**Comment by cinder92** [comment]
As you can see im using GrapQLi tool to send the query

![captura de pantalla 2017-09-01 a la s 18 26 06](https://user-images.githubusercontent.com/4725556/29990728-0bd8ded6-8f43-11e7-82ca-4f48d682d3ae.png)

its possible that tool are not sending correctly? im sending a post...

![captura de pantalla 2017-09-01 a la s 18 26 51](https://user-images.githubusercontent.com/4725556/29990738-24f0139e-8f43-11e7-830d-2027953b040e.png)

Your time its same valuable as mine, so. if don't have time to help then thanks.

**Comment by vladar** [comment]
The tool is sending a regular network request. Open developer tools in your browser and check what exactly it sends to the server (headers, body).
