### ISSUE TITLE
Backed enum serialization

### ISSUE THREAD

**Issue by theofidry** [webonyx/graphql-php#1617]
From #1608, `BackedEnum` are resolved as follows:

```php
if (is_a($value, \BackedEnum::class)) {
  return $value->value;
}
```

I find this serialization a bit strange. Indeed if you consider the following object:

```php
class UrlType {
  const WEBSITE = 'website';
  const OTHER = 'other';
}
```

with the following GraphQL configuration (using [OverblogGraphQLBundle](https://github.com/overblog/GraphQLBundle)):

```yaml
UrlType:
    type: enum
    config:
        values:
            WEBSITE: { value: website }
            OTHER: { value: other }
```

And the following class:

```php
class Url {
  function __construct(
    public string $type,
  ) {}
}
```

Then with the object `new Url(type: UrlType::WEBSITE)`, the returned JSON will be something along the lines of:

```json
{
  "url": {
    "type": "WEBSITE"
  }
}
```

Note how it is the GraphQL `UrlType` _name_ that is used to return the value. If you submit `type: WEBSITE` in GraphQL, then the value serialized to PHP will be `'website'`.

Now the issue: make `UrlType` into a backed string enum instead:

```php
enum UrlType: string {
  case WEBSITE = 'website';
  case OTHER = 'other';
}
```

Then the JSON response will now be:

```json
{
  "url": {
    "type": "website"
  }
}
```

I do not know what is correct from the GraphQL spec perspective, but surely having such different behaviour when transforming a pseudo-enum into a backed enum seems incorrect?

**Comment by spawnia** [comment]
Good catch, fixed with https://github.com/webonyx/graphql-php/releases/tag/v15.14.3. Please consider sponsoring.
