### ISSUE TITLE
Deep filtering doesn't call parseValue on ScalarType

### ISSUE THREAD

**Issue by TomHAnderson** [webonyx/graphql-php#1619]
I have a library https://github.com/API-Skeletons/doctrine-orm-graphql that adds filters to types (as well as creates types).  This works fine when I query on the root query.  But not when I query on a collection.

This works:

```graphql
{
  performances(filter: { date: { gte: "1995-01-01" } }) {
    edges {
      node {
        date
      }
    }
  }
}
```

But this doesn't:
```graphql
{
  artists {
    edges {
      node {
        performances(filter: { date: { gte: "1995-01-01" } }) {
          edges {
            node {
              date
            }
          }
        }
      }
    }
  }
}
```

Feel free to run this on https://ldog.apiskeletons.dev/graphiql

Now, my code creates two different InputObjectTypes by the same function for these filters but they're both the same Date type for gte.  I've exhausted avenues this could be happening in my library.   

The problem I'm getting is parseValue of the scalar Date type isn't called in the second query.  Can you comment?

**Comment by spawnia** [comment]
Do the `array $args` that are passed to the resolver of `Query.performances` differ from what is passed to the nested field?

**Comment by TomHAnderson** [comment]
This looks like a problem with my parseLiteral s on my types.   Will update when I know for sure.

**Comment by TomHAnderson** [comment]
That was the problem.  I've solved it.
