### ISSUE TITLE
[Not a Bug] PSR7 compilant middleware

### ISSUE THREAD

**Issue by Ngob** [webonyx/graphql-php#162]
Hi,
i've created a middleware (as defined in [http-interop](https://github.com/http-interop/http-middleware)) based on your library: 

https://github.com/phps-cans/psr7-middleware-graphql

I've also created some tool to be able to use your library easily when using [container-interop/service-provider](https://github.com/container-interop/service-provider) (it contains a generic `type-registry` aswell):

https://github.com/phps-cans/harmony-graphql-tool

I would be happy if you can give me some feedback.
Any ideas to improve libraries are welcome!

Thanks for the work done with the library.

**Comment by vladar** [comment]
Sweet! I'll look into your work on the weekend and will likely add to complementary tools section (if you don't mind).

**Comment by Ngob** [comment]
I will be honored if you do !
Thanks,

**Comment by vladar** [comment]
I added [a mention](http://webonyx.github.io/graphql-php/complementary-tools/) about your library in docs (marked as experimented as README says that it is under development). Thanks!

**Comment by Ngob** [comment]
Thanks I am glad to help. PSR-15 is not accepted yet, so I will inform you once the package is stable.
Thanks again for your work.
