### ISSUE TITLE
Document how to use shorthand schema with nested types

### ISSUE THREAD

**Issue by RedShift1** [webonyx/graphql-php#163]
Suppose a schema like this:

```
type Query
{
    parents: [Parent]
}

type Parent
{
    parentId: ID!
    displayName: String!
    children: [Child]
}

type Child
{
    childId: ID!
    foobar: String!
}
```

The example at https://github.com/webonyx/graphql-php/tree/master/examples/02-shorthand doesn't tell you how to resolve the field children when querying parents, for example:

`query { parents { children { foobar } } }`

Only resolves parents, not their children...

**Comment by vladar** [comment]
Have you seen this?
http://webonyx.github.io/graphql-php/type-system/type-language/#defining-resolvers

**Comment by RedShift1** [comment]
Yes, also doesn't tell you how to do it?

**Comment by vladar** [comment]
I guess the documentation is not clear enough, but it mentions `resolveField` option. So in short, you should do something like this:

```php
<?php
use GraphQL\Utils\BuildSchema;

$typeConfigDecorator = function($typeConfig, $typeDefinitionNode) {
    $name = $typeConfig['name'];
    // ... add missing options to $typeConfig based on type $name
    switch ($name) {
        case 'Parent':
            $typeConfig['resolveField'] = function($value, $args, $context, $info) {
                return $value->{$info->fieldName};
            };
            break;
    }
    return $typeConfig;
};

$contents = file_get_contents('schema.graphql');
$schema = BuildSchema::build($contents, $typeConfigDecorator);
```

Or alternatively, define your own [default resolver](http://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver).

**Comment by RedShift1** [comment]
Hmm I did tried that earlier and that decorator function never got called (which is why I made this report - I thought it was the wrong way to go about it) . I will try again, maybe I missed something.

**Comment by vladar** [comment]
Make sure you use v0.10+ (this function did not exist in v0.9+)

**Comment by RedShift1** [comment]
Aha it's working now. I was running version 0.9... Maybe mention in the docs this only works for versions > 0.10?

**Comment by vladar** [comment]
Yeah, makes sense. Thanks!
