### ISSUE TITLE
graphiql starter query null issue "Cannot return null for non-nullable field __Field.name."

### ISSUE THREAD

**Issue by mirro-orrim** [webonyx/graphql-php#165]
I have the graphiql document query:
`query IntrospectionQuery { 
__schema { 
queryType { name } 
mutationType { name } 
subscriptionType { name } types 
{ ...FullType } 
directives { 
name description args 
{ ...InputValue } 
onOperation onFragment onField } } } 
fragment FullType on __Type 
{ kind name description fields(includeDeprecated: true) 
{ name 
description 
args 
{ ...InputValue } 
type 
{ ...TypeRef } 
isDeprecated deprecationReason } 
inputFields 
{ ...InputValue } 
interfaces 
{ ...TypeRef } 
enumValues(includeDeprecated: true) 
{ name description isDeprecated deprecationReason } 
possibleTypes 
{ ...TypeRef } } 
fragment InputValue on __InputValue 
{ name description type 
{ ...TypeRef } defaultValue } 
fragment TypeRef on __Type 
{ kind name ofType 
{ kind name ofType 
{ kind name ofType 
{ kind name } } } }`

which is returning :

Executor.php
```php
InvariantViolation('Cannot return null for non-nullable field ' . $info->parentType . '.' . $info->fieldName . '.');
```

My test type-language:
```php
$contents = <<<EOC
schema
{
    query: Query
    mutation: Mutation
}
type Query
{
    user: String
}
type Mutation
{
    setToken(token: String): Int
}
EOC;
$document = Parser::parse($contents);
$schema = BuildSchema::buildAST($document);

$result = GraphQL::executeQuery(
                $schema,
                $requestString,
                /* $rootValue */
                $identity,
                $container = null,
                $variableValues = null, $operationName = null,
                $typeRepository->decoratorFieldResolver
            )->toArray(Debug::INCLUDE_DEBUG_MESSAGE | `Debug::RETHROW_INTERNAL_EXCEPTIONS);`
```

**Comment by vladar** [comment]
I suspect it's because your default field resolver (`$typeRepository->decoratorFieldResolver`) doesn't resolve arrays, and as a result is incapable to resolve introspection query.

We should probably force resolver for introspection. In the meantime, you can adjust your resolver to work with regular arrays.

**Comment by mirro-orrim** [comment]
Thanks to you, this resolved my issue!
