### ISSUE TITLE
any example implementations with rdbms like mysql?

### ISSUE THREAD

**Issue by galileomd** [webonyx/graphql-php#166]
looking for one more step in converting over a rest api to gql - how to incorporate our relational db to graphql-php

**Comment by vladar** [comment]
This is very project-specific and depends on your database abstraction layer. Here for example, how you can use it with doctrine ORM: for [PHP7+](https://github.com/Ecodev/graphql-doctrine) or for [PHP5.5+](https://github.com/rahuljayaraman/doctrine-graphql).

**Comment by galileomd** [comment]
sure, was just curious how to the SQL calls were integrated into the resolver functions...
this looked like a neat demo, however it doesnt seem to work. 
https://github.com/XAHTEP26/graphql-php-tutorial
the schema prints out correctly, but introspection requests come back with nothing.  any suggestions on debugging?

**Comment by vladar** [comment]
Sorry, I don't have time for this. You should raise an issue in this repo.
