### ISSUE TITLE
Argument printed by SchemaPrinter

### ISSUE THREAD

**Issue by Ngob** [webonyx/graphql-php#167]
Hello,

I am using the object SchemaPRinter to being able to print the schema. I ran into a potential error. I have query with multiple argument and their respective descriptions, my printed schema is (relevant code):
```
type Query {
  foo(
    # limit
    limit: Int

    # offset
    offset: Int
  ): [ToBill]
}
```

As you can see there is a double "\n" between `limit: Int` and  `#offset`.
I can fix it if you like.

Thanks for your work

**Comment by vladar** [comment]
It is an intended behavior for args with description. A spec-compliant parser should be capable to parse this definition. Have you tried to parse it with our parser? 

If parser can't parse it then there is likely a bug in the parser not in the printer.

**Comment by Ngob** [comment]
I tried to parse it via [apollo-server](https://github.com/apollographql/apollo-server), it can not parse the double carriage return in argument's list.

Thanks for your response, I will just remove my description and wait the full support of type-def language in apollo-server.

**Comment by vladar** [comment]
That's weird. I am pretty sure they use a standard parser from the graphql-js package. I just tested it and graphql-js parsed this schema just fine. Also, their printer produced the same output as in our library (with double "\n" between args).
