### ISSUE TITLE
Detecting breaking type changes against "frozen" queries

### ISSUE THREAD

**Issue by roippi** [webonyx/graphql-php#169]
Hm, that's a terrible issue title.  Naming things is hard.

**Background**

We're starting to roll out GraphQL to our native apps.  It's great.  In order to save a few bytes over the wire and protect ourselves from malicious stuff, we went with a "persisted queries" implementation where we stick the actual queries in a DB at build time and just send an identifier to said query over the wire.  This also enables regression testing: we have access to all the queries old apps are making in one place; we can test against the current schema (especially in CI) and see when stuff breaks.  We love this because it lets us move fast and make changes to our schema, and breaking changes get caught by tests before things make it to production.

**Quandary**

We're basically doing `DocumentValidator::validate` on all the old queries against the current schema.  This works great for detecting _most_ breaking changes - remove a field that an old app is using, it gets flagged.  Unfortunately it can't check type breakages.  Change an `int` to a `string` and it will still validate, but the apps aren't going to have a good time.

This is kind of similar to https://github.com/webonyx/graphql-php/issues/64 but narrower in scope.  We tend not to care about people making breaking changes to the schema - unless it actually breaks a deployed query.

I've looked at the available `Utils` and I could piece something together with `TypeInfo` (I'd also need to start capturing type info at app build time and sticking that in DB too).  This seems like it might be something that's of broader interest though - so I'm tossing in an issue to see if anyone else has done something like this before, and/or if there is appetite for baking this into an upstream Util.  Thanks.

**Comment by vladar** [comment]
Nice approach!

I think you should consider porting `findBreakingChanges` (as you mentioned the task is similar). One thing we can consider is to add information about type and field to breaking change result. 

Then you could take these breaking changes and additionally check them against your deployed queries using `Visitor`. 

It is much easier to maintain stuff that already exists in the reference implementation. But that's just my thoughts on this subject. Maybe there are other ideas?

**Comment by roippi** [comment]
I think you're right - looking at the js implementation, it's simply a facade for comparing two `TypeMap`s.  Then the trick is just filtering oldSchema down to the types touched by deployed queries before running the comparison - `Visitor` would work for that part nicely.

**Comment by vladar** [comment]
@roippi Any follow-up here or should I close?

**Comment by roippi** [comment]
We're going to do `findBreakingChanges` in the nearish future then revisit this.  Seems like the right approach.

**Comment by vladar** [comment]
I guess we can close this one as well, but let me know if you have anything else in mind regarding this issue.
