### ISSUE TITLE
Graphql and microservices

### ISSUE THREAD

**Issue by crirus** [webonyx/graphql-php#172]
Hello

Is there a way to build a graphql in a isolated set of microservices?
I'm wondering how would one define a schema that should load the type from another location?

For example:
```
$config = [
            'name' => 'query',
            'fields' => [
                'user' => [
                    'type' => Types::get('user'),
```

UserType will be in a separate project/microservice dealing with users. How should I define on both sides the config in order to work?

Right now my Types factory just creates a new instance UserType.

Thank you
Cristian

**Comment by vladar** [comment]
GraphQL schema is just a set of PHP objects. You can create them in any way you want (explicitly via PHP classes, using type language and BuildSchema or write your own custom builder).

The way how you do it is out of the scope of this library. 

I would personally store type definitions as text files written in [type language](http://webonyx.github.io/graphql-php/type-system/type-language/). Then I would collect them from all microservices and combine to single schema file + build using `buildSchema()` at separate build step.

But there are definitely other ways to do it as well.

**Comment by crirus** [comment]
Thank you, this is probably what I was looking for, a way to build some types without having a class implementation upfront.

**Comment by crirus** [comment]
Hello again,


After some more reading there seems to be some implementations regarding multiple graph APIs stitching.

Basically they introspect each API via URL and combine the schemas as well as linking types together on the stitcher side. Is there any plan for adding this to graphql-php?

**Comment by crirus** [comment]
const schema = mergeSchemas({
    schemas: [universeSchema, weatherSchema],
    links: [
      {
        name: 'location',
        from: 'Event',
        to: 'location',
        resolveArgs: parent => ({ place: parent.cityName }),
        fragment: `
          fragment WeatherLocationArgs on Event {
            cityName
          }
        `,
      },
    ],
  });

**Comment by vladar** [comment]
I don't see `mergeSchemas` in reference `graphql-js` implementation, so it's unlikely that we'll include it in this repo. Maintenance costs of such features may be quite high.

**Comment by crirus** [comment]
Actually they work on this concept in apollo here

https://github.com/apollographql/graphql-tools/tree/f03ae91d7daee20d0768557458819725b529a9b7/src/stitching

Regards.

**Comment by vladar** [comment]
Yeah, Apollo has many nice tools, but we won't be able to port and maintain all of them. So it should stay separate from this repo, same as apollo tools repo is separate from graphql-js.

**Comment by crirus** [comment]
Oh, well, maybe as a tool then. Will see what I can do about it and post back if I produce anything.

**Comment by crirus** [comment]
Do we have in grapql-php a transformation function from schema Introspection to actual schema?

**Comment by vladar** [comment]
Not really. This is useful for clients and less useful for servers, so we skipped it. But such utility does exist in the reference implementation (`BuildClientSchema`), so PR is welcome.

**Comment by vladar** [comment]
I guess you've figured this out already.
