### ISSUE TITLE
Caching the result of the parsed type definition file fails with "var_export does not handle circular references"

### ISSUE THREAD

**Issue by remipelhate** [webonyx/graphql-php#176]
Hi there,

I'm trying to cache the result of the parsed definition file as described in the [docs](http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations), but I'm always getting `var_export does not handle circular references`.

I'm using v0.11.1 with the following schema:

```graphql
# GraphQL/schema.graphql

schema {
    query: Query
}

type Query {
    events(account: ID!): [Event]!
    vehicles(event: ID!): [Vehicle]!
}

type Event {
    id: ID!
    name: String!
    vehicles: [Vehicle]!
}

type Vehicle {
    id: ID!
    make: String!
}
```

This is how I'm currently trying output the parsed result as a string:
```php
use GraphQL\Language\Parser;

$document = Parser::parse(file_get_contents(__DIR__.'/../GraphQL/schema.graphql'));

var_export($document->toArray(), true);
```

Am I doing something wrong? Or did something change in v0.11 compared to v0.10?

**Comment by vladar** [comment]
Sorry, it's a mistake in docs. You should call `$document->toArray(true)`. Simple `toArray()` does just a shallow conversion of AST to an array, `toArray(true)` will convert recursively.

**Comment by vladar** [comment]
Fixed docs

**Comment by remipelhate** [comment]
Perfect! Thanks for helping me out so quickly!
