### ISSUE TITLE
Scalar description aren't provided in introspection

### ISSUE THREAD

**Issue by mariomka** [webonyx/graphql-php#181]
Descriptions of custom scalar types defined with type language(schema.graphql) aren't provided in a type introspection.

```graphql
# An ISO-8601 encoded UTC date string.
scalar Date
```

```graphql
{
  __type(name: "Date") {
    name
    description
  }
}
```

Returns:

```json
{
	"data": {
		"__type": {
			"name": "Date",
			"description": null
		}
	}
}
```

**Comment by vladar** [comment]
Fixed via https://github.com/webonyx/graphql-php/commit/1487741f37d8e6b183c678a7a041b2be1f6c7fd2
