### ISSUE TITLE
Is there a way to separate type def and resolvers?

### ISSUE THREAD

**Issue by moon0326** [webonyx/graphql-php#182]
Hi,

I was wondering if graphql-php package supports separating type definition and resolvers. I would like to define type definition in json file.

I'm looking for something like http://dev.apollodata.com/tools/graphql-tools/generate-schema.html

Is this supported? I could not find anything in the example dir.

Thanks!

**Comment by vladar** [comment]
You can try using [type language](http://webonyx.github.io/graphql-php/type-system/type-language/). 

But if you want to define schema in json, you will have to create your own builder which will convert your json to type definitions. There is no ready tool for this in this package.

**Comment by vladar** [comment]
Also look at this repo: https://github.com/overblog/GraphQLPhpGenerator maybe it will be useful for you (they use it internally in Symfony [GraphQLBundle](https://github.com/overblog/GraphQLBundle))

**Comment by crirus** [comment]
I"ve also ported some of the apollo tools in a package, maybe you can use the code there. https://github.com/crirus/graphql-php-tools

**Comment by moon0326** [comment]
@vladar Thank you for insight. I will look into it.
@crirus That's interesting. Thank you so much! I will look into it.

have a great weekend both of you!

**Comment by crirus** [comment]
Sure, have fun. I am still not done with this, have a final issue with resolving extended fields from a schema to another, otherwise it's working fine delegating each field to it's own schema as well as creating extended schema and attaching resolvers to it. Let me know what you can figure out.
