### ISSUE TITLE
@deprecated directive

### ISSUE THREAD

**Issue by mariomka** [webonyx/graphql-php#183]
In `graphql-js` is possible to deprecate fields via `@deprecated` directive, check out graphql/graphql-js#384.

Do you have any plans to implement it?

**Comment by mariomka** [comment]
It's already implemented, I'm blind...

**Comment by tomasvts** [comment]
This is first in "webonyx deprecated" search results.

This is what you are looking for:
https://webonyx.github.io/graphql-php/type-system/object-types/#field-configuration-options
