### ISSUE TITLE
Allow overwriting internal types to improve result coercion

### ISSUE THREAD

**Issue by Rendez** [webonyx/graphql-php#184]
The 0.11.x update seem to have improved variable coercion and some of the scalar types as well. The coercion adheres the definition in http://facebook.github.io/graphql/October2016/#sec-Scalars.

Now, we've tried to extend `BooleanType` to make it more strict, so that it throws if the passed value isn't a boolean in order to avoid false positives within our app:

```php
class ExtendedBooleanType extends BooleanType {
    /**
     * @param mixed $value
     * @return bool
     */
    public function serialize($value) {
        if (!is_bool($value)) {
            throw new InvariantViolation("Boolean must be represented by strict value. " . Utils::printSafe($value) . " given.");
        }
        return $value;
    }
}
```
The need for this relates to running in weak mode, where even methods with return types :bool end up in coercion. Therefore defining an error inside `serialize` is important for us.

However, the `Instrospection` class (among others) uses static calls, including calls to `Type::boolean()`, so building our schema throws once again:
```
Schema must contain unique named types but contains multiple types named
```

- What are your thoughts on strictly checking for boolean to prevent errors?
- Is there a way we could point to our boolean definition from the different calling contexts?

**Comment by vladar** [comment]
I don't think that replacing standard types with custom types is a good idea because their parsing behavior is defined in spec and clients rely on it (except maybe ID type).

On the other hand, I do agree that serializing process is a bit different and could be customizable to some extent. Two options I see:

1. Introduce strict/weak mode for serialization
2. Allow defining optional custom serialization function

I'd like to keep this issue open for a while for discussion (maybe others will post their thoughts as well). Maybe I'll reconsider this and just allow defining own standard types.

In the meantime, the only workaround for you is to use Reflection to override `GraphQL\Definition\Type::$internalTypes`.

**Comment by Rendez** [comment]
@vladar thanks for the very quick answer. I agree let's keep this opened for a bit. Personally I do like _option 1._ because it plays nice when configuring PHP to run in either weak or strong typing mode.

**Comment by Rendez** [comment]
Reading the [spec](http://facebook.github.io/graphql/October2016/#sec-Boolean) for Boolean closer and given than PHP does have a bool type (unlike other langs), we're not limited to returning a coerced type. Therefore, even though is not coercing, I believe the next would be safe:

```php
class ExtendedBooleanType extends BooleanType {
    /**
     * @param mixed $value
     * @return bool
     */
    public function serialize($value) {
        $value ? true : false;
    }
}
```

"The Boolean scalar type represents true or false. Response formats should _use a built‐in boolean type if supported_; otherwise, they should use their representation of the integers 1 and 0."

Again, the point I'm trying to make is that PHP is already loose enough coercing types, and strict mode makes no difference to this behavior, leaving us with either tackling it here or using strict type with method return types: `serialize($value): boolean { ... } ` which we do not use. As I understand, GraphQL philosophy is to avoid returning typing errors and instead coerce.

**Comment by vladar** [comment]
Sorry, missed your last comment somehow. But I am not sure I am following it. `$value ? true : false` is a current behavior. But then what's your problem with it (again, I feel that I am missing something)?

**Comment by Rendez** [comment]
Sure...
```php
return !!$value; // returns coerced value, e.g.: $value = 'foo'; return !!$value; will equal (int) 1
```

```php
return $value ? true : false; // returns boolean value
```

**Comment by vladar** [comment]
It's the same:

```php
$foo = 'foo';
$bar = !!$foo;
var_dump($bar);

// outputs: bool(true)

```

**Comment by Rendez** [comment]
Oh my... echo VS var_dump, echo is obviously stringifying the real output. My bad.
