### ISSUE TITLE
New error handling, isClientSafe always false?

### ISSUE THREAD

**Issue by jasonbahl** [webonyx/graphql-php#188]
Hey, 

I'm trying to upgrade from v0.9.14 to v0.11.2 and the only issues I'm having are how the new Errors are handled. 

I want to display some errors in the response, so I've tried to throw them like so: 

`throw new \GraphQL\Error\UserError( 'My custom error message' );` 

But that still outputs:

```
"errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 2
        }
      ],
      "path": [
        "post"
      ]
    }
  ]
```

So I tried to implement my own error class, as outlined here: https://github.com/webonyx/graphql-php/blob/master/docs/error-handling.md#default-error-formatting

And I still get the `Internal server error` output when using that new class to throw errors. 

I did a bit of digging and it seems like this (https://github.com/webonyx/graphql-php/blob/master/src/Error/Error.php#L164) is causing all errors to have `isClientSafe` set to false. . .not sure if that's a bug or if I'm just doing something wrong still.

If I set Line 164 to true, then I do get a message instead of `Internal Server Error` but it's a long string containing the call stack, the message, etc. . .not just the `message` string that I'm throwing, and the category is still set to `internal` instead of the category I set in my custom error class.  

Here's an example (truncated): 

```
  "errors": [
    {
      "message": "GraphQL\\Error\\UserError: My custom error message in /Users/jasonbahl/sites/my-site/my-graphql-project/src/Data/DataSource.php:160\nStack trace:\n#0 /Users/jasonbahl/sites/my-site/my-graphql-project/src/Type/PostObject/PostObjectQuery.php(59):"
    }
]
```

I would expect message to just be `My custom error message` instead of the full trace. 

Any insight into what I might be doing wrong / what else I'm missing?

**Comment by vladar** [comment]
It's hard to say without test case. But https://github.com/webonyx/graphql-php/blob/master/src/Error/Error.php#L164 is executed only if error does not implement ClientAware interface.

If you could build a simple reproducible test case - I could take a look. But before you do, please make sure that you don't catch and re-throw these exceptions somewhere in your code.

**Comment by jasonbahl** [comment]
Ok, I've got the errors working in the Blog example of your repo, so something is definitely missing in my implementation. We can consider this closed and I'll dig into what's different in my codebase vs. the example. Thanks!

**Comment by jasonbahl** [comment]
Just wanted to follow up. The issue was indeed another instance of a try/catch that I had in a separate piece of connected code. 

I have tracing setup per the Apollo Tracing spec, and I had some try/catch logic around using the Fields resolver, or falling back to the defaultFieldResolver. . .removing the try/catch here fixes the issue. 

Thanks so much!
