### ISSUE TITLE
Ramsey UUID type problem

### ISSUE THREAD

**Issue by mysiar** [webonyx/graphql-php#191]
I have data model using Ramsye UUID,
I can't query api with graphql as the type is not recognized and throws error:

```
"Type error: Argument 1 passed to GraphQL\\Validator\\DocumentValidator::isValidLiteralValue() 
must be an instance of GraphQL\\Type\\Definition\\Type, null given,
called in /home/ubuntu/h88/api.epp.domeny.dev/vendor/webonyx/graphqlphp/src/Validator/Rules/ArgumentsOfCorrectType.php on line 27"
```

Did anybody had similar problem and could share how to solve it ?

**Comment by vladar** [comment]
Can you provide a test case to reproduce this?

Or at least your type definition, and data which causes this?

**Comment by mysiar** [comment]
each entity has id as below

```php
 /**
     *
     * @\Doctrine\ORM\Mapping\Column(type="uuid")
     * @\Doctrine\ORM\Mapping\GeneratedValue(strategy="CUSTOM")
     * @\Doctrine\ORM\Mapping\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     * @\Doctrine\ORM\Mapping\Id()
     * @\Symfony\Component\Serializer\Annotation\Groups({"view", "list"})
     *
     * @var \Ramsey\Uuid\Uuid
     */
    private $id;
```

**Comment by vladar** [comment]
You must understand that ID type expects a string, not custom objects.

So you have two options:

1. For each `id` field - define a resolver which will return a string representation of the ID, e.g.:
```php
$idField = [
    'type' => Type::id(),
    'resolve' => function ($value) {
        return (string) $value->getId();
    }
];

$myType = new ObjectType([
    'fields' => [
        'id' => $idField,
    ]
]);
```

2. Create your own [custom scalar ID type](http://webonyx.github.io/graphql-php/type-system/scalar-types/#writing-custom-scalar-types) and pass it in `types` option of the Schema instance (note that you must use v0.11.1+ for this to work).

**Comment by vladar** [comment]
Closing, but feel free to re-open if it's not solved for you
