### ISSUE TITLE
Allow to create schema w/o introspection types

### ISSUE THREAD

**Issue by jakubkulhan** [webonyx/graphql-php#192]
In production environment I wouldn't want anyone to download complete schema using introspection queries.

Previously (v0.9.14) it was possible to create `Schema` instance that didn't contain introspection types using custom [supplied `EagerResolutionStrategy` that did not contain introspection types](https://github.com/webonyx/graphql-php/blob/v0.9.14/src/Schema.php#L133). However, new version deprecated `typeResolutionStrategy` and automatically [adds introspection types in constructor](https://github.com/webonyx/graphql-php/blob/master/src/Type/Schema.php#L133).

I think there should be configuration option that allows/disallows introspection types.

**Comment by vladar** [comment]
Check out [this entry in docs](http://webonyx.github.io/graphql-php/security/#disabling-introspection) and let me know if it works for you.

**Comment by jakubkulhan** [comment]
@vladar Superb, it works. Thank you!
