### ISSUE TITLE
Make GraphQL implement LoggerAwareInterface

### ISSUE THREAD

**Issue by vasily-kartashov** [webonyx/graphql-php#194]
Would it be possible to implement LoggerAwareInterface and channel all the exceptional situations into it? At the moment it's quite hard to battle `Internal Server Errors` knowing nothing about underlying causes.

**Comment by vladar** [comment]
It is supposed that you use a [custom error handler](http://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting) to add logging, so I am curious why it doesn't work for you?

Also, have you tried [debugging tools](http://webonyx.github.io/graphql-php/error-handling/#debugging-tools)?

**Comment by vasily-kartashov** [comment]
I guess it could work. Debugging tools are not quite as convenient, because I specifically want see things gone wrong in log files, sometimes days after an exception was registered.

It it the proper use of custom formatters?
```
GraphQL::executeQuery(...)
    ->setErrorFormatter(function(Error $error) {
        $this->logger->warning('Exception while handing GraphQL request', ['exception' => $error]);
        return FormattedError::createFromException($error);
    })
    ->toArray();
```

**Comment by vladar** [comment]
You can do it in formatter, but formatter is mostly for formatting a message to an array. It is more appropriate to use errors handler, but that's after you.
