### ISSUE TITLE
Support "multipart/form-data" on the server

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#197]
For now we only support "application/json" and "application/x-www-form-urlencoded", but it would be nice to support "multipart/form-data" as well to be able to send GraphQL query along with files.

**Comment by crirus** [comment]
I pushed this change to my old PR, here is the code if you want to merge it alone

src/Server/Helper.php on line 72

```php
            } else if (stripos($contentType, 'multipart/form-data') !== false) {
                $bodyParams = $_POST;
```

**Comment by vladar** [comment]
Thanks, we also need some tests for it

**Comment by vladar** [comment]
Dupe of #178 (#220 is also related)
