### ISSUE TITLE
Error in OPTIONS response

### ISSUE THREAD

**Issue by freder** [webonyx/graphql-php#198]
for all my requests, I get the following error (on the `OPTIONS` request). the actual `POST` request works though.

```json
{
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:1) Unexpected <EOF>\n\n1: \n   ^\n",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
```

- requests are done with [react-apollo](https://github.com/apollographql/react-apollo)
- graphql-php version: `0.11.2`

**Comment by freder** [comment]
update: sending the same query with graphiql works just fine. if I'm not mistaken the main difference seems to be the `content-type` request header:

- apollo: `application/json`
- graphiql: `text/plain;charset=UTF-8`

**Comment by vladar** [comment]
You should not direct OPTIONS requests to GraphQL. They are sent by browser automatically (used for cross-origin resource sharing) and have nothing to do with GraphQL. Just process OPTIONS separately as required by CORS.

**Comment by freder** [comment]
@vladar I should have mentioned: was indeed talking about the automatic `OPTIONS` request by the browser.

could you elaborate a bit on _processing `OPTIONS` separately_ – I'm not entirely sure what you mean.

thank you.

**Comment by vladar** [comment]
Do you use any web framework? Most of them provide some means to handle different HTTP methods separately for the same URI.

Without a framework, you can just do something like this:

```php
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    // Do your CORS logic here
} else {
    $server = new GraphQL\Server\StandardServer(/* $options */);
    $server->handleRequest();
}
```

**Comment by freder** [comment]
thanks @vladar
