### ISSUE TITLE
Add examples + readme

### ISSUE THREAD

**Issue by trappar** [webonyx/graphql-php#2]
Without more information this project looks interesting but I'm not sure how to even get started. Is this something you're going to be expanding on in the future?

**Comment by vladar** [comment]
Definately, it's really in pre-release state. We explore best usage scenarious ourselves and will probably make significant changes to API before first usable release.

But if you want to experiment with it, check out tests as usage examples, say:

https://github.com/webonyx/graphql-php/blob/master/tests/StarWarsSchema.php
https://github.com/webonyx/graphql-php/blob/master/tests/StarWarsQueryTest.php

**Comment by vladar** [comment]
Added quick README for now. Feel free to open specific issues if something requires additional clarifications in Readme.
