### ISSUE TITLE
Adding extra data to errors

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#206]
Is it possible to add some extra data (such as "field") as described [here](https://www.howtographql.com/graphql-js/8-error-handling/)? (See the lower half of the article.)

**Comment by enumag** [comment]
If this is not supported, please give me some tips how to implement is and I'll send a PR.

**Comment by vladar** [comment]
It is documented [here](http://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting)

**Comment by caseycs** [comment]
@enumag look at `setErrorFormatter` method
