### ISSUE TITLE
Multiple errors from one resolver

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#207]
When resolving a mutation it can very easily result in multiple errors - especially validation of the user input. For example let's say I have a mutation like this:

```
mutation {
  createPerson(name: "", age: 4) {
    name
    age
  }
}
```

The resolver for createPerson should add two errors to the result:

1. Name cannot not be empty.
2. Age has to be >= 18.

By throwing an exception implementing `GraphQL\Error\ClientAware` interface I can only add one error to the result. How can I add two (or more)?

**Comment by enumag** [comment]
If this is not supported, please give me some tips how to implement is and I'll send a PR.

**Comment by vladar** [comment]
You have at least couple options:

1. Since these errors are domain errors vs GraphQL errors - model them in your schema. See https://github.com/webonyx/graphql-php/issues/97#issuecomment-287260324 and related discussion.

2. Collect all errors in your resolver, throw a custom exception with those errors attached and then add entries for each of your errors manually using custom error handling, for example:

```php
'resolve' => function($_, $args) {
    $errors = [];
    if (empty($args['name'])) {
        $errors[] = 'Name could not be empty';
    }
    if ($args['age'] < 18) {
        $errors[] = 'Age has to be 18+';
    }
    if (!empty($errors)) {
        $e = new MyValidationException();
        $e->myErrors = $errors;
        throw $e;
    }
}
```

Then in custom error handler:
```php
$myErrorHandler = function(array $exceptions) {
    $errors = [];
    foreach ($exceptions as $exception) {
        if ($exception instanceof MyValidationException) {
            foreach ($exception->errors as $message) {
                $errors[] = [/* Format the error as you want */];
            }
        } else {
            $errors[] = [/* Format the error as you want */];
        }
    }
    return $errors;
};

$result = GraphQL::executeQuery(/* $args */)
    ->setErrorsHandler($myErrorHandler)
    ->toArray(); 
```

**Comment by vladar** [comment]
Oh yeah, and the one option I keep forgetting about is to return an array of exceptions from your resolver (vs throwing them).

But that's not certain. I remember that we discussed it at some point, just don't remember if it is actually implemented %) so try it yourself.

**Comment by enumag** [comment]
Thank you! Very helpful answer. After some hacking with Overblog/GraphQLBundle I managed to successfully use my own error handler. The problem now is that I want to use the default handler in most cases (such as syntax errors in the GraphQL query) and only use the customized one for some of my own exception. Any tip how I can re-use the default handler?

**Comment by enumag** [comment]
Ok I think I solved that on my own. Posting it here for anyone else looking for the same thing.

```php
		$defaultFormatter = FormattedError::prepareFormatter(null, $debugMode);

		$executionResult->setErrorFormatter(
			function (\Throwable $exception) use ($defaultFormatter, $debugMode) {
				if ($exception->getPrevious() instanceof MyException) {
					return $this->formatException($exception->getPrevious(), $debugMode);
				}

				return $defaultFormatter($exception);
			}
		);
```
