### ISSUE TITLE
API for adding extensions in order to implement tracing

### ISSUE THREAD

**Issue by keithrobichaud** [webonyx/graphql-php#208]
Hello, first off I just want to say thanks for all the work everyone has put into this codebase, it's been awesome to work with so far!

I've noticed that there are some open issues in regards to adding better support for tracing, and I've spent a decent amount of time searching for answers but I was hoping that a post here would yield me to the ideal solution.

I spent a bit of time setting up some wrapped resolver functions as Jason suggests here: https://github.com/webonyx/graphql-php/issues/94#issuecomment-330273420
and this worked fine when I was using GraphQL::executeQuery as I could just directly do something like $result['extensions']['tracing'] = $traceData;
However, after switching to the StandardServer (needed to support batched queries) I was no longer able to use such a solution.

If there were a simple API for adding extensions onto the result executor that would be one simple solution for us. I looked through the codebase/docs and could not find anything. I don't mind opening a PR adding such support if it seems like something other people would find useful. I'm not sure what else extensions are used for outside of tracing, so if there was a native way to enable tracing that would be sufficient as well (seems like that may be a ways off though)

Thanks!

**Comment by vladar** [comment]
Thanks for your feedback. Have you seen https://github.com/webonyx/graphql-php/pull/193 ? Would it work for you?

Alternative is just to add an option `resultFormatter` to the server where you will be able to do whatever you want with execution result. Which solution would work better for you?

**Comment by keithrobichaud** [comment]
I was originally thinking that #193 would be sufficient for our use case, but I'm not sure how we would be able to add request start/end times from within the context of a resolver without doing some super janky stuff. A `resultFormatter` would definitely work if I'm interepreting what you mean correctly (pass in a function that takes the result as a param and returns a new formatted version of the result)

**Comment by keithrobichaud** [comment]
Actually, after further inspection, it seems I can already essentially do that using $result = $server->executeRequest() and then handling it in my application code.

**Comment by vladar** [comment]
For anyone interested, there is another proposal on how to enable apollo tracing for any existing schema: see https://github.com/webonyx/graphql-php/issues/289#issuecomment-399633709 PRs are welcome!
