### ISSUE TITLE
Ability to pass an error (or multiple errors) to execution context

### ISSUE THREAD

**Issue by viteksafronov** [webonyx/graphql-php#209]
AFAIK, the only way to set an error in resolver is to throw an Exception, which will be caught in Executor. Sometimes I want to set an error, but to continue my work in resolver. Also I'd like to send multiple errors at once (without concating them in a single exception message). Is it possible? If not, may this feature be implemented?

**Comment by vladar** [comment]
You have `$context` for this. Make a separate class for your context and pass your errors/notices/warnings to it. Then use [custom error handler](http://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting) to add your own errors to final result.

```php
class MyContext {
    private $errors = [];
    public function addError(MyException $e)
    {
        $this->errors[] = $e;
        return $this;
    }
}

// Later in your resolver:
'resolve' => function($value, $args, MyContext $context) {
    $context->addError(new MyException('Whatever you want'));
    $context->addError(new MyException('Whatever you want 2'));
}

// Now querying graphql:
$myContext = new MyContext();
$result = GraphQL::executeQuery($schema, $queryString, $rootValue, $myContext);

$result->setErrorsHandler(function($e, $defaultFormatter) use ($myContext) {
    $formattedErrors = array_map($defaultFormatter, $errors);
    foreach ($myContext->getErrors() as $error) {
        $formattedErrors[] = [
            // format your error as you need
        ];
    }
    return $formattedErrors;
});
```
