### ISSUE TITLE
Resolver data from multiple sources

### ISSUE THREAD

**Issue by crirus** [webonyx/graphql-php#212]
Hello

I have this situation where we save in database a structured set of data in a json format.

Imagine this:
a table with browser and a  table with browser versions.
In saved json we have some browser ids and several version ids for each browser.

On query we would like to display each browser with its versions from json but with names/IDs from their tables.

When I resolve the type where browsers is a field, I get that whole json data.
When I get to Browser resolver, the browser name field is taken from table, but versions info is back in that json, I don't have that data anymore, obviously.

Any suggestion?

**Comment by vladar** [comment]
Resolvers may accept different values. Just create a wrapper class for your json and pass it down to resolvers. Then in your resolver check what type of value you got and resolve accordingly.

Another option is just to introduce an interface that field resolver accepts and have multiple implementations. Polymorphism ftw.
