### ISSUE TITLE
customise response structure

### ISSUE THREAD

**Issue by andrewmclagan** [webonyx/graphql-php#213]
When forming responses they typically look like this:

````json
{
  "data": {
    "id": "123",
    "author": {
      "id": "1",
      "name": "Paul"
    },
    "title": "My awesome blog post",
    "comments": [
      {
        "id": "324",
        "commenter": {
          "id": "2",
          "name": "Nicole"
        }
      }
    ]
  }
}
````

Is it possible to modify this response structure to "normalise" it? For example:

````json
{
  result: "123",
  entities: {
    "articles": { 
      "123": { 
        id: "123",
        author: "1",
        title: "My awesome blog post",
        comments: [ "324" ]
      }
    },
    "users": {
      "1": { "id": "1", "name": "Paul" },
      "2": { "id": "2", "name": "Nicole" }
    },
    "comments": {
      "324": { id: "324", "commenter": "2" }
    }
  }
}
````

**Comment by vladar** [comment]
GraphQL is designed without normalization. So there are no built-in tools at the moment. If you need normalized data output, you should probably consider using other tools (i.e. Falcor).

But if you still want to do it with GraphQL (even if it's against GraphQL design), you'll have to use `GraphQL::executeQuery()` and then transform the result manually. 

One thing which may help you a bit is a [`__typename`](http://graphql.org/learn/queries/#meta-fields) field which you should add to every object field in the query. Technically you can do it as a [custom validation rule](http://webonyx.github.io/graphql-php/executing-queries/#custom-validation-rules) which alters query AST.

The rule itself could look something like this:

```php
use GraphQL\Validator\Rules\CustomValidationRule;
use GraphQL\Language\AST\SelectionSetNode;
use GraphQL\Language\AST\FieldNode;
use GraphQL\Language\AST\NameNode;

$myRule = new CustomValidationRule(function() {
    return [
        NodeKind::SELECTION_SET => function(SelectionSetNode $selectionSet) {
            $newSet = clone $selectionSet;
            $newSet->selections[] = new FieldNode([
                'name' => new NameNode([
                    'value' => '__typename'
                ])
            ]);
            return $newSet;
        }
    ];
});
```

I am writing this off based on memory, so not 100% sure that it will work out of the box. Feel free to ask more questions if needed.

The closure passed to the constructor of `CustomValidationRule` is a rule for [visitor](http://webonyx.github.io/graphql-php/reference/#graphqllanguagevisitor).

**Comment by andrewmclagan** [comment]
Thank you! thats a great  direction to start. Basically we want to transform / normalise on our server and not our frontends. It saves data transmission size and workload on the frontends. I will keep this open with our progress

**Comment by vladar** [comment]
Actually, I am probably wrong. Validation will ignore your AST changes as it is read-only. You will have to do a separate pass on your query before execution to add `__typename`:

```php
$myVisitor = [
    NodeKind::SELECTION_SET => function(SelectionSetNode $selectionSet) {
        $newSet = clone $selectionSet;
        $newSet->selections[] = new FieldNode([
            'name' => new NameNode([
                'value' => '__typename'
            ])
        ]);
        return $newSet;
    }
];

$documentNode = Parser::parse($request->queryString);
$modifiedDocumentNode = Visitor::visit($documentNode, $myVisitor);
$result = GraphQL::executeQuery($schema, $modifiedDocumentNode);
// transform $result->data as you need
```

**Comment by vladar** [comment]
Closing, but feel free to re-open if needed

**Comment by keithrobichaud** [comment]
just in case anyone is looking at this later, I had to do this in order for it to work:

```
$myVisitor = [
			NodeKind::SELECTION_SET => function(SelectionSetNode $selectionSet) {
				$newSet = clone $selectionSet;
				$length = count($newSet->selections);
				$newSet->selections[$length] = new FieldNode([
					'name' => new NameNode([
						'value' => '__typename'
					])
				]);
				return $newSet;
			}
		];
```
