### ISSUE TITLE
`resolveField` seems to always have empty `$args`

### ISSUE THREAD

**Issue by alfaproject** [webonyx/graphql-php#215]
I'm trying to use the `resolveField` of my custom type to hydrate some fields.
My use case is that the user can specify in an argument a mutator for that hydration.

Simple test schema:
```php
$queryType = new ObjectType([
    'name' => 'Query',
    'fields' => [
        'test' => [
            'type' => new ObjectType([
                'name' => 'Test',
                'fields' => [
                    'id' => [
                        'type' => Type::string(),
                    ],
                    'name' => [
                        'type' => Type::string(),
                    ],
                ],
                'resolveField' => function($value, $args) {
                    // $args = [];
                },
            ]),
            'args' => [
                'id' => [
                    'type' => Type::string(),
                ],
            ],
            'resolve' => function($parent, $args) {
                // $args = ['id' => 'one']

                $testList = [
                    'one' => [
                        'id' => 'one',
                        'name' => 'One',
                    ],
                ];
                return isset($testList[$args['id']]) ? $testList[$args['id']] : null;
            },
        ],
    ],
]);
```

Simple test query
```gql
query test {
    test(id: "one") {
        id
        name
    }
}
```

`$args` is an empty array, and I have no way to access the real arguments being passed from upstream. Not sure if I'm doing something wrong, but I can get the `$args` in every resolver except this one.

**Comment by vladar** [comment]
Not enough information to understand what's going on. What is your query? Did you try to reduce the case to only the failing field with arguments?

**Comment by alfaproject** [comment]
@vladar I updated the original post with a simple test

**Comment by vladar** [comment]
So why do you expect args in `resolveField`? There are no args for `id` or `name` field in the query, so there are no args in the resolver.

**Comment by alfaproject** [comment]
What do you mean?
`$args = ['id' => 'one']` as per the comment on the `resolve` method. Why is it not on the `resolveField` as well? That's what I'm not understanding.

**Comment by vladar** [comment]
The following query will produce args on `resolveField`:

```graphql
query test {
    test {
        id(myArg: "one") 
        name(myArg: "two") 
    }
}
```

`resolveField` is actually the same as resolve for each field, except it is moved to the type level. You use it like this:

```php
'resolveField' => function(User $user, $args, $context, ResolveInfo $info) {
    switch ($info->fieldName) {
        case 'id':
          /* Here $args['myArg'] === 'one' */
          return $user->getId();
        case 'name':
          /* Here $args['myArg'] === 'two' */
          return $user->getName();
        default:
          return null;
    }
}
```

[Related docs](http://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver-per-type)

**Comment by alfaproject** [comment]
I thought there would be some sort of inheritance going on or at least have a way to access the args further up the tree? ):

**Comment by vladar** [comment]
No, it's dumb and simple. Also, you shouldn't rely on parent args in your child types. The reason is that exact same type can be used in different fields with different sets of arguments. Relying on parent arguments like this is a bad practice and will lead to fragile code.

But if you really, really need it, the only way you have right now is to pass them yourself via `$context` (setting them to context explicitly in the parent and reading in the child).

**Comment by alfaproject** [comment]
Makes sense and fair enough. Thank you for your help mate. (:

**Comment by williamjieh** [comment]
> No, it's dumb and simple. Also, you shouldn't rely on parent args in your child types. The reason is that exact same type can be used in different fields with different sets of arguments. Relying on parent arguments like this is a bad practice and will lead to fragile code.
> 
> But if you really, really need it, the only way you have right now is to pass them yourself via `$context` (setting them to context explicitly in the parent and reading in the child).

Is there any code example for how to modify and pass  `$context` ?

**Comment by mfn** [comment]
See http://webonyx.github.io/graphql-php/executing-queries/
> **context**: Any value that holds information shared between all field resolvers. Most often they use it to pass currently logged in user, locale details, etc.
>
> It will be available as the 3rd argument in all field resolvers. (see section on Field Definitions for reference) graphql-php never modifies this value and passes it as is to all underlying resolvers.

The context is yours to define and you can do anything with it. You pass it in through the initial execuctor call and every resolver receives the value.

Some libraries on top of webonxy default it to the authenticated user object, some others create a mutable class which simply serves as passing data from one part to the other; as suggested here.

**Comment by mfn** [comment]
I believe none of the examples in https://github.com/webonyx/graphql-php/blob/master/examples/00-hello-world/graphql.php use the executor 😅 but it's as simple as adding the value to the `executeQuery` call (it's the fourth, set to `null` here => https://github.com/webonyx/graphql-php/blob/master/examples/00-hello-world/graphql.php#L58 ) and in your resolver it's always the 3rd argument.
