### ISSUE TITLE
null node when add access control on node field

### ISSUE THREAD

**Issue by vbelorus** [webonyx/graphql-php#216]
Hello

I use webonyx/graphql-php with overblog/graphql-bundle. 

I added access: "@=hasRole('ROLE_ADMIN')" to one of the fields and found that if user doesn't have such role result will be null to all node, not only for field.
Example:
request:
`query {
	clientCompanies {
		edges {
			node {
				id,
				name 
			}
		}
	}
}`

result (field name require role than user doesn't have):
`{
	"data": {
		"clientCompanies": {
			"edges": [
				{
					"node": null
				},
				{
					"node": null
				},
				{
					"node": null
				},
				{
					"node": null
				},
				{
					"node": null
				}
			]
		}
	},
	"extensions": {
		"warnings": [
			{
				"message": "Access denied to this field.",
				"locations": [
					{
						"line": 6,
						"column": 5
					}
				],
				"path": [
					"clientCompanies",
					"edges",
					0,
					"node",
					"name"
				]
			},
			{
				"message": "Access denied to this field.",
				"locations": [
					{
						"line": 6,
						"column": 5
					}
				],
				"path": [
					"clientCompanies",
					"edges",
					1,
					"node",
					"name"
				]
			},
			{
				"message": "Access denied to this field.",
				"locations": [
					{
						"line": 6,
						"column": 5
					}
				],
				"path": [
					"clientCompanies",
					"edges",
					2,
					"node",
					"name"
				]
			},
			{
				"message": "Access denied to this field.",
				"locations": [
					{
						"line": 6,
						"column": 5
					}
				],
				"path": [
					"clientCompanies",
					"edges",
					3,
					"node",
					"name"
				]
			},
			{
				"message": "Access denied to this field.",
				"locations": [
					{
						"line": 6,
						"column": 5
					}
				],
				"path": [
					"clientCompanies",
					"edges",
					4,
					"node",
					"name"
				]
			}
		]
	}
}`

Is it ok that we return null to all node, not only to field?

I found something strange when we loop through the foreach in \GraphQL\Executor\Executor::executeFields

If in $result = $this->resolveField($parentType, $source, $fieldNodes, $fieldPath); we have an exception then $responseName changes to node and apply null result to all node.

**Comment by crirus** [comment]
How are these @=hasRole('ROLE_ADMIN') working, can you give a schema definition example?

**Comment by vbelorus** [comment]
Maybe it's issue of overblog/graphql-bundle
This bundle generate such schema for this field:
```php
'name' => [
                        'type' => Type::nonNull(Type::string()),
                        'args' => [
                        ],
                        'resolve' => function ($value, $args, $context, ResolveInfo $info) use ($container, $request, $user, $token) {
                            $resolverCallback = function () use ($container, $request, $user, $token) {
                                return call_user_func_array(['Overblog\\GraphQLBundle\\Resolver\\Resolver', 'defaultResolveFn'], func_get_args());
                            };
                            $accessChecker = function ($value, $args, $context, ResolveInfo $info, $object) use ($container, $request, $user, $token) {
                                return $container->get('security.authorization_checker')->isGranted("ROLE_ADMIN");
                            };
                            $isMutation = $info instanceof ResolveInfo && 'mutation' === $info->operation->operation && $info->parentType === $info->schema->getMutationType();
                            return $container->get('overblog_graphql.access_resolver')->resolve($accessChecker, $resolverCallback, [$value, new Argument($args), $context, $info], $isMutation);
                        },
                        'description' => null,
                        'deprecationReason' => null,
                        'complexity' => null,
                        'public' => null,
                    ]
```

**Comment by mcg-web** [comment]
Hi @vbelorus, you should open this PR on the bundle or just join us on the symfony slack, If the problem is coming from the lib we'll then open a PR here. Also provide your schema It will be easier to find what going wrong...

**Comment by mcg-web** [comment]
@vbelorus the behavior is null but your field is not nullable so set it to null throw on invariantException on field parent (node)

**Comment by vbelorus** [comment]
@mcg-web you're right! If set this field nullable it works fine! Thanks a lot.

**Comment by mcg-web** [comment]
Nice to hear that! :+1:. Next time open PR directly on the bundle or just slack us :D
