### ISSUE TITLE
Conflicting requirements for SchemaConfig::setTypes

### ISSUE THREAD

**Issue by SevInf** [webonyx/graphql-php#217]
In our project, we replace built-in ID type with custom one. As stated in #174, it is necessary to call `SchemaConfig::setTypes` with the array of the types we are overriding. At the same time, we use type loader and we have a few object types, which are only referenced as interface implementation. In this case, we should call `SchemaConfig::setTypes` with a closure, but If we'll do so, `ID` type overriding will stop working.
Is there a way to achieve both those things at the same time?

**Comment by vladar** [comment]
`setTypes` is allowed to be closure for a very specific use case. In general, you just pass it as an array. Why do you need to pass your other types as closure?

**Comment by SevInf** [comment]
@vladar we lazy-load our graphql  types with `typeLoader` option. At the same time, we want to load everything when validating the schema (similar to ##168). If we do it, we can't override `id` type anymore, since by the time callback-style `$types` is called default `IDType` is already added.

**Comment by vladar** [comment]
I see. The issue with custom ID type occurred couple times already, so we obviously need a way to fix it (#174 was just a workaround). 

One idea I had was to exclude `ID` from global types (but keep existing `Type::id()` for backward compatibility and for those who uses simple strings as IDs)

The other option was to allow setting custom serialization/deserialization methods to existing ID type (but that would be global, which is probably not the best way to go).

If you have other ideas how to resolve it, please share. PRs are welcome as well (but better after discussion).

**Comment by vladar** [comment]
Will track this in #301 as it better reflects what has to be done.
