### ISSUE TITLE
Field definition for InputTypeObject does not work with callback function

### ISSUE THREAD

**Issue by ivome** [webonyx/graphql-php#22]
Sometimes the fields do not get added to an InputObjectType when they are defined as a callback. 

Specific example: 
https://github.com/ivome/graphql-relay-php/blob/master/src/Mutation/Mutation.php#L47

If we change that to a function, the test suite fails because the fields do not get added. For the normal ObjectType this seems to work as you can see a few lines after that.

**Comment by vladar** [comment]
Should be fixed in https://github.com/webonyx/graphql-php/commit/b890ef7cfe1b9805cafb53fd284c164a0894a521

**Comment by ivome** [comment]
Awesome, thanks for the quick fix! I found one more for InterfaceType, besides that, all other closure issues seem to be resolved with the latest fix. :+1:
