### ISSUE TITLE
Get result after Mutation

### ISSUE THREAD

**Issue by Exolve** [webonyx/graphql-php#223]
Hi Everyone, 

I have this issue I need help with, how do I know if a mutation is successful or not. My mutation always returns null. Is there a way to return a success message on succcess
Here is a sample return from my mutation call
{
data: {
signup: null
}
}

**Comment by mcg-web** [comment]
Hi, mutation is like resolver you can return from your mutation any array or object representing your output type.

**Comment by mcg-web** [comment]
[here an example](https://github.com/mcg-web/graphql-symfony-doctrine-sandbox/blob/master/src/AppBundle/GraphQL/Relay/Mutation/ShipMutation.php)

**Comment by Exolve** [comment]
<?php
namespace Schema\Mutation;

use Core\TypeRegistry;
use GraphQL\Type\Definition\ResolveInfo;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\InputObjectType;

use Helpers\SimpleCurl;

class MutationType extends ObjectType
{
    public function __construct()
    {
        $config = [
            'name' => 'Mutation',
            'fields' => [
                'signup' => [
                   'type' => new ObjectType([
                                'name' => 'CreateReviewOutput',
                                'fields' => [
                                    'user_id' => Type::int(),
                                    'user_firstname' => Type::string(),
                                    'user_lastname' => Type::string(),
                                    'user_email' => Type::string(),
                                    'status' => Type::boolean()
                                ]
                    ]),
                    'description' => 'Returns user by id',
                    'args' => [
                        'user_firstname' => Type::nonNull(Type::string()),
                        'user_lastname' =>Type::nonNull(Type::string()),
                        'user_email' =>Type::nonNull(Type::string()),
                        'user_phone' =>Type::nonNull(Type::string()),
                        'password'  =>Type::nonNull(Type::string()),
                        'business_name'  =>Type::nonNull(Type::string()),
                        'status'  =>Type::boolean(),
                    ]
                ],
                 'user' => [
                    'type' => TypeRegistry::user(),
                    'description' => 'Returns user by id',
                    'args' => [
                        'id' => TypeRegistry::nonNull(TypeRegistry::id())
                    ]
                ]
            ],
             'resolveField' => function($val, $args, $context, ResolveInfo $info) {                 
                return $this->{$info->fieldName}($val, $args, $context, $info);
            }
        ];
        parent::__construct($config);
    }

    public function signup($rootValue, $args)
    {
        $api_url = USER_SERVICE;
        $api_url .= '/signup';

          $fields['user_firstname'] = $args['user_firstname'];
          $fields['user_lastname'] = $args['user_lastname'];
          $fields['business_name'] = $args['business_name'];
          $fields['user_email'] = $args['user_email'];
          $fields['user_phone'] = $args['user_phone'];
          $fields['user_password'] = $args['password'];

        return json_decode(Simplecurl::post($api_url, $fields));
    }


    public function user($rootValue, $args)
    {

        $api_url = USER_SERVICE;
        $api_url .= '/user/get/'.$args['id'];
        return json_decode(Simplecurl::get($api_url));
    }

   
}

**Comment by Exolve** [comment]
thats my mutation declaration above and I am  returning

    object(stdClass)[392]
      public 'status' => string 'error' (length=5)
      public 'msg' => string 'Business exists, please use a different name' (length=44)

yet I still get 

{
    data: {
               signup: null
            }
    }

**Comment by Exolve** [comment]
whats missing

**Comment by Exolve** [comment]
I think I get it now, its working now, Thanks.
