### ISSUE TITLE
No DateTimeType?

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#228]
I'm a bit surprised that there is no type for time representation in this package. Most applications will need to have some time fields in their schema - does everybody write a custom type without sharing it? Or is there some reason to use normal string type instead of a dedicated date/time type?

**Comment by vladar** [comment]
Check out [this comment](https://github.com/graphql/graphql-js/pull/557#issuecomment-348646592) in the reference implementation and the whole thread.

**Comment by enumag** [comment]
Thanks for the link. It's interesting but ultimately doesn't really help me.

Is there some type outside of this repository you could recommend? Or some different approach? How are you solving this in your apps?

**Comment by vladar** [comment]
The link explains why there is no default date or time type.

Dates are fundamentally hard (apart from simplest cases). We used different solutions depending on a project. One time we even had to express dates as object types which included timestamp, expected local time, factual local time with timezone (timezones and DST rules also change from time to time).

So it depends mostly on your project and applies equally to GraphQL or any other API design. You've seen solutions proposed in the referenced thread - any of them can be valid in different situations.

**Comment by enumag** [comment]
Well I just need a DateTimeType which represents a UTC time as ISO-8601 format. Pretty much the most simple thing.

Here is my current implementation if anyone needs it:

```php
<?php declare(strict_types = 1);

namespace App\Library\GraphQL\Type;

use DateTime;
use DateTimeImmutable;
use GraphQL\Error\InvariantViolation;
use GraphQL\Language\AST\StringValueNode;
use GraphQL\Language\AST\ValueNode;
use GraphQL\Type\Definition\ScalarType;
use GraphQL\Utils\Utils;

class DateTimeType extends ScalarType
{
	/**
	 * @var string
	 */
	public $name = 'DateTime';

	/**
	 * @var string
	 */
	public $description = 'The `DateTime` scalar type represents time data, represented as an ISO-8601 encoded UTC date string.';

	/**
	 * @param mixed $value
	 */
	public function serialize($value): string
	{
		if (! $value instanceof DateTimeImmutable) {
			throw new InvariantViolation('DateTime is not an instance of DateTimeImmutable: ' . Utils::printSafe($value));
		}

		return $value->format(DateTime::ATOM);
	}

	/**
	 * @param mixed $value
	 */
	public function parseValue($value): ?DateTimeImmutable
	{
		return DateTimeImmutable::createFromFormat(DateTime::ATOM, $value) ?: null;
	}

	/**
	 * @phpcsSuppress SlevomatCodingStandard.TypeHints.TypeHintDeclaration.MissingParameterTypeHint
	 *
	 * @param ValueNode $ast
	 */
	public function parseLiteral($ast): ?string
	{
		if ($ast instanceof StringValueNode) {
			return $ast->value;
		}

		return null;
	}
}
```
