### ISSUE TITLE
Field "__typename" is not defined for type...

### ISSUE THREAD

**Issue by crirus** [webonyx/graphql-php#231]
Hello

I try to run a query with meta field "__typename". For some reason I get this error:
```Field \"__typename\" is not defined for type```
Do I need some config or changes in order to resolved this automatically?

Thank you

**Comment by vladar** [comment]
Need more data to reproduce. Type/schema definition/query causing this?

**Comment by crirus** [comment]
Hello

Query is as simple as this
```
query {
  publishers{
    userId
    __typename
  }
}
```

It works just fine for any field except when __typename is added I get
```
{
  "errors": [
    {
      "message": "Field \"__typename\" is not defined for type \"PublisherDetailsOutput\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "publishers"
      ]
    }
  ],
  "data": {
    "publishers": null
  }
}```

**Comment by crirus** [comment]
__typename is supposed to be auto filled on any type, right?

**Comment by vladar** [comment]
Can you please [enable debugging](http://webonyx.github.io/graphql-php/error-handling/#debugging-tools) to see the trace? In case of StandardServer it is [`debug` option](http://webonyx.github.io/graphql-php/executing-queries/#server-configuration-options).

**Comment by crirus** [comment]
Apparently it was some of my code $someType->getField($field_name) I called
throwing the error, if I skip __ prefixed values there, it's fine.

Sorry for false alarm

**Comment by vladar** [comment]
No problem
