### ISSUE TITLE
ability to override integer width values

### ISSUE THREAD

**Issue by roippi** [webonyx/graphql-php#233]
For some background, the graphql spec requires the INT type to be only 32 bits wide.  My team and I fundamentally disagree with this choice, but we're not really prepared to fight a spec battle.

In this library we have the ability to override internal types (https://github.com/webonyx/graphql-php/commit/f7248dec76cee2ad7af6a22799e8462963e935a9) so this is possible, but extending/overriding that part of [IntType](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/IntType.php#L20) is not feasible because these values are referenced as class constants.

Would you consider a PR modifying these to `protected static`s and referencing via `static::` instead so we can extend/override more easily?  Thanks.

**Comment by vladar** [comment]
I do understand these concerns, BUT the whole point of the spec is to have common grounds for GraphQL ecosystem of existing (and future) tools. Allowing customizing these constants means treating the spec as an advice vs strict rules. We won't do it in this library.

There is a similar discussion in [spec repo](https://github.com/facebook/graphql/issues/366) with some advises, including:

- using `floats`
- using `Strings`
- using `custom scalar` (for example something similar to [Int53](https://github.com/nakedible/graphql-scalar-int53) mentioned there)

Sorry for making it harder, but I do believe that sticking to the spec (as a rule) has more value in the long-term. Easy doesn't always mean right.

**Comment by mcg-web** [comment]
Giving user some liberty of choice is not a bad thing and not fundamentally changing the global spec of this graphQL... But this is an useless debat because this issue can just be fix by creating a custom int64 scalar type and use it instead of int.

**Comment by roippi** [comment]
We're going to be overriding this regardless whether you decide to accept this.  It's just a question of whether our override looks like this:
```
$fixedInt = new class() extends IntType {
  protected static $maxInt = PHP_INT_MAX;
  protected static $minInt = PHP_INT_MIN;
};
```

... or whether our override is the entire original class copy-pasted with values modified.  I'd prefer the former since it's less fragile.

**Comment by danydev** [comment]
if you want to avoid copy-paste and the PR is not accepted, you can still go with the tougher path using [runkit_constant_redefine](http://php.net/manual/en/function.runkit-constant-redefine.php) 😄

**Comment by vladar** [comment]
Sorry, I don't want to make it easier to break the spec.
