### ISSUE TITLE
Example 01-blog doesn't work properly

### ISSUE THREAD

**Issue by solo-framework** [webonyx/graphql-php#235]
An endpoint constantly returns the same result for any queries
`{"data":{"hello":"Your graphql-php endpoint is ready! Use GraphiQL to browse API"}}`
When I use ChromeiQL it can't show a schema for API

**Comment by vladar** [comment]
Something is wrong with your setup configuration. I just tried to follow instructions from scratch and everything worked. It looks like your ChromeiQL is not sending valid queries to the endpoint.

 Need more info to help you. Please check the network tab of your browser dev tools when using ChromeiQL and let me know what is getting sent in the browser request and what HTTP method is used.
