### ISSUE TITLE
Field definition for InterfaceType does not work with callback function

### ISSUE THREAD

**Issue by ivome** [webonyx/graphql-php#24]
This is possibly related to #22. When I try to define the `fields` as a callback function for an `InterfaceType`, I get an error: 

`Argument 1 passed to GraphQL\Type\Definition\FieldDefinition::createMap() must be of the type array, object given, called in /Users/ivo/Documents/workspace/graphql-relay-php/vendor/webonyx/graphql-php/src/Type/Definition/InterfaceType.php on line 66 and defined`

**Comment by vladar** [comment]
Managed to miss interface field definitions somehow. Thanks for catching!

Should be fixed in https://github.com/webonyx/graphql-php/commit/d37fb34e96d2f399bff8ffa65b897b767133fc32
