### ISSUE TITLE
Update with changes from graphql 0.12 and 0.13

### ISSUE THREAD

**Issue by danez** [webonyx/graphql-php#243]
I already started going through the commits of graphql and picking relevant changes.
- #237 
- #238
- #239 
- #240 
- #241 
- #242 

If you prefer I can also put the changes all in one branch.

I hope this is okay, but we would like to use some of the new features in my company and after I started I noticed it is fun todo, so I decided to go through all commits. :D

**Comment by vladar** [comment]
Hey @danez this is cool! I will be able to review/merge them somewhere at the beginning of the next week. Feel free to port as much as you want %) Thanks for those PRs!

**Comment by vladar** [comment]
Finally merged %)
