### ISSUE TITLE
Issue parsing variables

### ISSUE THREAD

**Issue by crirus** [webonyx/graphql-php#247]
Hello 

If I define a type like this:
```
'osId' => [
    'type' => Types::listOf(Types::nonNull(Types::get('OperatingSystemInput'))),
    'alias_of' => 'os_id'
],
```

Then I send in variables something like this, it fail parsing:
```
"osId":{"id":"14","versions":["562", "563"]}
```

But if I send array even if single element, it's fine.
```
"osId":[{"id":"14","versions":["562", "563"]}]
```

All this sent as a query works fine, without having to set array with single element for the list definitions.

Any thoughts?

Thanks

**Comment by mcg-web** [comment]
Hello,

This is normal behavior you define your type as `[OperatingSystemInput!]`, remove `Types::listOf()` if not what you want...

**Comment by crirus** [comment]
I need that a list, but then in variables I have to send a list even if I have a single element.
However, in query that is not mandatory.

I found the issue in [Values.php](https://github.com/webonyx/graphql-php/blob/94525c00252696b47673db1ca56fe0436c5949be/src/Executor/Values.php#L235).


with this code we could solve the issue

```
                if(!is_numeric(key($value))) {
                    $val[]  = $value;
                    $value = $val;
                }
```

**Comment by mcg-web** [comment]
I don't understand the issue with variables as an array. Changing this is totally against GraphQL specs, I don't think @vladar will agree with that :laughing:. This is out of my scope I'll leave @vladar decide...

**Comment by crirus** [comment]
It's not really an issue, since we can always send array even with single element.
I just pointed out that while on DocumentValidatior that parses full query this is handled even if I send a single object, not wrapped in array, with variables you can't really tell that received array is a list or the actual object as array.

One way to figure that out is to test if it's associative, and if true, it is safe to assume that's the actual object not array of single object, so you can wrap it in array.

**Comment by vladar** [comment]
Technically you are right, but I can't accept the solution proposed (`array_values($values) !==  $values`). This comparison is O(N) which will add up significantly to the execution time of EVERY list.

Also, we need tests for those cases. I can't accept a PR without related tests. I'll keep this issue open, because it is a valid request, but we really need to approach it more carefully and cover with tests to avoid regressions in future.

**Comment by vladar** [comment]
Actually, after looking into it - it is expected behavior for variables. See related notes in the [reference implementation](https://github.com/graphql/graphql-js/blob/35c68d403cf1020e1d30ea29f0546352d03dd49e/src/utilities/__tests__/valueFromAST-test.js#L169-L170).
