### ISSUE TITLE
Extract AST to separate project?

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#25]
Opening this per https://github.com/jayS-de/graphql-ast request for public discussion

**Comment by vladar** [comment]
While AST can be useful by itself, you can still use it by including whole graphql-php repo and just using AST classes.

That's how [js reference implementation](https://github.com/graphql/graphql-js) repository structured as well. 

Or maybe I am missing something?

**Comment by vladar** [comment]
What would be really great - is having AST as PHP module written in C. There is already C library for graphql parsing - https://github.com/graphql/libgraphqlparser with ruby and pythong wrappers around it. 

It would definately make sense to have it as separate repo if it was built as PHP module.

**Comment by jayS-de** [comment]
Yeah had some time to try a little bit around. For my project i only need the language part. The rest is not so interesting for me. And as there are some graphql ports to be found at packagist. Nearly all look the same when taking a look at the language part.

But yes a C module would be really nice. But as long as it's not out we have to stick to native implementation. :)

**Comment by vladar** [comment]
For now I am closing this, as there is no problem in using AST classes directly from this project.
