### ISSUE TITLE
Allowed PHP memory exhausted before query execution

### ISSUE THREAD

**Issue by varbrad** [webonyx/graphql-php#250]
Hi there!

I have a very simple set of types that are related (A `User` has a list of `List` types, and a `List` has a `User` type).

````php
class UserType extends ObjectType
{
  public function __construct()
  {
    parent::__construct([
      'fields' => [
        'id' => Type::id(),
        'username' => Type::string(),
        'lists' => Type::listOf(Types::list())
      ]
    ]);
  }
}
````

````php
class ListType extends ObjectType
{
  public function __construct()
  {
    parent::__construct([
      'fields' => [
        'id' => Type::id(),
        'title' => Type::string(),
        'user' => Types::user() // <- Removing this line
      ]
    ]);
  }
}
````

Omitting the commented line in `ListType` (`'user' => Types::user()`) works absolutely fine, and consumes around 2Mb of memory within the PHP script. and everything works lovely with the connection to my MariaDB and MongoDB interfaces, and queries work perfectly within GraphiQL and a simple test application. However, if that line remains, then it appears that `graphql-php` gets stuck in some sort of infinite loop where it quickly exhausts all available script memory. I have increased my PHP memory allowance to 1Gb and the issue remains and it quickly exhausts the entire 1Gb memory allowance. It doesn't even seem to be a query issue, as the issue persists even if a blank query (`{ }`) is sent in the POST body.

The PHP error message is not always the same (it can change between executions), but is usually

````
Fatal error: Allowed memory size of 134217728 bytes exhausted
(tried to allocate 262144 bytes) in /var/www/public/vendor/webonyx/graphql-php/src/Type/Definition/Type.php on line 32
````

Thanks for reading, I will keep having a play around with this, as it is probably something I am doing wrong as I am quite new to working with GraphQL in PHP.

Note: I have removed resolvers and field resolvers from the above examples for clarity (as they have no effect on the issue).

All the best.
👍

**Comment by varbrad** [comment]
My apologies. I realise now after talking through the issue with a friend that when GraphQL is 'parsing' the Schema, it must pick one of the two types to 'parse' first, and at this point the other type does not yet exist. It seems some sort of loop then gets entered where GraphQL is constantly trying to create the necessary schema data and keeps going between the two types until it consumes all of the script memory.

For anyone else running into a similar issue, it is simply a case of defining the `fields` property of the Type configuration as a `callable` function, which I found [here in the documentation](http://webonyx.github.io/graphql-php/type-system/object-types/#recurring-and-circular-types).

````php
class UserType extends ObjectType
{
  public function __construct()
  {
    parent::__construct([
      'description' => 'A user',
      // Fields is now a callable, that returns the original object with a resolver shown
      'fields' => function () {
        return [
          'id' => Type::id(),
          'username' => Type::string(),
          'lists' => [
            'type' => Type::listOf(Types::list()),
            'resolve' => function ($value, $args, $root) {
              return $root['db']->getUserLists($value['id']);
            }
          ]
        ];
      }
    ]);
  }
}
````

This all works perfectly now, of course it was my own fault 🤣 .

👍 

__TL;DR__ I should have [RTFM](https://en.wikipedia.org/wiki/RTFM).

**Comment by vladar** [comment]
Cool, glad that you've figured it out!
