### ISSUE TITLE
Nodelist iterator can access non existent offsets

### ISSUE THREAD

**Issue by cpartica** [webonyx/graphql-php#252]
There's an issue with the implementation of the node list iterator, it has to check for offsets before accessing it because offsets can be unset by a public method of this class per \ArrayAccess interface
Provided a PR for the fix https://github.com/webonyx/graphql-php/pull/251

**Comment by spawnia** [comment]
I can confirm this, has happened to me as well!

**Comment by vladar** [comment]
@spawnia Please check the conversation in the referenced PR and my last question. Do you have any preference on it?
