### ISSUE TITLE
Inconsistency between system scalar type serialize/parseValue methods

### ISSUE THREAD

**Issue by mcg-web** [webonyx/graphql-php#254]
Hi, after upgrading my project from 0.10 to 0.11 version I get some weird behaviors with system scalar types when using inputs with variables. I don't really get why we have a differents between `serialize/parseValue` methods.
Here an example `IntType::parseValue` no more accepts string but `IntType::serialize` does:

```php
(new IntType())->serialize('9') !== (new IntType())->parseValue('9'); // 9 !== null
```
In [JS implementation](https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L47-L48) both methods has the same behavior so why in PHP we add these differents? 
I override system scalar types to use 0.10 version right now but this is not the best solution... I'm just trying to understand the reason why...

How I override system scalar types without using reflection:
```php
// Override scalar types
$overrideScalarTypes = \Closure::bind(function () {
    self::$internalTypes = [
        self::ID => new MyType\IDType(),
        self::STRING => new MyType\StringType(),
        self::FLOAT => new MyType\FloatType(),
        self::INT => new MyType\IntType(),
        self::BOOLEAN => new MyType\BooleanType()
    ];
}, null, \GraphQL\Type\Definition\Type::class);
$overrideScalarTypes();
``` 
This can maybe helps some people encountering same issue.

**Comment by vladar** [comment]
As far as I remember it was done in #170. It was actually a valid issue (at least for strings and booleans). A related issue in graphql-js - https://github.com/graphql/graphql-js/issues/771 (yet they seem to fix only string case, not boolean or int).

So do you need to accept strings as integer input?

**Comment by vladar** [comment]
Sorry for the long delay with a response, I suggest to send a PR after I merge #248 (hopefully on this weekend)

**Comment by danez** [comment]
This problem is fixed in #248 as the `serialize` and `parseValue` methods have been aligned together.

**Comment by mcg-web** [comment]
Nice! Thank you @danez :+1: .

**Comment by vladar** [comment]
@mcg-web Can you check if the new version works for you and close if it is OK?

**Comment by mcg-web** [comment]
It seems to be OK! Thank you @vladar and @danez :+1:
