### ISSUE TITLE
Circular reference handled via proxies

### ISSUE THREAD

**Issue by simPod** [webonyx/graphql-php#255]
I'm injecting types via DI constructor. When schema is built, I'm getting this error:

`Schema must contain unique named types but contains multiple types named "CircularType" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).`

That is because I'm using proxies https://github.com/Ocramius/ProxyManager to get actual services so I avoid circular reference.

```php
class TypeOne
{
    public function __construct(TypeTwo $typeTwo)
    {
        // ...
    }
}

class TypeTwo
{
    public function __construct(TypeOne $typeOne)
    {
        // ...
    }
}
```

However the test for duplicate types is `$typeMap[$type->name] === $type` and that's always `false` when using proxies even though the wrapped type is the same instance.

How to handle this properly? My only solution so far is to fork this and remove that check

```php
        if (!empty($typeMap[$type->name])) {
            Utils::invariant(
                $typeMap[$type->name] === $type,
                "Schema must contain unique named types but contains multiple types named \"$type\" ".
                "(see http://webonyx.github.io/graphql-php/type-system/#type-registry)."
            );
            return $typeMap;
        }
```

**Comment by simPod** [comment]
The similar check is on Executor.php:942

**Comment by vladar** [comment]
Do you use proxies for circular types only? Have you seen this [article in docs](http://webonyx.github.io/graphql-php/type-system/object-types/#recurring-and-circular-types) and why it won't work for you?

**Comment by simPod** [comment]
Yup, only for circular types. I use dependency injection for types that I autowire and not using static (global) types which I consider to be a cleaner way. 

But I might have found a way -> opening PR as I believe it's not working properly in this library.

**Comment by vladar** [comment]
I am curious why your proxy manager (or DI container) creates multiple instances for the same underlying type? This seems wrong to me. It leads to subtle errors and may cause significant performance overhead (as basically, you have `{number of fields of this type}` objects per type vs 1) unless I am missing something.

**Comment by simPod** [comment]
The ocramius' https://github.com/Ocramius/ProxyManager creates multiple proxy instances with the same instance of underlying type within. Therefore, it doesn't create circular references when using DI. However I think this approach is no go with this library as it would require adding a new dependency.

Instead I started using callables those when invoked return the actual type instance. This way I can avoid circular references and still use DI. (https://github.com/webonyx/graphql-php/pull/257#issuecomment-373685194)

**Comment by vladar** [comment]
Closing after conversation in #257
