### ISSUE TITLE
Is the examples/03-server broken?

### ISSUE THREAD

**Issue by sarukuku** [webonyx/graphql-php#264]
Did the following:
1. Cloned the repo
2. Ran composer install
3. Ran `php -S localhost:8080 ./graphql.php` in the `examples/03-server` folder
4. Ran `curl http://localhost:8080 -d '{"query": "query { echo(message: \"Hello World\") }" }'`

I seem to always get this as a response:
```
{"errors":[{"message":"GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"","category":"request"}]}
```

Am I doing something horribly wrong?

**Comment by sarukuku** [comment]
Setting the content type works for me too. The error message was just a bit odd. I'll create a pull request later today to update the command.

**Comment by vladar** [comment]
Yeah, that's because CURL would send Content-Type `application/x-www-form-urlencoded` by default and we do support this type as well but then expect `query` prop in `$_POST` which is obviously not there.

**Comment by sarukuku** [comment]
There's now a pull request that updated the example curl commands.
