### ISSUE TITLE
Schema::getType adds a null type when typeLoader returns nothing

### ISSUE THREAD

**Issue by AlexSayHello** [webonyx/graphql-php#268]
I have noticed that the method  `Schema::getType` always defines a key in the $resolvedTypes instance variable.
```php
public function getType($name)
    {
        if (!isset($this->resolvedTypes[$name])) {
            $this->resolvedTypes[$name] = $this->loadType($name);
        }
        return $this->resolvedTypes[$name];
    }
```
The typeLoader may launch an error if the type cannot be resolved, but it can also return null

```php
$schema = new Schema([
     'query' => new ObjectType(['name' => 'Query'])
 ]);

$foo = $schema->getType('Foo'); //maybe returns null
```

The result is a key with a null value on the type map

![typemap](https://user-images.githubusercontent.com/10273130/38551073-8f9a96f6-3cb8-11e8-8061-baf886b2bd9b.png)

Is this behavior expected?
Could it be modified to ignore this key when the result of the type resolver is null?

**Comment by vladar** [comment]
Yeah, we should probably throw in this case.

**Comment by mgdigital** [comment]
In the current version 0.11.5 this creation of a null type allows us to break a GraphQL server using introspection queries, for example:

```
{
    __type(name: "NonExistentType") {
        enumValues {
            name
        }
    }
}
```
Followed by:
```
  {
		__schema {
			types {
				name
			}
		}
}
```
Results in Internal server error: Cannot return null for non-nullable field __Schema.types.

**Comment by vladar** [comment]
PR is welcome!

**Comment by vladar** [comment]
Looks like this has been [fixed already](https://github.com/webonyx/graphql-php/commit/17520876d86f3ab2d83156927bf7b65f59bd7063#diff-8a825b6b1c8fcf722f8d3a1bbfa3e708L224)
