### ISSUE TITLE
Default values not work for notNull fields

### ISSUE THREAD

**Issue by jantajov** [webonyx/graphql-php#274]
Field with type 'notNull' ignores default value and throws error:

`"Argument "paging" has invalid value {pageSize: 2}. In field "page": Expected "Int!", found null."`

```
// PagingType.php

$config = [
	'fields' => function () {
		return [
			'page' => [
				'type' => Type::nonNull(Type::int()),
				'defaultValue' => 1,
			],
			'pageSize' => Type::nonNull(Type::int()),
		];
	},
];
```

With nullable types default value works as expected but then client can pass null value into page field...

**Comment by vladar** [comment]
This is an issue in spec and reference implementation. See https://github.com/graphql/graphql-js/pull/1274 We will likely use the same solution eventually.

**Comment by mdio** [comment]
Since the PR on graphql-js has been merged, will the behaviour be ported to this library?

**Comment by vladar** [comment]
Yes, but this will be likely a part of 0.13 release

**Comment by mdio** [comment]
Thank you for the quick reply.
Is there any ETA on 0.13?

**Comment by vladar** [comment]
Unfortunately no, we've just released 0.12. But chances are high that it will take much less time than 0.12 %)

**Comment by mdio** [comment]
Hehe, okay. Thanks!

**Comment by enumag** [comment]
@vladar So will this be in 0.13 then? I noticed in another thread that you want to release it soon.

**Comment by vladar** [comment]
I did plan to include it in 0.13 but have little time now. And we already delayed the release for a while. Also in the reference implementation, it is a part of the 14.0.0 release.

We could include it in our 0.13 if someone ported these changes in the next couple of days. I'll try to find time but can't promise it.
