### ISSUE TITLE
multi querytye.php

### ISSUE THREAD

**Issue by limweb** [webonyx/graphql-php#275]
in blog example  I see Querytype.php  in put all query  in  this file   how can  to split this file to multi files and QueryType.php is rootQuerytype   
UserQuery.php ,StoryQuery.php ImageQuery.php  all to ==> QueryType.php

Thanks.

**Comment by limweb** [comment]
Myexample:

    $useryqry = (new UserQuery())->getFields();  // type of Objectype
    $queryqry = (new QueryType())->getFields();  // type of Objectype
    $query = new ObjectType(['name'=>'Query','fields'=> $useryqry    + $queryqry]);
    $schema = new Schema([
        'query' => $query
    ]);
        
    $result = GraphQL::execute(
        $schema,
        $data['query'],
        null,
        $appContext,
        (array) $data['variables']
    );

**Comment by limweb** [comment]
How  have a  good solution   thanks.

**Comment by vladar** [comment]
Well, technically a query is just a field in a QueryType object.

So you can do something like this instead:
```php
class UserQuery
{
    function getField()
    {
        return [
            'name' => 'user',
            'type' => Registry::userType(),
            'resolve' => [$this, 'resolveUser']
        ]
    }

    function resolveUser()
    {
        // resolve the query
    }
}

$userQuery = new UserQuery();

$schema = new Schema([
    'query' => new ObjectType([
        'fields' => [
            $userQuery->getField(),
            // add others
        ]
    ])
]);
```

**Comment by limweb** [comment]
please give Registry::userType(),  a  sample  thanks.

**Comment by limweb** [comment]
thanks
