### ISSUE TITLE
Spec Compliance: Strict input coercion for scalars

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#278]
The GraphQL specification defines strict rules for input coercion, especially of scalar types: http://facebook.github.io/graphql/October2016/#sec-Scalars

However, inputs that are passed in as variables are not validated accordingly, while literals are. `parseValue` mostly behaves the same as `serialize` - which allows for some loose coercion.

If i understand the specification correctly, such loose coercion is only allowed for results - outbound information that the server sends to the client. It makes sense in this case, the server should not break the contract it defines in its schema.

Inputs, regardless if they are provided as literals or as variables, are inbound information which come from the client and are sent to the server. In that case, strict validation makes absolute sense - if the client sends bad data, the server should not quietly coerce the value but rather throw an error.

While literals and variables have to be handled differently at first, they both fall into the category of Input Coercion. The spec is really clear on how inputs should be handled, see [Section 6.1.2](http://facebook.github.io/graphql/October2016/#sec-Coercing-Variable-Values):
> If the operation has defined any variables, then the values for those variables need to be coerced using the input coercion rules of variable’s declared type.

What is currently happening is that the result coercion rules, which are different from input coercion rules, are applied to input variables. On the other hand, input literals are treated different than input variables - while according to the specification, they should be handled the same in regards to the coercion.

It seems like there is a fundamental misunderstanding here. If it is on my side, maybe you can clear it up for me? If not, i think resolving this issue to ensure spec compliance requires breaking changes to the implementation.

**Comment by vladar** [comment]
Can you share the version of the lib you are referring to? Also, can you take a look at the master branch (there were multiple changes in this area recently)?

You may also find useful following readings (later are more relevant):

#170 
#184 
#254

**Comment by vladar** [comment]
Yeah, there were different opinions on this subject and the reference implementation choice had won this dispute in past.

So I think the best way to fix it is to report this issue in the reference implementation repo. If they admit it then we can revert back to our original fix (or use the solution they introduce eventually).

**Comment by spawnia** [comment]
A PR in the reference implementation is on the way to switch to strict input type coercion: https://github.com/graphql/graphql-js/pull/1382

**Comment by vladar** [comment]
Good news. I regret that I've published 0.12 with a reverted behavior. Will probably have to fast-forward to 0.13 with a recommendation to avoid 0.12 if scalar serialization is important.
