### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by simPod** [webonyx/graphql-php#284]
Hello,

is there any codestyle to comply with when contributing?

Thanks!

**Comment by vladar** [comment]
Ideally, we should follow PSR-4. But since there is no automatic PHP code style checks or PHP code style fixer in Travis, this is not enforced yet.

The best solution would be to set up code style checks or fixer for PSR-4, but I never found time for it. PRs are welcome!

**Comment by simPod** [comment]
There are no PSR-4 coding standards AFAIK 🤔 

Some defaults are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend but are pretty useless in their raw form TBH (eg. missing useful sniffs).

Personally I fancy this one https://github.com/doctrine/coding-standard It's the most advanced coding standard out there currently.

If interested, I can look into it.

**Comment by vladar** [comment]
Yeah, sorry, I meant PSR-2 initially

**Comment by vladar** [comment]
Doctrine code style looks reasonable for me. Go ahead with it if you have a moment!

**Comment by simPod** [comment]
Kk, you can assign me to this issue. Expect PR next week.

**Comment by fesor** [comment]
@vladar 

> there is no automatic PHP code style checks or PHP code style fixer in Travis

Why not use php-cs-fixer in dry run to be sure that all commits has proper code style?

**Comment by simPod** [comment]
@fesor Travis CS step will be part of the PR

**Comment by vladar** [comment]
Can you also add a note to [CONTRIBUTING.md](https://github.com/webonyx/graphql-php/blob/master/CONTRIBUTING.md) about code style requirements?

**Comment by mfn** [comment]
@vladar are you open for using a non-open source tool?

https://styleci.io/ comes to my mind which has a very nice feature: you can configure it to automatically push a "corrected" source version on PRs (disclaimer: not 100% this works on PRs created from remote repos, but it can be set to work on master branch too).

This means: once a style has been configured/agreed upon, every PR or master will automatically receive commits from the service with the violations being resolved. No more manual checking or discussion what is correct.

Also: it's free for open source:
> We love Open Source and as such, public PHP projects will always be free with StyleCI.

I apologize in advance if this is inappropriate to suggest. I'm a commercial customer of the service for some time now. It's simply a blessing.

(PS: it's not about StyleCI specifically, I just know this service. The point: auto-commit source correction saves everyone time).

**Comment by vladar** [comment]
@mfn Thanks for the suggestion! I've been thinking about this myself as code style checks just add unneeded resistance for those wishing to contribute. So the tool like this makes perfect sense. I'll review it when I have a moment. Maybe you have a sample project which we can use as a reference to set it up?

**Comment by simPod** [comment]
There's `phpcbf` binary, that fixes CS errors. IMO auto-commits to PRs from some 3rd party tool might not be always desired. Also, that tool will probably just run phpcbf as well. Personally, I think it does not add any value.

@vladar what do you mean by that resistance? I can't imagine how while being a contributor coding standard prevents me from contributing. In this case, when checks are automated and the errors are automatically reported by the tool (Travis), it's very easy to fix those errors. Also, for me as a contributor, I can safely use auto format in IDE for files that are already fully compliant with the standard without making unneeded changes in those files. I have the coding standard preset configured in IDE and as many OSS projects use this CS, it's very convenient. Also, other advantage is that some part of "non-business logic" review is done automatically so when reviewing PR, focus goes to logic that matters and not to reviewing missing spaces.

**Comment by vladar** [comment]
@simPod The point is to have all the benefits of enforced code style with no cost for contributors (automatically fixed errors). If we can achieve it with `phpcbf` - it would be great. I know there is also [prettier-php](https://prettier.io/blog/2018/04/09/plugin-php-0.1.html), but it is pretty much alpha and it is a bit weird to use js-based tools for this.

**Comment by simPod** [comment]
@vladar yup, that's why I have converted two (?) folders in src already so phpcbf can be soon run very easily when I submit the rest.

ad prettier: why not but still alpha. It has a potential though.
