### ISSUE TITLE
Tiny library for Batch processing

### ISSUE THREAD

**Issue by vasily-kartashov** [webonyx/graphql-php#290]
Hello,

I was wondering if you will find this library of mine https://github.com/vasily-kartashov/graphql-batch-processing worth mentioning on the documentation page. It's a simple batch processor that helps define all batch processing operations like collection, fetching, filtering and formatting in a simple builder like interface.

**Comment by vladar** [comment]
Yeah, I guess such tool would be useful for starters to work with batching. Feel free to send a PR mentioning your lib in [this section of docs](https://github.com/webonyx/graphql-php/blob/master/docs/complementary-tools.md) and I'll merge it.

**Comment by vladar** [comment]
Closed via #298
