### ISSUE TITLE
ResolveInfo::foldSelectionSet handles recursion incorrectly

### ISSUE THREAD

**Issue by gabym** [webonyx/graphql-php#30]
When calling `ResolveInfo::foldSelectionSet` recursively, `--$descend` should be replaced with `$descend - 1` otherwise in the next iteration step (in case we are in a loop) the results will be wrong.

**Comment by vladar** [comment]
Fixed in https://github.com/webonyx/graphql-php/commit/68d868198359f8c29190c271f8108f37f6fa2f51

Thanks for reporting!

**Comment by gabym** [comment]
Thanks for fixing so quickly
