### ISSUE TITLE
Allow StringType to serialize stringeable values

### ISSUE THREAD

**Issue by theofidry** [webonyx/graphql-php#302]
I'm not sure when this was removed, but it has been merged in #210 and should be in 0.11.5+. It's however nowhere to be found in the latest version: https://github.com/webonyx/graphql-php/blob/50dfd3fac2cc566335b1667c7e23b29a86df3846/src/Type/Definition/StringType.php

**Comment by vladar** [comment]
That's an issue, I've missed it when reviewed 0.12 PRs. We should restore it. PR is welcome!
