### ISSUE TITLE
A type can't be reused for multiple queries/mutations

### ISSUE THREAD

**Issue by bwaidelich** [webonyx/graphql-php#31]
When creating a root query & mutation with the same result type, an exception is thrown:
```
Schema must contain unique named types but contains multiple types named "<type>".
```
I would think it's rather common to reuse the same type – e.g. when returning an instance after creating it.
The `express-graphql` implementation allows this, I quickly checked.

When commenting out that check in `\GraphQL\Schema` everything seems to work, too.. Any particular reason for this invariant?

PS: Great library, very useful! ;)

**Comment by vladar** [comment]
I am curious about your exact use-case. Can you provide an example?

But in general, if you reuse the same type - just re-use the same object for this type %) 

Schema contains map of all types by name. If you have different objects for the same type name, which one should it return when calling `$schema->getType($name)`?

Another reason is that it is very easy to incidentally add two different types with same name.

graphql-js has exactly the same invariant - check https://github.com/graphql/graphql-js/issues/146

**Comment by bwaidelich** [comment]
Thank you for the quick reaction!

My bad. I have a rather complex schema, so I created one class per type extending `ObejectType` and using it like:

```
'fields' => [
    'someField' => [
        'type' => new CustomType(),
    ],
    // ...
```

(must have been late ;))

When reusing the same instance it does work indeed.


But I do wonder about the best way to split this up into multiple classes, especially with things like Dependency Injection.. I'll probably have to go for singletons.

**Comment by vladar** [comment]
@bwaidelich You don't have to build types as singletones. The only requirement is that same schema must contain only one instance with same type name.

The common way to fit into this requirement is to have factory instance per schema (some people call these type resolvers).

Simple example:
```php
class TypeFactory
{
    private $types = [];

    public function myType()
    {
        if (!isset($this->types['MyType'])) {
            $this->types['MyType'] = new MyCustomType();
        }
        return $this->types['MyType'];
    }
}
```

(obviously you can add some dynamism to avoid boilerplate). 

Then in your types (even if you extend ObjectType) you can use this factory:

```php
class MyCustomType extends ObjectType
{
    public function __construct(TypeFactory $types)
    {
        $config = [
            'name' => 'MyType',
            'fields' => function() use ($types) {
                return [
                    'recurse' => ['type' => $types->myType()],
                    'field1' => ['type' => $types->someOtherType()],
                ];
            }
        ];
        parent::__construct($config);
    }
}
```

**Comment by bwaidelich** [comment]
@vladar I forgot to respond: thanks for the tip, that's what I basically meant with "singleton" because the factory/resolver needs to be one. It works out quite nicely and I created a little bridge-package to make use of this in [Neos Flow](https://www.neos.io/): https://packagist.org/packages/wwwision/graphql
