### ISSUE TITLE
create mechanism for merge remote schema to local

### ISSUE THREAD

**Issue by Smolevich** [webonyx/graphql-php#313]
@vladar, it is possible to create remote schema by and merge with local . For example, move this implementation [graphql-tools](https://github.com/crirus/graphql-php-tools) ?

**Comment by vladar** [comment]
I afraid no. It is too much for us to maintain. But you can build a separate project on top of graphql-php (same as original apollo [graphql-tools](https://github.com/apollographql/graphql-tools) are built on top of [graphql-js](https://github.com/graphql/graphql-js))
