### ISSUE TITLE
Best Practice for modularizing code

### ISSUE THREAD

**Issue by rijulg** [webonyx/graphql-php#315]
Hey, 

Are there any best practices for modularizing the schema efficiently? 
I read a couple of articles in the Node.js implementation where people have exported fragments of the schema (queries, mutations etc) from single file then ultimately imported it in the main schema. 

I haven't seen anyone do this yet, but they can also go fractal with this by passing multiple arrays from one class and iterating through it in the main file; but since PHP does not have such a functionality I am not sure about what is the best way to do this.

For now, here's what I have done.

```php
...
$schema = new Schema([
    'query' => SchemaBase::getBaseQuery(),
    'mutation' => SchemaBase::getBaseMutation(),
]);
...
```

```php
class SchemaBase {
    public static function getBaseQuery(){
        return new ObjectType([
            'name' => 'Root',
            'fields' => [
                ((array) new EchoType()),
            ],
        ]);
    }
...
```
```php
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;

class EchoType {

    public $name;
    public $type;
    public $args;
    public $description;
    public $resolve;

    public function __construct(){
        $this->name = 'echo';
        $this->type = Type::string();
        $this->args = [
                'message' => Type::nonNull(Type::string()),
        ];
        $this->description = 'Try me';
        $this->resolve = function ($root, $args) {
                return "You Sent us $args[message]";
        };
    }

}
```

I am able to make the code much more modular like this but I am worried about the class/object to array conversion cost. 

Please suggest some better way to implement this. 

**Aside:** 
I saw in a talk that Facebook has developed Reflection/Introspection based autogenerators for their Hack/PHP codebase, is there any plan to introduce something like that?

We can probably leverage PSR4 or other conventions, suffix or prefix things with Types/Schema/GraphQL/Query/Mutation and then pull in the classes from a specified directory read the class constants (I prefer them over comments, but no real reason to not use class annotations) and do pretty much what I have done in the above example by default.

That should make writing modular code much easier as well as enable optimizing by caching the built schema.

**Comment by vladar** [comment]
We focus on core implementation. Even if you write something like annotation-based definitions you still need to convert them to lower-level object tree. And this project provide such low-level core implementation (same as facebook's reference implementation).

Features you describe should be implemented in separate projects. And in fact there are couple projects doing something similar. The [first one](https://github.com/Ecodev/graphql-doctrine) is for Doctrine with annotations. And the [second one](https://github.com/nuwave/lighthouse) uses Schema definition language (with Laravel).

I encourage you to take a look at those or to create your own project!
