### ISSUE TITLE
[SUGGESTION] QueryComplexity: allow calculating/retrieving of "complexity", not just report violations

### ISSUE THREAD

**Issue by mfn** [webonyx/graphql-php#316]
AFAICS, the implementation in `\GraphQL\Validator\Rules\QueryComplexity::getVisitor` can only calculate **and** report a violation.

It's not possible to "retrieve" the complexity, e.g. for cases there is _no_ violation.

What do you think about a way to simply retrieve the value (for analysis purpose) ?

I would like to track the complexity of each/selected queries and store the value in some log, but currently can't see a way to get it.

Thanks!

**Comment by vladar** [comment]
@mcg-web Can you take a look?

**Comment by mfn** [comment]
PS: same applies to `QueryDepth` too.

I'm not sure what qualifies a good design but I think a property on the plugin which can then be retrieved would suffice.

**Comment by mcg-web** [comment]
Here a way this can be done right now for `QueryComplexity`:

```php
<?php
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ObjectType;

$myLogger = new MyLogger();

$type = new ObjectType([
    'name' => 'MyType',
    'fields' => [
        'someList' => [
            'type' => Type::listOf(Type::string()),
            'args' => [
                'limit' => [
                    'type' => Type::int(),
                    'defaultValue' => 10
                ]
            ],
            'complexity' => function($childrenComplexity, $args) use ($myLogger) {
                $myLogger->debug('"someList" field childreen complexity: '.$childrenComplexity)
                
                return $childrenComplexity;
            }
        ]
    ]
]);
```

**Comment by vladar** [comment]
@mcg-web What about QueryDepth?

**Comment by mcg-web** [comment]
right we don't have no way to add debug message for QueryDepth
