### ISSUE TITLE
Set Error Response code for PSR Response

### ISSUE THREAD

**Issue by gohelkiran30** [webonyx/graphql-php#320]
As per discussion with in below thread, we can set custom error message using exceptions but it returns response code 200.
https://github.com/webonyx/graphql-php/issues/207

How to change response status code with error handler?

**Comment by vladar** [comment]
Errors handler affects the result of the GraphQL operation only. If you need to apply custom logic to PSR response, you can use server helper methods. E.g. something along the lines:

```php
$server = new StandardServer($config);
$executionResult = $server->executePsrRequest($request);
$psrResponse = $server->getHelper()->toPsrResponse($result, $response, $writableBodyStream);

if ($executionResult->data === null) {
    $psrResponse = $psrResponse->withStatus(500);
}
```
But keep in mind that if you use query batching `$executionResult` may be also an array, so real code will be more nuanced.

Also note that the StandardServer returning status code 200 for partial result is perfectly valid. The server changes status code when there is no data to return. But there is also #309, so things may change.
