### ISSUE TITLE
Feature Suggestion: Resolver Middleware

### ISSUE THREAD

**Issue by dereklavigne18** [webonyx/graphql-php#326]
As my schema grows I've found more and more of a need to add some of the same logic to all my resolvers. It would be nice if we could add some middleware that would be executed on resolvers in the schema when we go to execute the query. This could allow users to implement things like custom error handling, logging, and authorization on all resolvers without the need to add them to each resolver on the schema.

I have a few ideas of how this could work, so if there is interest I can post a PR or at least dump my thoughts here.

**Comment by vladar** [comment]
While I like the idea of resolver middlewares, we will implement it only if the reference implementation does it first. So I suggest you post this idea in [their GitHub](https://github.com/graphql/graphql-js). If they implement it - we'll do it too.
