### ISSUE TITLE
\GraphQL\Error\Error code is always 0

### ISSUE THREAD

**Issue by ilyazub** [webonyx/graphql-php#327]
Error code is always 0.

This is the state of things since v0.2, as I see.
https://github.com/webonyx/graphql-php/blob/dbeaf46631a094f1217a56e97756805f2991d1d4/src/Error/Error.php#L100

I want to pass own error formatter like this.
```php
function (\GraphQL\Error\Error $error) {
    return array_merge(
        [
            'code' => $error->getCode(),
        ],
        \GraphQL\Error\FormattedError::createFromException($error)
    );
}
```

It seems that `graphql-js` don't disallow adding error codes.

`apollo-server` explicitly [allows error codes](https://github.com/apollographql/apollo-server/blob/ae9da10e625cf283568ba6d29cea8c3e69a7a03f/docs/source/features/errors.md#codes). But errors are available via [`errors[].extensions.code`](https://github.com/apollographql/apollo-server/blob/ae9da10e625cf283568ba6d29cea8c3e69a7a03f/packages/apollo-server-errors/src/index.ts#L35).

In `graphql-php` `\GraphQL\Executor\ExecutionResult::__construct` is always invoked only with two arguments: `$data` and `$errors`. `$extensions` are never passed.

How to deal with error codes in `graphql-php`?

**Comment by vladar** [comment]
Error codes are the part of your application. So you define them in your own exceptions which you throw in resolvers. They are later available via `$error->getPrevious()` in the [error formatter](https://webonyx.github.io/graphql-php/error-handling/#custom-error-handling-and-formatting).

If you use a StandardServer, take a look at the [`errorFormatter` option](https://webonyx.github.io/graphql-php/executing-queries/#server-configuration-options)

**Comment by ilyazub** [comment]
Yes, you are right. But, when I `throw new UserError('test', 'TEST_ERROR_CODE')` and use specified above `errorFormatter`, `$error->getCode()` returns *0* instead of *100*. Because of `\GraphQL\Error\Error` constructor.

**Comment by ilyazub** [comment]
It works, thanks. The only edit to your code:
```diff
function (\GraphQL\Error\Error $error) {
    $prev = $error->getPrevious();
    return array_merge(
        - $prev ? ['extensions' => ['code' => $error->getCode()]] : [],
        + $prev ? ['extensions' => ['code' => $prev->getCode()]] : [],        
        \GraphQL\Error\FormattedError::createFromException($error)
    );
}
```

**Comment by vladar** [comment]
Yeah, I meant `$prev`
