### ISSUE TITLE
Deprecate callbacks in field types

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#35]
Deprecate following field definition form:
```php
[
    'name' => 'Foo',
    'fields' => [
        'bar'  => ['type' => function()  use(&$barType) { return $barType;}],
        'baz'  => ['type' => function()  use(&$bazType) { return $bazType;}],
    ]
]
```
in favor of:
```php
[
    'name' => 'Foo',
    'fields' => function() use (&$barType, &$bazType) {
        return [
            'bar' => ['type' => $barType],
            'baz' => ['type' => $bazType],
        ];
    }
]
```

**Comment by ooflorent** [comment]
Is there any reason why? What's the motivation behind this change?

**Comment by vladar** [comment]
This seems redundant. Also first notation adds some performance overhead because every field type has to be checked with `is_callable` and then validated against base `Type` class.

Pretty much everything you can do with first notation can be done with second as well. Also that's how reference js implementation works. It turns out that maintaining this library is way easier when there is little deviation from reference implementation (at least until things settle down with GraphQL itself).

But if you have any use-cases which require this feature - please describe them. That's pretty much the reason why I created these issues - to start a discussion if somebody needs them %)

**Comment by mcg-web** [comment]
:+1: for this change! it will be much more easier to implements dynamics fields without having to used hacks.

**Comment by vladar** [comment]
Done in https://github.com/webonyx/graphql-php/commit/c11f25794a16863ad727c844ca9083bf1cb3c3d1

**Comment by decebal** [comment]
must compliment you guys for referincing this issue in the actual error message! :1st_place_medal:

**Comment by Alexandru-Dobre** [comment]
Is there any chance the first notation could be permitted once again ?
We have a library that uses this and json models in order to build a loopback-like php graphql api factory. 
Having to move the callback to the fields rather than the type of each field would greatly complicate things since the field is linked to the middleware-connector pipeline during field construction. Here's a link to the concerned code : https://github.com/ampize/alambic/blob/master/src/Alambic/Alambic.php

**Comment by vladar** [comment]
@Alexandru-Dobre We can discuss it, but first I would like to figure out why it is impossible to change the code of your library for this notation (as it is also the only way reference js implementation allows you to define fields). I am pretty sure there should be a way to do this.

What will happen if you change [these lines](https://github.com/ampize/alambic/blob/master/src/Alambic/Alambic.php#L287-L297) to:
```php
$typeArray = [
    'name' => $type['name'],
    'fields' => function() use ($type) {
        $fields = [];
        foreach ($type['fields'] as $fieldKey => $fieldValue) {
            $fields[$fieldKey] = $this->buildField($fieldKey, $fieldValue);
        }
        return $fields;
    }
];
if (!empty($type['description'])) {
    $typeArray['description'] = $type['description'];
}
$this->alambicTypes[$typeName] = new ObjectType($typeArray);
```
Obviously you will have to remove closure for `type` option in `buildField` (it is also quite possible that you will have to wrap remaining code of this method to same closure as well).

Why this will not work?

**Comment by Alexandru-Dobre** [comment]
@vladar Thank you for the suggestion! It worked perfectly with minimum changes to our library code. The rest of the method doesn't need closures as only the "fields" part was exposed to a cyclic dependency issue (models for SQL databases had foreign keys pointing to each other) since we automatically exclude non-scalar fields as query args.

**Comment by vladar** [comment]
Nice!

**Comment by wowngasb** [comment]
I don't think this is a good idea, you can add lazy loading with all fields, but please don't deprecate callbacks in field types. Some time I need to build a object class like this, and make it extendable, you can modify the field you need and add some other field. But with the closure for fields, you must copy all the fields code.
``` php
namespace demo;

class Types
{
    // Types register 
}

class BasicMsg extends ObjectType
{

    public function __construct(array $_config = [], $type = null)
    {
        if (is_null($type)) {
            /** @var Types $type */
            $type = Types::class;
        }
        $config = [
            'description' => "base msg extendable",
            'fields' => []
        ];
                
        $config['fields']['msg_id'] = [
            'type' => $type::nonNull($type::ID()),
            'description' => "msg id",
        ];

        $config['fields']['msgContent'] = function() use ($type) {
            return [
                'type' => $type::MsgContentUnion([], $type),  // type MsgContentUnion have circular types of BasicMsg
                'description' => "msg content",
            ];
        };
        
        if (!empty($_config['fields'])) {
            $config['fields'] = array_merge($config['fields'], $_config['fields']);
        }
        parent::__construct($config);
    }
}

namespace app;

class Types extends \demo\Types 
{
    // rewrite types if you need
}

class BasicMsg extends \demo\BasicMsg   // class extends BasicMsg  and register in Types
{

    public function __construct(array $_config = [], $type = null)
    {
        if (is_null($type)) {
            /** @var Types $type */
            $type = Types::class;
        }
        $config = ['fields' => []];
                
        $config['fields']['msgContent'] = function() use ($type) {
            return [
                'type' => $type::MsgContentUnion([], $type),  // this MsgContentUnion maybe another Type register in Types whit the same name
                'description' => "msg content",
            ];
        };
        
        // you can add more fields
        $config['fields']['room_id'] = [
            'type' => $type::nonNull($type::Int()),
            'description' => "room id",
        ];

        if (!empty($_config['fields'])) {
            $config['fields'] = array_merge($config['fields'], $_config['fields']);
        }
        parent::__construct($config);
    }
}
```
