### ISSUE TITLE
Catchable Fatal Error: Object of class Closure could not be converted to string

### ISSUE THREAD

**Issue by Denys-Bushulyak** [webonyx/graphql-php#352]
GraphQL request query:
```graphql
query {
  greetings {
    short(text:"John")
    long {
      length
      text
    }
  }
}
```

Root map at `GraphQL::executeQuery`:
```php
[
    'Version' => function ($root, $args, $context, ResolveInfo $info) {

        return [
            'long' => function ($root, $args, $context, ResolveInfo $info) {
                $str = $root['short']."and Long text"; //Problem here: Catchable Fatal Error: Object of class Closure could not be converted to string

                return [
                    'text' => $str,
                    'length' => strlen($str),
                ];
            },
            'short' => function ($root, $args, $context, ResolveInfo $info): string {
                return strtoupper($args['text']) ?? 'default';
            },
        ];
    },
]
```

**Comment by Denys-Bushulyak** [comment]
Research showing that: `short` field didn't execute before passing as part of `$root` at `long` field Closure.

`$root['short'] instance of \Closure` and can't be concatenated to the string `"and Long text"`

**Comment by vladar** [comment]
But if your `$root['short'] is a closure, why do you call it as a string here:

```php
$str = $root['short']."and Long text";
```

Of course you'll get this error.

**Comment by Denys-Bushulyak** [comment]
It's not obvious. Maybe I wrong but expected than each field resolver has to be executed before passing to next `$root`.

**Comment by vladar** [comment]
But in your case, they are on the same level. `long` and `short` will get the same parent value of the "greetings" resolver.

**Comment by mfn** [comment]
It's a "chicken and egg" problem, isn't it?

You can't prematurely resolve the fields on the same level so you can the `\Closure` instance "instead", simply said?

**Comment by Denys-Bushulyak** [comment]
Agree.
