### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by agougousis** [webonyx/graphql-php#365]
Hi! I am trying to write some demo code that uses graphql-php with a couple of types that they have a circular dependency and I am getting an error "Unexpected end of JSON input".  I am not sure what is going on.

In a few words, a user has posts and a post has an author. The user (or author) is of type UserType and the post is of type PostType. So, the UserType has a posts field:

`'posts' => [
                'type' => Type::listOf(TypeRegistry::postType()),
            ]`

with a dummy resolver resolver:

```
protected function resolvePosts()
{
    $posts[] = (object) [
        'id'       => 3264,
        'title'    => 'Demo title 1',
        'authorId' => 13242
    ];

    $posts[] = (object) [
        'id'       => 883,
        'title'    => 'Demo title 2',
        'authorId' => 13242
    ];

    return $posts;
}
```
and the PostType has a author field:

```
'author' => [
                'type' => TypeRegistry::userType(),
            ],
```
with a dummy resolver:

```
protected function resolveAuthor($postObj)
    {
        $user = (object) [
          'id' => $postObj->authorId,
          'username' => 'Alexandros',
          'password' => 'wr3v43Rg3',
          'email' => 'alex@gmail.com'
        ];

        return $user;
    }
```

Then, when I try to run a "user" query, even without requesting the posts field, I am getting the "Unexpected end of JSON input" error. 

Any ideas ?

The code is [here ](https://github.com/agougousis/graphql-php-example)

**Comment by simPod** [comment]
How do you execute the query, do you use a client like graphiql? It probably returns not-json formatted exception and client won't show it because you're not converting it to json

**Comment by agougousis** [comment]
You are right! I tried with Postman, too, but I get an empty body. However, the PHP error log says:

PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in C:\laragon\www\graphqlphp\schema\Types\PostType.php on line 15

Of course, I suspect the circular dependency, but I don't know what am I doing wrong. I am using a type registry as recommended in the documentation.

**Comment by simPod** [comment]
ur fields are not callable, you're resolving arrays instantly

**Comment by agougousis** [comment]
Why ? If I am not missing something, the value of  $config['fields']   is an anonymous functions ( a closure). So, it can be called to return the fields.

**Comment by vladar** [comment]
Sorry I didn't look at your code at first.

The error [is here](https://github.com/agougousis/graphql-php-example/blob/master/schema/Types/PostType.php#L13-L26).

You must replace it with:
```php
$this->setFields(function() {
    return [
        // your fields
    ];
});
```

The whole point of making `fields` a closure is to postpone creation of the fields array and thus break the cycle. But you do create it first and then return it from the closure.

**Comment by agougousis** [comment]
I understand the purpose of the closure but I am not getting why the closure is not there. In the ObjectTypeExtension's constructor, I do:

```
$config['fields'] = $this->fields;
...
parent::__construct($config);
```

BUT before this constructor is called, the child constructor (of UserType or PostType) is called, which uses the ObjectTypeExtension's setFields() in order to assign to $this->fields an anonymous function that returns the real fields.

So, when the constructor of ObjectType is called, the value of the  $config['fields'] is a closure. As it is in the documentation: http://webonyx.github.io/graphql-php/type-system/object-types/#recurring-and-circular-types

You can verify this by putting a var_dump like this:

```
class ObjectTypeExtension extends ObjectType {

    protected $fields;

    public function __construct()
    {
        $config['fields'] = $this->fields;

        if (method_exists($this, 'resolveField')) {
            $config['resolveField'] = [$this, 'resolveField'];
        }

        var_dump($config);
        die();

        parent::__construct($config);
    }
   ...
}
```


Maybe, I am too tired to understand.  :-/

**Comment by vladar** [comment]
You see the array created [here](https://github.com/agougousis/graphql-php-example/blob/master/schema/Types/PostType.php#L13-L26)?

It must be created inside a closure (which is called later - during query execution), but you create it immediately in the constructor at this line.

So what you get is a following sequence of actions:
```php
PostType::__construct();
  TypeRegistry::userType();
    UserType::__construct();
      TypeRegistry::postType();
        // And here the fun happens because constructor of the PostType (at the very first line)
        // didn't finish yet, so Registry attempts to create a new instance, hence the loop
        PostType::__construct();
```

**Comment by agougousis** [comment]
Damn me! Now I see! 
So, even before the setFields() is called we are trapped into this loop trying to calculate the parameter.

**Comment by agougousis** [comment]
Thanks guys!!
