### ISSUE TITLE
Question about section use for global functions in all classes on branch master

### ISSUE THREAD

**Issue by Smolevich** [webonyx/graphql-php#368]
For example, in latest release [v0.12.6](https://github.com/webonyx/graphql-php/blob/v0.12.6/src/Executor/ExecutionResult.php#L4) has one use section with `use`, but on [master](https://github.com/webonyx/graphql-php/blob/master/src/Executor/ExecutionResult.php#L9-L10) there many sections with `use` for global functions. What is the profit in this behavior?

**Comment by simPod** [comment]
It is very well summed up here https://github.com/doctrine/coding-standard/pull/15

TL;DR: it's faster ;)

**Comment by Smolevich** [comment]
Do you have any benchmarks for this usecase?

**Comment by simPod** [comment]
No, I have not done any
