### ISSUE TITLE
[BUG] Notice: Trying to get property of non-object in Utils/ASTDefinitionBuilder.php on line 421

### ISSUE THREAD

**Issue by steffans** [webonyx/graphql-php#370]
I am using the graphql schema files to define my types, etc. Using the Parser::parse/AST::toArray to convert the schema files. However the comments give me a PHP notice in as of version 0.12

`Notice: Trying to get property of non-object in Utils/ASTDefinitionBuilder.php on line 421`

The node description is a `string` not an Object (Line 421):

```php
if ($node->description) {
     return $node->description->value;
}
```

**Comment by simPod** [comment]
Can you add more info how to reproduce the issue? Just run tests and there always is StringValueNode. Some examples:

![image](https://user-images.githubusercontent.com/327717/46724712-ea132600-cc7a-11e8-9098-7e0a39625973.png)

![image](https://user-images.githubusercontent.com/327717/46724729-f26b6100-cc7a-11e8-976c-02e5a6c0cbba.png)

![image](https://user-images.githubusercontent.com/327717/46724739-f7301500-cc7a-11e8-8238-26893193b339.png)

**Comment by steffans** [comment]
@simPod Sorry, found it. I was using a cached AST from 0.11, so with a 0.12 AST it works 👍🏻

**Comment by vladar** [comment]
FYI, I added a note in UPGRADE.md for 0.11 -> 0.12 upgrade about AST cache incompatibility. Thanks for brining this up!
