### ISSUE TITLE
When is the date of next release?

### ISSUE THREAD

**Issue by Smolevich** [webonyx/graphql-php#371]
I intested this class https://github.com/webonyx/graphql-php/blob/master/src/Utils/SchemaExtender.php, but he doesn't exists in the last stable version, when is the date of next release?

**Comment by vladar** [comment]
We had plans to fix couple more issues before the release but may choose to postpone them to future releases and release immediately instead. If so, we'll release it in the next week. But no guarantee here.

**Comment by jbtbnl** [comment]
@vladar I'm interested in a release containing the SchemaExtender as well. Are there blocking issues in dev-master that we can help fix?

**Comment by vladar** [comment]
Yeah, sorry for the delay. Just published v0.13.x.

**Comment by jbtbnl** [comment]
@vladar thank you!
