### ISSUE TITLE
error

### ISSUE THREAD

**Issue by devalexandre** [webonyx/graphql-php#372]
when I try use display a error

{"errors":[{"message":"Syntax Error: Unexpected <EOF>","category":"graphql","locations":[{"line":1,"column":1}]}]}

https://gist.github.com/devalexandre/a21483dc42736d7e125c57d3cfe9ae12

**Comment by simPod** [comment]
IMO if you put breakpoint to line :40/41 it can guide you to the place from where it is thrown and help you to find why is it so.

**Comment by devalexandre** [comment]
thanks, I find in guide
