### ISSUE TITLE
How to handle a partial error?

### ISSUE THREAD

**Issue by yaquawa** [webonyx/graphql-php#374]
Suppose we are querying a list of post:

```graphql
Query {
    posts: [Post]
}
```

```graphql
query {
    posts {
        id
        title
        body
    }
}
```

The requesting user does not have the read permission of some of the retrieved posts. 
Say if we got 10 posts, 2 of them are not allowed to be read by the requesting user (or maybe only the `title` field is can be read). 

How can I handle such a "partial error" case?

**Comment by simPod** [comment]
I guess it depends on you, AFAIK this is not part of GQL specification. 

I see two options:

1. You can return 8 ports in `"data"` and two errors in `"errors"` field of response
2. Just return auth error for the whole request (easier ofc)

**Comment by mfn** [comment]
Or:

3. You only return 8 posts

> does not have the read permission of some of the retrieved posts.

Counter-question: why are those then retrieved?

Just throwing in some perspective, suggested points 1) and 2) are perfectly valid and it really depends on your use-case.

In _my_ casts, as I'm working with a system which also has the concept of posts, the ones the user has no permission are never returned (and if you try to get a specific post you don't have permission it's treated as missing).

**Comment by yaquawa** [comment]
@simPod Thanks! But how can I 

> You can return 8 ports in "data" and two errors in "errors" field of response

as you said?

**Comment by yaquawa** [comment]
@mfn For example, you have a system that has many posts, most of the posts are free, but some of the posts are premium user only. But you still want the normal user to see the title and the thumbnail of the post, how do you handle this?

**Comment by simPod** [comment]
@yaquawa 8 ports in data is simple, just return them. 

For those errors, personally I would have 

1) created something like a ExposableExceptionsBuffer service
2) during query runtime added exceptions into that buffer if access to Post is unauthorized
3) formatted those exceptions from buffer when constructing response (`"errors"` field specifically)

Maybe someone will have better way tho.

> But you still want the normal user to see the title and the thumbnail of the premium post, how do you handle this?

That would be the first way I suppose

> You can return 8 ports in "data" and two errors in "errors" field of response

There are 3 options we came up with but it all depends on your domain logic. For example if I had private repository here named FooBar, I wouldn't want you to know. Therefore https://github.com/simpod/foobar returns 404. But in your case you wouldn't return 404 ofc.

**Comment by yaquawa** [comment]
@simPod Thanks!

For this

> formatted those exceptions from buffer when constructing response ("errors" field specifically)

is there a way to collect the errors it in the resolver and output the error automatically by just using the `webonyx/graphql-php`'s function?

**Comment by mfn** [comment]
> But you still want the normal user to see the title and the thumbnail of the premium post, how do you handle this?

How about an additional field/flag on the post, giving indication about this? Like `posts.has_permissions` or something.

Don't you need _some information_ in the frontend to mark the as "premium"?

I doubt a series of GraphQL errors is the right solution here; just IMHO.

**Comment by simPod** [comment]
That's true, you maybe return PremiumPost object instead of standard post. And maybe Union Type would be suitable for that 🤔 https://graphql.org/learn/schema/#union-types

**Comment by yaquawa** [comment]
@simPod What I want to do is just as you said:

> You can return 8 ports in "data" and two errors in "errors" field of response

I want to know if there is a way to gather the error info in `webonyx/graphql-php` while resolving.
Can you tell me how?

**Comment by yaquawa** [comment]
@mfn 

> How about an additional field/flag on the post, giving indication about this? Like posts.has_permissions or something.

sure I can, but the response still contain the `body` of the post even I have a `has_permissions` flag.

**Comment by simPod** [comment]
None that I know of, I'd go with that buffer service I mentioned earlier

**Comment by simPod** [comment]
> sure I can, but the response still contain the body of the post even I have a has_permissions flag.

This could be IMO solved with Union Type

**Comment by mfn** [comment]
> sure I can, but the response still contain the `body` of the post even I have a `has_permissions` flag.

I understand, but for this example, this is an error in your resolver logic, isn't it?

The body could be null for that. Fun fact: if you make the body non-null but return null due to permissions, you automagicallly have this information in the graphql errors.

**Comment by mfn** [comment]
But: I understand you have a desire to solve this differently => not arguing against it and I'm following this discussion with interest!

**Comment by vladar** [comment]
Either interface or union type is what you use for such things. Such cases are exactly the reason why abstract types exist. Modeling your API is not something the library can do for you. 

Alternatively split your model to something like this:
```graphql
type PostDetail {
  body: String!
  otherAuthSpecificField: String!
}
type Post {
  title: String!
  isPublic: boolean
  details: PostDetail
}
```

And then return null in your `details` for non-public posts.
Another alternative (which is more a hack) - mark all fields (except title) as nullable and just return nulls for them when there is no access.

There are plenty of ways to model it, but that is API modeling which is your responsibility as an API author.

**Comment by yaquawa** [comment]
@vladar Thanks for your reply!!

> It will still return nulls in the final result but will also add two entries in errors section of the result.

I didn't expect that will happen, good to know!
I guess this is the most ideal way to handle it in `webonyx/graphql-php`.
