### ISSUE TITLE
Syntax Error GraphQL (xxxxx) Unterminated string

### ISSUE THREAD

**Issue by wanxe** [webonyx/graphql-php#379]

**Comment by roelofjan-elsinga** [comment]
I have this problem as well. It happens when I submit a mutation containing a string with linebreaks "\n". Did you manage to fix this problem?

**Comment by wanxe** [comment]
Not yet :(
In fact I've closed the issue thinking that is just a problem on my front end side but if you have the same problem... May be is a library problem related.

**Comment by roelofjan-elsinga** [comment]
@wanxe I've done some research and stumbled upon this post: https://stackoverflow.com/a/50764657/2482417

So instead of passing the string to the GraphQL mutation, pass a variable instead.

```js
mutation($message: String) {
  createMessage(fullName: "FirstName LastName", message: $message)
}
```

Now with the variables you can pass the multi-line string:

```js
variables: {
  message: `
    This is a string on 
    multiple lines, and
    it works just fine
  `
}
```

It's kind of tedious, but it's a limitation GraphQL has and doesn't have anything to do with this specific library I think.

**Comment by vladar** [comment]
Both of the following forms should work, please try:

```graphql
mutation {
  sendEmail(message: "Hello,\n  World!\n\nYours,\n  GraphQL.")
}

mutation {
  sendEmail(message: """
    Hello,
      World!
     Yours,
      GraphQL.
  """)
}
```

**Comment by roelofjan-elsinga** [comment]
@vladar I've tried both of those and they didn't seem to work. Perhaps we're on different versions. Anyway, there are at least 3 different solutions in these comments, so hopefully it helps others.

**Comment by vladar** [comment]
The best thing you could do is to add a test case in [ParserTest](https://github.com/webonyx/graphql-php/blob/1417a4369744c562d1a6e1bae30e2de749bea6a6/tests/Language/ParserTest.php) to demonstrate the issue. Then it should be easy to fix.

I guess I can add one myself when I have a chance, but not sure when I'll have time for this.
