### ISSUE TITLE
Change Closures to callable classes

### ISSUE THREAD

**Issue by ArnoudThibaut** [webonyx/graphql-php#380]
Hello,

I'm planning to make the schema generated by Api-platform cacheable because it is currently generated for each graphql query.

To do this, it's necessary to remove all closures in the schema since they are not natively serializable  in php.

It's already possible to replace closures used in api-platform by invokeable classes and just cached the parts managed by api-platform but I think that it's better to be able to cache the whole schema.

So what do you think about replacing closures by invokeable classes in order to making the whole schema more easily cacheable ?

**Comment by vladar** [comment]
Why do you need the schema cacheable? Serializing and unserializing the whole schema will be not much more performant than creating one in the runtime. The most performance gains are possible from the type lazy-loading. Serialization won't give you much performance wins.

**Comment by vladar** [comment]
Also, take a look at [this thread](https://github.com/webonyx/graphql-php/issues/229#issuecomment-359704382) on performance optimizations
