### ISSUE TITLE
Unknown type

### ISSUE THREAD

**Issue by rudiedirkx** [webonyx/graphql-php#385]
Sometimes I get an `Unknown type` error. I have 0 explicit types included in the schema `types` so they're all lazy loaded.

```
query {
	user {
		reservations {
			... on CourtReservation {
				id
			}
			... on ClassReservation {
				id
			}
		}
	}
}
```

Error: `Unknown type "ClassReservation".`

`reservations` is a list of `ReservationInterface`, which has implementations `CourtReservation` and `ClassReservation`.

It seems the interface doesn't know that until `resolveType`. Did I set it up wrong? I'm using `InterfaceType` and `ObjectType` classes.

I could add `ClassReservation` to the schema `types`, but I don't like not knowing why that would be necessary. The entire schema is pretty big, so I like the lazy loading.

When I listen to the type registry, it loads several irrelevant types (fields and args of relevant types), but not `ClassReservation`...

**Comment by rudiedirkx** [comment]
I guess I understand why it happens. An interface doesn't know its implementations. And there's no name-to-type registry. But how do I fix it without preloading all types in the schema?

**Comment by rudiedirkx** [comment]
I suppose that's exactly what `types` is for...

> Most often it happens when the object type is never referenced in fields directly but is still a part of a schema because it implements an interface which resolves to this object type in its resolveType callable. 

So lazy loading is not what I expected. It's not lazy-only-when-needed. It's more lazy-in-the-right-order.

Sorry! Carry on.

**Comment by vladar** [comment]
You could define `types` as a closure (which is called when such situation happens). If it doesn't happen, then those types won't be loaded. But yeah, this is an edge case which is hard to combine with lazy-loading.
