### ISSUE TITLE
[Question] Why is ResolveInfo::$fieldNodes an array?

### ISSUE THREAD

**Issue by nagledb** [webonyx/graphql-php#387]
ResolveInfo::$fieldNodes has the following doc block:

```
/**
 * AST of all nodes referencing this field in the query.
 *
 * @api
 * @var FieldNode[]|null
 */
```

So far I've only ever seen it contain exactly one node (the node corresponding to the field being resolved). When would this be empty/null? When would this contain more than one element?

**Comment by simPod** [comment]
I have replaced all documented `array` types with the closest concrete types I have been able to find.

You can run `ExecutorTest::testProvidesInfoAboutCurrentExecutionState()`, `StarWarsQueryTest::testAllowsUsToQueryForTheFriendsOfFriendsOfR2D2()` or `ResolveInfoTest::testFieldSelection()` where it contains `FieldNode[]`

**Comment by nagledb** [comment]
The `FieldNode[]` type is correct.

In my testing (including the three test cases you referenced), it *always* contains exactly one `FieldNode`. It's never `null`, and it never contains more than one `FieldNode`. Thus why I'm asking if there are any such cases.

If there aren't, maybe it should eventually get changed to $fieldNode as `@var FieldNode`? (It'd be a breaking change to the public API so I know it can't be changed easily.)

**Comment by vladar** [comment]
Consider the following query:

```
query {
  ...F1
  ...F2
}

fragment F1 on T {
  field1
}

fragment F2 on T {
  field1
}
```

When field1 is resolved in the query which node should be in the `fieldNode`?

**Comment by nagledb** [comment]
Thanks for the example! I didn't even realize it was legal to have duplicate fields (but I do see it in the spec now that I know to look for it).
