### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by nagledb** [webonyx/graphql-php#390]
Please add a code of conduct. GitHub makes it easy:

https://github.com/webonyx/graphql-php/community/code-of-conduct/new?template=contributor-covenant

More info on codes of conduct for open source projects here: https://opensource.guide/code-of-conduct/

**Comment by nagledb** [comment]
I suggested it because I saw at https://github.com/webonyx/graphql-php/community that we didn't have one and it's recommended. I also noticed that digiaonline/graphql-php had one but webonyx/graphql-php didn't. If someone's choosing between the two projects, it's not inconceivable that it would be a factor they'd consider.

I haven't seen any signs that anyone here has problematic conduct. But having a code of conduct in place *before* a problem occurs will surely make handling such a situation easier if it does occur.

It also sends a pretty positive signal that the maintainers actually care about how people behave towards one another. That's not always a safe assumption.

**Comment by simPod** [comment]
Personally, I have no experience with code of conducts. But as far as I can tell, if someone doesn't behave even after he has been given a warning, he is always cast out in some way (closing, locking issue, ban, w.e) from a project. With or without that code of conduct file present in the repository.

> It also sends a pretty positive signal that the maintainers actually care about how people behave towards one another. That's not always a safe assumption.

To me that is implicit and covered by Github terms where needed. TBH I don't see any value in it (eg. issue and PR templates mentioned by that Community section are handy). I just simply think that it is a bit redundant as everything harmful is already covered by ToS. Just my 2c.

**Comment by nagledb** [comment]
GitHub's terms describes GitHub's expectations. The Code of Conduct describes the project maintainer's expectations.

Having a code of conduct says "this project is explicitly inclusive and welcoming". Deciding to *not* have one simply because it's a bit redundant would be a signal to me that the project doesn't actually emphasize or prioritize those values.

I think a Code of Conduct is valuable. Lots of other projects have them and seem to find them valuable. GitHub itself recommends having one, so evidently they see value in a project having one.

Maybe you don't see value in it and that's fair. But do you actually see harm in it?

**Comment by simPod** [comment]
Github solves this by requiring you to add a conduct file into your repository. The file is unrelated to the source code and shouldn't be there. Github should create separate view like wiki or something, not force you to actually polute the code base :/ And be honest, nobody will ever read it, like nobody reads ToS anywhere ;)

**Comment by vladar** [comment]
I do see a value of the code of conduct when a community grows significantly and formal rules become necessary. But I don't think we need it yet. Code of conduct and other unnecessary "rules" also create an impression of a formal and unfriendly environment. So I would really postpone it until necessary.
