### ISSUE TITLE
Create Deferred type classes

### ISSUE THREAD

**Issue by rudiedirkx** [webonyx/graphql-php#391]
I have wrapped my Deferreds in 2 functions:

```
'resolve' => GraphQLProxy::deferredMany(ReservationPlayer::class, 'reservation_id'), # $root to many: $building->floors
'resolve' => GraphQLProxy::deferredOne(Resource::class, 'resource_id'), # $root to one: $building->reception
```

It's the only 2 I've needed so far, but I can imagine many more kinds of Deferred loading.

It'd be very nice to create a Deferred class, and use it to store the queue and resolver. So instead of a Deferred object with a closure that returns a closure etc, it's just a single object that contains everything (for that specific field).

In my case, that would be

```
'resolve' => new CustomDeferredMany(ReservationPlayer::class, 'reservation_id'),
'resolve' => new CustomDeferredOne(Resource::class, 'resource_id'),
```

The default/provided would be the same as currently:

```
'resolve' => new CallbackDeferred(function() {
  // Return closures in closures
});
```

No need for static magic, or closures in closures. All the logic in a nice class. With some refactoring, it could be backward compatible by making `Deferred` a specific of the (new) `DeferredInterface`.

I don't understand PHP Promises, so I can't make a PR, but I still wanted to mention it. <s>There are very few Deferred usages, so it might be doable...</s> Or maybe I'm talking nonsense. Let me know.

(Deferred might have few usages, but calling a field's resolver might have many.)

**Comment by vladar** [comment]
But can't you already do the same using __invoke for such classes? A resolver is basically any callable, so you can wrap it as you want. Or am I missing something?

**Comment by rudiedirkx** [comment]
If `__invoke` is good enough for the graphql lib, that might be good enough for me. That depends on how callability is checked everywhere. You know that, I haven't checked.

I'm gonna try it. Be right back.

**Comment by rudiedirkx** [comment]
Yes. That works perfectly! Thanks.
