### ISSUE TITLE
WDYT about defining your schema in an objective way

### ISSUE THREAD

**Issue by simPod** [webonyx/graphql-php#393]
I have created this library https://github.com/simPod/GraphQL-Utils to power up creating schema definitions (and some other things like DateTime scalar etc.) 

I'm using it for a while on several projects and I'd love to know what do you think about it or even better, if you could try it. Current state is the best I alone could come up with, there are no more tweaks I can think of so when other people had a look, it would help.

I built it because I hate when there are huge/many arrays in PHP and defining schema just with arrays is very vulnerable to human errors (typos+need to remember docs) / cannot be statically tested.

If you find it handy, would be cool if it could be added to "suggested" dependencies. If not, just ignore.

Thanks for feedback! Sorry if OT

**Comment by vladar** [comment]
This is awesome! We actually have related issue https://github.com/webonyx/graphql-php/issues/70 but having such tools in the separate repo makes total sense to me. So I'll close it and recommend using your library instead.

Please post a PR with a link to your project in [complementary tools doc](https://github.com/webonyx/graphql-php/blob/master/docs/complementary-tools.md).
