### ISSUE TITLE
Can I customize the visibility of parts of the schema?

### ISSUE THREAD

**Issue by yaquawa** [webonyx/graphql-php#405]
Hi!
I want to know can I customize the visibility of parts of the schema with `graphql-php`? just like how the `graphql-ruby` deals with the [visibility of schema](http://graphql-ruby.org/authorization/visibility).

I have a project with 3 types of account (admin,client,user), currently, all of the schema mixed together, I want to separate the schema by the account type.

with this we can:

1. skip unnecessary parsing
2. skip unnecessary authorization logic
3. better security (especially, in terms of introspection)

currently, to achieve `2` and `3` I have to write the check logic manually, which can be a big pain when the project get bigger and bigger.

**Comment by vladar** [comment]
This is a nice feature, but it is not supported in this library. There is a related issue in the reference implementation: https://github.com/graphql/graphql-js/issues/113

I think we'll wait until it is resolved there. Feel free to re-open when it happens.

**Comment by sebastienbarre** [comment]
@yaquawa I'd love to know how you implemented this feature, I need to skip fields as well based on the user.
