### ISSUE TITLE
GraphQL invalidation for reactive GraphQL

### ISSUE THREAD

**Issue by smolinari** [webonyx/graphql-php#41]
Hi,

I'd like to make mention of a project I am following and while looking through their docs, they mention an "invalidation server". 

https://github.com/apollostack/apollo/blob/master/design/high-level-reactivity.md

@vladar - can you imagine this also being possible within graphql-php or is it a separate project? I'd imagine separate. What are your thoughts on the possibility of a "reactive graphQL" PHP application server?

Scott

**Comment by vladar** [comment]
Thanks for brining this up. 

But that is really something that could be built on top of graphql library. The goal of this library (as well as reference implementation) is to provide rather simple but powerful tools that others can utilize to build application servers like the one from the article.

The problem with PHP though is that it is not the best tool for reactive applications (at least pure PHP at it's current state). See #9 for more discussion on this topic.

**Comment by smolinari** [comment]
Thanks. That is what I thought. And, for one, I certainly appreciate your work with this library. 

It's going to be fun, however, to pick it apart to make work properly in a threaded PHP environment (which is needed for reactive PHP apps). :wink: 

Scott
