### ISSUE TITLE
Add "real path" for ResolveInfo object

### ISSUE THREAD

**Issue by SerafimArts** [webonyx/graphql-php#412]
Did not find the possibility of obtaining a real query path =\

## Query Example

```graphql
{
    root: object {
        inner: listOfSomething {
            ...on Example { value }
        }
    }
}
```

## Actual

Actual `->path` for "value" field ResolveInfo

```php
\var_dump($info->path);

// ['root', 'inner', 0, 'value']
```

## Expected

```php
\var_dump($info->realPath);

// ['object', 'listOfSomething', 'value']
```

**Comment by vladar** [comment]
This is actually an expected behavior. The path shows which **data** entry produced an error. It doesn't route back to the field of the query (location does that), it allows you to find an entry in your result which caused an error. So aliases and array indexes are both valid elements of the path.

**Comment by SerafimArts** [comment]
@vladar I need this information for correct memory management. For example - information about the reflection of the field, about the type that is contained there, or, for examplу. But Webonyx does not provide the ability to get information about the path to the field.

And I cannot specify the route (ie, the resolver) that was hung this way:
```php
// it's physically impossible to route this route.
$router->wherePath('a.b.c')->then(function (...) { return 42; });
```

**Comment by vladar** [comment]
I guess it is a feature request then, not a bug report - please create another ticket for it as this one is a bit misleading.

Actually I am quite curious on what are you trying to route at all? Resolvers require just type and field names. There might be endless variations of paths in graph (especially if they are cyclical). So routing resolvers by the query field path might be not the best idea.

But even if you try it - I afraid that field path is not enough for your use case. Because there are abstract types. Consider the following schema:

```graphql
type A {
  a: B
}

type B {
  b: C
}

interface C {
  c: String
}

type C1 implements C {
  c: String
}

type C2 implements C {
  c: String
}
```

As you see `a.b.c` qualifies for both - `C1.c` and `C2.c`.

**Comment by SerafimArts** [comment]
> I guess it is a feature request then

Yep

**Comment by SerafimArts** [comment]
> Actually I am quite curious on what are you trying to route at all? 

It is assumed that this is an extended functionality of the ready-made routing (would you like some possibilities) =)

Examples with interfaces and unions are already solved for my part on the basis of the argument "on": https://github.com/railt/railt/blob/master/resources/routing.graphqls#L17-L54

...for the rest, it’s a very long time to describe the benefits that can be obtained by having information on the **real path**, but in particular, I can then implement sharing of data into hereditary resolvers. Like this: 
![image](https://user-images.githubusercontent.com/2461257/49333225-fa38e900-f5cb-11e8-947e-42a76e4d502f.png)

Now the data can be shared not in all the resolver of descendants, but only in the immediate (ie, including aliases)
