### ISSUE TITLE
PHP7.3 Warning

### ISSUE THREAD

**Issue by Teeoo** [webonyx/graphql-php#419]
> Maybe this is a mistake

> error code:

`
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
`

> php version:

`
PHP 7.3.0 (cli) (built: Dec  7 2018 11:01:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
`

> code /src/Executor/Executor.php on line 544

```php
case NodeKind::INLINE_FRAGMENT:
                    if (!$this->shouldIncludeNode($selection) ||
                        !$this->doesFragmentConditionMatch($selection, $runtimeType)
                    ) {
                       continue;
                    }
                    $this->collectFields(
                        $runtimeType,
                        $selection->selectionSet,
                        $fields,
                        $visitedFragmentNames
                    );
                    break;
```

**Comment by mfn** [comment]
There's no such code in the latest release, which version of webonxy/graphql-php are you using?

**Comment by Teeoo** [comment]
> There's no such code in the latest release (…anymore), which version of webonxy/graphql-php are you using?

~0.10.2

**Comment by mfn** [comment]
It is, see https://github.com/webonyx/graphql-php/releases => 0.13 is the latest.

If you're by chance using a Library on _top_ of webonxy, you've to contact the library developers to upgrade.

https://github.com/Folkloreatelier/laravel-graphql comes to my mind. It's orphaned but has many users and is stuck on 0.10.2 (coincidence?)

**Comment by Teeoo** [comment]
> It is, see https://github.com/webonyx/graphql-php/releases => 0.13 is the latest.
> 
> If you're by chance using a Library on _top_ of webonxy, you've to contact the library developers to upgrade.
> 
> https://github.com/Folkloreatelier/laravel-graphql comes to my mind. It's orphaned but has many users and is stuck on 0.10.2 (coincidence?)


Yes, now it is https://github.com/Folkloreatelier/laravel-graphql, I will contact the author to upgrade later.
