### ISSUE TITLE
Consider implementing Parle-based lexer

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#428]
PHP has [Parle](https://pecl.php.net/package/parle) extension in Pecl, which is designed for high-performance lexing/parsing. My initial research shows that Lexer written for Parle can be 15-300% more performant than our current one and has more stable memory footprint.

**Comment by unkind** [comment]
It implies that `GraphQL\Language\Lexer` should choose strategy internally or you consider BC break with `Lexer` interface and multiple implementations?

**Comment by vladar** [comment]
@unkind Somehow missed your question. I think this would be an automatic swap of lexers in presence of Parle extension (because it would be just faster). Or maybe via setting a global config/environment variable. So this wouldn't mean a breaking change.

But this is a "nice to have" kind of feature and at the moment I tend to implement only necessary stuff. So closing this one until we actually need it.
