### ISSUE TITLE
Faulty result due to memoized results

### ISSUE THREAD

**Issue by timbrandin** [webonyx/graphql-php#43]
I have a BIG problem with memoized results, in this example with memoizing on I get faulty result on the leaf node:

Query:
```gql
{
  surveys(school_category:SCHOOL) {
    nid
    modules {
      survey
    }
  }
}
```

Faulty result, `survey` in each module should match the `nid` from the survey.

```json
{
  "data": {
    "surveys": [
      {
        "nid": 85,
        "modules": [
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          }
        ]
      },
      {
        "nid": 707,
        "modules": [
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          }
        ]
      }
    ]
  }
}
```

And if I turn off memoization ([Executor.php#L366-L372](https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php#L366-L372)) I get the correct result:
```json
{
  "data": {
    "surveys": [
      {
        "nid": 85,
        "modules": [
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          },
          {
            "survey": 85
          }
        ]
      },
      {
        "nid": 707,
        "modules": [
          {
            "survey": 707
          },
          {
            "survey": 707
          },
          {
            "survey": 707
          },
          {
            "survey": 707
          },
          {
            "survey": 707
          },
          {
            "survey": 707
          },
          {
            "survey": 707
          }
        ]
      }
    ]
  }
}
```

I'm not sure it's safe to memoize using the AST location and fieldname, my recommendation is to remove this performance optimization now until someone figures out how to look at the parent if that is different than previously memoized, but also that doesn't take into account if say any contextual parameter has changed. Say the user is added in some level of the graph and passed down, although atm it doesn't seem to be possible to reference the context in the resolvers to be able to add stuff (this works in the JavaScript implementation, context is passed as the third parameter). But that seems like another issue.

**Comment by mcg-web** [comment]
What's your Type System Definition please? I'm going to try to write a test to 
reproduce this bug and fix it...

**Comment by vladar** [comment]
We should consider how to approach this fix properly. I did have a bad feeling about this optimization when implemeted it on request, but couldn't come up with example that would break it.

Now when we have such example we can think of better ways to implement such improvements. I am personally a fan of React's approach when you build your component and then can improve it's performance by using hooks to provide hints for rendering process.

I guess we could come up with some optional per-field (or per-type) hooks. The question is how to make such hooks easy to use and clear for end-users.

But for now I guess we'll have to just disable memoization for lists.

**Comment by mcg-web** [comment]
:+1: for disabling this, I think the good solution is to leave optimizations / caching to developers, most already have a caching system in their apps, that can be easily reused...

**Comment by vladar** [comment]
Cool, will you work on this? I've got some unexpected personal stuff to figure out which distracted me from the project for a while, but hopefully will be back on track soon.

As for this issue, I guess the test case is the most important part of this to catch possible regressions in future perofmance optimizations.

Also just FYI - I plan to add a suite of benchmarks using https://github.com/phpbench/phpbench Then we will have some grounds to work on future performance optimizations.

**Comment by mcg-web** [comment]
I can take this fix, not really a huge modification :+1:

**Comment by johanobergman** [comment]
Yeah I originally requested this but as mentioned, it's not really the responsibility of this library. `resolve` not being called when the developer expects it to be is not worth it.
