### ISSUE TITLE
Custom field Resolver when using Type Language.

### ISSUE THREAD

**Issue by hemratna** [webonyx/graphql-php#441]
I am planning to integrate GraphQL in the [DirectUs](https://directus.io) which is a Headless CMS.
 
DirectUs allows users to manage their Database table from [DirectUs App](https://github.com/directus/app).
As the table schema can be modified on the fly (from the DirectUs App), I am using the [Type language to define the GraphQL schema](http://webonyx.github.io/graphql-php/type-system/type-language/). We autogenerate the schema when any DB changes happen. 

We already have [REST API](https://github.com/directus/api). So I am planning to warp the REST API with GraphQL.

For that, I need Custom field Resolver for each field in the type definition.

Kindly guide me, How to use the Custom field Resolver for each field, query, and mutation or how to extend the default field resolver while using Type Language.

Thanks.

**Comment by simPod** [comment]
Not sure it that's what you're looking for. You can set custom default resolver using `fieldResolver` config option, see http://webonyx.github.io/graphql-php/executing-queries/

And also custom resolver per field http://webonyx.github.io/graphql-php/type-system/object-types/#field-resolution

**Comment by hemratna** [comment]
Hi @simPod 
Thanks a lot for quick reply.

For the http://webonyx.github.io/graphql-php/executing-queries/ can you guide me on how to define the `$fieldResolver` in the below-suggested code?
```
use GraphQL\GraphQL;

$result = GraphQL::executeQuery(
 	$schema, 
    $queryString, 
    $rootValue = null, 
    $context = null, 
    $variableValues = null, 
    $operationName = null,
    $fieldResolver = null, //Custom field Resolver when using **Type Language** to define the schema 
    $validationRules = null
);
```

For the http://webonyx.github.io/graphql-php/type-system/object-types/#field-resolution, I am creating the GraphQL schema dynamically. I don't have the individual PHP class for each type in the schema where I can write the logic for data fetching as mentation on http://webonyx.github.io/graphql-php/data-fetching/.

**Comment by simPod** [comment]
@hemratna see this http://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver

Just copy paste it into ur class and then you can start tweaking it for your needs.

```php
class MyCustomResolver {

public function __invokable($source, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info)
{
    $fieldName = $info->fieldName;
    $property = null;

    if (is_array($source) || $source instanceof \ArrayAccess) {
        if (isset($source[$fieldName])) {
            $property = $source[$fieldName];
        }
    } else if (is_object($source)) {
        if (isset($source->{$fieldName})) {
            $property = $source->{$fieldName};
        }
    }

    return $property instanceof Closure ? $property($source, $args, $context, $info) : $property;
}
}
```
then
```php
$result = GraphQL::executeQuery(
 	$schema, 
    $queryString, 
    $rootValue = null, 
    $context = null, 
    $variableValues = null, 
    $operationName = null,
    $fieldResolver = new MyCustomResolver(), // Rather inject it through DI, though
    $validationRules = null
);
```

Quickly typed it here on github but should work. You get the idea.

**Comment by hemratna** [comment]
Is there any way not to use DI?
How can I pass the arguments to the 
`public function __invokable($source, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info)` from `$fieldResolver = new MyCustomResolver()`

Thanks a lot for such a quick response. 👍

**Comment by simPod** [comment]
@hemratna my example was without DI :)

Just pass anything that's invokable for `$fieldResolver`. It gets invoked by executor so those args are passed there by executor as well.

**Comment by simPod** [comment]
```php
$result = GraphQL::executeQuery(
    $schema, 
    $queryString, 
    $rootValue = null, 
    $context = null, 
    $variableValues = null, 
    $operationName = null,
    ANYTHING INVOKABLE HERE, preferable with following arguments: $source, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info
    $validationRules = null
);```

**Comment by hemratna** [comment]
Oh my bad.

I have to change the `__invokable` to `__invoke` on your refrence code.

**Comment by simPod** [comment]
Yes my bad, sorry. Will edit it.
