### ISSUE TITLE
Persisted queries

### ISSUE THREAD

**Issue by Daniel15** [webonyx/graphql-php#443]
Relay supports a concept called "persisted queries" whereby the GraphQL queries are persisted on the server side, and the client only needs to send an identifier (eg. a hash) to execute it. This avoids having to re-upload and re-parse the query every time it's executed, and the server can store the query in some intermediate form (such as a serialized AST) to improve performance.

Does graphql-php support this, or do you have any plans to add it?

Reference: https://facebook.github.io/relay/docs/en/persisted-queries.html

**Comment by Daniel15** [comment]
Actually, I guess this wouldn't need too much server support... You'd just need to use a script to scrape all the GraphQL queries from the client-side code, persist them somewhere, and have the server endpoint load the persisted queries. Would be good to have docs for how to do this, though!

**Comment by vladar** [comment]
This feature is available through [the server](https://webonyx.github.io/graphql-php/executing-queries/#server-configuration-options). Read about `persistentQueryLoader` option there.

**Comment by Daniel15** [comment]
Does this also support "automatic persisted queries" (see https://blog.apollographql.com/automatic-persisted-queries-and-cdn-caching-with-apollo-server-2-0-bf42b3a313de) or should I open a separate feature request for that?

**Comment by vladar** [comment]
This is out of the scope of this library. We aim to provide core features from the spec and graphql-js. 

You can implement persisting as a separate project. Look at what apollo-server does for the reference. If you do implement such a server, please let us know and we'll add it in the [complementary tools](https://webonyx.github.io/graphql-php/complementary-tools/) section in docs.
