### ISSUE TITLE
Can Generate Document for scheme?

### ISSUE THREAD

**Issue by Chrisdowson** [webonyx/graphql-php#446]
Can this library generate static documentation for GraphQL API schema?And How?

**Comment by vladar** [comment]
There is a `SchemaPrinter` utility. Check it out [in docs](https://webonyx.github.io/graphql-php/reference/#graphqlutilsschemaprinter). It will print SDL-representation of the existing schema.

If you need other types of documentation - there are separate tools. Check them out in the [awesome-graphql repo](https://github.com/chentsulin/awesome-graphql#tools)
