### ISSUE TITLE
Packagist integration broken

### ISSUE THREAD

**Issue by simPod** [webonyx/graphql-php#447]
Is packagist integration setup well / migrated from the Legacy auto-update? It shows dev-master as a commit from January https://packagist.org/packages/webonyx/graphql-php#dev-master

Packagist possibly shows this message on package detail for @vladar 
> This package is using the legacy GitHub service and will stop being auto-updated in early 2019. Please set up the new GitHub Hook for Packagist so that it keeps working in the future.

**Comment by vladar** [comment]
Yeah, switched to the new packagist syncing method (using webhooks). Thanks!
