### ISSUE TITLE
How to implement object type with custom serialization

### ISSUE THREAD

**Issue by mariusklocke** [webonyx/graphql-php#448]
Hey everyone,

not sure if a got the title right, but I think my example is quite simple.
I implemented a custom scalar type for handling [dates](https://github.com/mariusklocke/liga-manager-api/blob/master/src/Infrastructure/API/GraphQL/DateType.php). That works fine. My resolvers get a proper `DateTime` object for that.

Now I want to add a custom type for [date periods](https://github.com/mariusklocke/liga-manager-api/blob/master/src/Infrastructure/API/GraphQL/DatePeriodType.php). If I implement that by extending `ObjectType` and having "from" and "to" fields of my custom date type, my resolvers get an associative array. I think i somehow need to implement `parseValue()` like in `DateType` above, but that method is only for instances of `LeafType`.
My goal is that the resolver gets an instance of my custom value object for date periods and NOT an associative array.

Can somebody explain how to implement that? I couldn't find an example for that in the docs.

**Comment by simPod** [comment]
I'd recommend using this https://github.com/simPod/GraphQL-Utils/blob/master/src/Type/DateTimeType.php

**Comment by simPod** [comment]
But just looking at it I don't see what might be wrong on your end. Cannot find difference between that basic DateTime type inplementation of yours and mine.

**Comment by mariusklocke** [comment]
@simPod Thanks for sharing your implementation of a DateTimeType, but that does not cover compound types required for date periods.

**Comment by simPod** [comment]
Can you show your DatePeriod extending ObjectType? And what is your query, what are your arguments and how resolvers looks like?

IMO having `type DatePeriod` with `from` `to` fields of `scalar DateTime` must work or at least does for me.

**Comment by mariusklocke** [comment]
@simPod That was my last try:

```
class DatePeriodType extends InputObjectType
{
    use SingletonTrait;

    public function __construct()
    {
        $config = [
            'fields' => function () {
                return [
                    'from' => [
                        'type' => DateType::getInstance()
                    ],
                    'to' => [
                        'type' => DateType::getInstance()
                    ]
                ];
            }
        ];
        parent::__construct($config);
    }
}
```

Using that type for query arguments results in getting the value for that as associative array in my resolvers. I'd like to have an object instance if my custom class for DatePeriod instead, but i don't know where to put my serialization/parsing logic.

You can find all my project's code here: https://github.com/mariusklocke/liga-manager-api

**Comment by simPod** [comment]
You should get something similar in your resolver:

![image](https://user-images.githubusercontent.com/327717/53376793-daf9ef80-395f-11e9-9ec9-e02dca7516db.png)

But I suppose you'd rather get object than array, am I right? AFAIK that's not possible and you should do it in your resolver. It seems to be handled here https://github.com/webonyx/graphql-php/blob/master/src/Utils/AST.php#L398

**Comment by mariusklocke** [comment]
That's a pity :(

But thanks for the quick support! Will then implement my own parsing/deserialization methods and invoke it in resolvers.

I'll close this issue for now. If anyone knows a better solution, feel free to re-open ;)
