### ISSUE TITLE
yii\base\ErrorException: "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by rodrigosaraiva** [webonyx/graphql-php#450]
We are using Craft CMS with CraftQL and it is using the graphql-php package.

These errors are showing to us, when we make a call to the API, and the only way that we got this running is replacing the continue at switch for break statement.

How we can fix this at the package?

[-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/vendor/webonyx/graphql-php/src/Validator/Rules/OverlappingFieldsCanBeMerged.php:355

[-][-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/vendor/webonyx/graphql-php/src/Executor/Executor.php:532

**Comment by vladar** [comment]
> How we can fix this at the package?

Upgrading to the latest version?

**Comment by vladar** [comment]
If you are having trouble updating you could also fix it yourself by sending a PR in the 0.12.x branch and I would release a new patch version for 0.12.x
