### ISSUE TITLE
Schema file import

### ISSUE THREAD

**Issue by abdullahseba** [webonyx/graphql-php#451]
Is there a way to allow schema files to import each other?
I've looked at the [docs](https://webonyx.github.io/graphql-php/type-system/type-language/) and searched previous issues but found nothing on this. I have a lot of types and would like them to be modular in mutlple files. 
See [here](https://www.apollographql.com/docs/react/advanced/fragments.html#webpack-importing-fragments) for an example of this.

I have a structure that looks somewhat like this:

|── schema.gql
|── user.gql
|── role.gql

Then under `schema.gql` I want something like this:
```gql
# import './user.gql'
# import './role.gql'

schema {
    query: Query
}

type Query {
  User(id: ID!, userName: String): User
  Role(id: ID!): Role
}

```

Does this make sense?
Or should I combine all the files as a string in PHP before runing `BuildSchema::Build`?

**Comment by vladar** [comment]
This library implements GraphQL spec which doesn't have support for module imports at the moment. Apollo example is based on comments. Technically you could do it yourself by analyzing resulting schema AST and merging ASTs of "imported" files.

But the simplest way is just to concatenate graphql files manually into a single string before parsing.

As soon as [GrahpQL spec](https://facebook.github.io/graphql/draft/) introduces imports we will implement them.
