### ISSUE TITLE
How to use a custom resolver?

### ISSUE THREAD

**Issue by abdullahseba** [webonyx/graphql-php#452]
What am I supposed to return in a custom resolver for a custom type?

I have the following resolver class:
```php

class MyCustomResolver
{
    public function __invoke($source, $args, $context, ResolveInfo $info)
    {
        switch ($info->fieldName) {
            // case 'id':
                // return 2;
            case 'user':
                return ['id'=>1];
            default:
                return 666;
        }
    }
}
```
My type looks like this:
```gql
type User {
  id: ID!
  email: String
  firstName: String
  lastName: String
}
```
The first problem is that by default GraphiQL returns this error:

```qgl
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 12,
          "column": 9
        }
      ],
      "path": [
        "__schema",
        "directives",
        0,
        "locations"
      ]
    }
  ]
}
```
which doesnt help much.

but if I hit the run button again, then I get:

```gql
{
  "data": {
    "user": {
      "id": "666"
    }
  }
}
```
or if I uncomment `case 'id'`:
```gql
{
  "data": {
    "user": {
      "id": "2"
    }
  }
}
```
But I never see what `case 'user'` returns and I have made sure that it get run. 
Yet if I use a resolver in the query, it works fine with no errors:

```php

class Query extends ObjectType
{
    public function __construct()
    {
        parent::__construct(
            [
                'name' => 'Query',
                    'fields' => [
                        'user' => [
                            'type' => Types::user(),
                            'description' => 'Returns user by id (in range of 1-5)',
                            'args' => [
                                'id' => Type::nonNull(Type::id())
                            ],
                            'resolve' => function ($source, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info) {
                      
                                 return ['id'=>2,'firstName'=>'test'];
                            // }
                            ]
                            ],
            ]
        );
    }
}
```
Problem with this is that I want to use the type langauge so I have to use a custom resolver.

**Comment by vladar** [comment]
> I have the following resolver class:

You didn't explain where did you use it so I have to guess a bit.

I assume you had assigned it to the `resolveField` of the `User` type. `User` type has no field `user` hence your `case 'user'` is never reached. Field `user` exists only in the `Query` type. You shouldn't use the same resolver for the fields of different types.

> The first problem is that by default GraphiQL returns this error:

Use [debugging tools](https://webonyx.github.io/graphql-php/error-handling/#debugging-tools) during development.

> Problem with this is that I want to use the type langauge so I have to use a custom resolver.

Some hints on how to use custom resolvers with type language [in docs](https://webonyx.github.io/graphql-php/type-system/type-language/#defining-resolvers)

i.e.

```php
$typeConfigDecorator = function($typeConfig, $typeDefinitionNode) {
    $name = $typeConfig['name'];
    // ... add missing options to $typeConfig based on type $name
    if ($name === 'Query') {
        $typeConfig['resolveField'] = new MyCustomResolver();
    }
    return $typeConfig;
};

$contents = file_get_contents('schema.graphql');
$schema = BuildSchema::build($contents, $typeConfigDecorator);
```

**Comment by abdullahseba** [comment]
Of course! I forgot to mention that... the resolver is on `executeQuery` so:
```php
     $result = GraphQL::executeQuery(
                $schema,
                $query,
                $rootValue = null,
                $context = null,
                $variableValues = null,
                $operationName = null,
                new MyCustomResolver()        
            );
```
 Sorry for the late reply.

**Comment by vladar** [comment]
Default resolver is called for all fields which do not have their own resolvers. **It is not recommended** to use it the way you are trying to use it.

I already posted you a preferred method of defining resolvers with schema defined via type language (see example in my previous comment).

With your current setup you'll have to check for both - type name (via `$info->parentType->name`) and field name (`$info->fieldName`) for custom resolve logic. And, the most important part - you must still resolve all other fields of all other types (see [here](https://webonyx.github.io/graphql-php/data-fetching/#default-field-resolver) on how standard default resolver does it).

**Comment by abdullahseba** [comment]
I see. I'm not actually using the type language. I just used it to represent my user type more simply.
Right now my resolvers are under the `Query` type:

```php
     'name' => 'Query',
        'fields' => [
            'user' => [
            'type' => Types::user(),
            'args' => [
            'id' => Type::nonNull(Type::id())
            ],
            'resolve' => function ($source, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info) {
                 ...
                 return ['id'=>$user[0]->id,'firstName'=>$user[0]->first_name];
            }
```
I wanted to register a type's resolver under its self rather than under the `Query` type. But as far as I can see, only `resolveField` is supported directly under a type. So I though the next best thing would be to have a cutom resolver class that registred each type resolver. I could still do that under the `Query` type, but that I dont think its as clean.

**Comment by vladar** [comment]
GraphQL is about returning only what is requested. That's why resolvers are always defined **on a field level**, not a type level.

You may have 100 fields on a type, but if only 2 of them are requested in a query you don't want to fetch data for all 100 of those fields.

**Comment by abdullahseba** [comment]
Makes sense, but I would have thought there would be a way to do it. I have one more question if you don't mind before closing this issue. Our PHP backend already has validation for emails, usernames, numbers etc. I don't know if I should use custom scalar types for these fields and retire our validation system, or use strings and do validation at the resolver level. Right now GraphQL has 2 types of verification as I see it. Required and Type. But with something like a username were it should all be lower case and no more than say 30 characters, I'm finding it difficult to decide if everything should be a custom scalar type or a required string with all the validation on the resolver level. I've seen custom scalar types for emails, URLs phone numbers etc. But these are not native types to programming languages like string, int etc are, and I'm finding it a very fine line between scalar types and resolver level validation.

**Comment by vladar** [comment]
> But these are not native types to programming languages like string, int etc are, and I'm finding it a very fine line between scalar types and resolver level validation.

This is an area where best practices are still being established. My personal preference is to use custom scalar types for things covered by specs and generally known only (like URLs, emails, etc). And don't use them for app-specific types.

Put your validation in separate utils/layer and call them in your resolvers. Sometimes it even makes sense to extract field definitions for common fields to separate utils instead of having a custom scalar type.

Just my 2 cents.
