### ISSUE TITLE
Get the max depth of input query before execution.

### ISSUE THREAD

**Issue by hemratna** [webonyx/graphql-php#453]
Hi Team,
Is there any way to get the max depth of input query before execution?

As per the documentation, We can validate the max depth via 
`$rule = new QueryDepth($maxDepth = 2);`
`DocumentValidator::addRule($rule);`

But can we have the max depth info of input query in the resolver function? This info help us to write efficient resolver.

Thanks a lot for such an amazing library.

**Comment by mfn** [comment]
@hemratna does this answer help? https://github.com/webonyx/graphql-php/issues/316#issuecomment-408760772

**Comment by vladar** [comment]
We actually have #436 which is a good fit for such use-case. Once it is merged we should consider adding a corresponding method to it.

Right now the workaround is to create your own validation rule similar to QueryDepth and manually set max depth to your $context (3rd argument in resolves) after validation but before execution.
