### ISSUE TITLE
PHP "Cannot use object of type stdClass as array"

### ISSUE THREAD

**Issue by djrumbold** [webonyx/graphql-php#456]
Using version 0.13.1 and PHP 7.1.25

I'm seeing this PHP error on line 165 of src/Utils/Value.php

It occurs whenever I try to use a non-scalar type for a mutation argument.

For example:

mutation Something($foo: Foo) {
    Something(Foo: $foo) {
        id
    }
}

with these variables:

{
  "foo": {
    "bar": "hello"
   }
}

And I've declared a FooType class that extends GraphQL\Type\Definition\InputObjectType and I've declared a suitable mutation resolver that I know works with other input types (e.g. Type::int or Type::string) other than an instance of FooType.

It looks like the coerceValue function is successfully determining that $type is an instance of InputObjectType but then when looping through the fields via `foreach ($fields as $fieldName => $field)` trips up on this part (lines 164 and 165):

                if (array_key_exists($fieldName, $value)) {
                    $fieldValue   = $value[$fieldName];

At this stage, $value is a stdClass object and so the error is correct - PHP can't use a stdClass object as an array. The fieldName does exist (e.g. "bar") and can be access by $value->$fieldName, or by first doing something like $value = get_object_vars($value), but I feel that at this point we've (my development team and myself) might have missed something.

**Comment by vladar** [comment]
How do you JSON-decode those variables? This library expects variables to be decoded as an associative array:

```php
$variables = json_decode($variablesJSON, true);
```

We should probably communicate this somehow either via docs or via a descriptive error message (or both).

**Comment by djrumbold** [comment]
Thanks for the tip @vladar , that's solved it for us!

We were JSON-decoding without the second parameter -
`$variables = json_decode($variablesJSON);`
and ending up with a structure comprised of stdClass objects rather than arrays, which has worked up until this point but obviously doesn't work for input object types parsing.
