### ISSUE TITLE
Is there more document for Validation Rules

### ISSUE THREAD

**Issue by Chrisdowson** [webonyx/graphql-php#460]
I think there is not enough documentation about the Validation rules。I need Custom Validation Rules,Where can I get more details?

**Comment by vladar** [comment]
At the moment there is no documentation for writing custom validation rules. But you could use [existing validation rules](https://github.com/webonyx/graphql-php/tree/master/src/Validator/Rules) in the source code as a reference.

In short, the validation rule is a class [implementing ValidationRule interface](https://github.com/webonyx/graphql-php/blob/master/src/Validator/Rules/ValidationRule.php). Its main method is `getVisitor` which is expected to return a structure suitable for [AST Visitor](https://webonyx.github.io/graphql-php/reference/#graphqllanguagevisitor).

Then inside visiting functions you should add any errors encountered to validation context using [reportError method](https://github.com/webonyx/graphql-php/blob/master/src/Validator/ValidationContext.php#L73).

And don't forget adding your custom rule during execution as [described in docs](https://webonyx.github.io/graphql-php/executing-queries/#custom-validation-rules).
