### ISSUE TITLE
Config Decoration of Types from Extended Schema

### ISSUE THREAD

**Issue by inanc-g** [webonyx/graphql-php#461]
@Torsten85 introduced `SchemaExtender` with #362 and #186, allowing to extend an existing schema with additional SDL.

But how do you decorate the config of new types added by an extension?
`BuildSchema::build` accepts a `$typeConfigDecorator`, but `SchemaExtender::extend` does not.

Decorating new types in the original Schema does not work, since they do not exist yet when building the unextended schema.

Example:
```php
$sdl = '
  type Query {
    defaultValue: String
  }
  type Foo {
    value: Int
  }
';

$typeConfigDecorator = function ($typeConfig) {
  switch ($typeConfig['name']) {
    case 'Foo': // works as expected
        $typeConfig['resolveField'] => function () { /* whatever */ };
        break;
    case 'Bar': // Never the case as this type does not exist 
                // in the original unextended Schema
        $typeConfig['resolveField'] => function () { /* whatever */ };
        break;
  }

  return $typeConfig;
};

$documentNode = \GraphQL\Language\Parser::parse($sdl);
$schema = \GraphQL\Utils\BuildSchema::build($documentNode, $typeConfigDecorator);

// how to decorate the config of type `Bar`?
$extensionSdl = '
  type Bar {
    foo: Foo
  }
';

$extendedDocumentNode = \GraphQL\Language\Parser::parse($extensionSdl);
$extendedSchema = \GraphQL\Utils\SchemaExtender::extend($schema, $extendedDocumentNode);
```

The way I see it it's not possible to pass a configDecorator for newly introduced types to the `SchemaExtender` or am I missing something?

**Comment by vladar** [comment]
Yeah, `$typeConfigDecorator` is not available in the JS version. It was our own addition which didn't find it's way into the extendSchema util yet. PR for adding it is welcome!

@Torsten85 maybe you can look into it?

**Comment by spawnia** [comment]
Released as of https://github.com/webonyx/graphql-php/releases/tag/v14.9.0
