### ISSUE TITLE
Link in documentation is broken

### ISSUE THREAD

**Issue by kamilkuz** [webonyx/graphql-php#462]
In page: https://webonyx.github.io/graphql-php/complementary-tools/
first link: Standard Server is broken - it leads to page with 404 error.
Can someone paste proper link here ?

**Comment by vladar** [comment]
Thanks for noticing. The valid link is https://webonyx.github.io/graphql-php/executing-queries/#using-server. Not sure why site-gen didn't recognize it.

Anyways, there is a search in docs too.
