### ISSUE TITLE
Donations to fund development

### ISSUE THREAD

**Issue by jasonbahl** [webonyx/graphql-php#463]
Hello,

I've been using this library for the past 2 years in WPGraphQL, and it's been wonderful. 

Do you have any way to accept donations to continue funding future development?

I'm in the process of releasing a licensed extension for WPGraphQL that will allow me to bring in some income to support my efforts on WPGraphQL and other potential future extensions. 

I would like to contribute a percentage of my earnings back to this project. Looking forward to hearing more about how to coordinate this. 

Thanks,

Jason

**Comment by vladar** [comment]
Hey, thanks for considering donations! I started the [open collective](https://opencollective.com/webonyx-graphql-php) to streamline the process. Let me know if you have any suggestions.

**Comment by jasonbahl** [comment]
Sweet! I’ll use this to start. Once I have an idea how much my extension will bring in I’ll have a better idea on how much I can contribute here. Thanks!!

**Comment by vladar** [comment]
Thanks for the donation! For some reason, OpenCollective doesn't show it in the list of backers in README, but I'll figure it out.

**Comment by jasonbahl** [comment]
All good. Not super concerned about showing up. More concerned with contributing to help sustain graphql php 😀

**Comment by simPod** [comment]
https://help.github.com/en/articles/sponsoring-a-developer
