### ISSUE TITLE
Looking for some concrete information on improving performance

### ISSUE THREAD

**Issue by SonarSoftware** [webonyx/graphql-php#468]
There's a few things scattered around the docs, and I've read through all the issues here. I'm trying to figure out what else I can do to improve the performance of my API.

Currently, I am building a (very large) schema using the `Schema` object. I'm using a type registry that I built.

I have dynamic resolvers in all my types to handle relation resolution using a custom data loader. Most of the time consumed is building up `ObjectType` objects. I can't cache/serialize these easily due to the closures for resolution.

Is there a recommended course of action I can take here to improve the perf? I don't mind if it's laborious, but all the testing I've done in changing things around have not made a big difference.

**Comment by vladar** [comment]
Some details would be useful.

How many types do you have?
How many fields per type on average?
Which process consumes most of the time - new schema instance creation, query parsing or execution?
How deep is the query which is slow?
How many fields and types it affects?
Slow means how many milliseconds?

Also, try the following:
1. Define all `fields` and `interfaces` of your types as closures
2. Define [`typeLoader`](https://webonyx.github.io/graphql-php/type-system/schema/#lazy-loading-of-types) (e.g. use your type registry for this)
3. Keep in mind that `overblog/dataloader-php` has a perf issue ([described it here](https://github.com/webonyx/graphql-php/issues/244#issuecomment-381411178)). Make sure it doesn't affect you
4. Also [experimental executor](https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md#try-it-experimental-executor-with-improved-performance)

**Comment by SonarSoftware** [comment]
Hey vladar, thanks a lot for the quick response! I'll try to answer your questions below.

> How many types do you have?

Well over 1K.

> How many fields per type on average?

I'm not sure the average is useful, some are large (10+) some are pretty small (1-2.) There's a pretty wide range, it depends on the object, but there's a good amount of large ones.

> Which process consumes most of the time - new schema instance creation, query parsing, validation or execution?

That I am not 100% sure on yet - I'm still going through and profiling. I'll post up the Blackfire once I have it cleaned up.

> How deep is the query which is slow? 

Roughly three relations, it gets worse the bigger it is, but not by that much to be honest.

> How many fields and types it affects?

Lots.. the query is very large, and dynamically generated by our internal tools so it's pretty ugly to look at.

> Slow means how many milliseconds?

It's not awful, honestly - I've been able to get it down to 500-600ms from request to response which, considering how large the schema is, I don't think is awful. That being said, I'm just looking to see if there's anything I can do better (as obviously, the faster the better!)

1. I will give this a try!
2. Done this already.
3. Not using this, I built my own (we use ElasticSearch so I needed something pretty custom.)
4. Tried this, did not really help at all (and broke introspection for me.)

**Comment by SonarSoftware** [comment]
> And by the way, do you have any logic in your ObjectType constructors (other than just defining the type config)?

Nothing super complex, but it does new up the models and convert them to the type definition. There's some slowdown there. I was investigating perhaps defining them using type language instead, but I'd still need to pass in the resolvers which I'd then need to define somewhere, and I don't know if that would make a big difference or not. Do you think it would?

**Comment by SonarSoftware** [comment]
For anyone coming across this in future, I spent most of today working through this without a ton of luck. Then I tried out running this library on top of a Swoole server - API responses that were previously taking 250-300ms dropped to 30ms. It basically supercharges your type registry since you don't have to keep instantiating new objects on every request.

Not necessarily a plug in fix but definitely something worth trying if you're hunting for performance.

**Comment by vladar** [comment]
ObjectType constructors should be as lightweight as possible. If you can - move most of your model-wiring logic into the `fields` closure. 

It is really hard to provide any further help without code examples/profiling results. But I suspect that 200-300ms for 1k+ schema and default PHP execution model is a quite expected result.

The execution model of Swoole (and other similar tools) obviously works better for GraphQL, but it requires you to be much more careful in your code: in PHP we are used to the fact that server frees-up resources for us, so it is much easier to introduce memory leaks in such environments which would lead to crashes.

So everything has pros and cons. But if you are aware of them - I would definitely recommend Swoole for the GraphQL API server.

**Comment by SonarSoftware** [comment]
Yeah, I am very happy with the performance and quality of this library overall - didn't want to make it sound like it was bad! I was just wondering if there was anything else I should be doing to improve the performance even further. I figured 300ms for resolution wasn't awful, just wanted to see how much better I could do.

Definitely not a 'plug and play' solution by using Swoole, but it's definitely helped a lot in my use case! Thanks for your help and feedback.
