### ISSUE TITLE
One liner shorthand for field definition?

### ISSUE THREAD

**Issue by feihe-houzz** [webonyx/graphql-php#47]
Currently for field (such as currency in below example), only array type definition is allowed (has to be an array within which defines a "type"). In other GraphQL implementations such as https://github.com/Youshido/GraphQL, a simpler shorthand like this is allowed:

**Proposed**
`
'currency' => Type::string()
`

**Current**
```
      $ProductType = new ObjectType([
			'name' => 'Product',
			'fields' => [
				'title' 		=> [
					'type' => Type::string()
				],
				'priceStr' 		=> [
					'type' => Type::string()
				],
				'currency' 		=> [
					'type' => Type::string()
				]
			]
		]);
```
I have a rough code change that can convert to a pull request, if more ppl find it handy.

**Comment by vladar** [comment]
Yeah, I agree that it is convenient and I don't envision any significant cons. Will be happy to merge a PR for this. So feel free to submit it when you have a chance.

**Comment by vladar** [comment]
Fixed in https://github.com/webonyx/graphql-php/commit/5148c3bf03973c6643f55361b52c739e3bf0bce8
