### ISSUE TITLE
Stuck on Promise implementation

### ISSUE THREAD

**Issue by SonarSoftware** [webonyx/graphql-php#473]
Probably doing something stupid, but hoping someone can help.

I'm trying to use https://packagist.org/packages/streamcommon/promise in combination with Swoole, and struggling with figuring out how to finally resolve the promise in the end. Everything seems to be working correctly (my Promise adapter is returning resolved promises, `then` is getting called in it with an `ExecutionResult`) but once I get to calling `GraphQL::promiseToExecute` and calling `then` on the final GraphQL Promise, I can't figure out how to get the final data set out of it to return. I'm obviously missing how to finally resolve that Promise wrapper, but I've been banging my head against this all day and I'm hoping someone can help point me in the right direction.

**Comment by vladar** [comment]
Not sure what is your issue? You can't "return" from a promise. Whatever happens in a promise stays in a promise chain. You must just continue your logic inside the last closure. Unless I am missing something?

```php
GraphQL::promiseToExecute(...)->then(function($result) {
    echo json_encode($result);
    exit;
})
```

**Comment by SonarSoftware** [comment]
Thanks, I'll give that a try. I was stuck on the docs at https://webonyx.github.io/graphql-php/data-fetching/#async-php showing using a `return` which doesn't really work - figured I must be missing something. Seems obvious to just echo it out now :)
