### ISSUE TITLE
What is the proper way to let ObjectType resolveField function know the upper query name

### ISSUE THREAD

**Issue by williamjieh** [webonyx/graphql-php#478]
For example , below schema:

```
type Book {
  img: String!
  title: String!
  author: String!
  price: Int!
}

type Query{
  featured_book():[Book]
  best_seller_book():[Book]
}

query {
  featured_book {
    img
    title
    author
    price
  }
  best_seller_book {
    img
    title
    author
    price
  }
}
```

for `featured_book` query, I want the img field return big image, for `best_seller_book` query, I want the img field return normal image, I don't know how to let the Book object type know which upper query is calling it, so it can return different size image.I think use arguments might be an option, is there any other way besides that ?

Thank you!

**Comment by simPod** [comment]
Sounds a bit magical to me. When querying the same book, I'd expect the same result.

Why don't you simply create two fields, one for big and one for normal image? Or pass arguments to `img` field of type enum `ImageSize`?

**Comment by williamjieh** [comment]
@simPod , I'm trying to find a way that don't need to change the schema , or change it as little as possible.

**Comment by simPod** [comment]
All I'm saying that IMO it's wrong to return different results for the same query.

**Comment by simPod** [comment]
I don't see a problem for frontend guy to change few lines and modify his queries ;)

**Comment by mfn** [comment]
I don't think you can _easily_ traverse the tree "up".

But in the `featured_book` and `best_seller_book` queries you can e.g. use the `$context` to set a state which is also available when the children are resolved.

But I don't know if the order is guaranteed, e.g. children nodes of `featured_book` evaluated direct after the query was resolved but before children of node `best_seller_book` are being processed.

Or when you resolve the individual book types form a query, you add some internal meta data to your own values/models itself to figure out how the should behave when the specific field is resolved.

Definitely magic/dirty.

**Comment by vladar** [comment]
Agree that this is a hack. Don't do it like this. If you do, then you will regret later (unless it is a write-once project) as maintenance will become a mess. This is against "GraphQL way".

As they said, the schema/query must be changed to make it work as needed. Changing schema doesn't mean breaking it. You could add arguments to field `img` which will be totally backward-compatible.

In general, I don't see any reason why frontend guys would be against this in favor of dirty hacks. Maybe there is a lack of communication. If it is the case - invite them here to discuss as it doesn't make any sense for me.

**Comment by williamjieh** [comment]
Thank you guys. Will try to communicate with frontend guy about this.
