### ISSUE TITLE
Issue with Field Resolving Performance

### ISSUE THREAD

**Issue by meddy** [webonyx/graphql-php#480]
I'm working on an API that isn't terribly complex, less than 50 types atm. I have a query that selects around 20 fields, with some of the fields being 3 levels nested. This API is in development, so everything is mock data being generated with Faker. Which means none of the run time I'm seeing is a problem with waiting for external services.

```php
$fooType = new ObjectType([
    'name' => 'Domain',
    'fields' => [
        'field1' => Type::nonNull(Type::string()),
        'field2' => Type::nonNull(Type::boolean()),
        'field3' => Type::nonNull(Type::listOf(Type::nonNull($nestedType))),
        'field4' => Type::nonNull(Type::string()),
        'field5' => Type::nonNull(Type::string()),
        'field6' => Type::nonNull(Type::listOf(Type::nonNull($nestedType))),
         // etc...
    ],
]);

$searchResultsType = ObjectType([
    'name' => 'SearchResults',
    'fields' =>[
        'foo' => Type::nonNull(Type::listOf(Type::nonNull($fooType))),
        'bar' => new ObjectType([
            'fields' => [
                 'total' => Type::nonNull(Type::int()),
            ];
        ]);
     ];
]);

$queryType = new ObjectType([
    'name' => 'Query',
    'fields' => [
          'searchResults' => [
                'type' => $searchResultsType
                'resolve' => function() {
                        return $this->mockData->createSearchResults();
                 }
          ]
     ]
]);
```
As you can see, I resolve by returning the entire payload in the parent resolver for the query. I don't resolve any child fields in lower level resolvers. When I run a query like this it can take 6 or more seconds, returning only 100 records. It seems to chug a lot in logic related to resolving fields (`completeValue`, `getPromise`, `collectSubFields`).

Here is a profile snapshot of a request.
<img width="1625" alt="Screen Shot 2019-05-22 at 5 09 52 PM" src="https://user-images.githubusercontent.com/244631/58216728-7aefbc80-7cb4-11e9-8ce4-cbd4298f9b95.png">

Am I doing this right? I've implemented the same API in Apollo Server for NodeJS and the response time is basically instant.

I've tried implementing the optimizations mentioned in the wiki. I set everything up to be lazy loaded, and I tried the experimental executor (which maybe runs a little faster). It seems like my problem is specifically there is a lot of overhead for resolving every single field.

**Comment by vladar** [comment]
This is not quite normal. Make sure xdebug is disabled and that the issue is not in data mocking library. If that is not the case - please share a repo on github where I could take a look at it. It's hard to help without a reproducible example.

**Comment by meddy** [comment]
I disabled XDebug and XHProf and the response times were cut way down. I didn't realize they would have such a dramatic effect. Thanks!
