### ISSUE TITLE
Is it possile to split QueryType class into multiple smaller classes?

### ISSUE THREAD

**Issue by williamjieh** [webonyx/graphql-php#482]
In what I know, all queris are implement in one class. The instance of this class will be used to pass into Schema class :

https://github.com/webonyx/graphql-php/blob/master/examples/01-blog/Blog/Type/QueryType.php

my question is, if I have 50 or 100 queries, then the QueryType class can become very big. 
Is it possile to split it into multiple smaller classes?

Thanks!

**Comment by mfn** [comment]
webonxy is the reference low-level implementation of the GraphQL spec and provides you the most basic / primitive building blocks.

That said, yes, you're right, given that example you references, that class will become big.

Either doing it manually or using framework specific implementations, you can separate and organize the queries / mutations / types as you want and stitch them together however you like.

Relates issue with big schemas are:
- [lazy loading of types](http://webonyx.github.io/graphql-php/type-system/schema/#lazy-loading-of-types)
- [Caching](http://webonyx.github.io/graphql-php/type-system/type-language/#performance-considerations)

Just an example how it can be done: https://github.com/rebing/graphql-laravel uses the approach that you define a PHP class for each query in a folder and register it. So each query has its own class where it defines the name, it's fields / input args and how it's resolved, etc.

Or https://github.com/nuwave/lighthouse , which uses a DSL / schema first approach (everything is defined in `*.schema` files) and uses directives to reference the code / classes which implement the resolvers.

[You can find more examples in the docs.](http://webonyx.github.io/graphql-php/complementary-tools/)

HTH

**Comment by vladar** [comment]
Query type config is just an array. You can split/merge this array the way you want. Just combine it when constructing the query type and pass it in the constructor the way it makes sense for your app.

**Comment by williamjieh** [comment]
Thank you @mfn and @vladar , I found a similar closed issue, and this one solves my problem!
https://github.com/webonyx/graphql-php/issues/275
