### ISSUE TITLE
Bug: Missing enum values when building schema from AST array

### ISSUE THREAD

**Issue by franzwilding** [webonyx/graphql-php#484]
It took me some time to figure this out: if you build a schema from an AST array you need to set enum values in the typeConfigDecorator callback: 

```php 
BuildSchema::build($astArray, function($typeConfig, $typeDefinitionNode) {
            $fullType = $manager->getSchemaType($typeConfig['name']);
            if($fullType instanceof EnumType) {
                foreach($typeConfig['values'] as $key => $value) {
                    $typeConfig['values'][$key]['value'] = $fullType->getValue($key)->value;
                }
            }
            return $typeConfig;
        });
```

You should mention this in the docs (https://webonyx.github.io/graphql-php/type-system/type-language/#defining-resolvers)

**Comment by vladar** [comment]
I don't think we should do this. If we have to - then it is possibly a bug which has to be fixed instead. Could you provide original issue description? Like AST example and your expectations on lib behavior (which are not fulfilled)?

**Comment by vladar** [comment]
I just checked this with the following test case:

```php
    public function testInputObjectValidation()
    {
        $schemaStr = '
enum Foo {
    A
    B
}

type Query {
  foo: Foo
}

schema {
    query: Query
}
';
        $schema = BuildSchema::build($schemaStr);
        $A = $schema->getQueryType()->getField('foo')->getType()->getValue('A');
        $B = $schema->getQueryType()->getField('foo')->getType()->getValue('B');
        $this->assertEquals('A', $A->value);
        $this->assertEquals('B', $B->value);
    }
```

To clarify: `$typeConfig` doesn't have `value` key in it but in such case, value is considered equal to the name of the enum entry, so it is not required.

Closing for now. Please provide more info on what you are trying to achieve if I am missing something.
