### ISSUE TITLE
Config resolveField should accept any kind of callable 

### ISSUE THREAD

**Issue by inceddy** [webonyx/graphql-php#488]
The `resolveField` config param currently only accepts closures and invokable objects.

https://github.com/webonyx/graphql-php/blob/387f416984211489075e9dcaedb4f120c86398d1/src/Executor/ReferenceExecutor.php#L632

This should be improved to any kind of callable. E.g. when in a custom type I'd like to use `[$this, 'resolveField']` .
Changing line 632 in ReferenceExecutor.php should do the trick.
````php
return call_user_func($resolveFn, $source, $args, $context, $info); 
````

**Comment by vladar** [comment]
Yeah, PR is welcome!

**Comment by vladar** [comment]
Actually, I just checked and it seems to work with any callable. Feel free to re-open with more details or some failing test-case.

**Comment by vladar** [comment]
Here is a test case BTW:

```php
namespace GraphQL\Tests\Regression;

use GraphQL\GraphQL;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Schema;
use PHPUnit\Framework\TestCase;

class ResolveFieldCallableTest extends TestCase
{
    public function testResolveFieldCallable()
    {
        $schema = new Schema([
            'query' => new ObjectType([
                'name' => 'Query',
                'fields' => ['foo' => Type::string()],
                'resolveField' => [$this, 'resolveField']
            ]),
        ]);

        $result = GraphQL::executeQuery($schema, '{ foo }');
        $this->assertEquals(['data' => ['foo' => 'bar']], $result->toArray());
    }

    public function resolveField()
    {
        return 'bar';
    }
}

```

Keep in mind that `resolveField` must be public, otherwise, it won't be accessible during execution.
