### ISSUE TITLE
Fatal Error after last commit

### ISSUE THREAD

**Issue by aponscat** [webonyx/graphql-php#49]
Hi, 

First of all, let me thank you for this great library!

We're getting a Fatal error when using graphql-php after last commit, yesterday it works fine.

PHP Deprecated:  GraphQL\Schema constructor expects config object now instead of types passed as arguments. See https://github.com/webonyx/graphql-php/issues/36 in /var/www/tnc2016/vendor/webonyx/graphql-php/src/Schema.php on line 62
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/tnc2016/vendor/webonyx/graphql-php/src/Validator/Rules/LoneAnonymousOperation.php on line 18

Please contact us if you want more info on reproducing this bug.

**Comment by geshido** [comment]
Solved here by removing "... extends PHPUnit_Framework_TestCase" in file src/Validator/Rules/LoneAnonymousOperation.php

**Comment by mcg-web** [comment]
Thank you @geshido and @aponscat ! @geshido can you create a PR to fix it please?

**Comment by geshido** [comment]
#50

**Comment by mcg-web** [comment]
Nice ;), thank you for the fix
