### ISSUE TITLE
Question regarding single type instance assertions

### ISSUE THREAD

**Issue by ncrypthic** [webonyx/graphql-php#490]
Hi,

I made a library to automatically generate types from doctrine metadata. The single instance assertions had been quite a nuisance so that I need to make a hack to dynamically create graphql types [https://github.com/ncrypthic/doctrine-graphql/blob/master/src/DoctrineGraphQL.php#L336](here).

Is the [single instance assertion](https://github.com/webonyx/graphql-php/blob/master/src/Utils/BuildSchema.php#L118) really necessary?

Or is there any other way to improve it?

I am willing to contribute to do the improvement.

Thanks

**Comment by vladar** [comment]
Lots of accidental and hard-to-track errors are prevented by this check, so yes, it's necessary. I.e.:

```graphql
type A {
  field: Boolean
}

type A {
  field: String
}

type B {
  a: A
}
```

But it's not the only one - there are cases where people store state in the type instance and accidentally create multiple types which makes it really tricky to debug.

We prefer to prevent it in the first place. Plus, logic-wise - why would you want two instances of the same type (within one schema)?

**Comment by ncrypthic** [comment]
I see... Maybe my case is kinda special, because I use it along with ORM relationships concept (e.g. one-to-many, many-to-many, etc.).

With those relationships concept, first I must declare an `ObjectType` for every entity with only their primitive (non relational) properties only. Then after all those types are defined, I need to add the relational fields. This is where the issue arise. I cannot modified / replace previously defined type intentionally because of the guard.

Can we provide any replace mechanism? If yes, will it be safe to do so?

**Comment by ncrypthic** [comment]
On file [src/Utils/TypeInfo.php#L162](https://github.com/webonyx/graphql-php/blob/master/src/Utils/TypeInfo.php#L162)
```php
// https://github.com/webonyx/graphql-php/blob/master/src/Utils/TypeInfo.php#L162
161.            Utils::invariant(
162.                $typeMap[$type->name] === $type,
163.                sprintf('Schema must contain unique named types but contains multiple types named "%s" ', $type) .
164.                '(see http://webonyx.github.io/graphql-php/type-system/#type-registry).'
165.            );
166.            return $typeMap;
```

Can we replace just compare the `config` property value? 🤔 

```php
161.            Utils::invariant(
162.                $typeMap[$type->name]->config === $type-config,
```

**Comment by vladar** [comment]
@ncrypthic Not really. This looks like a hack. Besides arrays are always compared by value, not by reference which is slow on big arrays + may produce some hard-to-debug issues.

```php
        $foo = ['my array'];
        $bar = ['my array'];
        var_dump($foo === $bar); // true
```

```php
        $foo = ['my array', new stdClass()];
        $bar = ['my array', new stdClass()];
        var_dump($foo === $bar); // false
```
