### ISSUE TITLE
Add a reference to ExecutionContext inside ExecutionResult

### ISSUE THREAD

**Issue by Vincz** [webonyx/graphql-php#514]
I think it would be great to be able to get the `ExecutionContext` from within the `ExecutionResult`. It would allow to know what append to get the result (what was the query, ...). Would be great for logging, caching, etc... 
I tried to find another way to get this information but with the promise adapter, the result is really isolated from the rest. 
The changes would be minor and there would be no bc break. 
What do you think ? Should I submit a PR ?

**Comment by vladar** [comment]
Execution context is an implementation detail which we are not going to expose to the public. Besides, we have two different executors (reference/coroutine) and they have different execution contexts.

Could you list which parts of it you are interested in? I think some of them could already be available.

**Comment by Vincz** [comment]
I'm using this implementation through the Symfony bundle. I wanted to know what was the query being executed and what was the result of the execution (for some specifics queries, I wanted to trigger some publications in a redis channel for a subscription server). Also, I didn't want to parse a already parsed query string and wanted to access the Document node directly.

**Comment by vladar** [comment]
Not sure about Symfony bundle, but with this base library you can do it like this:

```php
use GraphQL\GraphQL;
use GraphQL\Language\Parser;
use GraphQL\Executor\ExecutionResult;
use GraphQL\Error\Error;

try {
    $doc = Parser::parse($queryString); // returns instance of DocumentNode
    $result = GraphQL::executeQuery($schema, $doc);
} catch (Error $e) {
    $result = new ExecutionResult(null, [$e]);
}
```

If you need to access it from resolvers - just assign document to your `$context`.
