### ISSUE TITLE
GraphQL Federation support

### ISSUE THREAD

**Issue by EdgarPost** [webonyx/graphql-php#515]
I was wondering if there are any plans to implement the [Federation specification](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/) which makes it easier to use different GraphQL endpoints across microservices without schema stitching.

More in-depth information about this topic: https://blog.apollographql.com/apollo-federation-f260cf525d21

Perhaps it's a already been discussed, but I couldn't find anything.

**Comment by vladar** [comment]
We follow the [reference implementation repo](https://github.com/graphql/graphql-js). So unless this feature lands there (and in the official graphql spec) there are no plans supporting it in this lib.

But it could be a separate project utilizing this lib (same way as Apollo utilizes graphql-js under the hood for their initiatives)

**Comment by jmbarrios** [comment]
I'm working on a sample implementation using this package and the Apollo Federation Spec

**Comment by estudiogenius** [comment]
+1

**Comment by pascaldevink** [comment]
@jmbarrios any update on your progress? I'd love to take a look at any implementation for this you have

**Comment by vladar** [comment]
If anyone builds a library with federation support - feel free to add it to [Complementary tools](https://github.com/webonyx/graphql-php/blob/master/docs/complementary-tools.md) section of the docs and send a PR!
