### ISSUE TITLE
Solving the N+1 problem in a long-lived context

### ISSUE THREAD

**Issue by moufmouf** [webonyx/graphql-php#516]
Hey guys,

While developing [GraphQLite](http://graphqlite.thecodingmachine.io/), I cam into an issue I cannot solve easily: https://github.com/thecodingmachine/graphqlite/issues/103

I thought I would ask for some guidance here. Here is the issue.

The "Solving the N+1 problem" documentation advocates this kind of solution:

```php
'resolve' => function($blogStory) {
    MyUserBuffer::add($blogStory['authorId']);

    return new GraphQL\Deferred(function () use ($blogStory) {
        MyUserBuffer::loadBuffered();
        return MyUserBuffer::get($blogStory['authorId']);
    });
}
```

This is working great for most use cases. But I have an issue for users that would be using Webonyx/GraphQL in the context of a long lived process (like Swoole).

Typically, in the case of a Swoole app, the application will execute many requests.

So instead of having a `MyUserBuffer` with static methods, I would like to have a different instance of `MyUserBuffer` for any GraphQL request.

I saw that there is an "execution context" object, and I would love to be able to access that object and to be able to bind my `MyUserBuffer` instance to that object. That way, when the request finishes, the execution context disappears and my buffer disappears along it.

The fact is I don't have access to the "execution context" object from the resolver (the ResolveInfo class does not link back to the exe context)

I could of course put the `MyUserBuffer` instance in the `$context` of the query, but I'm developing GraphQLite and I would prefer to keep the context clean. That way, the end-user can use the context and I'm not cluttering it.

Any idea how I could solve this problem?

Oh, and BTW, thanks a lot for this library, it really rocks.

**Comment by mfn** [comment]
> put the `MyUserBuffer` instance in the `$context`

I was under the impression this is the preferred approach. Because this context can exist for each and every GraphQL execution context, in isolation.

And still you can _share_ it when e.g. performing batch requests via the apollo spec.

Other then that I think it's really up to you how you want to have it behave.

You can also take inspiration from JS DataLoader, which is the get go solution for GraphQL JS => https://github.com/graphql/dataloader:
> Each DataLoader instance represents a unique cache. Typically instances are created per request when used within a web-server like express if different users can see different things.

**Comment by vladar** [comment]
Yeah, `$context` is exactly for things like this. I guess you'll have to ask your users to implement some interface for their context class or expose a property with your buffers.

Execution context is an implementation detail which we are not going to expose to the public. Besides, we have two different executors (reference/coroutine) and they have different execution contexts.

**Comment by moufmouf** [comment]
Ok, makes sense. Thanks for the answer!
