### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by MrMoronIV** [webonyx/graphql-php#520]
I'm pretty sure I'm in the wrong place here but how would oauth2 be able to protect my graphql api?

I already have an oauth2 server active which protects a slim framework api. Is there any direction on how to combine oauth2 (league package) with graphql-php while also having some public requests possible without login?

**Comment by vladar** [comment]
At the moment auth is out of the scope of this library. It should be implemented prior to graphql execution and many frameworks already provide those tools.

However, if you create a project binding together graphql-php and oauth2 library - we will mention it in the [complementary tools](https://webonyx.github.io/graphql-php/complementary-tools/) section in docs.
