### ISSUE TITLE
Invalid input type for single element in List type

### ISSUE THREAD

**Issue by dnyg** [webonyx/graphql-php#521]
According to the GraphQL specification regarding [List](https://graphql.github.io/graphql-spec/June2018/#sec-Type-System.List):

> **Input Coercion**
> 
> ...
> 
> If the value passed as an input to a list type is not a list and not the null value, then the result of input coercion is a list of size one, where the single item value is the result of input coercion for the list’s item type on the provided value (note this may apply recursively for nested lists).

This means that if an Input is defined as `[Int!]` I should be able to provide an integer, and it will coerce it into a List with this element as the single element.

This works fine if I just provide the integer in the query

```
query {
  someQuery(id: 35) {
    ...
  }
}
```

Although `id` here is defined as a `[Int!]`, it can accept the integer, and it is passed to the resolver as `[35]` as it should. So far so good.

However when attempting this using variables:

```
query someQuery($id: Int!) {
  someQuery(id: $id) {
    ...
  }
}
```

it fails with the error

> Variable "$id" of type "Int!" used in position expecting type "[Int!]".

Is there any way to get around this?

**Comment by vladar** [comment]
Your variable definition should be still compatible with argument type:

```graphql
query someQuery($id: [Int!]) {
  someQuery(id: $id) {
    ...
  }
}
```
Then you can pass single value in variables: `$variables = ['id' => 5]`.

See [corresponding spec section](https://graphql.github.io/graphql-spec/June2018/#sec-Validation.Variables):

> Variable usages must be compatible with the arguments they are passed to.
> ...
> List cardinality must also be the same.
