### ISSUE TITLE
support \stdClass for input types

### ISSUE THREAD

**Issue by adam1658** [webonyx/graphql-php#534]
Hi, thanks for a great project - it's been very useful.

I've got a custom scalar<sup>1</sup> in my app which represent JSON values that validate against a given JSON Schema. In my scalar's parseValue method I validate the value against my Schema using [opis/json-schema](https://github.com/opis/json-schema). It expects JSON arrays to be arrays and JSON objects to be \stdClass instances.

I've tried decoding my variables JSON with \stdClasses (and casting the root variables object to an associative array - leaving only input types and scalars as \stdClasses). This works great for my custom scalar, but it now means all my inputs are \stdClasses - which I'm ok with, but this library isn't.

[Value::coerceValue](https://github.com/webonyx/graphql-php/blob/v0.13.6/src/Utils/Value.php#L160-L217) expects input types to be associative arrays or Traversables. It returns the content as an array. **Would you consider casting \stdClasses to arrays in this method, if they are passed in?** That way I could safely pass a \stdClass in. The method could then return the array version as it currently does, or cast back to \stdClass before returning (only if it received a \stdClass in the first place) - I'm not worried about this detail, my resolvers could be written to deal with input types in either format.

I'd be happy to do a pull request if you think this is a suitable feature / solution. If you have any other suggestions for how I can get my custom scalars decoded as \stdClasses without touching the inputs, please let me know.

<sup>1</sup>I have multiple custom JSON scalars, each with their own JSON schemas. I find these really useful for things like user preferences - key value pairs where the values are all different types. I just store that JSON in a column in the DB and make sure that it matches the JSON Schema whenever I update it (through GraphQL)

**Comment by vladar** [comment]
I think this change is quite minor and won't affect anything, so I am OK with the explicit casting of stdClasses to arrays. Feel free to submit a PR.

But we must ensure we have tests for this feature to avoid regressions in the future (i.e. if we accidentally remove this casting after some reference implementation changes)
