### ISSUE TITLE
String! field type contains '"' return errors

### ISSUE THREAD

**Issue by treoden** [webonyx/graphql-php#537]
Hi,

I have a blog type with name and content are String! field type.
But when I try to input a name with '"' inside it returns error.
I then try to use "addcslashes($data[$name], '"')" to add slashes before double quotes but it does not work if I have '\\"' in data
`mutation {createCmsPage (page : {id: 3 name: "Ab'out u\\"s" status: 1 content: "This is content" layout: "oneColumn" meta_keywords: "" meta_title: "" meta_description: "" } )`

It returns error: 
"Syntax Error: Expected :, found String \u0022 status: 1 content: \u0022"

Is there any solution for this ?

Thanks for your support

**Comment by vladar** [comment]
You need to add commas in your object

**Comment by treoden** [comment]
> You should add commas to your object

Hi Vladar could you help to be more detailed ?

Thanks

**Comment by vladar** [comment]
Actually, it's not the comma, sorry for the confusion. It's about back-slashes - you need only one (not two). So your query should be:

```graphql
mutation {
  createCmsPage(page : {id: 3 name: "Ab'out u\"s" status: 1 content: "This is content" layout: "oneColumn" meta_keywords: "" meta_title: "" meta_description: "" })
}
```

Or if you need backslash in the text - three of them (one to escape the quote and another one to escape your back-slash):
```graphql
mutation {
  createCmsPage(page : {id: 3 name: "Ab'out u\\\"s" status: 1 content: "This is content" layout: "oneColumn" meta_keywords: "" meta_title: "" meta_description: "" })
}
```

**Comment by treoden** [comment]
Hi Vladar

Thanks for your response.
I have tried your suggestion but it does not work

`mutation {createCmsPage (page : {id: 3 name: "Ab'o\\\ut us" status: 1 content: "wweqweqw" layout: "oneColumn" meta_keywords: "" meta_title: "" meta_description: "" } )`

Error message:
"Syntax Error: Invalid character escape sequence: \ut us"

On top of that, I also facing issue when I try to input a html as a content. It show me :
"Syntax Error: Unterminated string."

**Comment by vladar** [comment]
If you struggle with escaping strings I would suggest using variables in your mutations instead of using literals. For example:

```graphql
mutation ($input: MyInputObjectType) {
  createCmsPage(page: $input)
}
```

Then pass your variables along with query. See [this article](https://webonyx.github.io/graphql-php/concepts/#mutations) in docs for more details.

**Comment by treoden** [comment]
Thanks a lot Vladar

I will try it
