### ISSUE TITLE
Problems reverting doPrint with fromArray

### ISSUE THREAD

**Issue by sirio3mil** [webonyx/graphql-php#538]
I'm trying to cache schema, first I made an SchemaPrinter::doPrint but when try to restore it using AST::fromArray everything goes well but query return an error.

This is my [schema generation class](https://github.com/sirio3mil/cinema-expressive/blob/schema-cache/src/App/Factory/GraphQLHandlerFactory.php), there you can see the generation and later restore process, also [schema exported file](https://github.com/sirio3mil/cinema-expressive/blob/schema-cache/schema.graphql).

This is the output when use cache schema

```
{
    "errors": [
        {
            "debugMessage": "Cannot return null for non-nullable field query.search.",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 5,
                    "column": 5
                }
            ],
            "path": [
                "search"
            ]
        }
    ]
}
```

Any idea?

**Comment by vladar** [comment]
When printing schema, resolvers are unset. You should reassign them in the typeConfigDecorator
