### ISSUE TITLE
Where is the right place to get each query result separately when there is multiple query in one request payload?

### ISSUE THREAD

**Issue by williamjieh** [webonyx/graphql-php#541]
Hi,
I want to know where is the right place to get each query result separately when there is multiple query in one request payload?
As what I know, I can get the full response like this:
`$result = GraphQL::executeQuery(...)`
If there is only one query in the request payload, this way is Okay, but if there is multiple queries in the request payload, I want to get each query result separately ( to set these result to cache server with different keys), is it possible?
Thanks!

**Comment by vladar** [comment]
You can pass your query in the `$context` variable of this call (see option `context` [in docs](https://webonyx.github.io/graphql-php/executing-queries/#using-facade-method)).

So basically here is an example of how you could do it:

```php
use GraphQL\Language\Parser;
use GraphQL\GraphQL;

$result = [];
foreach ($queries as $queryString) {
    $doc = Parser::parse($queryString);
    $context = new stdClass();
    $context->query = $doc;
    $result[] = GraphQL::executeQuery($schema, $doc, null, $context);
}
```

Then in your resolvers:
```php
function ($value, $args, $context, $info) {
    $query = $context->query;
}
```
