### ISSUE TITLE
QueryPlan Field "__typename" is not defined for type ...

### ISSUE THREAD

**Issue by oesteve** [webonyx/graphql-php#544]
QueryPlan throw "Field "__typename" is not defined for type ..." when query has __typename field.

Thanks!

**Comment by oesteve** [comment]
Maybe a solution too simple, I don't know if it's enough https://github.com/webonyx/graphql-php/pull/545

**Comment by vladar** [comment]
Hey, thanks for noticing! This is definitely a bug, but the question is if we should really exclude __typename or just handle it properly and include in the output.

I guess the expectation of most users would be not to have it included, but curious to hear other opinions first (if any). So I will keep your PR open for a while and if we don't get any objections - will merge it.

**Comment by keulinho** [comment]
I think it would be cleaner to include it also to the QueryPlan, as i find it weird to just exclude this field.
But i don't have a special use case that it must be included, IMHO it would just be cleaner if it is included.
An argument for including it is that it is possible to add your own `__typename` with its own resolver and so own, for the sake of consistency i would argue that if the library allows you to add it like a normal field it should be added to the query plan.

**Comment by vladar** [comment]
> An argument for including it is that it is possible to add your own __typename with its own resolver and so own

This is actually not the case. Fields with `__` prefix are fields reserved for introspection, and you can't redefine them (see [in the code](https://github.com/webonyx/graphql-php/blob/master/src/Utils/Utils.php#L534-L554)).

Also, the introspection is not a part of a general data resolution process - it is a separate mechanism that is available in the regular query for convenience.

**Comment by oesteve** [comment]
Hey! I don't have a position for this case ... but if __typename is ignored in queryplan, what do we expect from the getFieldSelection method? will be ignored? will it return true like other types?

**Comment by mikespub** [comment]
Are there any plans to fix this in the future? I noticed several PRs on this, but none of them made it into the repo, and the problem still exists...

Thanks

**Comment by spawnia** [comment]
Fixed as of https://github.com/webonyx/graphql-php/releases/tag/v14.6.4
