### ISSUE TITLE
Unknown type error with Interface 

### ISSUE THREAD

**Issue by gohelkiran30** [webonyx/graphql-php#548]
Getting below error while implementing interfaces 
Unknown type "CarVehicle". Did you mean "Vehicle", "OldVehicle", or "CarData"?

I think the document misses a full example. There is only how to define an interface and how to use interface in types, but how to query using this is not mentioned anywhere in docs. Also resolve functions not used in example.

**QueryType**

```
'verticalData' => [
    'type' => InterfaceTypes::vehicleInterface(),
    'description' => 'Return vehicle data based on Reg Number',
    'args' => [
        'id' => Types::id(),
    ],
    'resolve' => function ($root, $args, $c) {
        return $c['Actions']->get('VehicleAction')->getVehicleById($args['id']);
    }
]
```

**VehicleInterfaceType**
```
[
    'name' => 'VehicleInterface',
    'description' => 'Vehicle data',
    'fields' => function () {
        return [
            'id' => Types::id(),
            'make' => Types::string(),
        ];
    },
    'resolveType' => function ($value) {
        if($value->getVehicleVertical() == 'bike') {
            return Types::bikeVehicle();
        }

        return Types::carVehicle();
    }
];
```

**CarVehicleType**

```
[
    'name' => 'CarVehicle',
    'description' => 'Car Information from prefill api data',
    'fields' => function () {
        return [
            'vehicleType' => Types::id(),
            'make' => Types::string(),
       ];
    },
    'interfaces' => [
        InterfaceTypes::vehicleInterface()
    ]
];
```

I am running below query 

```
query{
  verticalData(id: 199){
    make
    ... on CarVehicle {
      vehicleType
    }
  }
}
```

CarVehicle type is not recognized 

If I remove inline fragment from query like this

```
query{
  verticalData(id: 199){
    make
  }
}
```

Than it gives an error 
Schema must contain unique named types but contains multiple types named \"CarVehicle\". Make sure that `resolveType` function of abstract type \"VehicleInterface\" returns the same type instance as referenced anywhere else within the schema (see http://webonyx.github.io/graphql-php/type-system/#type-registry).

**Comment by gohelkiran30** [comment]
Type registry class which returns only single instance of CarVehicle 
```
use Type\CarVehicleType;
use Type\VerticalDataType;

class Types
{
    // Object types
    private static $carVehicle;
    private static $verticalData;

     public static function carVehicle(): CarVehicleType
    {
        return self::$carVehicle ?: (self::$carVehicle = new CarVehicleType());
    }
    public static function verticalData(): VerticalDataType
    {
        return self::$verticalData ?: (self::$verticalData = new VerticalDataType());
    }
}
```

**Comment by vladar** [comment]
This situation is possible when the object type is never referenced in fields directly but is still a part of a schema because it implements an interface.

You have to pass such "orphan" types via option `types` when constructing the schema. See details about this option [in docs](https://webonyx.github.io/graphql-php/type-system/schema/).

Alternative workaround is to add a dummy field of this object type somewhere in the schema.
