### ISSUE TITLE
What about array dot-notation at $args in next major version?

### ISSUE THREAD

**Issue by XAKEPEHOK** [webonyx/graphql-php#559]
Every time, when I use graphql in by php backend, I install awesome lib https://github.com/adbario/php-dot-notation that can access arrays in dot-notation. Its very userful for graphql, because null-allowed values are default graphql behavior, and often needs to check that array key exists in args.

This lib very fast and userful. Please, think about it for the next major release

**Comment by vladar** [comment]
While it is unlikely that we'll use any lib (`graphql-php` uses zero-dependencies in production mode apart from some PSR) I am still curious how do you suggest using it? Any example?
