### ISSUE TITLE
Spec compliance improvement, data should not be set

### ISSUE THREAD

**Issue by AndreasHeiberg** [webonyx/graphql-php#56]
> If an error was encountered before execution begins, the data entry should not be present in the result.

https://facebook.github.io/graphql/#sec-Data

Currently this is not the case. I know it's a minor thing, but it's worth fixing to be fully compliant with the spec.

**Comment by vladar** [comment]
You are correct. We need to fix this for next version. Feel free to send a PR if you have a chance %)

In the meantime you have full control of how response is serialized. Just use `GraphQL::executeAndReturnResult` vs `GraphQL::execute` and apply your own transformation of `GraphQL\Executor\ExecutionResult` to `array`.
