### ISSUE TITLE
 Can we collect schema types aware of contextValue parameter passed to executor

### ISSUE THREAD

**Issue by videni** [webonyx/graphql-php#568]
# use case

I have 2 entrypints

admin
shop

```
User:
    private1:
        type: ID!
        public: '@=$context["schemaName"] in ['admin']'

```

the field  `private1` can only be showed when access through `admin` entrypoint. please look [Fields public Control](https://github.com/overblog/GraphQLBundle/blob/master/docs/security/fields-public-control.md) for more details.  

src/Type/Schema.php
```

    /**
     * Returns array of all types in this schema. Keys of this array represent type names, values are instances
     * of corresponding type definitions
     *
     * This operation requires full schema scan. Do not use in production environment.
     *
     * @return Type[]
     *
     * @api
     */
    public function getTypeMap()
    {
        if (! $this->fullyLoaded) {
            $this->resolvedTypes = $this->collectAllTypes();
            $this->fullyLoaded   = true;
        }

        return $this->resolvedTypes;
    }

```

Add contextValue argument to getTypeMap, all the way to  `GraphQL\\Type\\Definition\\FieldDefinition::defineFieldMap`. please look this [debug trace](https://gist.github.com/videni/11851462f23d07851dd8f242f4d92f2a), It is very long, so I save it in a gist.

**Comment by vladar** [comment]
Looks like this is something very specific to [overblog/GraphQLBundle](https://github.com/overblog/GraphQLBundle).

@mcg-web is there anything related to webonyx library in this request? If not, I'll close (I see the same issue created in your repo)

**Comment by mcg-web** [comment]
@vladar I think this issue is related to the bundle and not this lib indeed. I'm closing it, if needed we will reopen it later.
