### ISSUE TITLE
How to correctly handle multiple deferred / promise?

### ISSUE THREAD

**Issue by mfn** [webonyx/graphql-php#573]
In a resolver I need to access:
- `$model->relation1` => so I use a dataloader
- however after `relation1` is loaded, I need another relation _on that one_
- `$relation1->relation2` => again via dataloader

There is incentive using the dataloader also for `relation2` because this may be required in other resolvers too (without relation1)

I came up with a resolver looking like this:
```php
'resolve' => function (Model $model, $_) {
    $dataloader = $this->getDataLoaderFor('relation1');
    $dataloader->batch($model->relation1_id);

    $deferred = new Deferred(function () use ($model, $dataloader) {
        return $dataloader->load($model->relation1_id);
    });

    $syncPromise->then(function (Relation1 $relation1) use () {
        $dataloader = $this->getDataLoaderFor('relation2');
        $dataloader->batch($relation1->relation2_id);

        return new Deferred(function () use ($relation1, $dataloader) {
            return $dataloader->load($relation1->relation2_id);
        });
    });

    return new Deferred(function () use ($syncPromise) {
        return $syncPromise;
    });
},
```
I know closures are verbose in PHP already 😄 however I realized when I need _dependent_ deferred using `->then()`, I need to wrap it in yet another `Deferred` because `->then()` returns a `SyncPromise` which is not handled by webonxy.

Is this "amount of code" expected? Is the approach correct / good? Can I simplify the above?

Note: it's not about reducing LoC, I could do that sparing temporary variables. It's more about the approach, because currently it's:
- `Deferred`
- `->then()` returning a `SyncPromise`
- contains a closure which returns a `Deferred`
- to return the `SyncPromise` I need to wrap it in a `Deferred`

I guess I would have expected I could return `$deferred->then(…)` directly without wrapping it again.

Thanks!

**Comment by vladar** [comment]
Have you tried this:

```php
'resolve' => function (Model $model, $_) {
    $dataloader = $this->getDataLoaderFor('relation1');
    $dataloader->batch($model->relation1_id);

    return new Deferred(function () use ($model, $dataloader) {
        $relation1 = $dataloader->load($model->relation1_id);
        $dataloader2 = $this->getDataLoaderFor('relation2');
        $dataloader2->batch($relation1->relation2_id);

        return new Deferred(function () use ($relation1, $dataloader2) {
            return $dataloader2->load($relation1->relation2_id);
        });
    });
},
```

I've added a test for this scenario and it seems to be working as expected.

Resolver:

https://github.com/webonyx/graphql-php/blob/46a99a34c1dc20fc85673e45989f2702d4be3671/tests/Executor/DeferredFieldsTest.php#L170-L187

Test:

https://github.com/webonyx/graphql-php/blob/46a99a34c1dc20fc85673e45989f2702d4be3671/tests/Executor/DeferredFieldsTest.php#L556-L637

**Comment by mfn** [comment]
🤔

Well, bummer on my side. I _thought_ I created an example where I would _need_ 3 nested deferrds. But I failed, because I realized as I saw your example, yes, I can correctly reduce it to 2 levels. Ok #fail 😄 

### But…
… I'll try once more to distill my actual question better 🤞

The way I understand it: every dataloader depending on the outcome of _another_ dataloader, needs to be wrapped in a deferred.

My initial example has 2 dataloaders, so correctly you nested it twice.

So when I've `n` dataloaders, the code will be come:
- dataloader 1
- deferred
  - dataloader 2
  - deferred
    - dataloader 3
    - deferred
      - dataloader `n`
      - deferred

AKA callback hell.

What I tried to come up with, using `->then()`, was to _un-nest_ this:
- dataloader 1
- deferred
- then
  - dataloader 2
- then
  - dataloader 3
- then
  - dataloader `n`

I _think_ I can actually do that, with the only restriction:
- `then` returns a `SyncPromise`
- to make the GraphQL resolver accept this, I've to wrap it in a deffered

I.e., same as above but ends with:
- …
- then
  - dataloader `n`
- deferred returning SyncPromise

Could I better express what I meant?

**Comment by vladar** [comment]
You could try something like this:

```php
$resolver = function() {
    $promise = new SyncPromise() // or any A+ promise implementation actually
    $promise->then(function(){})
        ->then(function(){})
        ->then(function(){});

    return new Deferred(function () use ($promise) {
       return $promise->resolve($initialResolvedValue)
    });
}
```

But even if this technique works you should re-check if it actually produces a meaningful sequence of calls to enable batching. The thing is - there is no native event loop or task queue in plain PHP so we emulate them in this library (kind of).

My concern is that this sequence of promises could just resolve sequentially without any benefits to batching.

**Comment by vladar** [comment]
Can you try PR #581 which should address this?
