### ISSUE TITLE
Support Github Actions as ci

### ISSUE THREAD

**Issue by Smolevich** [webonyx/graphql-php#574]
Do you have plans on support GIthub Actions or use GIthub Actions instead travis ci?

**Comment by vladar** [comment]
There is a maintenance cost of switching. So I guess the question is what benefits we'll get from GitHub Actions which justify those costs?

I didn't have enough time to dig into GitHub Actions yet but if someone could provide a quick overview of why it would be beneficial for us (comparing to Travis) - it would be helpful.

**Comment by shmax** [comment]
Wow, how have I never heard of this?! Can't wait to start tinkering...

**Comment by Smolevich** [comment]
@vladar, i can prepare PR with changes for using GitHub Actions

**Comment by mfn** [comment]
@Smolevich please re-read https://github.com/webonyx/graphql-php/issues/574#issuecomment-554626111
> but if someone could provide a quick overview of why it would be beneficial for us (comparing to Travis) - it would be helpful.

**Comment by Smolevich** [comment]
I provide some advantages of Github Actions
1. GitHub Actions have three virtual environments: macos, ubuntu and windows. Links [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources)
2. You can simply to determine event triggers in ci, link [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows)
3. GitHub Actions released and it's not third party instrument

You can try to use GitHub Actions and travis both and compare them in work

**Comment by simPod** [comment]
_To me the main advantage is that it's directly developed and supported by Github. Travis does not seem to be developed at all. We can expect GitHub actions to get better and better, can't say that about Travis._ 

_Github is adding really cool new features to work with git after msft acquisition, beating Gitlab and Bitbucket in that. I'm really looking forward when Github also gets ahead Gitlab CI_.

**Comment by Smolevich** [comment]
PR with changes https://github.com/webonyx/graphql-php/pull/584

**Comment by vladar** [comment]
@simPod I suggest you create a failing PR (or maybe couple PRs - for style, PHPStan, unit test failures). Then if everything works as expected we can mark them as required and remove Travis!

And once again, great job @Smolevich, thanks!
