### ISSUE TITLE
Resolving Value Objects with EnumType fields

### ISSUE THREAD

**Issue by JasonTheAdams** [webonyx/graphql-php#577]
Greetings!

In my project we have an `InputOption` enum value object class. Each instance represents a single possible value limited to the enum options. We're then mapping the class to an `EnumType` within GraphQL PHP with the corresponding names and values. 

The issue we're having is that the value which gets passed to GraphQL PHP to get resolved during the `EnumType->serialize($value)` method is an instance of the enum class. The lookup fails because it's expecting a string or integer in the [MixedStore::offsetExists](https://github.com/webonyx/graphql-php/blob/master/src/Utils/MixedStore.php#L93) method. In our case, the class does have a `__string()` method to cast the instance to a string, but the `is_string()` php method does not honor this.

Would folks be open to adding something like the following to the `offsetExists` method?
```php
if (is_object($offset) && method_exists($offset, '__toString')) {
    return array_key_exists((string)$offset, $this->standardStore);
}
```

I'm happy to make a PR for this, but figured I'd start the discussion here and see if I'm thinking in an appropriate direction.

**Comment by simPod** [comment]
IMO it's out of scope of this lib. Also, did you mean `__toString()`, not `__string()`?

What I do is enum wrapper:

```php
<?php

declare(strict_types=1);

namespace MyNs;

use MyNs\EnumBuilder;
use GraphQL\Type\Definition\EnumType;

final class MyEnum extends EnumType
{
    private const NAME = 'EnumName';

    public function __construct()
    {
        parent::__construct(
            EnumBuilder::create(self::NAME)->buildFromEnum(EnumClass::class)
        );
    }
}
```

In EnumBuilder I map my enum values to gql enum.

**Comment by JasonTheAdams** [comment]
Thanks @simPod!

Unless I'm reading this wrong, the wrapper has to do with creating the `EnumType` from the Enum class. If that's the case that isn't the issue I'm having; the corresponding `EnumType` is being constructed just fine.

The issue I'm having is resolving the value during a query. The value it's attempting to resolve is an instance of the enum class, not the underlying value. So instead of it resolving `'disabled'` it's attempting a lookup on `new InputOption('disabled')`, which is just a value object for the "disabled" value.

Does that make sense?

**Comment by simPod** [comment]
Ah I see. There's a lot of conditions in `offsetExists()` already so tweaking one to support `__toString()` would not hurt performance I guess. But the change you propose would probably break this part of code, hm?

https://github.com/webonyx/graphql-php/blob/2320b3cede6b0b31131457a5a627ada8b12890f6/src/Utils/MixedStore.php#L107-L109

**Comment by JasonTheAdams** [comment]
True, only for classes that are specifically using the `__toString()` method. I would imagine that most classes are not using that magic method unless they intend the class to be cast in that way. I wouldn't imagine this to be a common problem, especially since I'd imagine most values being looked up at this post are native types.

Another option would be to provide an interface that can be implemented on the class and then checked for on the instance. That would protect against any backwards compatibility.

**Comment by spawnia** [comment]
You should be able to fix that by overwriting `serialize` on your `EnumType`:

https://github.com/nuwave/lighthouse/blob/b52e3646b0e7fea9671a316fb6f1947862e99099/src/Schema/Types/LaravelEnumType.php#L53-L66

**Comment by vladar** [comment]
> The lookup fails because it's expecting a string or integer in the MixedStore::offsetExists method

MixedStore is supposed to support any offset type. It should work with objects too:

https://github.com/webonyx/graphql-php/blob/46a99a34c1dc20fc85673e45989f2702d4be3671/src/Utils/MixedStore.php#L107-L109

So maybe you have different instances somehow? Have you tried doing singletones for those values or I am missing something here?

**Comment by vladar** [comment]
An example would be beneficial

**Comment by JasonTheAdams** [comment]
I tested out @spawnia's idea of extending the `EnumType` and overwriting the `serialize` method and this did the trick. I think this is a better solution than changing this library as the internal enum value isn't reliably a string, so an interface would be necessary for a robust solution and that feels overly complicated.

@vladar That really only works if it's the same instance. In my case we're trying to compare the enum's internal value, not the object instance.
