### ISSUE TITLE
Merging Schema Files with Repeated Type Definitions

### ISSUE THREAD

**Issue by xlttj** [webonyx/graphql-php#579]
I have a huge schema split into multiple files for maintainability.

Example:

```
type Query {
  user(name: String!): User!
}

type User {
  id: ID!
  name: String!
}
```

and another file

```
type Query {
  file(id: ID!): File!
}

type File {
  id: ID!
  name: String!
}
```

It seems like I can't merge them by repeatedly using something like

```
$ast = Parser::parse(file_get_contents($file));
$schema = SchemaExtender::extend($schema, $ast);
```

because type Query is defined in both files. Tools like https://github.com/Urigo/merge-graphql-schemas are able to handle this. Is merging schema files like that somehow possible with PHP, too?

**Comment by vladar** [comment]
You should use another syntax for this when extending the same type:

```graphql
extend type Query {
  file(id: ID!): File!
}
```
