### ISSUE TITLE
Empty object is [] instead of {}

### ISSUE THREAD

**Issue by rudiedirkx** [webonyx/graphql-php#59]
`query { user { reservations } }` returns `ReservationInterface`s, implemented by `XReservation` and `YReservation`. Let's say it returns 2 XReservations and 2 YReservations. If you add an inline fragment to only return anything for XReservations, the 2 YReservations will be completely empty. An empty array in PHP translates to an empty array in JSON, instead of an empty object.

Query:

```
{
	user {
		reservations {
			... on XReservation {
				id
			}
		}
	}
}
```

Result:

```
reservations: [
  {id},
  {id},
  [],
  []
]
```

I think those 2 `[]` should be `{}`, because they're known objects, not lists.

**Comment by vladar** [comment]
Nice catch %) 

Looks like we need to convert empty arrays to `stdClass` explicitly for such cases. Alternative is to use separate array-like class implementing JsonSerializeable in Executor, yet this will be way slower, so will likely just use stdClass.

**Comment by rudiedirkx** [comment]
I was thinking about `ArrayAccess` too, but you're probably right. It's unnecessary in 95% of cases, and way slower.

I know too little about the code to fix it, but I am curious to see the fixing commit.

**Comment by vladar** [comment]
I already fixed it, just not pushed yet because still doing some other improvements to the library. Will post a link to commit here when closing.

**Comment by vladar** [comment]
Fixed in https://github.com/webonyx/graphql-php/commit/a612b780c9c08e96f969e609093e793050cfd76b
