### ISSUE TITLE
How to use query batching

### ISSUE THREAD

**Issue by lobovmaxim** [webonyx/graphql-php#600]
Hello, Vladimir!
I am tried to use Query batching how described at https://webonyx.github.io/graphql-php/executing-queries/#query-batching

My endpoint code is:
` $schema = new Schema(['query' => Types::query(), 'mutation' => Types::mutation()]);
  $config = ServerConfig::create()->setSchema($schema)->setDebug(true)->setQueryBatching(true);
  $server = new StandardServer($config);
  $server->handleRequest();`

The code works well with query: 
`query {event(id: 27) {id}}`

But don't work with batching query:
`[{"query": "{event(id: 27) {external_id content}}"}]`

There is an error:
`{
  "errors": [
    {
      "message": "Syntax Error: Unexpected [",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}`

Please, help me how to use query batching.

**Comment by vladar** [comment]
The difference between single and batch queries is in the JSON body of your HTTP requests.

Expected JSON body for a single query:

```json
{
  "query": "query { event(id: 27) {id} }",
  "variables": {}
}
```

Expected JSON body for a batch query:

```json
[{
  "query": "query { event(id: 27) {id} }",
  "variables": {}
}]
```

Given your error message, it looks like you are trying to send a JSON like this:

```json
{
  "query": "[{\"query\": \"{event(id: 27) {external_id content}}\"}]",
  "variables": {}
}
```

In other words, you are trying to put a batch inside your GraphQL query while it should be one-level higher (in the JSON body of the HTTP request).
