### ISSUE TITLE
Are there any Tools for Easier Definition of Type / Automatic Inference of Type?

### ISSUE THREAD

**Issue by joshglenn** [webonyx/graphql-php#607]
I want to take my SQL database and create a GraphQL endpoint for it. So, I am trying out graphql-php.

Is there any tool that you know of which can make it easier to define types? 

Let me explain: I can go to my database, pull out all the records from a given table, and create php objects from each row and its fields. I can then JSON encode that and send it over an HTTP endpoint.

Is there anything that will take a sample JSON object, and generate / infer the graphql-php type from that?

**Comment by vladar** [comment]
Check out https://webonyx.github.io/graphql-php/complementary-tools/

Maybe https://github.com/thecodingmachine/graphqlite or https://github.com/simPod/GraphQL-Utils will work for you.

**Comment by joshglenn** [comment]
Looks like some great tools there. I have been checking some of them out. Thanks for sharing that info, it will come in handy.

I wound up using a schemabuilder to build the schema from a graphql definition, then served everything up using a simple resolver.

**Comment by vladar** [comment]
Closing this as it seems to be answered.
