### ISSUE TITLE
Support `repeatable` directives

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#608]
The specification recently included a new keyword `repeatable` that allows specifying directives that may be defined multiple times.

https://github.com/graphql/graphql-spec/pull/472

Reading multiple directives already works fine, so that part should not be too hard. We will have to add support for the new keyword and adapt the validation steps to handle it.

Partial support was already added to the reference implementation: https://github.com/graphql/graphql-js/pull/1965

Full support is underway, too: https://github.com/graphql/graphql-js/pull/1541

**Comment by spawnia** [comment]
@vladar do you have plans for a next release where this can land?

Asking because I am planning a major version jump in Lighthouse and want to upgrade `graphql-php` with it.

**Comment by vladar** [comment]
Let's set a deadline, otherwise, I will keep postponing it 😉 Let's publish 14.0 on the 21st of June (still need several things to do before publishing).

**Comment by spawnia** [comment]
That's going to be a nice birthday present for me 🍰 Cool!

Let me know what i can do to help, i would love to get more involved with the project.

**Comment by vladar** [comment]
Oh, that's a good match :)

Thanks for proposing help! Added you as a maintainer. I am definitely happy to have more maintainers, especially people like you committed to GraphQL community!
