### ISSUE TITLE
get default resolver for the field throuth type instance

### ISSUE THREAD

**Issue by apapilov-sc** [webonyx/graphql-php#609]
I want to test my entire scheme by testing each type individually to decouple testing process and make it more expressive. mock root element and then instantiate the one I want to test. something like this:

```
public function testTestCarOwnerIsCorect() {

$expected = [
    'id' => '2342',
    'name' => 'Alex',
    'age' => 21,

];
$car = Car::query()->where('id', 22)->get()->first();

$carGraphqlType = $this->app->get(CarGraphqlType::class);
$ownerResolver = $carGraphqlType->owner;
$owner = $ownerResolver($car);

self::assertEquals($expected, $owner);
}
```

if I define resolver explicitly on CarGraphqlType for "owner filed" I can easily get it and resolve the owner field.

```
$carGraphqlType = $this->app->get(CarGraphqlType::class);
$ownerResolver = $carGraphqlType->owner;
$owner = $ownerResolver($car);
```

Is there a way to get a default resolver from a field through its Type instance, if the resolver is not defined explicitly. There gotta be a way to do it since It works well when I query it through graphql endpoint. (while resolver for owners is not defined on the CarGraphqlType under the hood it somehow resolve it using default resolver).

```
query {
    cars(id:3) {
        id
        owner{
            id
            name
            age
        }
    }
}
```

So. Is there some way to do so, without explicitly defining resolver for "owner" on "CarGraphqlType".

$carGraphqlType = $this->app->get(CarGraphqlType::class);
$ownerResolver = $carGraphqlType->owner;
$owner = $ownerResolver($car);

**Comment by vladar** [comment]
You can get default resolver via:

```php
use GraphQL\Executor\Executor;

$defaultResolver = Executor::getDefaultFieldResolver();
```

**Comment by vladar** [comment]
Closing this but feel free to re-open if you think we should discuss it further.
