### ISSUE TITLE
StandardServer error handler results in error

### ISSUE THREAD

**Issue by OssiPesonen** [webonyx/graphql-php#612]
So I am curious to know how I could implement a custom error handler with StandardServer. It's a configurable option. Preferably something that can alter the PSR-7 `$response` so that I can tell it what HTTP code to return as well as the output contents.

I tried the examples and attempted to pass a callback function. However I receive the following error when attempting to execute a false query

```
{
    "error": "Argument 1 passed to App\\GraphQL\\GraphQLController::App\\GraphQL\\{closure}() must be an instance of GraphQL\\Error\\Error, array given, called in /var/www/html/vendor/webonyx/graphql-php/src/Executor/ExecutionResult.php on line 148"
}
```

My StandardServer configuration:

```
$config = ServerConfig::create()
    ->setSchema($schema)
    ->setContext($context)
    ->setQueryBatching(true)
    ->setErrorsHandler(function (\GraphQL\Error\Error $error) {
        return FormattedError::createFromException($error);
    });
```

So are the docs wrong here? 

Also, could the `$response` be altered inside the error handler or what other ways are there to do so with StandardServer?

```
->setErrorsHandler(function (\GraphQL\Error\Error $error) use (&$response) {
    $output = [
        'errors' => [FormattedError::createFromException($error)]
    ];

    $httpResponseStatus = HttpStatusCodes::INTERNAL_SERVER_ERROR;
    $response = $response->withJson($output)->withStatus($httpResponseStatus);
    return $output;
});
```

**Comment by OssiPesonen** [comment]
Not sure if I am doing something wrong, but apparently the argument passed to the errorhandler callback is indeed an `array` and the 0 index contains the GraphQL\Error\Error object instance.

**Comment by OssiPesonen** [comment]
Would it be a good idea to actually be able to return some type of http status code from error handlers which gets passed to PSR-7 response? Now I have to do this:

```
$errorCode = false;

$config = ServerConfig::create()
    ->setSchema($schema)
    ->setContext($context)
    ->setQueryBatching(true)
    ->setErrorsHandler(function (array $error) use (&$errorCode) {
        $errorCode = $error[0]->getCode(); # Does not work yet, but could
        return FormattedError::createFromException($error);
    });

$server = new StandardServer($config);
$response = $server->processPsrRequest($request, $response, $response->getBody());

if($errorStatusCode) {
    $response = $response->withStatus($errorStatusCode);
}
```

I am not 100% sure if the GraphQL specification is opinionated on http codes, but I would think this is benefitial.

**Comment by OssiPesonen** [comment]
Alright so any Exception thrown from a resolver can set a message, but not HTTP code, because of this row:

https://github.com/webonyx/graphql-php/blob/599b03b59bf990e289337b1b79dc6aea31ea882e/src/Error/Error.php#L104

We can get around this, but it would be really helpful if the 0 is actually a parameter in the constructor, BUT it would be backwards incompatible because the $nodes would have to be shifted.

Not sure if this can be done. Thoughts?

**Comment by mfn** [comment]
Afaik the fundamental issue here is, it's not "defined" what should exactly be sent over HTTP (i,e, which code). There's no standard for it.

You might be interested in https://github.com/APIs-guru/graphql-over-http though

**Comment by OssiPesonen** [comment]
Well we can control HTTP codes depending on what kind of exception is thrown from a resolver, for example 403 Forbidden, but because the Error constructor passes a statuscode 0 to Exception class constructor, which it extends, it will always return 0. So we have to read the status from the category information. This is not a major issue and only concerns the HTTP protocol, but I still don't see why the status code is set to 0 in the first place when it could have come from the exception being thrown?

**Comment by simPod** [comment]
The Error is HTTP agnostic so it should not know about any HTTP status codes IMO. While it might make sense in your use case, in others it might not. 0 is default value so I guess that's the reason.

**Comment by OssiPesonen** [comment]
So it was about not being opinionated on the protocol. I am closing this issue. Thank you for your responses!
