### ISSUE TITLE
Detecting unused "variable values" in input?

### ISSUE THREAD

**Issue by mfn** [webonyx/graphql-php#615]
I recently had a bug in an application where I provided a variable value as input which wasn't consumed though => it was a typo and the (real) variable in question was nullable, thus there was no immediate GraphQL error.

Is there a way to detect "unused" variable values?

To give an example, this test:
```php
    public function testAllowsNullableInputsToBeSetToAValueInAVariable() : void
    {
        $doc      = '
      query SetsNullable($value: String) {
        fieldWithNullableStringInput(input: $value)
      }
        ';
        $result   = $this->executeQuery($doc, ['value' => 'a']);
        $expected = ['data' => ['fieldWithNullableStringInput' => '"a"']];
        self::assertEquals($expected, $result->toArray());
    }
```
if I modify it:
```diff
diff --git a/tests/Executor/VariablesTest.php b/tests/Executor/VariablesTest.php
index a2d698b..74c71f7 100644
--- a/tests/Executor/VariablesTest.php
+++ b/tests/Executor/VariablesTest.php
@@ -551,7 +551,7 @@ class VariablesTest extends TestCase
         fieldWithNullableStringInput(input: $value)
       }
         ';
-        $result   = $this->executeQuery($doc, ['value' => 'a']);
+        $result   = $this->executeQuery($doc, ['value' => 'a', 'foo' => 'bar']);
         $expected = ['data' => ['fieldWithNullableStringInput' => '"a"']];
         self::assertEquals($expected, $result->toArray());
     }
```
then there's no error/warning/etc that `foo` is not being used.

thanks!

**Comment by vladar** [comment]
Good question. It makes sense to add as a feature request I guess. Technically shouldn't be that hard to implement in the userland too. You just need to parse your query and then check the list of variable names in AST against your array keys.

Feel free to submit a PR if you decided to tackle it!

**Comment by mfn** [comment]
> You just need to parse your query and then check the list of variable names in AST against your array keys.

Ugh. Feels a bit out of my league TBH 😄 

But thanks for acknowledging the usefulness. Not sure if I can cook up something though.

**Comment by vladar** [comment]
It is not that hard. Use something like this as a reference:

```php
use GraphQL\Language\Parser;
use GraphQL\Language\OperationDefinitionNode;

$document = Praser::parse($queryString);
foreach ($document->definitions as $definition) {
  if ($definition instanceof OperationDefinitionNode) {
    // here is a list of all query variables which you can match against your $variables:
    $definition->variableDefinitions;
  }
}

$result = GraphQL::executeQuery(
    $schema,
    $document // just pass the document in place of $queryString
);
```

I am closing this for now but feel free to re-open if you want to work on this utility.
