### ISSUE TITLE
How can I add schema directives?

### ISSUE THREAD

**Issue by codler** [webonyx/graphql-php#617]
I like to create Enforcing access permissions as described here, so I can do Authorization and ACL
https://www.apollographql.com/docs/graphql-tools/schema-directives/#enforcing-access-permissions
I cant find anything in the documentation

**Comment by vladar** [comment]
You should be able to use directives the same way in SDL (see [this example from tests](https://github.com/webonyx/graphql-php/blob/master/tests/Language/schema-kitchen-sink.graphql) - at the very bottom). Those directives should be available on type instance via `$type->astNode` or `$type->extensionASTNodes` (if type was extended).

**Comment by Tyler-Gauch** [comment]
@vladar How can you use schema directives from php when extending ObjectType. Do I need to pass an extension/ASTNode in the `$config`?

**Comment by mwijngaard** [comment]
@Tyler-Gauch directives are not intended to be used this way, see: https://github.com/graphql/graphql-js/pull/746#issuecomment-301554231 . You can inject your own metadata into the config object for tracking runtime information.

**Comment by vladar** [comment]
@mwijngaard You are right. We will also add `extensions` feature in one of the next versions. But for now, just use a custom config. It still makes sense to keep custom metadata under `extensions` config key.

Closing this but feel free to re-open if you want to continue the discussion.
