### ISSUE TITLE
How to fill current user into context?

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#618]
I'm using the StandardServer. Now I need to handle authentication and authorization. I figured that my field resolvers should most likely get some info about currently authenticated user in `$context` and perform the related authorization. it is also confirmed in your [documentation](https://webonyx.github.io/graphql-php/executing-queries/#server-configuration-options) that context should be used for this purpose.

My question is how do I get this information from where I call `$this->server->executeRequest($operation);` to the callback I pass to `ServerConfig::setContext()`?

The solution is obviously the `OperationParams` object since I create it right before calling `executeRequest` and it is passed to the context callback. But where exactly in the `OperationParams` should this be? I'm guessing `$extensions`? Something like this? Any convention how I should or shouldn't use the extensions array?

```php
$user = $this->authenticator->authenticateUser($request);
$content = $request->getContent();
$queryData = json_decode($content, true);
// error handling
$queryData['extensions']['__authentication'] = $user;
$operation = OperationParams::create($queryData);
$result = $this->server->executeRequest($operation);

...

$config = ServerConfig::create();
$config->...
$config->setContext(
	function (OperationParams $params, DocumentNode $doc, string $operationType) {
		$user = $params->extensions['__authentication'];
		// create and return context value with $user.
	}
);
return new StandardServer($config);
```

As you can see I mostly solved it. Just asking if this is the "best practice" how to get the current user to the field resolvers.

**Comment by vladar** [comment]
In most cases you don't even need to use a Closure:

```php
$user = $this->authenticator->authenticateUser($request);
$context->user = $user;
$config->setContext($context);
```

A closure is useful only if your context depends on the query. But even then you can just `use` for closure:

```php
$user = $this->authenticator->authenticateUser($request);
$context->user = $user;
$config->setContext(
    function (
        OperationParams $params,
        DocumentNode $doc,
        string $operationType
    ) use ($context) {
        $context->propertyDependingOnQuery = $watever;
        return $context;
    }
);
```

Does it help?

**Comment by enumag** [comment]
Not at all, I'm running the server inside an event loop (using Amphp) which means the StandardServer instance is created way sooner than a request comes and it will need process many requests, possibly even at the same time. So I certainly can't call `$config->setContext()` based on the request data.

**Comment by vladar** [comment]
Oh I see. The `StandardServer` was written with the standard PHP environment in mind 😬 But it uses a [Helper](https://github.com/webonyx/graphql-php/blob/master/src/Server/Helper.php) class under the hood which does most of the work.

The idea was that people in non-standard environments could re-use parts of the standard flow via Helper and define their own pieces of logic when needed. I'd suggest looking at this class and maybe adding changes that would make things easier for your case in a PR.

**Comment by enumag** [comment]
Actually the StandardServer works just fine for me. The only thing is that any metadata the request has (such as the authenticated user) need to be part of the `$result = $this->server->executeRequest($operation);` call, which means they need to be inside the Operation object (or so I think anyway...).

As I wrote above, using the `['extensions']` part of Operation works just fine for this. I just wasn't entirely sure if this is correct usage since it isn't exactly documented anywhere. But yeah it works fine...

If the `'extensions'` key is meant for something different than maybe we should add `'metadata'` key to the Operations object?

**Comment by enumag** [comment]
Ah I see... I could call `Helper::executeOperation($config, $operation)` instead and use different $config for every call. But... I really think the configuration should be one-time setup and metadata better be part of the `OperationParams` so I like my current solution better than using Helper directly.

**Comment by vladar** [comment]
For a bit more context - here is how `extensions` appeared in the code: #413 Technically they are coming from clients but I guess you can use them for your case (just make sure that users can't override your extensions via query/post params).

**Comment by enumag** [comment]
I see, I guess I'll use something like `['extensions']['metadata']['currentUser']` and make sure to `unset($queryData['extensions']['metadata'])` to prevent possible security issues. Thanks for your feedback!
