### ISSUE TITLE
Allow defining types using name

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#62]
Allow following definition form (in addition to existing):

``` php
'fields' => [
   'id' => 'Id!',
   'author' => 'User',
   'mentions' => '[Mention!]',
   'totalCommentCount' => 'Int',
   'comments' => [
       'type' =>'[Comment!]',
       'args' => [
           'after' => [
               'type' => 'Id',
               'description' => 'Load all comments listed after given comment ID'
           ],
           'limit' => [
               'type' => 'Int',
               'defaultValue' => 5
           ]
       ]
    ]
];
```

It opens up path to schema serialization and constant arrays for schema definitions, which may be useful for future optimizations. Also it opens up path to defining schema using [GraphQL schema language](http://graphql.org/learn/schema/#type-language).

Obviously actual loading of type by name has to be delegated to user-land code (will likely add new option to schema constructor for type resolver).

Should be BC.

**Comment by rudiedirkx** [comment]
I'm afraid that will be very slow. Seems like a lot of parsing before even parsing the query, and then executing it. Serialization is especially useful if it skips the expensive part, but serializing this wouldn't skip the expensive part (parsing it).

Maybe there's a readable in-between solution: define a factory and accept string types.

This format is fantastic in JS because you can `comments: [CommentType]` and `names: [String]`, because JS types are variables, but PHP doesn't have that, so maybe the schema syntax shouldn't try.

(I'm mostly interested in speed, not configuration ease or prettiness.)

**Comment by mcg-web** [comment]
Hi we using a [generator](https://github.com/overblog/GraphQLPhpGenerator) that look like what you want to do @vladar but it compile php classes behind the scene for performance issue :D.

**Comment by vladar** [comment]
I plan to work on performance improvements. 
In general the plan is to release new docs + version 1.0 then work on performance improvements for 1.1.

As for this proposal - it might have different advantage for future. PHP 5.6+ has constant arrays. They are stored in byte-code cache together with class definition. So a) PHP doesn't need to parse these arrays on every request b) they are stored in shared memory (basically it is the only way to share something as variable between requests in PHP, without using `serialization/deserializtion`).

As for performance penalty for creating whole schema on each request - I am researching ways to avoid it. Actually it is clear now that it is possible with some relaxed validation and minor modifications to type resolution in schema.

The main problem here is that the only way to get all interface implementors in static time is by scanning all object types and comparing if it implements some interface. Disabling validation rules that call this logic should do the work (+several Schema tweaks...).

Alternatively I've been thinking about adding `implementors` option to interfaces to avoid this problem alltogether (see #40), but it might be actually evil to do if you have such definition in two places (ObjectType `interfaces` or InterfaceType `implementors`), so need to consider this carefully.

**Comment by rudiedirkx** [comment]
I didn't mean PHP parsing the array. I bet that's fast. I mean your code has to parse the array. It has to parse `'[Mention!]'` and `'Id'` and there will be **many** of those. Every ms it's parsing and not yet executing is a waste. I'm very curious to see the performance difference.

My current (not big) schema takes 10-11 ms to init, and only then does it start parsing the query and executing it. I've tried a few different libraries and methods and this one's the fastest, done like in the README, with `use (&$humanType, &$droidType)` etc.

**Comment by intellix** [comment]
Actually, why should the schema be defined as an array? I'm looking at defining types as string to use for mocking in the front-end and was searching for the ability to parse that in our graphql-php implementation to allow sharing the schema. Take a look at this: https://github.com/apollostack/graphql-tools

**Comment by vladar** [comment]
@intellix Those two things are not related. 

Ability to define schema as array is desirable for performance. Even if you define your schema using GraphQL schema language you must still parse it and represent as PHP value.

Some people prefer to avoid parsing overhead to get best performance.

As for GraphQL schema language - we do have parser for it (see https://github.com/webonyx/graphql-php/blob/master/tests/Language/SchemaParserTest.php), but it only produces AST. One step is missing - to recreate actual type definitions from this AST.

Right now this step is hard to implement in generic way (due to `resolve`, `resolveType` handlers and some other things), but you can write glue code for your own projects which will transform such ASTs to actual type definitions.

**Comment by vladar** [comment]
This feature requires more efforts than provides benefits.

**Comment by rudiedirkx** [comment]
What's the current/dev best way to define a schema? Still everything in one place with many closures?, or have I missed a cool new feature in the meantine?

**Comment by vladar** [comment]
@rudiedirkx There are couple other options:

1. Using doctrine annotations (experimental projects [here](https://github.com/rahuljayaraman/doctrine-graphql) and [here](https://github.com/Ecodev/graphql-doctrine)).

2. Using GraphQL [type language](http://graphql.org/learn/schema/#type-language). Not documented yet, but simple example is available [here](https://github.com/webonyx/graphql-php/tree/master/examples/02-shorthand).

3. You never had to define everything in one place. [This example](https://github.com/webonyx/graphql-php/tree/master/examples/01-blog) shows how you can split types to files.
