### ISSUE TITLE
SchemaPrinter - order of fields

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#628]
In my application I'm using `SchemaPrinter::doPrint($this->schema);` to generate the schema for the front-end part of our application.

Between two releases of the back-end API there were some schema changes and when we commit the new schema in front-end we see these changes.

However the diff also contains some changes that are not relevant - some objects have the order of their fields changed. I'm not aware of making any changes that would cause this so I'm not sure why it happened. Could the SchemaPrinter order the fields alphabetically or something to make sure the order is deterministic and stays the same?

**Comment by enumag** [comment]
I think it was a problem on my side.

**Comment by vladar** [comment]
Reference implementation has [a tool](https://github.com/graphql/graphql-js/blob/master/src/utilities/lexicographicSortSchema.js) for lexicographic schema sorting.

We don't have it yet so PR is very welcome!
