### ISSUE TITLE
Type name is null in introspection when using Type::listOf

### ISSUE THREAD

**Issue by dmongeau** [webonyx/graphql-php#63]
As described in the issue Folkloreatelier/laravel-graphql#50 the type name is null when using listOf.

Query:

```
{  
  __type(name: "User") { 
    name 
    fields { 
      name 
      type { 
        name 
      } 
    } 
  } 
}
```

Response:

```json
{
  "data":{
    "__type":{
      "name": "User",
      "fields":[
        {"name": "followings", "type":{"name": null }},
      ]
    }
  }
}
```

I suspect this is because `public $name` is not set in the ListOfType. It may be setted in the constructor. I can submit a pull request if it makes sense.

**Comment by vladar** [comment]
It is not a bug. ListOf and NonNullType are not named types (their name is `null`). Instead wrapped type is stored in `ofType` field.

Change your query to:
```
{  
  __type(name: "User") { 
    name 
    fields { 
      name 
      type { 
        name 
        ofType {
          name
        }
      } 
    } 
  } 
}
```
and you will see what I mean.

If you try `graphql-js` at http://graphql-swapi.parseapp.com/ and run the same query against any type containing `nonNull` or `listOf` field - it will return the same result.

Also I am curious where do you use this?

**Comment by dmongeau** [comment]
Ok I understand, sorry about that! Actually, it's not coming from me. Someone as filled an issue on laravel-graphql.

**Comment by vladar** [comment]
No problem! %)
