### ISSUE TITLE
Introduce query plan as a replacement for ResolveInfo::getFieldSelection

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#65]
Currently we have `ResolveInfo::getFieldSelection()` to do simple look-aheads. But it is too limited for real-world scenarios and provides little help when resolving field of union or interface type. Better tool has to address more use-cases. Basically it should provide convenient interface to answer following questions:

1. What sub-fields were requested (regardless of fragment types)? 
2. What types were referenced by fragments?
3. What sub-fields were requested for given type?
4. What args/directives were set for given field?

Current `getFieldSelection` only answers question 1. 

The syntax for this could be something like this:
```php
function resolve($value, $args, $context, ResolveInfo $info) {
    $queryPlan = $info->lookAhead();

    // Answers #1:
    $fields = $queryPlan->subFields();
    $deepFieldRequested = $queryPlan->has(['nested', 'deeper', 'evenDeeper']);

    // Answers #2:
    $types = $queryPlan->referencedTypes();

    // Answers #3:
    $typeSpecificFields = $queryPlan->subFields('TypeReferencedByFragment');
}
```

This needs further design with regards to nested syntax + things may get quite complicated for type-dependent deep fields.

**Comment by decebal** [comment]
@vladar I had to write a wrapper around `ResolveInfo` In my use case that answers  #4 in a similar way `foldSelectionSet` does.

**Comment by decebal** [comment]
@vladar sure thing, I'll do the pull request asap (this week), while I really need to start working on this for my project as it currently has some only hacks in order to cover for missing type definitions in resolveInfo
