### ISSUE TITLE
NamedTypeNode#name should be of type NameNode (?)

### ISSUE THREAD

**Issue by simPod** [webonyx/graphql-php#655]
Merged in https://github.com/webonyx/graphql-php/pull/647 we introduced type for `NamedTypeNode#name` as `NameNode|string` (was `string` before).

Another context is in this discussion with @shmax https://github.com/webonyx/graphql-php/pull/645#discussion_r411432617

I'd vote for constraining it to the `NameNode` only, dropping the `string` type.

**Comment by shmax** [comment]
Did you read my analysis of the situation? The type **is** legitimately both a `string` and a `NamneNode` at different times. It's weird and probably some kind of unintended flaw that never got noticed, but it is consistent with the reference library (which also incorrectly annotates it as a `NameNode`. If you change it back to a `NameNode`, you will (rightly) get complaints from PHPStan.

**Comment by simPod** [comment]
Yes, but I was rather wondering if we could simplify the code around it so we can safely use NameNode everywhere. I'm not sure yet if we need to follow reference implementation here or not.

**Comment by shmax** [comment]
You're talking about sorting out the runtime mechanics that write a string to `NamedTypeNode.Name`? Might be worth looking into, but that's a much more complex task than simply changing the annotation back to `NameNode`.

**Comment by simPod** [comment]
I might have not described it clearly but just changing the type hint is not a solution. I shall take a look into it.

**Comment by vladar** [comment]
Yeah, NamedTypeNode#name should be definitely of type NameNode.

We create it here:

https://github.com/webonyx/graphql-php/blob/ed8fb628ad20325aec2c9f99c451cc0eca8b7f53/src/Language/Parser.php#L1006-L1014

And `parseName` always returns `NameNode`. Annotation with `NameNode|string` is probably wrong. But then I am curious what usages rely on this being `string`. We should fix those.

**Comment by shmax** [comment]
It gets written with a string as part of [Visitor::visit](https://github.com/webonyx/graphql-php/blob/master/src/Language/Visitor.php#L283). The [same general sort of thing](https://github.com/graphql/graphql-js/blob/4150d1f51360a7981181cfec42a135394c7340f1/src/language/visitor.js#L274) happens in the reference library. So, if there's a bug, then we inherited it from them.

**Comment by spawnia** [comment]
Resolved as of https://github.com/webonyx/graphql-php/pull/697
