### ISSUE TITLE
ASTDefinitionBuilder description Trying to get property 'value' of non-object

### ISSUE THREAD

**Issue by mirro-orrim** [webonyx/graphql-php#660]
I recently updated from php 7.0 to 7.3 and "webonyx/graphql-php": "~0.10.0", to "^0.13.8"
because the break, continue 2 issue.
ASTDefinitionBuilder description
Documentation says description should be a string and it is! so what am I missing here?

I'm getting the error:
Trying to get property 'value' of non-object

ASTDefinitionBuilder line 102
Currently causing problems:
```php
        if ($node->description) {
            return $node->description->value;
        }
```
This modification works:
```php
     return $node->description;
```

**Comment by vladar** [comment]
This was a change in SDL format. See this notice in UPGRADE.md: https://github.com/webonyx/graphql-php/blob/master/UPGRADE.md#breaking-descriptions-in-comments-are-not-used-as-descriptions-by-default-anymore

Old:

```graphql
# Description
type Dog {
  ...
}
```

New:

```graphql
"Description"
type Dog {
  ...
}

"""
Long Description
"""
type Dog {
  ...
}
```
