### ISSUE TITLE
ID Input Coertion

### ISSUE THREAD

**Issue by enumag** [webonyx/graphql-php#663]
My application is using uuids everywhere. So far I've been using the ID type for them which is okay according to GraphQL spec.

The issue is that when the client gives me an invalid UUID (such as an empty string), my application fails with error 500 - without clear indication what went wrong.

According to [specification](https://spec.graphql.org/June2018/#sec-ID):

> When expected as an input type, any string (such as "4") or integer (such as 4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL server expects. Any other input value, including float input values (such as 4.0), must raise a query error indicating an incorrect type.

How can I validate the input and raise an appropriate query error?

**Comment by spawnia** [comment]
Use a [custom scalar type](https://webonyx.github.io/graphql-php/type-system/scalar-types/).

**Comment by enumag** [comment]
No. I want to stick with the ID type since the documentation states it's possible.

**Comment by spawnia** [comment]
> **any** string ... should be coerced ...

`''` is also a string. `graphql-php` is correct here, so i don't think this is an issue with the library.

My suggestion still holds, though. You should be able to overwrite the built-in type if you really want too.

**Comment by enumag** [comment]
I didn't say it was an issue with the library. I just don't know how to achieve what the documentation suggests so I'm asking for an advice.

Using a custom type is a different approach to solving the goal but not an answer to my question and therefore off topic here.

**Comment by enumag** [comment]
Oh... you meant to overwrite the default type. Hmm... not sure if that's possible 🤔

**Comment by vladar** [comment]
This is possible (exactly because of requests like this). Check this out for details: #401 (also related: #555). We'll need a better way eventually but existing workaround should unblock you for now.
