### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by numaquevedo** [webonyx/graphql-php#665]
Hello!

We have been using the library for a while and we recently hit a performance-related issue. Essentially a query is taking longer than 30 seconds and it is a simple select. It looks like:

`SELECT * FROM table WHERE (created >= timestamp AND created <= timestamp) AND anotherfield = 'VALUE' AND anotherfield2 IN (n1,n2,n3,n4...n500);`

All those columns are indexed but they are not being used because of the `*` in the SELECT. We created a composite index but it did not help.

I recently learned that MySQL has the option `FORCE INDEX(index_name)` that we could use in the query. We tried it and it executes under 1 second. I am wondering if:

- Is there is a way to add these kinds of options to the query generated by the library?
- Is there a way to intercept the query about to be executed, append these options and proceed with the execution?

Please advice.

Thanks in advance!

**Comment by spawnia** [comment]
You can use the fourth resolver argument `ResolveInfo` to get information about the current field selection: https://webonyx.github.io/graphql-php/reference/#graphqltypedefinitionresolveinfo

**Comment by numaquevedo** [comment]
> You can use the fourth resolver argument `ResolveInfo` to get information about the current field selection: https://webonyx.github.io/graphql-php/reference/#graphqltypedefinitionresolveinfo

@spawnia Is there a way to actually intercept the query that is going to be executed, and modify it?

**Comment by spawnia** [comment]
Don't know. That's a totally different question though and seems out of scope.

**Comment by mfn** [comment]
@numaquevedo the webonxy library has no SQL layer so you're already building the query on your own, no?

**Comment by vladar** [comment]
As @mfn correctly pointed out you control your SQL. This library doesn't generate any SQL for you. Maybe you are using some wrapper library built on top of it?

**Comment by numaquevedo** [comment]
You guys are right. I got the wrong idea initially and did not fully understand the library. Thanks to your help, I figured the issue out.
Closing this!
