### ISSUE TITLE
No error sent to Rollbar

### ISSUE THREAD

**Issue by djibarian** [webonyx/graphql-php#667]
When an error is raised from the query execution, even setting the `Debug::RETHROW_INTERNAL_EXCEPTIONS` or `Debug::RETHROW_UNSAFE_EXCEPTIONS`, the exception is catched in the outer loop but is not sent to Rollbar.

Is like Rollbar not liking the exception, because even logging it doesn’t work.

```
try{
   GraphQL::executeQuery(/* query */)->toArray(/* debug flags */);
}
catch(Exception $e){
  /* here the exception comes, as a PDOException in this case, so it looks like it is re-thrown properly */
  Rollbar::log(Level::ERROR, “this is sent”);
  Rollbar::log(Level::ERROR, $e); /* this is not */
}
```

Removing the catch, the error is not sent.

Generating the error outside the `executeQuery` call, the error is sent.

So, what’s the difference in `$e` if in both cases `get_class($e)` returns the same `PDOException`?

**Comment by vladar** [comment]
This doesn't sound like an issue with this library - exceptions are re-thrown and caught properly. Must be some problem with Rollbar.

It could have something to do with `PDOException` nuances with code. See this for more details: https://www.php.net/manual/en/class.pdoexception.php#95812

Closing this but feel free to re-open if you still think it relates to this library.
