### ISSUE TITLE
Some errors are not passed through error handler

### ISSUE THREAD

**Issue by Mutisz** [webonyx/graphql-php#668]
Errors created in `Helper::validateOperationParams` are not passed to custom error handler and error formatter. Instead they are returned directly from `Helper::promiseToExecuteOperation` . 

This seems to be incorrect behaviour. For example these errors will be omitted in any error logging done in custom error handler.

**Comment by vladar** [comment]
Hey, thanks for reporting. Can you share an example of what you mean?

**Comment by spawnia** [comment]
Closing due to lack of feedback.
