### ISSUE TITLE
custom scalar type with type language

### ISSUE THREAD

**Issue by surajpatta** [webonyx/graphql-php#672]
My schema looks as below
`scalar Email
schema {
 query: Query
}
type Query {
 users(email: Email!): User!
}
type User {
 name: String!
 email: Email!
}`
I have created the EmailType as per the documentation. I too have added it to the resolver
`$resolvers = [
 'Email' => new EmailType(),
 'Query' => ['users' => function($root, $args, $context, ResolveInfo $info) {
   return ['name'=>'John Doe', 'email'=>'johndoe@example.com'];
 }],
];`
But this custom type is not working when using only GraphQL type language.

**Comment by spawnia** [comment]
I don't see how the problem you are having shows a bug within this library.

Have a look at the examples to find out how to build a working server: https://github.com/webonyx/graphql-php/tree/master/examples
