### ISSUE TITLE
Looking for advise on implementation design for GraphQL in PHP

### ISSUE THREAD

**Issue by jchariot** [webonyx/graphql-php#677]
I have been developing REST API in PHP for a long while now, but now I am trying out GraphQL. I am trying to understand how I should implement GraphQL in PHP for a bigger project. 

The code below is basically from the example code, and I simply modified the "resolve" part of the field to create an object that fetches data from the database.

```
<?php
require_once 'vendor/autoload.php';

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Schema;
use GraphQL\GraphQL;

try {
	
    $queryType = new ObjectType([
        'name' => 'Query',
        'fields' => [
			'listAllUsers' => [
                'type' => Type::string(),
                'args' => [
					'nothing' => ['type' => Type::string()]
                ],
                'resolve' => function ($rootValue, $args) {
					require_once 'models/DB_userCollection.php';
					$obj = new userDatabase();
					return $obj->getCollection();
                }
            ],
        ],
    ]);

    $schema = new Schema([
        'query' => $queryType,
    ]);

    $rawInput = file_get_contents('php://input');
    $input = json_decode($rawInput, true);
    $query = $input['query'];
    $variableValues = isset($input['variables']) ? $input['variables'] : null;

    $rootValue = null;
    $result = GraphQL::executeQuery($schema, $query, $rootValue, null, $variableValues);
    $output = $result->toArray();
} catch (\Exception $e) {
    $output = [
        'error' => [
            'message' => $e->getMessage()
        ]
    ];
}
header('Content-Type: application/json; charset=UTF-8');
echo json_encode($output);

?>
```

The code above works fine, and I keep on adding the fields and things work fine for a small project. But if I have a database that has multiple collections, say 20 collection. Each collection then has the regular CRUD (Create, Read, Update, Delete), so this means 80 fields is required. A single PHP file with all 80 fields will get quite long. 

So usually how do we do this? How can I make it so that all the fields and such are on other PHP files instead? What is the preferred method here, so that the size of the entry point file here stays the same?

**Comment by spawnia** [comment]
This library does not offer a blessed solution for this, it is rather meant to be a solid base upon which further abstractions can be built.

My advice is to look for a framework that builds atop this library, see https://webonyx.github.io/graphql-php/complementary-tools/

Personally, i use (and maintain) https://github.com/nuwave/lighthouse.
