### ISSUE TITLE
not getting args passed to nested fields

### ISSUE THREAD

**Issue by dadamssg** [webonyx/graphql-php#678]
I cannot figure out how to pass arguments to nested fields. My `args` get correctly assigned to the top most level but are nowhere to be found when passed to a  nested field.

I have this query:

```graphql
query SearchOpportunities($filter: ListFilter $pagination: Pagination $taskFilter: ListFilter $taskPagination: Pagination) {
  opportunities(filter: $filter pagination: $pagination) {
    nodes {
     	description
      grossrevenue
      priornotes
      company {
        companyname
        accountmanager {
          firstname
        }
      }
      tasks(filter: $taskFilter pagination: $taskPagination) {
        nodes {
          subject
        }
      }
    }
    meta {
      page
      pageSize
      resultSetCount
    }
  }
}
```

And these variables:

```json
{
  "pagination": {
    "page": 1,
    "pageSize": 20
  },
  "filter": {
    "name": "cmpy_universalid",
    "comparator": "is not blank",
    "values": []
  },
  "taskPagination": {
    "page": 1,
    "pageSize": 20
  },
  "taskFilter": {
    "name": "source_universalid",
    "comparator": "is not blank",
    "values": []
  }
}
```

This is on my `Opportunity` type:
![image](https://user-images.githubusercontent.com/881986/85333824-df74e080-b49f-11ea-9907-d9cb9923ad5b.png)

I've also tried removing the `resolve` on the `tasks` field definition and adding a `resolveField` to the `Opportunity` type:
![image](https://user-images.githubusercontent.com/881986/85334310-a5580e80-b4a0-11ea-903d-3fdb45823133.png)

The types coming  from `$container['graphql.schema.list_filter']` and `$container['graphql.schema.pagination']` are both `InputObjectType`s  and are correctly passed to the top  level `opportunities` query.

**Comment by vladar** [comment]
Ideally, we need some reproduction project to debug this. Can you replicate this problem with the simplest possible local schema?

But we can also try debugging this remotely.

1. Please provide your schema SDL for those types (i.e. are there any interfaces involved?) 
2. Can you show the full stack trace of your resolver?
3. Can you show the full contents of `$info (GraphQL\Type\Definition\ResolveInfo)` variable?
4. What result do you get with this query?

**Comment by vladar** [comment]
Oh, and which version do you use? :)

**Comment by dadamssg** [comment]
Went through the exercise of creating a minimum reproducible example and it behaved as  i expected. Traced through the code and forgot that my coworker implemented a middleware in our app that normalizes all json keys to lowercase in payloads. The camelcase variables in the query weren't getting matched up with the variables that were getting converted to lowercase. Ugh, that was a waste of time. Sorry!

Oh an congrats on the new release!

**Comment by vladar** [comment]
Thanks! Glad that you've figured it out!
