### ISSUE TITLE
How to tackle relay connection, pagination, etc

### ISSUE THREAD

**Issue by leemason** [webonyx/graphql-php#68]
As the title suggests, any ideas here?

Im almost at a loss at where to start, im using the laravel wrapper package, but neither this or the laravel project reference connection types, or how you would go about creating them?

Im guessing i could do it through the type system, but wanted to check if ive missed some docs somehwere that could help me out.

**Comment by mcg-web** [comment]
Have you try to use [nuwave/laravel-graphql-relay](https://github.com/nuwave/laravel-graphql-relay)?

**Comment by vladar** [comment]
I am not aware about laravel package details, but there is separate project https://github.com/ivome/graphql-relay-php for integration with Relay (it is referenced in Complementary tools section in README)

**Comment by vladar** [comment]
Closing this. But feel free to re-open if that didn't help %)

**Comment by leemason** [comment]
thanks for the info, yes those resoures helped alot, i havent used them, but they have shown me the way to getting it all working. thanks again.
