### ISSUE TITLE
Semver?

### ISSUE THREAD

**Issue by alanpoulain** [webonyx/graphql-php#680]
Hello,
The new release (v14.0.0) has suddenly changed the semantic versioning (previous version was v0.13.8) from an initial development version to a major version.
Is it wanted?

**Comment by spawnia** [comment]
This matches the versioning of the reference implementation and is intended: https://github.com/graphql/graphql-js/tags?after=v14.0.0

**Comment by alanpoulain** [comment]
OK thanks for the answer.
