### ISSUE TITLE
Using custom scalar types fails in isTypeSubTypeOf

### ISSUE THREAD

**Issue by brunobg** [webonyx/graphql-php#683]
I think I found a bug, related to the workaround in https://github.com/webonyx/graphql-php/issues/681#issuecomment-650187470. 

What I'm doing? Executing this query:

```graphql
query q($input: TestScalarType) {
      fieldWithScalarInput(input: $input)
}
```

`TestScalarType` is a `class TestScalarType extends ScalarType` that is registered according to the workaround in the comment linked above. Schema is below.

```graphql
scalar TestScalarType @scalar(class: "ModelariumTests\\TestScalarType")

schema {
  query: TestType
}

input TestInputObject {
  t: TestScalarType
}

type TestType {
  fieldWithObjectInput(input: TestInputObject): String
  fieldWithNullableStringInput(input: String): String
  fieldWithNonNullableStringInput(input: String!): String
  fieldWithScalarInput(input: TestScalarType): TestScalarType
}
```

Running:

```php
GraphQL::executeQuery($schema, $query, null, null, 'input' => 'valid');
```

Returns an error:

```
class GraphQL\Error\Error#692 (15) {
  public $message =>
  string(92) "Variable "$input" of type "TestScalarType" used in position expecting type "TestScalarType"."
```

apparently this is caused by this:

```php
    public static function isTypeSubTypeOf(Schema $schema, $maybeSubType, $superType)
    {
        // Equivalent type is a valid subtype
        if ($maybeSubType === $superType) {
            return true;
        }
``` 

$maybeSubType is a `MyOwnScalar` and $superType is a CustomScalarType. Perhaps the comparison should be `instanceof` instead of equality? Or am I missing something?

I can submit the entire testcase if desired.

**Comment by vladar** [comment]
Yeah, the full test case would be great, thanks!

**Comment by brunobg** [comment]
Reproduced here: https://github.com/Corollarium/modelarium/blob/d965a19468cf7aad8dd623041f1fa57a64a3daba/tests/Unit/ScalarExtendTest.php#L101

If you want me to isolate in a PR here let me know. I can send the fix too -- `instanceof` comparison works.

**Comment by vladar** [comment]
This means that there are two different instances of the same type in the schema which shouldn't happen. Using `instanceof` would be a workaround for this but not a fix. A good fix should guarantee the only instance (so that `===` works there).

**Comment by brunobg** [comment]
Well, but your suggestion leads to multiple instances, since it will call `new`:

```
$schema->getConfig()->typeLoader = function($typeName) use ($originalTypeLoader) {
    $type = $originalTypeLoader($typeName);
    if ($type instanceof \GraphQL\Type\Definition\CustomScalarType) {
        $directives = $type->astNode->directives;
        // Look for your `@scalar` directive in $directives and return your custom class instead
        $customClass = findMyScalarClassName($directives);
        return new $customClass($type->config);
    }
    return $type;
}
```

**Comment by vladar** [comment]
I mean there shouldn't be two instances of the same type within one schema (of course you can create multiple instances of a type as long as they are not both added to the same schema).
