### ISSUE TITLE
Parser::__callStatic is incorrectly typed

### ISSUE THREAD

**Issue by unclecheese** [webonyx/graphql-php#698]
Many of the `parseXXX` methods that `Parser::__callStatic()` maps to return `NodeList`, which is incompatible with its  `Node` return type.

`Parser::argumentsDefinition()` for instance, throws a `TypeError`.

There doesn't appear to be a great way to solve this without breaking the API. Best solution is probably to make `public static` counterparts to these methods so they avoid `__callStatic()`.

**Comment by spawnia** [comment]
Nice to see someone actually use the partial parse functions.

Converting them to non-magical methods would definitely be the way to go, but involves an unfortunate amount of boilerplate and typing. Something for a rainy, uninspired weekend.
