### ISSUE TITLE
Expose version in GraphQL class

### ISSUE THREAD

**Issue by mcg-web** [webonyx/graphql-php#700]
Hi since this lib is a requirement to a lot of projects and libs, it will be very useful to make the differences between two version easily.  This change will ask a minor effort to this lib but will ease dependents maintenance works. [Symfony does this like that](https://github.com/symfony/http-kernel/blob/master/Kernel.php#L76-L84). I can make the changes if its ok for you.

**Comment by spawnia** [comment]
The way symfony does it seems a bit tedious, maybe a slimmed down version with some helpers would be sufficient too.

```php
const VERSION = '14.0.1';

public static function majorVersion(): int
{
    return explode(self::VERSION, '.')[0];
}

...
```

**Comment by mcg-web** [comment]
Yes I agree Symfony way of doing is complex for the need. Your helper seems to enough to answer to the need.

**Comment by vladar** [comment]
Maybe you could use https://github.com/Ocramius/PackageVersions instead? Maintaining version number warrants a process and tooling around releases. I am not sure that we should introduce those when there is a known workaround?

**Comment by mcg-web** [comment]
Thank you @vladar I'll give this one a look but like this lib, limiting dependencies usage is also a requirement.

**Comment by mcg-web** [comment]
Ok the package is fully answering to my need. Thank @vladar and @spawnia !
