### ISSUE TITLE
Major and minor version error

### ISSUE THREAD

**Issue by SuddenlyRust** [webonyx/graphql-php#703]
I think there is an mistake here. We jumped from version [0.13.9](https://github.com/webonyx/graphql-php/releases/tag/v0.13.9) to [14.0.1](https://github.com/webonyx/graphql-php/releases/tag/v14.0.1) could someone look into that? Or is this intended?

![image](https://user-images.githubusercontent.com/14092921/87300246-cfd04100-c50d-11ea-9fb7-5b4c65b6ab7e.png)

**Comment by spawnia** [comment]
Duplicate of https://github.com/webonyx/graphql-php/issues/680
