### ISSUE TITLE
Why are error results thrown?

### ISSUE THREAD

**Issue by inceddy** [webonyx/graphql-php#704]
In my current application I have a fixed number of common exceptions that might occure while resolving a mutation.
To handle this scenario I have created a UnionType combining the expected ObjectResultType and several ErrorResultTypes.
I thought I could catch the exceptions in a try-catch block within the resolver and then pass them down to resolveType, but unexpectedly Throwable results are [thrown again](https://github.com/webonyx/graphql-php/blob/0ccc99ee0ec4be51ba54abfd1059089a7b697cbb/src/Executor/ReferenceExecutor.php#L737) .

Why is this behaviour important?

**Comment by spawnia** [comment]
That behaviour seems like it might be a leftover from porting the `graphql-js` reference implementation. There, resolving fields is usually done async inside of a `Promise`. There is some weirdness when throwing in `async` functions, so this might mechanism might be there to smooth things over.

I tried to disable the re-throwing and found that it causes 21 tests to fail.

**Comment by inceddy** [comment]
Ok seems to be something deeply nested within `graphql-php`. I'll find another solution, but stumbling across this behavior made me curious.

**Comment by vladar** [comment]
Yeah, you can return exceptions from resolvers, not just throw them. 

> Why is this behaviour important?

There are several use-cases where this is useful. One is when you use lists:

```php
"resolve" => function () {
    return [
        "item1",
        new MyException("Error with item2"),
        "item3",
    ];
}
```
see also https://github.com/webonyx/graphql-php/issues/374#issuecomment-433014872

The other is when some parent resolver decides that a field must be an error:

```php
"resolve" => function () {
    return [
        'title' => 'My Title',
        'secureContent' => new MyException("You can't read this"),
    ];
}
```

I guess you could just wrap your custom exceptions to work around this OR use a non-throwable class for such errors.

Closing this as answered but feel free to follow-up if you have questions.
