### ISSUE TITLE
What happened here with versioning?

### ISSUE THREAD

**Issue by jacor84** [webonyx/graphql-php#707]
Hi. Just a quick question for @vladar: why the release after v0.13.9 was v14.0.1 and not v0.14.1? Was it by mistake or because of compatibility breaks? But then why not v1.0? :smiley:

**Comment by mfn** [comment]
https://github.com/webonyx/graphql-php/issues/703
https://github.com/webonyx/graphql-php/issues/680

**Comment by jacor84** [comment]
Thanks!
