### ISSUE TITLE
Is it possbie to take the fields collector out of the ReferenceExecutor ?

### ISSUE THREAD

**Issue by glickel** [webonyx/graphql-php#727]
Hi,
to be able to create our own executor without coping / pasting a lot of code from ReferenceExecutor, is it possible to take the fields collector out of the ReferenceExecutor ?
I'm taling about the two methods `collectFields` and `collectSubFields`.

My skills and experience do not allow me to predict the bad impacts on the API exposed by this librairy. That's why I'm asking you. 
Nevertheless, if you consider it possible and relevant to do so, I can create the PR.

**Comment by vladar** [comment]
I don't think it is a reasonable thing to do. Those methods are implementation details. Exposing them to the public will increase the API surface and make maintenance harder (as now changes to those methods can't be breaking).

At the moment I am strictly opposed to any changes increasing maintenance costs for this library.
