### ISSUE TITLE
Allow interfaces to implement other interfaces

### ISSUE THREAD

**Issue by Kingdutch** [webonyx/graphql-php#728]
v15 of graphql-js implemented an addition to the GraphQL spec which allows interfaces to implement other interfaces. It would be nice to be able to do this in PHP as well. For example when there is a generic Node interface and a specialised Media Node type needs to be created for images, videos, etc.

graphql-js implementation: https://github.com/graphql/graphql-js/pull/2084
spec addition: https://github.com/graphql/graphql-spec/pull/373

Article on why this is useful: https://dev.to/mikemarcacci/intermediate-interfaces-generic-utility-types-in-graphql-50e8

The following GraphQL schema snippet currently doesn't parse but would be expected to parse after implementation.

```gql
interface Node {
  uuid: ID!
}

interface Media implements Node {
  uuid: ID!
  url: String!
}

type Image implements Media & Node {
  uuid: ID!
  url: String!
}
```

**Comment by spawnia** [comment]
A PR for this would certainly be welcome.

I am on the fence about this counting as a breaking change. Using the feature in the schema definitely can break clients who do not know how to deal with this spec addition.

Depending on the implementation this might be non-breaking as in: users of this package can upgrade and all their code will still work.

**Comment by vladar** [comment]
This will be a part of the 15.0 release as it is indeed breaking. I am going to prepare a roadmap for 15.0 with a list of issues/tasks to guide anyone willing to contribute (no ETA though).

**Comment by Kingdutch** [comment]
`BuildClientSchema::testLegacySupportForInterfacesWithNullAsInterfacesField` is part of making sure this change is backwards compatible : )  From what I can tell, the public API also hasn't changed. So pending a maintainer review I think this should be able to land in a minor version.

The only thing I can come up with is if people made their own classes to implement types that do not extend `ObjectType` or `InterfaceType` but should support implementing interfaces. Those custom classes should implement the `ImplementingInterface` interface (which both `ObjectType` and `InterfaceType` do in the PR). I don't really see a use-case for this though as the library assumes specific types in many locations.
