### ISSUE TITLE
SchemaPrinter is not extendable

### ISSUE THREAD

**Issue by kurzyx** [webonyx/graphql-php#729]
Hi,

A while back [a PR was accepted](https://github.com/webonyx/graphql-php/pull/671) that changed the private methods in the SchemaPrinter class to protected. This would allow for extending the SchemaPrinter class.

However, all method calls within this class still use `self::`, so late static binding does not work resulting in the class not being extendable.

Am I missing something?

**Comment by spawnia** [comment]
No, changing to `static` seems sensible.

**Comment by kurzyx** [comment]
Seems that this was fixed in https://github.com/webonyx/graphql-php/pull/747.
