### ISSUE TITLE
CustomScalar usage as resolvers

### ISSUE THREAD

**Issue by mathieutu** [webonyx/graphql-php#732]
Hi, 
I use a Type language schema, and I'm trying to implement custom scalar resolving.

In the graphqljs implementation, the custom scalar type is just a standard resolver like for other types, but it doesn't seem to be the case in graphql-php.

I've seen a [previous issue](https://github.com/webonyx/graphql-php/issues/173) that @vladar said to use the `typeConfigDecorator` option, and to handle it by hand.

I actually don't understand why this can't be considerated like a standard resolver, this should simplify the process, and this follow the graphqljs api.

Thanks.

Some links about that:
https://uptoskill.com/graphql-custom-scalars/
https://www.apollographql.com/docs/apollo-server/schema/scalars-enums/#date-as-a-scalar
https://www.graphql-tools.com/docs/scalars/

**Comment by spawnia** [comment]
Types are just something else then resolvers, even in GraphQL. I see how the example in https://uptoskill.com/graphql-custom-scalars/ would be misleading you into thinking that - they have confusing variable naming. Their variable `resolvers` should really be called `types`.

That said, you can use custom scalars with SDL, as mentioned.
