### ISSUE TITLE
`GraphQL::setPromiseAdapter()` considered deprecated?

### ISSUE THREAD

**Issue by vhenzl** [webonyx/graphql-php#735]
As per [this comment](https://github.com/webonyx/graphql-php/blob/8ee8eec1bb312c5e302d7ba9a9216bf6ad9b851e/src/Executor/Executor.php#L95-L97), I'm wondering if `GraphQL::setPromiseAdapter()`, and `Executor::setPromiseAdapter()` and `Executor::getPromiseAdapter()` shouldn't be deprecated.

Seems logical as `GraphQL::execute()` and `GraphQL::executeAndReturnResult()` have been deprecated a long time ago, `GraphQL::promiseToExecute()` doesn't need them and `GraphQL::executeQuery()` doesn't use them.

Having them deprecated would IMO make more obvious how to set up custom promise adapters correctly. 

Context: overblog/dataloader-php#39. Also related to #664.

**Comment by vladar** [comment]
Yes, we should deprecate it. A PR is welcome!
