### ISSUE TITLE
Graphql : Cannot return null for non-nullable field

### ISSUE THREAD

**Issue by maikelohcfg** [webonyx/graphql-php#739]
Hello every one

I am using graphql and have some weird issue,

First some context about package version:

api-platform/core: 2.5.7
webonyx/graphql-php: 14.3.0
This is my models

`
class Book {
	/**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
	protected $id;
	/**
     * @ORM\Column(type="string")
     */
	protected $name;
	/**
    * @ORM\OneToMany(targetEntity="Comment", mappedBy="book", cascade={"all"}, orphanRemoval=true)
    */
	protected $comments;
}

class Comment {
	/**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
	protected $id;
	/**
     * @ORM\ManyToOne(targetEntity="Book", inversedBy="comments")
     * @ORM\JoinColumn(name="book_id", referencedColumnName="id")
     */
	protected $book;
	/**
     * @ORM\ManyToOne(targetEntity="Customer")
     * @ORM\JoinColumn(name="localizacion_id", referencedColumnName="id", onDelete="CASCADE")
     */
	protected $customer;
	/**
     * @ORM\Column(type="text")
     */
	protected $comment;
}

class Customer {
	/**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
	protected $id;
	/**
     * @ORM\Column(type="string")
     */
	protected $name
}`

This is my graphql query:
`{
  books {
    edges {
      node {
        id
        _id
        name
         comments {
          edges {
            node {
              id
              _id
              customer {
                id
                name
              }
            }
          }
        }
      }
    }
    totalCount
   pageInfo {
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
    }
  }
}`

When a request from customer only id it work perfect and return proper IRI so the customer is not null at all, but when customer name is requested and exception is being raised with debug message: Cannot return null for non-nullable field "Customer.name"."

Any help will be welcome, thanks in advantage

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of this project.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
