### ISSUE TITLE
PHP 8 syntax error

### ISSUE THREAD

**Issue by brandonfarber** [webonyx/graphql-php#742]
https://php.watch/versions/8.0/deprecate-required-param-after-optional

Required parameters declared after optional parameters now throw a deprecation notice.

https://github.com/webonyx/graphql-php/blob/master/src/Error/FormattedError.php#L280

You can just get rid of the `= null` in the argument list. `callable` is already nullable via the `?` mark

**Comment by spawnia** [comment]
Can you create a PR?
