### ISSUE TITLE
Order of SchemaPrinter output is not consistent

### ISSUE THREAD

**Issue by joesaunderson** [webonyx/graphql-php#750]
I am running a command to dump out the contents of my schema, we store this in Git.

This command seems to have an inconsistent order i.e nothing in the schema changes, but the output changes order.

Usage:

```php
$schema = $this->executor->getSchema();
SchemaPrinter::doPrint($schema)
```

Is there anyway to make sure this maintains the same order?

**Comment by spawnia** [comment]
Please provide a working code example to reproduce the issue and include example outputs.

**Comment by lukasluecke** [comment]
I have the same issue, but it doesn't happen regularly / reliably, so it's hard to provide a reproduction. It just moves around some parts of the schema seemingly randomly 🤔
