### ISSUE TITLE
`Utils::getOperation` deviates from graphql-js' getOperationAST

### ISSUE THREAD

**Issue by Kingdutch** [webonyx/graphql-php#754]
## Problem
The [`Utils::getOperation`](https://github.com/webonyx/graphql-php/blame/master/src/Utils/AST.php#L595) implementation in this library deviates from [`getOperationAST`](https://github.com/graphql/graphql-js/blob/master/src/utilities/getOperationAST.js) in two important ways:

1. It accepts documents with multiple operations without specifying an operationName. This is considered invalid by the graphql-js implementation.
2. It only provides the name of the operation whereas users of the library (such as myself ^^) may want the entire operation instead of just the name.

## Proposed resolution
We have a few options here depending on how much/little we want to break and how we want to approach releasing this in a semver compatible manner.

### Add a new method
Since the name of the operation that's currently implemented also differs we can implement the method from `graphql-js` with the name that it has over there, this also makes discovery easier.

```
    /**
     * Returns the operation given a document and operation name.
     *
     * If a name is not provided, an operation is only returned if only one is
     * provided in the document.
     *
     * @api
     */
    public static function getOperationAST(DocumentNode $document, string $operationName = null) : ?OperationDefinitionNode
    {
        $operation = NULL;
        foreach ($document->definitions->getIterator() as $node) {
            if ($node instanceof OperationDefinitionNode) {
                if ($operationName === NULL) {
                    // If no operation name was provided, only return an Operation if there
                    // is one defined in the document. Upon encountering the second, return
                    // null.
                    if ($operation !== NULL) {
                        return null;
                    }
                    $operation = $node;
                }
                elseif ($node->name instanceof NameNode && $node->name->value === $msg->getOperationName()) {
                    return $node;
                }
            }
        }
        return $operation;
    }
```

The original method (`getOperation`) is left unaffected because using the new method would cause it to fail for documents that contain multiple operations, without an operation name specified. Currently this would default to the first operation.

### Fix the behaviour of `getOperation` too

This would implement `getOperationAST` and adjust `getOperation` to match the expected behaviour of rejecting documents by calling `getOperationAST` and only returning the name. This fixes the behaviour but requires no changes in existing call sites.

### Deprecate `getOperation`
Not necessarily a resolution on its own but one that can be combined with either of the above approaches. This would require changing the call sites in the GraphQL PHP library itself. This allows to remove `getOperation` in the future ensuring we don't have methods that aren't present in the implementation that we follow.

We can also decide not to deprecate this method and let them live side-by-side depending on what's needed, but the difference in behaviour may then become confusing.

**Comment by spawnia** [comment]
We can certainly add `getOperationAST` that functions like the reference implementation, good suggestion.

Following that, my vote goes towards leaving `getOperation` unchanged and marking it as deprecated.

**Comment by Kingdutch** [comment]
One day I'll create a separate project in which I can properly run all the tests and coding standards instead of abusing the GitHub actions. Today was not that day, sorry for the noise.

**Comment by spawnia** [comment]
Released with https://github.com/webonyx/graphql-php/releases/tag/v14.8.0
