### ISSUE TITLE
Hook into operation validation for tracing purposes

### ISSUE THREAD

**Issue by fabis94** [webonyx/graphql-php#757]
Currently there's no way to fully implement the Apollo Tracing mechanism like described here: https://github.com/apollographql/apollo-tracing#response-format

The part that we can't do at the moment is get the validation time, because validation is done internally and can't be accessed/hooked into. Would be great if we could hook before/after the validation process to get the total time it took.

**Comment by spawnia** [comment]
This issue is something we should consider when implementing https://github.com/webonyx/graphql-php/issues/289
