### ISSUE TITLE
Can i apply schema directives to an object using inline types?

### ISSUE THREAD

**Issue by jensdenies** [webonyx/graphql-php#758]
Hi,

Thanks for the great package, really enjoy working with it so far.

I was looking for a way to apply schema directives to an object type but I couldn't find a way to do so.

After digging around in the issues, I noticed a few other issues mentioning directives but it is not apparent to me whether this is supported when using inline types as opposed to the schema language.

Thanks.

**Comment by spawnia** [comment]
Directives are a concept that exists just within the schema definition language *SDL*, they have no direct runtime equivalent.

If you were to construct your schema from SDL, types hold a reference to the original AST node which contains the directives: https://github.com/webonyx/graphql-php/blob/5289a5440e0bfb56d883ab0cd57a46b6a97d41fc/src/Type/Definition/ObjectType.php#L61

When you are not using SDL, you can just pass arbitrary extra config keys when constructing types: https://github.com/webonyx/graphql-php/blob/5289a5440e0bfb56d883ab0cd57a46b6a97d41fc/src/Type/Definition/ObjectType.php#L106

```php
$foo = new ObjectType(['name' => 'Foo', 'arbitrary' => 123]);
$foo->config['arbitrary'];
```

**Comment by jensdenies** [comment]
Thanks @spawnia, I'll use your examples to get it working. Is it possible to get these directives to show up in the SDL when generating one through the SchemaPrinter?

**Comment by spawnia** [comment]
https://github.com/webonyx/graphql-php/issues/552
