### ISSUE TITLE
ListOfType could contain NonNull

### ISSUE THREAD

**Issue by brunobg** [webonyx/graphql-php#762]
**Describe the bug**

Close this if I'm wrong, but `GraphQL\Type\Definition\ListOfType` lists a number of types on its phpdocs but is missing `NonNull` on `$ofType` and `getWrapperType`:

```
/** @var ObjectType|InterfaceType|UnionType|ScalarType|InputObjectType|EnumType */
```

You could have something like `[MyType!]` which makes a `ListOfType[NonNull[ObjectType]]`. This is not a bug per se, but stan is complaning about a if that should never happen in my code when it actually does. Am I missing something? If this issue is correct I can send the trivial PR to fix it.

**Comment by spawnia** [comment]
The newest version already has a different annotation there.
