### ISSUE TITLE
Introduce a way for getting operation type w/o having to parse request document twice

### ISSUE THREAD

**Issue by fabis94** [webonyx/graphql-php#764]
To be able to tell if you're running a query, mutation or subscription you need a DocumentNode, but a DocumentNode is being built internally (inside `\GraphQL\Server\Helper::promiseToExecuteOperation` it looks like - using `Parser::parse`).

Of course I can get it by invoking `Parser::parse()` manually, but then the request ends up being parsed twice which isn't very efficient. I'm worried that if the request is very big, this can leave a noticeable performance impact.

**Comment by spawnia** [comment]
You can parse the query string yourself and pass the parsed `DocumentNode` to the executor.

**Comment by fabis94** [comment]
Not a great option, considering much of StandardServer up has to be copy-pasted into a custom implementation (because a lot of helpful methods of `GraphQL\Server\Helper` are private) just to get this information.

**Comment by spawnia** [comment]
True, it is not that straightforward.

https://github.com/webonyx/graphql-php/blob/5289a5440e0bfb56d883ab0cd57a46b6a97d41fc/src/Server/Helper.php#L284-L290

You can just do:

```php
$helper = new Helper();
$parsedBody = $helper->parseHttpRequest();
$parsedBody->query = Parser::parse($parsedBody->query);
```

Open to PRs to make the standard server and/or helper more modular and convenient to extend.
