### ISSUE TITLE
PDO SQLSRV

### ISSUE THREAD

**Issue by nickmclary** [webonyx/graphql-php#765]
good afternoon

have a problem use pdo sql server connection? 
because I'm not getting it ...

**Comment by nickmclary** [comment]
<?php

namespace App\GraphQL;

class Connection
{
    private static $conn;
    public static function get()
    {
        if (!self::$conn){

        self::$conn = new \PDO("sqlsrv:Server=localhost,1433;Database=exemplo_graphql", "intra2021conn", "intra2021");
        self::$conn->setAttribute( \PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

        }
        return self::$conn;
    } 

}

**Comment by nickmclary** [comment]
namespace App\GraphQL;

class Connection
{
    private static $conn;
    public static function get()
    {
        if (!self::$conn){

        // self::$conn = new PDO('sqlsrv:Server=localhost,1433;Database=exemplo_graphql', 'intranet2021conn', 'intranet2021');
        // self::$conn->setAttribute(PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

        self::$conn = new \PDO("sqlsrv:Server=localhost,1433;Database=exemplo_graphql", "intranet2021conn", "intranet2021");
        self::$conn->setAttribute( \PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );


        }
        return self::$conn;
    } 

}

**Comment by nickmclary** [comment]
namespace App\GraphQL;

class Connection
{
    private static $conn;
    public static function get()
    {
        if (!self::$conn){

        self::$conn = new \PDO("sqlsrv:Server=localhost,1433;Database=exemplo_graphql", "intranet2021conn", "intranet2021");
        self::$conn->setAttribute( \PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

        }
        return self::$conn;
    } 

}

**Comment by spawnia** [comment]
This has nothing to do with this library.
