### ISSUE TITLE
phpstan, \GraphQL\Language\AST\FieldNode::$arguments and `??`

### ISSUE THREAD

**Issue by mfn** [webonyx/graphql-php#769]
Upgraded to phpstan 0.12.69 with level 6 today and I got this:
```
  112    Property GraphQL\Language\AST\FieldNode::$arguments
         (GraphQL\Language\AST\NodeList<GraphQL\Language\AST\ArgumentNode>) on
         left side of ?? is not nullable.
```
I'm using `\GraphQL\Language\AST\FieldNode::$arguments` in a code like this:
```php
                foreach ($selectionNode->arguments ?? [] as $argumentNode) {
                    $fields[$name]['args'][$argumentNode->name->value] = $this->getValue($argumentNode);
                }
```

The fix is easy but when I got curious and checked the project, I found out it also uses the pattern `?? []` a few times in combination with this field:
![image](https://user-images.githubusercontent.com/87493/105658474-d11ff480-5ec6-11eb-94cb-7a3fd2069727.png)

I found that field also on other node types:
![image](https://user-images.githubusercontent.com/87493/105658583-088ea100-5ec7-11eb-995a-580fda6ba7b2.png)

None of them specifies `null`ability.

However I also see that this project uses level 3 and I can't say when/if this analysis kicks.

I'm trying to figure out if removing the `?? []` is truly safe or not or maybe the library also could use adjustments here?

**Comment by simPod** [comment]
IIRC null checks kick in lvl 4.

Though there's some magic in Node constructor so it would be problematic to check statically with current code state.

```php
    /**
     * @param (NameNode|NodeList|SelectionSetNode|Location|string|int|bool|float|null)[] $vars
     */
    public function __construct(array $vars)
    {
        if (count($vars) === 0) {
            return;
        }

        Utils::assign($this, $vars);
    }
```

**Comment by spawnia** [comment]
The specific typehints you are referring to are indeed never `null`. Some related properties were, so I went ahead and created https://github.com/webonyx/graphql-php/pull/770 to ensure the typehints for those are accurate as well.
