### ISSUE TITLE
Freeze on Loading Screen

### ISSUE THREAD

**Issue by barangungor** [webonyx/graphql-php#776]
Hey i got your package in my symfony project, i could create database but my screen freeze on loading screen when i run project to APIPlatform. I see this errors on Chrome Console

```
Failed to load resource: the server responded with a status of 404 (Not Found)    init-graphiql.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)    graphiql.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found)    graphiql-style.css:1 
```

**Comment by spawnia** [comment]
This package does not deal with JS or CSS at all, so this is not within scope.
