### ISSUE TITLE
Using results of already executed mutations in subsequent mutations

### ISSUE THREAD

**Issue by lb9203** [webonyx/graphql-php#780]
I'm wondering if it's possible to use the result of a mutation as an argument in a mutation that's executed after the first mutation in a batch request, or is the only possibility making consecutive requests to the API.

Example:
```
mutation{
    create: createUser(){id}
    update: updateUser(name: "example", id: <id from create>){name}
}
```

**Comment by spawnia** [comment]
GraphQL has no such mechanism.

This library is pretty much just a copy of the graphql-js reference implementation, which in turn just implements the GraphQL spec. I believe there were some rfcs about this in the spec repo, perhaps you should check there.
