### ISSUE TITLE
Broken Query causes Exception

### ISSUE THREAD

**Issue by hooby404** [webonyx/graphql-php#781]
Not sure if this is intended behavior (garbage in - garbage out), but I definitely did not expect it and went searching for a non-existent mistake in my schema definition.

If this is working as intended, just close the issue.

### Steps to reproduce:

Take any, existing query that works, for example:
```
user {
    id
}
```
And then add an argument that is not defined in the schema, and put in an empty array like this:
```
user(
    doesnotexist: []
) {
    id
}
```
### Expected result:

Error Response with message:
```
Unknown argument "doesnotexist" on field "user" of type "Query".
```

### Observed result:

Exception:
```
GraphQL\\Type\\Definition\\Type::getNullableType(): Argument #1 ($type) must be of type GraphQL\\Type\\Definition\\Type, null given, called in /var/www/html/vendor/webonyx/graphql-php/src/Validator/Rules/ValuesOfCorrectType.php on line 75
```

**Comment by spawnia** [comment]
I believe we have a validation rule with a nice error message in place, but tightening the type hints might have lead to premature failure. I think we might have to relax the type constraint or wrap the call in a try/catch to fail gracefully on garbage inputs.
