### ISSUE TITLE
Recommendations for handling arrays and JSONs

### ISSUE THREAD

**Issue by christyjacob4** [webonyx/graphql-php#783]
I'm new to graphQL and I have looked up a lot of issues on how graphQL handles arrays and JSON types. I could not find a concrete answer. I was looking for recommendations on how I can parse responses that are JSON or a PHP array. 
Thanks

**Comment by spawnia** [comment]
This repository and the issue tracker are used to advance the development of `graphql-php`.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by christyjacob4** [comment]
What would be the right forum to ask questions about the usage of this library ?

**Comment by spawnia** [comment]
@vladar perhaps we can enable GitHub discussions?

**Comment by christyjacob4** [comment]
@spawnia  help would really be appreciated. The docs and examples don't seem to be of much help since they depict only basic usages.
