### ISSUE TITLE
how do I handle sub selects in a resolver?

### ISSUE THREAD

**Issue by ChrisJokinen** [webonyx/graphql-php#787]
Hello,

I was working with the code modeled from https://github.com/webonyx/graphql-php/tree/master/examples/02-shorthand and I was trying to make a sub select but I am not certain how to handle the sub type.

for example if I have 
`query{ user(id:1){ id, name, orders { order_id, status } } }`

in the example 02 code I had made a call to a db to query for a user of id 1 and it would return the data. Then I matched the returned data to the schema and returned it with out issue. But once I add the orders sub select I am not certain how to extend the request to a different resolver...suggestions?

**Comment by spawnia** [comment]
Use `$root` in your resolver for `orders`.
