### ISSUE TITLE
"GraphQL Request parameters "query" and "queryId" are mutually exclusive" when using Apollo iOS 0.40.0

### ISSUE THREAD

**Issue by cwdt** [webonyx/graphql-php#789]
When using Apollo iOS 0.40.0 we're getting a "GraphQL Request parameters "query" and "queryId" are mutually exclusive" error.

In the Apollo docs I found this:

1. When the client makes a query, it will optimistically send a short (64-byte) cryptographic hash instead of the full query text.
2. If the backend recognizes the hash, it will retrieve the full text of the query and execute it.
3. If the backend doesn't recognize the hash, it will ask the client to send the hash and the query text so it can store them mapped together for future lookups. During this request, the backend will also fulfill the data request.

This package does not support this flow though. Is this by design, or is this faulty?

**Comment by spawnia** [comment]
> If the backend doesn't recognize the hash, it will ask the client to send the hash and the query text

How is that implemented in Apollo Server?

**Comment by cwdt** [comment]
I'm fairly new to GraphQL, but I found this in the Apollo server documentation: 
`To persist a query string, Apollo Server must first receive it from a requesting client. Consequently, each unique query string must be sent to Apollo Server at least once. After any client sends a query string to persist, every client that executes that query can then benefit from APQ.`

And the following sequence diagram:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/9107601/112024472-86bc9c00-8b34-11eb-9e74-5b830b61f861.png">

https://www.apollographql.com/docs/apollo-server/performance/apq/

**Comment by spawnia** [comment]
I believe that this library's standard server is supposed to mirror the functionality of Apollo Server - the de-facto most popular GraphQL server. Perhaps this change is even possible without breakage.

@cwdt consider https://github.com/webonyx/graphql-php/tree/master/src/Server, the implementation should be simple enough for you to try and make a PR that fixes this behaviour.

**Comment by cwdt** [comment]
I'm going to give it a shot this week. Thanks for confirming!
