### ISSUE TITLE
Add meaningfull benchmarks for Parsing, Validation and Execution

### ISSUE THREAD

**Issue by vladar** [webonyx/graphql-php#79]
Benchmarks is the first step towards the work on performance optimizations and best practices guide. Those optimizations only make sense when there are reliable metrics to compare with.

Obviously benchmarks should be executed against type systems, which are close to real-world apps.

One example exists in benchmarks folder (using [phpbench](https://github.com/phpbench/phpbench)).

**Comment by vasily-kartashov** [comment]
If it's of any interest this is the [`sample_prof`](https://github.com/nikic/sample_prof) result on an actively developed application of mine. The result is stable in the top part of the table.

Path | Line | Hits
-----|------|-----
src/Language/Visitor.php | 443 | 154261
src/Language/Visitor.php | 455 | 99419
src/Utils/Utils.php | 223 | 73642
src/Language/Visitor.php | 450 | 70320
src/Utils/TypeInfo.php | 85 | 33942
src/Language/Visitor.php | 177 | 31358
src/Language/Lexer.php | 546 | 25955
src/Language/Lexer.php | 606 | 22674
src/Utils/Utils.php | 303 | 21848
src/Language/Visitor.php | 245 | 20102
src/Type/Definition/Type.php | 246 | 20078
src/Type/Definition/Type.php | 262 | 17920
src/Type/Definition/NonNull.php | 46 | 17717
src/Language/Visitor.php | 288 | 17582
src/Language/Lexer.php | 534 | 16630
src/Type/Definition/FieldDefinition.php | 220 | 16547
src/Utils/Utils.php | 308 | 15583
src/Type/Definition/FieldDefinition.php | 106 | 15075
src/Language/Visitor.php | 183 | 14139
src/Utils/Utils.php | 425 | 12962
src/Utils/TypeInfo.php | 386 | 12913
src/Language/Visitor.php | 473 | 12744
src/Executor/Executor.php | 1359 | 12115
src/Utils/Utils.php | 429 | 11194
src/Utils/Utils.php | 34 | 10254
src/Language/AST/NodeList.php | 117 | 10217
src/Type/Definition/FieldDefinition.php | 245 | 9893
src/Language/Visitor.php | 237 | 9733
src/Language/Visitor.php | 227 | 9456
src/Type/Definition/ObjectType.php | 149 | 9454
src/Language/Visitor.php | 180 | 9197
src/Utils/TypeInfo.php | 238 | 9030
src/Utils/TypeInfo.php | 295 | 8233
src/Language/Visitor.php | 363 | 7992
src/Type/Definition/FieldDefinition.php | 266 | 7879
src/Language/AST/NodeList.php | 119 | 7748
src/Language/Visitor.php | 185 | 7530
src/Utils/Utils.php | 444 | 7415
src/Type/Definition/FieldDefinition.php | 185 | 7130
src/Type/Definition/ObjectType.php | 123 | 7125
src/Language/AST/NodeList.php | 106 | 7018
src/Language/Visitor.php | 412 | 6910
src/Language/Visitor.php | 428 | 6559
src/Language/Lexer.php | 464 | 6453
src/Type/Definition/NonNull.php | 61 | 6227
src/Type/Definition/Type.php | 86 | 6200
src/Language/AST/NodeList.php | 53 | 5941
src/Language/AST/NodeList.php | 49 | 5794
src/Type/Definition/FieldDefinition.php | 173 | 5557
src/Language/Parser.php | 146 | 5411
src/Utils/TypeInfo.php | 227 | 5231
src/Type/Definition/ListOfType.php | 45 | 5061
src/Executor/Promise/Adapter/SyncPromise.php | 72 | 4959
src/Type/Introspection.php | 728 | 4922
src/Type/Definition/FieldDefinition.php | 107 | 4897
src/Utils/Utils.php | 309 | 4506
src/Type/Definition/Type.php | 95 | 4504
src/Type/Definition/Type.php | 39 | 4281
src/Type/Definition/Config.php | 120 | 4182
src/Executor/Promise/Adapter/SyncPromise.php | 33 | 3784
src/Executor/Promise/Promise.php | 21 | 3667
src/Type/Definition/NonNull.php | 22 | 3648
src/Language/AST/NodeList.php | 108 | 3612
src/Language/AST/NodeList.php | 31 | 3555
src/Type/Definition/Type.php | 57 | 3387
src/Language/Visitor.php | 417 | 3359
src/Executor/Promise/Adapter/SyncPromiseAdapter.php | 23 | 3187
src/Validator/ValidationContext.php | 158 | 3092
src/Type/Definition/FieldDefinition.php | 96 | 3087
src/Language/Visitor.php | 430 | 3084
src/Executor/Promise/Adapter/SyncPromise.php | 79 | 3030
src/Language/Token.php | 129 | 2972
src/Type/Definition/FieldArgument.php | 113 | 2946
src/Language/Parser.php | 484 | 2911
src/Type/Definition/Type.php | 76 | 2787
src/Type/Introspection.php | 749 | 2752
src/Type/Definition/FieldDefinition.php | 75 | 2700
src/Utils/TypeInfo.php | 127 | 2655
src/Executor/Promise/Promise.php | 35 | 2646
src/Type/Definition/FieldArgument.php | 60 | 2642
src/Language/Visitor.php | 386 | 2594

**Comment by spawnia** [comment]
We do have some benchmarks in place now and are effectively using them when doing performance work.
