### ISSUE TITLE
Usage of the `list<T>` PHPDoc annotation

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#811]
Since @simPod has brought this up in some PRs, let's have a proper discussion about annotating sequentially numerically indexed arrays in PHPDocs.

PHPStan added partial support for this type in https://github.com/phpstan/phpstan-src/pull/83/files, but is lacking the full validation capabilities (ensuring gapless indexes) that Psalm provides https://psalm.dev/docs/annotating_code/type_syntax/array_types/#listsa. Thus, they do not even mention their usage in the docs: https://github.com/phpstan/phpstan/pull/4282

I think we should hold off on using `list<T>` until PHPStan fully commits to supporting it properly. Until then, `array<int, T>` does a pretty good impression of it, with the added bonus of IDE compatibility.

**Comment by spawnia** [comment]
Apparantly, those two types are not the same. I think the semantics line up with the new `array_is_list` function in PHP 8.1: https://php.watch/versions/8.1/array_is_list

```php
/** @var list<int> */
$a = [1, 2];
unset($a[0]); // Should not be allowed, or the type must be array<int, int>
```

**Comment by simPod** [comment]
Yes, the question should be whether we want to adapt the `list` type. But since it's indirectly introduced by `array_is_list()` in 8.1 I see no issue here. As you said, `list<T>` is covariant to `array<int, T>` but are not the same.

**Comment by spawnia** [comment]
We could start using `list<T>` through `@phpstan-`-prefixed PHPDocs for now. I am not sure if the juice is worth the squeeze, I can't recall hitting bugs in this library due to sparse arrays.
