### ISSUE TITLE
Introspection.php::_enumValue, missing 'value' field?

### ISSUE THREAD

**Issue by mailopl** [webonyx/graphql-php#846]
I'm using GraphQLite implementation that relies on webonyx/graphql-php.

I have an Enum like:
```
class Gender {
    const MEN = 'm';
    const WOMAN = 'w';
}
```

Introspection.php seems to not contain 'value' field when generating _enumValue ObjectType.

As far as I understood I should be able to define an enum that has different values than key names, and still be able to generate schema for it just like here: https://github.com/IgorDePaula/laravel-graphql/blob/master/vendor/webonyx/graphql-php/docs/type-system/enum-types.md 
```
$episodeEnum = new EnumType([
    'name' => 'Episode',
    'description' => 'One of the films in the Star Wars Trilogy',
    'values' => [
        'NEWHOPE' => [
            'value' => 4,
            'description' => 'Released in 1977.'
        ],
        'EMPIRE' => [
            'value' => 5,
            'description' => 'Released in 1980.'
        ],
        'JEDI' => [
            'value' => 6,
            'description' => 'Released in 1983.'
        ],
    ]
]);
```

These values 4/5/6 I should be able to retrieve by calling introspection:
```
enumValues(includeDeprecated: true) {
                        value # but this is missing
                        name
                        description
                        isDeprecated
                        deprecationReason
 }

```

Thank you in advance and sorry if this is my mistake and implementation is correct.

**Comment by spawnia** [comment]
Those values are only meant for internal use in PHP. From a client perspective, GraphQL `enum` types only contain the names, see http://spec.graphql.org/draft/#sec-The-__EnumValue-Type

**Comment by mailopl** [comment]
Thank you.
