### ISSUE TITLE
schema config name not support int

### ISSUE THREAD

**Issue by tsingsun** [webonyx/graphql-php#85]
when i set EnumType , i set the key use int,it throw exception.i think int name it's common use in api

```php
'gender'=>[
                'type'=> new EnumType([
                    'name'=>'genderEnum',
                    'values'=>[
                        '1' => ['value'=>'男'],
                        '2' => ['value'=>'女'],
                    ],
                ])
            ],
```

GraphQL\Error\InvariantViolation
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "1" does not.
trace:
1. in /Users/tsingsun/workspace/Git/yak-host/vendor/webonyx/graphql-php/src/Utils.php
 in /Users/tsingsun/workspace/Git/yak-host/vendor/webonyx/graphql-php/src/Type/Definition/Config.php at line 251 – GraphQL\Utils::invariant(0, 'Names must match /^[_a-zA-Z][_a-...', 1)

**Comment by vladar** [comment]
This is done for [compatibility with graphql-js](https://github.com/graphql/graphql-js/blob/7064b9d27cc677b714098d3851ba1daa2fca1043/src/type/definition.js#L941). 

And they add this constraint for purpose. The idea of enums is to provide clear human-readable entries via it's definition. For example:
```
enum Gender {
  MALE
  FEMALE
}
```
which is self-explanatory. But what you are trying to do is to define this Enum as:
```
enum Gender {
  1
  2
}
```
It is explicitly prohibited by this constraint. 

Enum definitions can be sometimes confising. So I'll try to explain it a bit...

In graphql-php each enumeration entry is presented by `name` and `value` (same for graphql-js). The full form for Enum definition is:
```php
$genderType = new EnumType([
    'name'=>'genderEnum',
    'values' => [
        ['name' => 'MALE', 'value'=> 1],
        ['name' => 'FEMALE', 'value'=> 2]
    ],
]);
```
(short form where name is set via array key is equivalent of this full form).

But in graphql spec there is no VALUE part. Enum entry is only represented by it's NAME. So VALUE is implementation detail. It is only used when internal representation of enum entry in your app differes from it's exposed name.

Your resolvers are supposed to return VALUE for enum fields. For example: 
```php
'gender' => [
    'type' => $genderType,
    'resolve' => function($value) {
        return is_male($value) ? 1 : 2;
    }
]
```

But graphql-php will transform this VALUE to NAME to include in response. So response will actually contain: `"gender": "MALE"` (or `"gender": "FEMALE"`)

Reverse transformation happens for inputs. Clients send NAME in mutations (or field arguments), e.g:
```
query GetBestEmployee {
  bestEmployee(gender: MALE)
}
```
graphql-php will convert it to VALUE before passing to your resolver in $args:
```php
'bestEmployee' => [
    // ...
    'args' => [
        'gender' => [
            'type' => $genderType,
        ]
    ],
    'resolve' => function($value, $args) {
        // Note: $args['gender'] contains either 1 or 2, but not "MALE" or "FEMALE"
    }
]
```

Fortunately, enums are way easier when NAME and VALUE are the same. Then you can define it like:

```php
$genderType = new EnumType([
    'name'=>'genderEnum',
    'values' => [
        'MALE', 'FEMALE'
    ],
]);
```

or 

```php
$genderType = new EnumType([
    'name'=>'genderEnum',
    'values' => [
        'FEMALE',
        'MALE' => ['deprecationReason' => 'Replaced by robots']
    ],
]);
```

Hope this helps. But if I misunderstood something in your issue - please clarify.

**Comment by vladar** [comment]
Closing it. But feel free to re-open if I missed something.
