### ISSUE TITLE
Fully comply with the spec for the error result format

### ISSUE THREAD

**Issue by spawnia** [webonyx/graphql-php#894]
http://spec.graphql.org/draft/#sec-Errors.Error-result-format

> GraphQL services should not provide any additional entries to the error format since they could conflict with additional entries that may be added in future versions of this specification.

If individual services decide to add such entries, that is not even as bad. Given this library is supposed to be a non-opinionated base implemenation of the spec, we absolutely should not.

I already started a pull request that removes the `category` entry. I think we should do the same for other non-spec entries such as `debugMessage` and `trace` (are there more?).

**Comment by simPod** [comment]
hmm though I must admit I use those 😅 (`debugMessage` and `trace`). Have not checked yet how hard it would be to implement it in user land.

**Comment by spawnia** [comment]
To clarify: I would drop `category`, but move the other entries under `extensions`.
