### ISSUE TITLE
buildSchema

### ISSUE THREAD

**Issue by petecoop** [webonyx/graphql-php#90]
Hey, is there anything similar to `buildSchema()` from `graphql-js`? Which allows you to build the schema from the GraphQL Schema language.

I've found it to be a much nicer/quicker way when building schema's in node and was hoping to find something similar in PHP.

If not would it be possible based on the parser already available in the project? I'd be happy to look into it if I could be pointed in the right direction, I'm planning on using this on a few projects.

**Comment by vladar** [comment]
Unfortunately not yet. PR is welcome!

As for direction...

Current parser is capable of parsing schema definition language. It produces AST document for schema definition. The one step which is missing is to actually traverse this AST and create type definitions along the way.

So here is an example of Schema language parsing: [SchemaParserTest.php](https://github.com/webonyx/graphql-php/blob/master/tests/Language/SchemaParserTest.php). We tried to keep this project as close as possible to `graphql-js` so it maps directly to [schema-parser-test.js](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-parser-test.js)

Next you can look into [buildASTsSchema.js](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js) which traverses this AST. Most of the methods and variable names are the same or similar in this lib, so make sure to search through the codebase to avoid unnecesarry work %)

Differencies are mainly in dropping prefixes and porting js functions as static methods:
e.g. `use GraphQL\Type\Definition\ObjectType` vs `import GraphQLObjectType from '../type/definition'` or `GraphQL\Utils\AST::valueFromAST` `import { valueFromAST } from './valueFromAST';`

And feel free to ask any questions along the way.

**Comment by petecoop** [comment]
Thanks for the swift reply and some direction, I will have a look into it when I can!

**Comment by petecoop** [comment]
I've opened a PR #91 for this, not done just yet but passing the initial tests.

It's pretty much identical to the js code, although at one point the js just started using a scoped var so had to turn it into a instanced class rather than just all static methods
