### ISSUE TITLE
Skip & include directives don't prevent from resolving scalar arguments

### ISSUE THREAD

**Issue by a-gierczak** [webonyx/graphql-php#932]
Hello, let's save you have a `user` node, which contains `findByName` query, to which you can provide `name`. 
Name would be a required scalar parameter of `NonEmptyString` type. However you only want to conditionally include this part of the query, so you use `@skip` or `@include` directive:
```
{
  user {
    findByName(name: "") @skip(if: true)
  }
}
# or you can skip whole user part of this query
{
  user @skip(if: true) {
    findByName(name: "")
  }
}
```
Let's say `NonEmptyString` scalar checks if the value is, as you probably guessed, a non empty string. Otherwise it throws an error. 

What I would expect to happen is that, in skipped parts of the query, the argument would not be resolved. However if you run this query it will result in an error.

**Comment by spawnia** [comment]
From the GraphQL Spec: http://spec.graphql.org/draft/#sec--skip

> The @skip built-in directive may be provided for fields, fragment spreads, and inline fragments, and allows for conditional exclusion during execution as described by the if argument.

Given *validation* and *execution* are distinct phases of resolving a GraphQL query, the behaviour of this library is correct.

That said, the GraphQL spec is able to change and evolve. You can propose a change at https://github.com/graphql/graphql-spec. If it lands, I am happy to reopen and fix compatibility.
