### ISSUE TITLE
SchemaExtender Not Loading Custom Scalar Types Correctly 

### ISSUE THREAD

**Issue by abdullahseba** [webonyx/graphql-php#933]
The `SchemaExtender` doesn't appear to load custom scalar types that extend `ScalarType` correctly.  You get the following error: `"Expected a value of type Email but received: test@test.com. Value of type null is not callable"`.  Inline definitions using `CustomScalarType` work. `error_log`ing [here ](https://github.com/webonyx/graphql-php/blob/master/src/Executor/ReferenceExecutor.php#L952) shows that `$returnType` is an instance of `CustomScalarType` rather than `EmailType` (when using `SchemaExtender`).

Test case: https://gist.github.com/abdullahseba/0e2cb2a8598eba0f44b736806d599e68

**Comment by spawnia** [comment]
Thanks for the test case. Next step would be to add a failing test case to this library through a pull request.

**Comment by abdullahseba** [comment]
Sorry, not sure I follow.  The code in the gist demonstrates the issue.  Line [118 ](https://gist.github.com/abdullahseba/0e2cb2a8598eba0f44b736806d599e68#file-graphql-php-L118) and [152](https://gist.github.com/abdullahseba/0e2cb2a8598eba0f44b736806d599e68#file-graphql-php-L152) lets you toggle between class/inline definition and using the extender or not.  Could you elaborate on what you want from a PR?

**Comment by spawnia** [comment]
If we actually want to fix this issue in the library, we should have a test case that covers this functionality in https://github.com/webonyx/graphql-php/blob/master/tests/Utils/SchemaExtenderTest.php

**Comment by abdullahseba** [comment]
Ah, I see!  I'll see if I can contribute something.
