### ISSUE TITLE
Field name as part of the field config

### ISSUE THREAD

**Issue by simPod** [webonyx/graphql-php#945]
Currently, we expect the object receives a field definitions as `key -> value` where `key` is a field name and `value` is there rest of field configuration. I propose to allow a name to be a part of field configuration.

Now, it is not possible to create a field factory as: 

```php
function createField(): array {
  // no way to pass a name here
  return [
    'description' => 'desc',
    ...
  ];
}
```

I'd love to have this for more flexibility:

```php
function createField(): array {
  return [
    'name' => 'Field',
    'description' => 'desc',
    ...
  ];
}
```

**Comment by simPod** [comment]
Though, it is a bit in conflict with https://github.com/webonyx/graphql-php/pull/914 I'll try to find out what can be done.

**Comment by simPod** [comment]
Hm, what if we drop dependency on an array-key and rely on a field config?

**Comment by simPod** [comment]
For the sake of consistency it makes sense to me. E.g. objects have the `name` entry as well.

**Comment by simPod** [comment]
Hm, there's a lot of complexity around resolving field name from keys.

**Comment by simPod** [comment]
FieldDefinition expects name as a part of config

https://github.com/webonyx/graphql-php/blob/88f9f4913a8ebcafa43c61fee1761fcf26e3f63d/src/Type/Definition/FieldDefinition.php#L73-L75

**Comment by vhenzl** [comment]
> Now, it is not possible to create a field factory […]

Have you tried it? What exactly is the problem? AFAIK, it should work. 

The complexity is to support ["shorthand definitions"](https://webonyx.github.io/graphql-php/type-definitions/object-types/#shorthand-field-definitions). The field name is required in the config passed to `FieldDefinition` constructor but optional in object config. If it's not provided in object config, it's inferred from the fields array key. The same applies to interface fields, [input object fields](https://webonyx.github.io/graphql-php/type-definitions/inputs/#:~:text=When%20not%20set%20-%20inferred%20from%20fields%20array%20key), [enum values](https://webonyx.github.io/graphql-php/type-definitions/enums/#shorthand-definitions) and even [field args](https://webonyx.github.io/graphql-php/type-definitions/object-types/#:~:text=inferred%20from%20args%20array%20key).

**Comment by simPod** [comment]
This https://github.com/webonyx/graphql-php/pull/914 enforced input fields to be `array<string, ...>`

```
TypeError : GraphQL\Type\Definition\InputObjectType::initializeField(): Argument #1 ($name) must be of type string, int given, called in /vendor/webonyx/graphql-php/src/Type/Definition/InputObjectType.php on line 76
 /vendor/webonyx/graphql-php/src/Type/Definition/InputObjectType.php:99
 /vendor/webonyx/graphql-php/src/Type/Definition/InputObjectType.php:76
 /vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:188
 /vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:135
 /vendor/webonyx/graphql-php/src/Utils/TypeInfo.php:194
 /vendor/webonyx/graphql-php/src/Type/Schema.php:228
 /vendor/webonyx/graphql-php/src/Type/Schema.php:214
 /vendor/webonyx/graphql-php/src/Type/SchemaValidationContext.php:281
 /vendor/webonyx/graphql-php/src/Type/Schema.php:587
```

**Comment by simPod** [comment]
Docs says about field name

> Required. Name of the input field. When not set - inferred from fields array key

So it is not required. Do we want it to be required or not?

**Comment by simPod** [comment]
Hm, we support this 

```php
        new InputObjectType([
            'name'   => 'SomeInputObject',
            'fields' => [
                'f' => static function () : Type {
                    return Type::string();
                },
            ],
        ])
```

which is not documented but field name is not required then.

**Comment by vhenzl** [comment]
You are right, #914 really broke it.

> is not documented but field name is not required 

It is documented, purely, but it is. The behaviour is the same for object's, interface's and input's fields; all of them supports (or should support) these three forms: https://webonyx.github.io/graphql-php/type-definitions/object-types/#shorthand-field-definitions

>Docs says about field name
>> Required. Name of the input field. When not set - inferred from fields array key
>
>So it is not required. Do we want it to be required or not?

It depends on context. The name is required in the `InputObjectField`'s constructor, but it's optional in the `InputObject` config. If it's not provided in the field config, it's _inferred from fields array key_.

It should not be required. All three forms should be supported to allow for concise type definition.

**Comment by spawnia** [comment]
I added a more complete set of test cases and adapted the implementation in https://github.com/webonyx/graphql-php/pull/946

**Comment by spawnia** [comment]
Funtionality is restored in #946
