### ISSUE TITLE
How can I receive fields for 'resolve' ?

### ISSUE THREAD

**Issue by nepster-web** [webonyx/graphql-php#95]
**My query is:** 
```
      $queryString = '{
            Record(id: "7") {
                id,
                alias,
                visible
            }
        }';
```

**My ContentSchema is:**
```
        $queryType = new ObjectType([
            'name' => 'Query',
            'fields' => [
                'Record' => [
                    'type' => $contentType,
                    'args' => [
                        'id' => Type::string(),
                        'alias' => Type::string(),
                    ],
                    'resolve' => function ($v, $a, $c, ResolveInfo $info) {

                        // need get query fields list:  id, alias, visible
                        // and execute optimal query to my store 
                       // $store->find()->select(['id', 'alias', 'visible'])->all();

                    },
                ],
            ],
        ]);
```

How can I get a list of requested fields to build optimal query?

**Comment by vladar** [comment]
You can use `$info->getFieldSelection()` for now. See comments on [how to use it](https://github.com/webonyx/graphql-php/blob/master/src/Type/Definition/ResolveInfo.php#L82-L113).

But it will be likely deprecated in favor of #65 one day (no timeline set yet). We deprecate things without breaking usually (by issuing E_USER_DEPRECATED warning), so you will have time to migrate when it happens.

Or you can implement #65 yourself and submit a PR %)

**Comment by nepster-web** [comment]
Oh, thank you very much.

I know GraphQL and this library badly, but maybe I will think up something later.
