### ISSUE TITLE
Field type is known only on runtime

### ISSUE THREAD

**Issue by art-zhitnik** [webonyx/graphql-php#962]
Suppose, we have type `SomeType` with field `someField`. `someField` can be an instance of types `A`, `B` or `C`. But we don't know what exactly type it will be on construction time, only on runtime. How can I solve this? Can I use interface `InterfaceForABC` as `someField` definition?

**Comment by vhenzl** [comment]
This seems like a use case for unions. The return type of `someField` would be a union of `A`, `B` and `C`:

```graphql
type A {
    a1: String
    a2: Int
}

type B {
    b1: String
    b2: Int
}

type C {
    c1: String
    c2: Int
}

union ABC = A | B | C

type SomeType {
    someField: ABC
}

type Query {
    some: SomeType
}
```
Then you can query this schema like this:

```graphql
query {
    some {
        someField {
            ...on A {
                a1
            }
            ...on B {
                b1
                b2
            }
            ...on C {
                c2
            }
        }
    }
}
```
This is quite a general question, I would recommend reading the [official GraphQL documentation](https://graphql.org/learn/). More about unions [here](https://graphql.org/learn/schema/#union-types).

Have also look at [Schema Definition](https://webonyx.github.io/graphql-php/schema-definition/) section of the `graphlq-php` doc. For [unions](https://webonyx.github.io/graphql-php/type-definitions/unions/), you have to provide `resolveType` function. It's called during execution to decide what concrete type you are actually returning.

**Comment by vhenzl** [comment]
You could actually use an interface as well:

```graphql
interface InterfaceForABC

type A implements InterfaceForABC {
    a1: String
    a2: Int
}

type B implements InterfaceForABC{
    b1: String
    b2: Int
}

type C implements InterfaceForABC{
    c1: String
    c2: Int
}

type SomeType {
    someField: InterfaceForABC
}

type Query {
    some: SomeType
}
```

The query would be exactly the same as before.

You will also need to provide `resolveType` function.

Both approaches are valid, depends on the particular use case and what makes more sense. If there is a natural interface (even if empty) that all the types can implement, use interface, if the field returns otherwise unrelated types (e.g. a search result), use union.
