### ISSUE TITLE
Validate arguments

### ISSUE THREAD

**Issue by nepster-web** [webonyx/graphql-php#97]
My apologies but I continue study your library. And I don't understand where can I validate arguments?

For example, I have a mutation:

```
mutation (
        $alias: String, 
        $isVisible: Boolean
    ) {
    updateRecord(
        alias: $alias,
        is_visible: $isVisible
    ) {
        alias,
        is_visible
    }
}
```
Ok, it's easy because arguments use variables and attached separately. But what if the query will be like this (without variables):

```
mutation {
    updateRecord(
        alias: 'new_alias',
        is_visible: 1
    ) {
        alias,
        is_visible
    }
}
```

This is a very simple example but I really need the ability to validate incoming data. 
I can use **resolve** method in my schema: 

```php
'resolve' => function ($record, $args, $context, ResolveInfo $info) {
   // $info->getFieldSelection()
   // Validate arguments  
},
```

**However, maybe this is not the best idea?**

I see that your library has validators. But documentation is pure. So maybe I need to create my own validator?

Please, tell me where should I work with the incoming data?

**Comment by vladar** [comment]
There are two kinds of validations:

**1. Formal type vaidation**. 
When you need to make sure that args provided by user match your type definitions. GraphQL does it for you automatically. So for example you have following mutation:

```php
$mutations = new ObjectType([
  'name' => 'Mutation',
  'fields' => [
    'updateRecord' => [
      'type' => $somePayloadType,
      'args' => [
        'alias' => Type::nonNull(Type::string()),
        'is_visible' => [
          'type' => Type::nonNull(Type::boolean()),
          'defaultValue' => false
        ]
      ],
      'resolve' => function($record, $args, $context, ResolveInfo $info) {
        // here `$args['alias']` is always set and is string
        // and `$args['is_visible']` is always set and boolean (false by default if omitted in query)
      }
    ]
  ]
]);
```
In other words you can safely rely on `$args` being formally valid inside `resolve`. If user provides invalid args (for example object for `alias` arg which expects string) - graphql will return error in response and will not call `resolve`.

**2. Domain or business logic validation**
It is perfectly fine to do additional business logic validation in `resolve` method. The only thing you should consider is how to return errors.

One option would be to just throw in resolver. Then you will get `error` entry in response automatically. Other option is to include `userErrors` field in your mutation Payload type to differentiate formal errors (which are usually client developer errors) from app logic errors.

But I have a feeling that I am missing something in your problem, so if it doesn't answer your question - feel free to continue asking %) I am totally fine with it.

**Comment by nepster-web** [comment]
I'm interested in the second kind: **"Domain or business logic validation"**.

For example, we have several fields:
**alias** - must be unique
**name** - must be string (min 5 and max 32 characters)
**lang** - value from the list [ru, en, fr]

My app has a library for validation. Assume, client entered the wrong data and got 2 errors:
**alias** - Already exists
**lang** - Not found

I can throw Exception and the error is automatically placed in the errors list.
The description of this is here: http://webonyx.github.io/graphql-php/error-handling/

**But I would like to show the client all of the errors. What do I do?**

And one more question about "[Custom Error Formatting](http://webonyx.github.io/graphql-php/error-handling/)":

Assume I have my custom exception (MyCustomException) and I want catch it:

```php
try {
    $schema = new Schema([
        // ...
    ]);

    $body = GraphQL::execute($schema, $query);
    $status = 200;
} catch(\MyCustomException $e) {
...
} catch(\Exception $e) {
...
}
``` 

I can't do it because it falls in GraphQL\Error\Error and `$error->getPrevious()` even not  returns MyCustomException. I can't define my exception.

Why was this decision taken and what should I do?

**Comment by vladar** [comment]
All errors are caught because GraphQL spec defines what should appear in result and what shouldn't in different error scenarios. In order to ensure that all implementations do follow the spec we handle this logic automatically.

Another reason is that whole query shouldn't fail if some nullable field throws (it's the same idea why php has notices and warnings - errors in nullable fields are not fatal for query to be processed and shouldn't affect user experience).

But every exception you throw in resolver must be available via `$error->getPrevious()`. If you don't get it somewhere - then this is a bug. Can you provide a test case when you can't get your error this way?

**Comment by vladar** [comment]
Also note that for business logic / domain errors - it makes sense to use different approach for error handling: not throwing in resolver, but having common interface for all mutation payload types, e.g.:

```
interface Payload {
  ok: Boolean!

  # Contains errors which are safe to show to end-user:
  userErrors: String[]
}

type UpdateRecordPayload implements Payload {
  ok: Boolean!
  userErrors: String[]
  myField: String
  myOtherField: String
}

type Mutation {
  updateRecord(alias: String!, is_visible: Boolean!): UpdateRecordPayload
}
```

You may need some code to automate creating such mutations, but then in case of errors your resolver could do something like this:
```php
'resolve' => function($record, $args, $context, ResolveInfo $info) {
  if (!isUnique($args['alias'])) {
    $errors[] = 'Alias must be unique';
  }
  if (somethingElseIsWrong($args['alias']) {
    $errors[] = 'Something else is wrong';
  }
  if (!empty($errors)) {
    return ['ok' => false, 'userErrors' => $errors];
  }
}
```

We do use similar approach internally.

**Comment by nepster-web** [comment]
**1 - about $error->getPrevious()**
I was checked it one more time and everything works correctly.

**2 - about errors**
I create my custom type:
```php
class ErrorsType extends Type implements InputType, OutputType, LeafType
{
    public function __construct()
    {
        Utils::invariant('ErrorsList');
    }

    public static function getInstance()
    {
        return new self();
    }

    public function serialize($value)
    {
        return $this->parseValue($value);
    }

    public function parseValue($value = [])
    {
        return $value;
    }

    public function parseLiteral($ast)
    {
        // TODO: test
        return null;
    }

}
```

And my test `resolve`:
```php
'resolve' => (function ($obj, $args) {
    
    $errors = [];
    $errors['alias'] = 'Alias must be unique';
    $errors['name'] = 'Something else is wrong';

    if (count($errors)) {
        return [
           'errors' => $errors
        ];
      }

       return [
           'alias' => $args['alias'] ?? null,
           'is_visible' => $args['is_visible'] ?? null,
       ];

}),
```

Assume I do this query:
```
mutation (
    $alias: String, 
    $isVisible: Boolean,
    $translateTitle: String,
    ...
) {
    updateRecord(
        alias: $alias,
        is_visible: $isVisible,
        translate: {
            title: $translateTitle,
           ...
        }
    ) {
        alias,
        is_visible,
        errors
    }
}
```

And get this answer:
```
{
  "data": {
    "updateRecord": {
      "alias": null,
      "is_visible": null,
      "errors": {
        "alias": "Alias must be unique",
        "name": "Something else is wrong"
      }
    }
  }
}
```
or this (if there are no errors):
```
{
  "data": {
    "updateRecord": {
      "alias": "test",
      "is_visible": false,
      "errors": null
    }
  }
}
```

There are two questions which I’d like to know:
1) Do I understand this idea correctly?
2) Should client always ask for **error** attribute in the request?

**Comment by vladar** [comment]
What is `ErrorsType`? Why is it extending `Type` and implements `InputType`, `OutputType`, `LeafType`? Where did you get this? This is never needed - these are pretty much internal stuff in graphql-php, you shouldn't be touching it this way.

Your custom error type should be ObjectType or just String (if you only need message for errors).

As for resolver, mutation query and response - everything looks correct. And yes - client is supposed to request `errors` in query explicitly.

**Comment by nepster-web** [comment]
I created `ErrorsType` for return an array of errors. 
If I use `Type::string()` I must return json, like this:
```php
'resolve' => (function ($obj, $args) {
...
    return [
       'errors' => json_encode($errors),
    ];
...
}),
```
I try use `Type::listOf(Type::string())` but the response skipped array keys, for example:
```
{
  "data": {
    "updateRecord": {
      "alias": null,
      "is_visible": null,
      "errors": [
        "Alias must be unique",
        "Something else is wrong"
      ]
    }
  }
}
```

So I created custom `ErrorsType` and I can return correct errors list (with array keys). 
**Can I do it in another way?**

A few words about explicit `error` field in the request:
 - `error` field  mixed with other fields. Are you sure those are best practices?
 - If `error` field is not empty then other fields is empty. It's not pretty.  What do you think about this? 

Thank you.

**Comment by vladar** [comment]
On best practices - see [this discussion](https://github.com/facebook/graphql/issues/117) and answers of Lee Byron who is an author of the specification and graphql-js.

About error type.
Your error should be object type. GraphQL doesn't support arbitrary keys in responses (and your ErrorsType is definitely not a best practice), so what you actually want is something like this:

```graphql
type UserError {
  message: String!
  code: Int
  # Here you store original argument that caused an error (if you need it)
  inputKey: String
}

type Mutation {
  updateRecord(alias: String!, is_visible: Boolean): UpdateRecordResult
}

# This type can implement some interface common to all mutations
type UpdateRecordResult {
  ok: Boolean!
  userErrors: [UserError!],
  # This is not included in response when there are errors
  # Alternatively you can just add payload as fields of this type directly (but then all of them must be not null)
  payload: UpdateRecordPayload
}

type UpdateRecordPayload {
  field1: MyType!
  field2: SomeOtherType
}
```

I forgot about one more option you have to return several errors. You can do so by returning array of exceptions from your resolver. GraphQL *should* convert them all to errors (but I don't remember excactly, so you should try it first)

Also this discussion is not related to graphql-php itself. It's about general GraphQL concepts and approaches. I shared my vision, but you may also ask at [graphql spec](https://github.com/facebook/graphql) repo where authors of spec can help you with idiomatic best practices or on stackoverflow.

**Comment by nepster-web** [comment]
Thank you very much. 
When I find this information, I will create the message here. I think it will be useful.
