### ISSUE TITLE
Provide access to field variables through Error object

### ISSUE THREAD

**Issue by LastDragon-ru** [webonyx/graphql-php#980]
In our logs I see few: 

```
Cannot return null for non-nullable field "MyType.property".
```

Probably some data are invalid in the database and I need to fix it (or maybe allow nulls). But the problem is: this error is totally useless and there is no way to reproduce it because `GraphQL\Error\Error` doesn't have any information about variables that were passed from the js client :(

Would be good if `Error` will also store variables.

**Comment by spawnia** [comment]
We have solved debugging issues like this through the use of [Sentry](https://sentry.io). I recommend generally improving the logging and traceability of what happens in your application.
